### ISSUE TITLE
[Bug]: Korean doesn't work properly

### ISSUE THREAD

**Issue by pppaapp** [RafaelGB/obsidian-db-folder#1005]
### What happened?

A bug happened!

https://github.com/RafaelGB/obsidian-db-folder/assets/31263588/5199e8f7-d3cd-4a74-a2ad-1554ae387723

Only `미 미 미` should be generated, but `미 미 미` and `미` are generated.

### What platform were you using?

Desktop

### Version of the plugin

3.5.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by stefandanzl** [comment]
Sorry, I can't replicate that, pasting `미 미 미` works as expected and creates only one column for me
Furthermore it would be really difficult to replicate and debug the issue without even knowing how to use the korean typeset properly

**Comment by stefandanzl** [comment]
But feel free to post some more korean column ids to test

**Comment by pppaapp** [comment]
It's sad news.

> Sorry, I can't replicate that, pasting `미 미 미` works as expected and creates only one column for me Furthermore it would be really difficult to replicate and debug the issue without even knowing how to use the korean typeset properly

it's sad news

problem only occurs when typing Korean text on the keyboard

copy & paste can't reproduce this problem
