### ISSUE TITLE
[BUG] cell can't be selected sometimes

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#102]
**Describe the bug**
Sometimes cells on newly created column can't be selected

**To Reproduce**

Files: 
- [test db.md](https://github.com/RafaelGB/obsidian-db-folder/files/8837846/test.db.md)
- [test1.md](https://github.com/RafaelGB/obsidian-db-folder/files/8837847/test1.md)
- [test2.md](https://github.com/RafaelGB/obsidian-db-folder/files/8837848/test2.md)
- [test3.md](https://github.com/RafaelGB/obsidian-db-folder/files/8837850/test3.md)

Steps:
1. create column
2. select cells 

**Expected behavior**
cells can be selected

**Screenshots**

https://user-images.githubusercontent.com/38974541/172003559-11d01b18-2224-47a3-aa9a-3d13531f6cd0.mov

**Desktop (please complete the following information):**
 - OS: MacOs monterey 12.3.1
 - Version Obsidian 0.14.6 Installer 0.14.6

**Comment by RafaelGB** [comment]
I will check it. Thanks

**Comment by RafaelGB** [comment]
Looks like different issues. But could be check once Is released, thanks for comment about it

**Comment by RafaelGB** [comment]
Okey, This happens just when you add a column with the "insert right" of the last column

I will investigate the cause
