### ISSUE TITLE
[Bug]: does not work with existing columns with a space in their ID

### ISSUE THREAD

**Issue by nerkuda** [RafaelGB/obsidian-db-folder#1025]
### Contact Details

nerkuda@gmail.com

### What happened?

In the table settings, I added an existing column, for example, "место покупки". Column ID was automatically changed to "место_покупки". The existing values from the notes are not displayed in the table.

If you change the value in the table, the "место_покупки" field will be created in the .md file next to the existing "место покупки" field

### What platform were you using?

Desktop

### Version of the plugin

3.5.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by stefandanzl** [comment]
First of all you're not supposed to have spaces in your properties' names

I tested it myself and created `test test` with value `test`
![image](https://github.com/RafaelGB/obsidian-db-folder/assets/19376127/943e4abf-759f-43d4-8bd5-fe8a88788580)

In the DB plugin when adding existing properties i get following recommendations:
![image](https://github.com/RafaelGB/obsidian-db-folder/assets/19376127/13768551-48b1-46c1-82aa-cb19f2933d6c)

When choosing `test-test` the corresponding testvalue gets displayed correctly in the DB view 
`test test` however would not show anything.

So even with spaces it's working

**Comment by 23426356587** [comment]
I saw this issue and fixed it by replacing spaces with _ 

Annoying but manageable

**Comment by LynetteCullens** [comment]
> First of all you're not supposed to have spaces in your properties' names
> 
> I tested it myself and created `test test` with value `test` ![image](https://private-user-images.githubusercontent.com/19376127/298390532-943e4abf-759f-43d4-8bd5-fe8a88788580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODA5ODMsIm5iZiI6MTcxMzM4MDY4MywicGF0aCI6Ii8xOTM3NjEyNy8yOTgzOTA1MzItOTQzZTRhYmYtNzU5Zi00M2Q0LThiZDUtZmU4YTg4Nzg4NTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE5MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NGE2YjBkMTc0ODg3Y2FjYTYyMjZmM2ZlMjc5NjIwODM2OTdmYWI0Zjg0OGUyNzc1MmI4ZDdmOTRiOTgzODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FDRqZDtcHVZc8OOe3MhxcasRQmKzWh-gVSo2wEFqIDo)
> 
> In the DB plugin when adding existing properties i get following recommendations: ![image](https://private-user-images.githubusercontent.com/19376127/298390619-13768551-48b1-46c1-82aa-cb19f2933d6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODA5ODMsIm5iZiI6MTcxMzM4MDY4MywicGF0aCI6Ii8xOTM3NjEyNy8yOTgzOTA2MTktMTM3Njg1NTEtNDhiMS00NmMxLTgyYWEtY2IxOWYyOTMzZDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE5MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMTk4NzE1Zjk0NWQyMTZhYmY4NjMxZGQ0NDAzMzI3YTY1MWEwNTJmN2UxMzY1MmU0MDhjNDY0NGY1MzUzY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0B56_8xpjQIbmJRrhIEXaBHpy9MCm5R0XcV6De1gS64)
> 
> When choosing `test-test` the corresponding testvalue gets displayed correctly in the DB view `test test` however would not show anything. ![image](https://private-user-images.githubusercontent.com/19376127/298390845-402e2c02-0b3e-4402-9977-54f81a0037c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODA5ODMsIm5iZiI6MTcxMzM4MDY4MywicGF0aCI6Ii8xOTM3NjEyNy8yOTgzOTA4NDUtNDAyZTJjMDItMGIzZS00NDAyLTk5NzctNTRmODFhMDAzN2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE5MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNDRlNmEzOWVmY2E3NzViNjQ5Yjk3YmFkZjQwMzE5YmZmZjg5YWQ2ZTRhNDg5YzE1ZDNjM2IwNDVmYjdmMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._UvcolYTFDNRsBZVfiXxA2_14mLK2KXT-CoweWLYoCU)
> 
> So even with spaces it's working

How would I go about getting the plugin to read a "-' in the column ID? I'm not allowed to change the ID itself because a plugin is depending on that particular format.
Edit: Specifically the nested columns under the column with a "-" in the title.
