### ISSUE TITLE
[Bug]: Uncaught (in promise)

### ISSUE THREAD

**Issue by almays** [RafaelGB/obsidian-db-folder#1050]
### Contact Details

almays@gmail.com

### What happened?

DB files just stopped working. After opening any DB file, Obsidian hangs, need to force quit from the system tools.
Mac os latest version. Obsidian latest version.

<img width="545" alt="Снимок экрана 2024-04-13 в 18 05 44" src="https://github.com/RafaelGB/obsidian-db-folder/assets/19815/db3f1d2a-a17e-4414-8ec2-f60882794ae6">

### What platform were you using?

Desktop

### Version of the plugin

3.5.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by almays** [comment]
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'style')
    at QW (plugin:dbfolder:485:74013)
    at VV.constructUI (plugin:dbfolder:487:68686)
    at HV.display (plugin:dbfolder:487:69855)
    at SettingsSearch.getTabResources (plugin:settings-search:229:15)
    at SettingsSearch.buildPluginResources (plugin:settings-search:129:12)
    at eval (plugin:settings-search:112:12)
    at t.<anonymous> (app.js:1:2200871)
    at app.js:1:237056
    at Object.next (app.js:1:237161)
    at a (app.js:1:235879)
```

**Comment by almays** [comment]
Seems it has to do with Dataview. Just dataview codes in normal documents also hang Obsidian. So it is not a DB Folder issue. It is a general Dataview problem.

**Comment by almays** [comment]
Seems it was some weird local issue. I created new vault, moved content files. Reenabled all plugins. And now it works. Seems it was some cache or legacy settings data mixing up the things.

**Comment by chardskarth** [comment]
Seeing this error intermittently. It gets resolved when reopening db file.
