### ISSUE TITLE
[FR] Add support for autocomplete of tags and links

### ISSUE THREAD

**Issue by icytree** [RafaelGB/obsidian-db-folder#107]
Like it is available in general in Obsidian

https://user-images.githubusercontent.com/80559262/172063051-2a64bbd4-0adc-4a54-b134-50b2ad56c6ea.mp4

**Comment by RafaelGB** [comment]
Sure! It will be added to the roadmap

**Comment by RafaelGB** [comment]
using as a reference kanban plugin. The idea is using a react portal

https://github.com/mgmeyers/obsidian-kanban/blob/main/src/components/Editor/autocomplete.ts

**Comment by RafaelGB** [comment]
Thanks to the astounding work of Kanban plugin, this feature have a solid base
First steps of my adaptation to dbfolder:

https://user-images.githubusercontent.com/11924043/187089029-9472ddfa-ec4a-445c-beb8-7f913e99f33f.mov

**Comment by RafaelGB** [comment]
Will be added with the next version!

https://user-images.githubusercontent.com/11924043/187145417-fc7caf13-7590-4d69-946f-64e51546772b.mov
