### ISSUE TITLE
Is this plugin dead?

### ISSUE THREAD

**Issue by profucius** [RafaelGB/obsidian-db-folder#1077]
### What happened?

I would like to know if @RafaelGB has decided to permanently cease development of this plugin, or if he plans to return to it in the future. There is no indication of archival or making the repo public, yet RafaelGB has no significant activity on Github for the past 3+ months.

If users are to trust investing their time and resources into using this plugin, then a warning by the developer on the Readme.md that the plugin is in archive mode is due.

If you have decided to move on, then I am sorry to hear it, but I can understand as well.

### What platform were you using?

Desktop

### Version of the plugin

.

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
hello @profucius !

Currently I have too much work to do and I was waiting until the release of custom views by Obsidian developers (you can watch the official roadmap)

The custom views will include native databases, so I prefer to wait how to work with it to do not re-program.

I really want to refactor this plugin with the future native features.

While that moment arrives, I also make another plugin called ZettelFlow and maybe I can merge both ideas.

Thanks for your interest with your question!

**Comment by profucius** [comment]
Great news! I had heard about the Custom Views being planned but had lost track of it; Totally makes sense now. Looking forward to seeing what comes next from them and you. Thanks for your diligence and hard work!

**Comment by berot3** [comment]
Does anyone know if custom views is expected this year or maybe next?
