### ISSUE TITLE
[FR] - Suggest existing fields upon new column creation

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#112]
It would be handy to receive suggestions for preexisting properties (from inline fields or front matter). 

So if I press the + for a new column, in the menu there might be a "Choose From:" option that then shows you all of the already existing fields/properties that are in those notes.

**Comment by RafaelGB** [comment]
Hi @arminta7 
Could be interesting! I catalog it as long term.

**Comment by RafaelGB** [comment]
On progress. The idea is to use a modal to choose between the actual new column of select from an existing one

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/183882461-308b1fc9-13f8-4363-a2c2-7d9a8a39978d.mov

Prototype pe of the modal. What do you think?

**Comment by arminta7** [comment]
Looks great!
