### ISSUE TITLE
[BUG] Checkbox column visualization

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#114]
**Describe the bug**
When you create a new one and tell it to be a checkbox, that type is not saved. Also then it comes out dislocated.

1-Create new column
2-Add text
3-Select column type checkbox
4-Reselect column type checkbox

**Screenshots**

Edit: New video

https://user-images.githubusercontent.com/7627504/172841392-034327ad-3fe8-48e7-8a46-81b3d8ff9633.mp4

**Desktop (please complete the following information):**
 OS: Windows 11
obsidian v0.14.15
plugin 1.7.0

**Comment by RafaelGB** [comment]
if You refresh the page still happens?

**Comment by RafaelGB** [comment]
seems to end the onBlur action before modify type of column. Could be interesting add an onMouseOver action to the label to fix this problem
