### ISSUE TITLE
[FR] Add pagination

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/obsidian-db-folder#116]
To support big amount of information its necessary a pagination

**Comment by RafaelGB** [comment]
Demo

https://user-images.githubusercontent.com/11924043/186698340-ad886980-c3f3-4848-9af0-58eca7ef3e6b.mov

**Comment by RafaelGB** [comment]
Final result. Quite proud of

https://user-images.githubusercontent.com/11924043/186856362-29dac64a-59f7-488b-bd4d-3d85b4a76978.mov

**Comment by RafaelGB** [comment]
In addition, size of every page will be configurable

https://user-images.githubusercontent.com/11924043/186927604-f562cbee-dec0-4d37-8794-69951f454d17.mov

**Comment by RafaelGB** [comment]
there are 2 bugs to fix on process and I will generate a version. 

Looking forward to launching pagination along with autocomplete!

**Comment by Gentleman03** [comment]
Amazing, looking forward to test it :)
