### ISSUE TITLE
Not able to install from obsidian community plugin

### ISSUE THREAD

**Issue by Gourav1910** [RafaelGB/obsidian-db-folder#118]
When I click on the install button in obsidian then it shows a msg "No appropriate version found". 

![image](https://user-images.githubusercontent.com/101202140/172997355-fc6c815e-14d5-44a7-8b49-9a220aaf6c7a.png)

**Comment by RafaelGB** [comment]
Hi @Gourav1910 
1.7.0 needs to update Obsidian to 14.15 version witch is avaliable since monday

**Comment by Gourav1910** [comment]
oh ok problem solved. Thanks.

**Comment by RafaelGB** [comment]
Anytime!
