### ISSUE TITLE
freeze column gap

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#120]
**Describe the bug**
there is a gap to the left when freezing the first column

**To Reproduce**
1. freeze column
2. swipe to the right

**Expected behavior**
not show a gap

**Screenshots**

https://user-images.githubusercontent.com/38974541/173099455-e8c0e97a-6254-470d-95a1-58efdf920091.mov

**Desktop (please complete the following information):**
 - OS: MacOs monterey 12.3.1
 - Version Obsidian 0.14.15 Installer 0.14.6

**Comment by RafaelGB** [comment]
Catalogued as visual =) thanks

Depends of the used appearance could happen

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/releases/tag/1.7.1 check new version =) this issue will be available
