### ISSUE TITLE
[FR] Remove all values of notes with an option is removed ( tags too)

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#121]
**Describe the bug**
When deleting the select option in the column settings, they are not deleted in the cells, instead they are added to the new one added. Is this behavior normal ?

**To Reproduce**
1. go to settings
2. remove current select options
3. create new select options

**Expected behavior**
delete current select option and provide only the new ones.

**Screenshots**

https://user-images.githubusercontent.com/38974541/173099886-46c6d1b6-5a10-459e-9256-be6bb854d444.mov

**Desktop (please complete the following information):**
 - OS: MacOs monterey 12.3.1
 - Version Obsidian 0.14.15 Installer 0.14.6

**Comment by RafaelGB** [comment]
that's the expected behaviour because that vault exist yet in some cell, so is added when the db is refreshed

**Comment by RafaelGB** [comment]
We can open a discussion about this. it's a design decision

**Comment by imeed166** [comment]
So then, the `x` in the setting is only valid if the select options are not used.

**Comment by imeed166** [comment]
In my opinion, deleting the select option should delete everything. But as long as it's not a bug, I don't mind.

**Comment by RafaelGB** [comment]
Remove the label there could be a function that removes the value of all cells maybe

**Comment by RafaelGB** [comment]
okey you just wrote it =P okey, So could be catalogued as feature

**Comment by andrey-jef** [comment]
> that's the expected behaviour because that vault exist yet in some cell, so is added when the db is refreshed

This is what I expect from the plugin too. I don't want to delete all my entries when I remove an option in multi-select. 

In my case, i have many proj as multi-select. If a proj is archived, then I remove that proj from the multi-select, but that proj should be intact for the previously typed row.

**Comment by andrey-jef** [comment]
> Remove the label there could be a function that removes the value of all cells maybe

Interesting, this is also the behavior of database-table in Notion when I reproduce the OP's actions in Notion. When I delete an option from multi-select, that option will also be deleted from all rows within the database-table

**Comment by RafaelGB** [comment]
Not bad at all =)

https://user-images.githubusercontent.com/11924043/187665963-f9b1c920-f596-444b-bedb-03d92291efa1.mov
