### ISSUE TITLE
[FR] control edition that starts with ![[ but is not finished inside

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#123]
**Describe the bug**
In one of the files, the changes are not persisted

**To Reproduce**
[test db.md](https://github.com/RafaelGB/obsidian-db-folder/files/8880247/test.db.md)
[test1.md](https://github.com/RafaelGB/obsidian-db-folder/files/8880248/test1.md)
[test2.md](https://github.com/RafaelGB/obsidian-db-folder/files/8880249/test2.md)
[test3.md](https://github.com/RafaelGB/obsidian-db-folder/files/8880250/test3.md)
[test4.md](https://github.com/RafaelGB/obsidian-db-folder/files/8880251/test4.md)
[test5.md](https://github.com/RafaelGB/obsidian-db-folder/files/8880252/test5.md)

**Expected behavior**
persist the change in `test1`

**Screenshots**

https://user-images.githubusercontent.com/38974541/173101058-a16a0130-34c2-4daa-b8e9-e37f9e7d60e8.mov

**Desktop (please complete the following information):**
 - OS: MacOs monterey 12.3.1
 - Version Obsidian 0.14.15 Installer 0.14.6

**Comment by imeed166** [comment]
I see.

**Comment by RafaelGB** [comment]
I can add another rule to the existing ones  if you write  `![[` but is not finished inside your text to be wrapped with ""

**Comment by RafaelGB** [comment]
btw, with the 1.7.0  , if you don't want that the "old" databases markdown column is wrapped with "" you can edit inside the markdown the __file__ column and change `isInline: false` to `isInline: true`

**Comment by imeed166** [comment]
Ah, thanks was wondering about that.

**Comment by RafaelGB** [comment]
was a quick fix just including ! into yaml breakers
```ts
export const MarkdownBreakerRules = Object.freeze({
  INIT_CHARS: ['`', '"', '[', '{', '*', '!'],
  BETWEEN_CHARS: [':'],
  UNIQUE_CHARS: ['?'],
})
```

If you find another one could be included too
