### ISSUE TITLE
tag option don't appear right in dark mode

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#124]
**Describe the bug**
the tag options can't be read in dark mode

**To Reproduce**
1. create tag column
2. create tag options
3. enable dark mode

**Expected behavior**
text in tag options should be readable in dark mode also

**Screenshots**

https://user-images.githubusercontent.com/38974541/173101548-897d7915-cecd-4159-8c9d-8c59c2d95cc5.mov

**Desktop (please complete the following information):**
 - OS: MacOs monterey 12.3.1
 - Version Obsidian 0.14.15 Installer 0.14.6

**Comment by RafaelGB** [comment]
the react-select component shows lighter colours on dark mode, could be difficult get the perfect color with all the appearance flavours, but will be added as visual

**Comment by RafaelGB** [comment]
Fixed by @artisticat1

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/releases/tag/1.7.1 check new version =) this issue will be available
