### ISSUE TITLE
sort is lost when renaming column

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#125]
**Describe the bug**
When renaming a column, the sorting is lost, until I refresh the database.

**To Reproduce**
1. sort a column
2. rename that column

**Expected behavior**
persist sort when renaming

**Screenshots**

https://user-images.githubusercontent.com/38974541/173101950-2bbb58e6-71ce-4828-8b2d-ec631d2b4f72.mov

**Desktop (please complete the following information):**
 - OS: MacOs monterey 12.3.1
 - Version Obsidian 0.14.15 Installer 0.14.6

**Comment by RafaelGB** [comment]
looks like the origin of this bug is the same of https://github.com/RafaelGB/obsidian-db-folder/issues/122

Probably fix one fix the other. Thanks =)
