### ISSUE TITLE
multi-column sort info

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#127]
**Is your feature request related to a problem? Please describe.**
When sorting by multiple columns, you can't know which column was sorted first, then second, then third...

**Describe the solution you'd like**
A number after the arrow to indicate the sort priority

**Describe alternatives you've considered**
you have to remember by which columns you sorted first

**Additional context**
source: database plugin

https://user-images.githubusercontent.com/38974541/173110014-0cce514c-ba83-4108-a2a8-3f16e3e2533a.mov

**Comment by RafaelGB** [comment]
I tried it with the first iteration, but the framework does not allow me to do it easily. A second iteration will be considered for this functionality when we migrate to react-table v8

Catalogued as visual

**Comment by imeed166** [comment]
You'll migrate to react-table v8 when it becomes stable ?

**Comment by RafaelGB** [comment]
the first time it comes out of beta, it will be the highest priority

**Comment by imeed166** [comment]
if you don't mind me asking, what are the main changes/improvement from migrating ?

**Comment by RafaelGB** [comment]
the use of React 18 (performance x5 aprox)

capacity to 10000+ rows

Typescript native (so much less potential bugs)

being typescript native allow me to use all the features of the table (pagination, Size adjustments, custom filters…. )

**Comment by RafaelGB** [comment]
Today I am specially productive 


https://user-images.githubusercontent.com/11924043/187682696-23518775-8485-440f-b07f-e1f5b0b84826.mov
