### ISSUE TITLE
[FR]Improvement of the display position of the number of files

### ISSUE THREAD

**Issue by kazdonkai** [RafaelGB/obsidian-db-folder#130]
Hi,
Currently, the number of files in the database is displayed in the text input location of the filter, but when a search string is entered, the result of that search, the number of files, is not displayed. Therefore, we would appreciate it if you could consider separating the location where the search is entered from the location where the number of files is displayed.
![スクリーンショット 2022-06-11 21 56 33](https://user-images.githubusercontent.com/90127278/173189217-bd92995c-f0b2-46e4-8a5d-18f870cca042.png)

**Comment by RafaelGB** [comment]
could be moved from placeholder to label , sure!

**Comment by RafaelGB** [comment]
final design


https://user-images.githubusercontent.com/11924043/189389607-c801b3de-baca-4a44-b4ca-03825cf2dd3a.mov
