### ISSUE TITLE
Automatically set a particular attribute for each item that is added to the folder or tag

### ISSUE THREAD

**Issue by crazymedguy** [RafaelGB/obsidian-db-folder#132]
If I shift a new item with no dataview attributes to a folder with the database folder, I would like the plugin to be able to automatically assign a default value for a tag to it. I reckon this could build up to 'combined databases' using tags from smaller databases as well, for example:

smaller database A - automatically tagged with `#example1`
smaller database B - automatically tagged with `#example2`
smaller database C - automatically tagged with `#example3`

big database X - combines all of A/B/C by including `#example1`, `#example2` and `#example3`

**Comment by RafaelGB** [comment]
could be a subtask of
https://github.com/RafaelGB/obsidian-db-folder/issues/94
I am not sure if its a duplicated issue
