### ISSUE TITLE
[FR] search inline fields that do not start the line or be bold

### ISSUE THREAD

**Issue by galsom** [RafaelGB/obsidian-db-folder#134]
First of all I'd like to thank you for this amazing plugin! Have been playing around with it an seems really useful.

In my vault I have Person notes where each person has its own note with properties like first name, last name, birthday, etc.

Each of these properties is managed using a Dataview inline field in an unordered list, e.g:

```
- First Name:: John
- Last Name:: Doe
- Birthday:: 28/03/1979
```

<img width="206" alt="image" src="https://user-images.githubusercontent.com/48659253/173250868-f335dd28-9c28-4650-99f1-39f54b94d616.png">

During some of these tests, I noticed that inline fields are also rendered correctly if they contain text before, like a dash.

<img width="214" alt="image" src="https://user-images.githubusercontent.com/48659253/173250617-a8e75e93-2b94-4930-9836-162e2111626d.png">

When I change the value using the plugin like the following example, the updated value is correctly saved in the note

<img width="193" alt="image" src="https://user-images.githubusercontent.com/48659253/173250671-7f71cc0f-8e62-4acf-989c-fc713cdde522.png">

The value however is not update in the inline field, but added on top of the note as a new entry

<img width="201" alt="image" src="https://user-images.githubusercontent.com/48659253/173251053-98618372-c529-4021-967b-efdce603f8de.png">

I'm not a developer, but when looking in the source code for the term `inline`, I came across the following [line](https://github.com/RafaelGB/obsidian-db-folder/blob/9ec7acb394d3d46f93d954f6ce1abef64a7d5b7e/src/parsers/RowDatabaseFieldsToFile.ts#L21) of code

`        array.push(`${key}:: ${inlineFields.inline[key]}`);`

Could this be the reason that the dash in front of the inline field is ignored?

**Comment by RafaelGB** [comment]
hi @galsom 

I see the problem here.
The plugin before add a new inline field search if it already exist, but the way it’s searched is being at start of a line

In you example the inline field is behind a -
So the plugin thinks that does not exist and add a new one. I am afraid that changes thst behaviour to edit that case its not trivial but could be added to the roadmap

**Comment by RafaelGB** [comment]
While this issue is into the backlog, you can use the editing option by replacing:

- Birthday:: x/y/z

for:

Birthday:: x/y/z

**Comment by galsom** [comment]
Thank you for the tip of using it without an unordered list. The disadvantage that that has is that when you render the MarkDown, all the values are placed on one line by convention:

<img width="429" alt="image" src="https://user-images.githubusercontent.com/48659253/173683173-376a95e7-69b8-49ba-b390-3685949892e3.png">

That is why I started using the unordered lists. If somebody has another idea, please do share :-).

In the mean time I look forward to all the progress you make and hopefully this can be added.

**Comment by RafaelGB** [comment]
New regex expression:
```ts
const inlineFieldRegex = new RegExp(`(^|(.*)(\\s))([_\\*~\`]{ 0, 2}${columnId}[_\\*~\`]{ 0, 2}[:]{2}\\s)+([\\w\\W]+?$)`, 'gm');
```

https://user-images.githubusercontent.com/11924043/187700499-299cc39e-24aa-44ac-8e57-62fa5e3bd4b8.mov

**Comment by RafaelGB** [comment]
works for write but dataview needs parentheses between key:: value to read it.  Working on another one

**Comment by RafaelGB** [comment]
I have a solid candidate => https://regex101.com/r/yc7mAq/1
