### ISSUE TITLE
[BUG] Embedding local images doesn't work

### ISSUE THREAD

**Issue by artisticat1** [RafaelGB/obsidian-db-folder#136]
**Describe the bug**
Embedding local images in a text column doesn't work

**To Reproduce**
1. Add an image to your vault (e.g. `img.png`)
2. Open a database folder
3. Add a new text column
4. In the column settings, set "Enable media links" to off
5. In one of the rows, type `![[img.png]]`, then exit the cell. No image is shown.
6. Close the database
7. Reopen the database
8. The row we tried to add the image to has disappeared from the database

**Expected behavior**
The image is shown in the text column, and persists after closing/reopening the database

**Desktop (please complete the following information):**
 - OS: Windows
 - Plugin version: 1.7.0

**Comment by RafaelGB** [comment]
I am working on this. I'm trying to see what's broken... when the embed string arrives to renderMarkdown does not continue the function, so the handleEmbeds service does not do its magic

```ts
export async function renderMarkdown(
  cell: Cell,
  markdownString: string,
  domElement: HTMLDivElement,
  depth: number
) {
  try {
    const view: DatabaseView = (cell as any).tableData.view;
    const column = cell.column as unknown as DatabaseColumn;
    const { media_height, media_width, enable_media_view } = column.config;
    if (enable_media_view && isValidHttpUrl(markdownString)) {
      markdownString = `![embedded link|${media_height}x${media_width}](${markdownString})`;
    }
    console.log("rendering markdown", markdownString);
    domElement.empty();
    const dom = domElement.createDiv();

    dom.addClasses(["markdown-preview-view", c("markdown-preview-view")]);
    dom.createDiv(c("embed-link-wrapper"), (wrapper) => {
      wrapper.createEl(
        "a",
        {
          href: domElement.getAttr("src") || view.file.basename,
          cls: `internal-link ${c("embed-link")}`,
        },
        (link) => {
          link.setAttr("aria-label", view.file.basename);
        }
      );
    });
    await MarkdownRenderer.renderMarkdown(
      markdownString,
      dom.createDiv(),
      view.file.path,
      view
    );
   // STOPS HERE BY SOME MISTERIOUS REASON
    domElement.addClass("is-loaded");
    if (depth > 0) {
      await handleEmbeds(dom, view, --depth);
    }
  } catch (e) {
    LOGGER.error(e);
  }
}
```

**Comment by RafaelGB** [comment]
Okay.... Looks like  `MarkdownPreviewView` works! (instead of use `MarkdownRenderer`)

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/174375818-d8a0243a-a848-4a22-9538-677e2c6979cd.mov

**Comment by artisticat1** [comment]
Great! I tested it and it works, but when I close and reopen the database, the image stops showing up.

**Comment by RafaelGB** [comment]
just work with inline fields yet
