### ISSUE TITLE
[FR] Display arrays as multiline - parse required

### ISSUE THREAD

**Issue by trungng2006** [RafaelGB/obsidian-db-folder#137]
**Is your feature request related to a problem? Please describe.**
Currently, the plugin combine all the arrays into 1 line. It create friction when I am trying to scan through the table.

**Describe the solution you'd like**
I would like it to be displayed as multiline. So it is easier to differentiate between the array items
For example:
I would like the table to show:
Author:
- Author 1
- Author 2
- Author 3

Rather than:
Author 1, Author 2, Author 3

**Comment by RafaelGB** [comment]
Hi @trungng2006 
The idea is to show that list with text column, is that right?

For multiline exist the tags column. If your requirement is to be displayed as a dot list needs an aditional parsing in text column. Could be considered, sure!

**Comment by trungng2006** [comment]
Thank you for your prompt response!!!

I think it would also be nice if when we add dot list in the db table, it
also show up as dot list in the file YAML. (So its work both way).

**Comment by RafaelGB** [comment]
sorry @trungng2006 but I have to discard this issue. You can always choose tags and works in both ways, but repeat the same logic on text column its redundant
