### ISSUE TITLE
[FR]New column type: ordinal column

### ISSUE THREAD

**Issue by OriOYue** [RafaelGB/obsidian-db-folder#138]
> ### Bloggers, could you consider adding a new column type: serial number.
 > 
 > ### After fixing this serial number column to the first column, 
 > 
> ### it is very convenient to view the data, and we do not need to manually add the serial number ourselves.

![image](https://user-images.githubusercontent.com/72482686/173582846-8f63ec2c-df0a-4738-be99-288bee745fe9.png)

**Comment by RafaelGB** [comment]
Sure! In addition, internally this serial number already exist, I could add an option to just display id.

My question is... Should it be draggable or just stay at first position?

**Comment by RafaelGB** [comment]
discarded cause could not be draggable right now
