### ISSUE TITLE
KANBAN transclusion plugin incompatibility

### ISSUE THREAD

**Issue by antomonte** [RafaelGB/obsidian-db-folder#141]
**Describe the bug**
Instead of writing the tasks directly on the Kanban board, I usually add the transclusion of them, so that I can have the tasks distributed along their context (daily notes, topic notes...), but gathered and ordered into the Kanban boards.

The bug is that as long as "DB folder" plugin is active, the Kanban plugin doesn't render transcluded texts (tasks)

**To Reproduce**

With DB folder activated:
![image](https://user-images.githubusercontent.com/5910/174270821-47a7bbb8-ff66-4634-a166-b96ae890039e.png)

With DB folder DE-activated
![image](https://user-images.githubusercontent.com/5910/174271344-8407dba7-7a37-4f39-8530-b9af236897d2.png)

**Expected behavior**
No matter the status of "DB folder" plugin, it shouldn't affect to rendering Kanban boards

**Desktop (please complete the following information):**
 - Windows. Current version (as of today)

**Comment by RafaelGB** [comment]
Hi @antomonte 
I will check how to fix this incompatibility, thank you for your report.

**Comment by RafaelGB** [comment]
Looks like its fixed with the current beta version, You can try it with BRAT @antomonte 
Don't know if the newest version of kanban fixed it too

**Comment by antomonte** [comment]
Hi!
seems to work properly now. Many thanks for your support!
