### ISSUE TITLE
Ability to change the size of columns and alignment of cells

### ISSUE THREAD

**Issue by TheAussieTinker** [RafaelGB/obsidian-db-folder#147]
**Is your feature request related to a problem? Please describe.**
The way the table auto formats is not ideal in some circumstances. some cells are too big and the text is aligned strangely

**Describe the solution you'd like**
Add an ability to modify the size of columns manually.
Add an ability to set the alignment of text in the cell (left, centre, right as well as up, middle, down) that way you can have text positioned perfectly in the centre

Also as a side note it would be cool if there was an option to display the max/min value of a column at the bottom under the table (like notion)

**Comment by RafaelGB** [comment]
it’s actually into the roadmap

https://github.com/RafaelGB/obsidian-db-folder/issues/50

**Comment by RafaelGB** [comment]
the problem is that its not compatible with dnd columns, requirre aome refactor
