### ISSUE TITLE
[BUG] Property Type Change 

### ISSUE THREAD

**Issue by kazdonkai** [RafaelGB/obsidian-db-folder#148]
Hi,
In version 1.7.2, it is no longer possible to change the property type of columns.

**Comment by RafaelGB** [comment]
thanks!  I will give it a check

The template feature needed a refactor and something could be affected.

**Comment by RafaelGB** [comment]
@kazdonkai I could not reproduce it. Think was fixed with https://github.com/RafaelGB/obsidian-db-folder/issues/114

**Comment by kazdonkai** [comment]
I reinstalled it and it is now available.
thanks.
