### ISSUE TITLE
Ability to rename filenames directly in the database

### ISSUE THREAD

**Issue by crazymedguy** [RafaelGB/obsidian-db-folder#152]
We can edit text properties, but we cannot edit the filename directly. Would be nice to be able to rename files directly in the database like a textfield.

**Comment by RafaelGB** [comment]
the principal problem with this is the integration of the autorenaming link of all the references inside the vault. Needs to check if could be done

**Comment by RafaelGB** [comment]
I found. a way to use context-menu of obsidian

<img width="1098" alt="Screenshot 2022-09-08 at 14 24 19" src="https://user-images.githubusercontent.com/11924043/189120906-8d01fb8d-c952-4616-996f-621dfe9cead8.png">
