### ISSUE TITLE
Batch import data

### ISSUE THREAD

**Issue by lbgws2** [RafaelGB/obsidian-db-folder#153]
I have an existing data table, which may be an XLS or CSV file

I tried to copy the entire column of data, but after pasting it became the content of a cell.

Either paste or import method is OK. The plug-in automatically creates a file name and expands it to the corresponding number of lines

**Comment by RafaelGB** [comment]
I think this issue is duplicated
https://github.com/RafaelGB/obsidian-db-folder/issues/129
