### ISSUE TITLE
[FR] Label for external links

### ISSUE THREAD

**Issue by yurijserrano** [RafaelGB/obsidian-db-folder#157]
**Good Evening Rafael**

**I hope you are well and safe.**

I would like to suggest that it might be possible to **include a label for external links** so that the column size could be reduced.

Through **Dataviewjs** I am able to do this by invoking the **elink** function, so I think it is possible to port this.

And an example can be seen below:

![01](https://user-images.githubusercontent.com/14169134/174685043-410c0a1e-fd95-4668-b91e-5292dcde6390.png)

**I am at your disposal for any clarification.**

**Have a nice day**

**Comment by RafaelGB** [comment]
hi @yurijserrano , thanks for your comment.


The idea here its to use the label of the column as an alias of external links, right? Could be a toggle button on header settings, the section of the media, sure :)

**Comment by yurijserrano** [comment]
> hi @yurijserrano , thanks for your comment.
> 
> The idea here its to use the label of the column as an alias of external links, right? Could be a toggle button on header settings, the section of the media, sure :)

**Yes, that's the idea** :smiley: 

**Thank you so much Rafael**

**I wish you a wonderful day**

**Comment by RafaelGB** [comment]
=)

https://user-images.githubusercontent.com/11924043/189493228-b9d774e3-0f66-403c-8a06-34d537bc9bb4.mov

**Comment by yurijserrano** [comment]
Great @RafaelGB  :smiley: 

This way the columns will get much smaller

I would just like to make one suggestion, that is related to give the user the ability to choose the label of the links instead of being based only on the column name, this way the user would have more flexibility

Thank you in advance for all the support and attention you have given

**Comment by RafaelGB** [comment]
I can add your suggestion in another issue, sure =)

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/356

**Comment by yurijserrano** [comment]
Great @RafaelGB 

Thank you so much :smiley: 

I think many users will benefit from this because it will considerably decrease the column size

I wish you a great day
