### ISSUE TITLE
change font color to improve readability

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#159]
**Is your feature request related to a problem? Please describe.**
When viewing a cell that contains `time` property, it's easy to know which one doesn't have a value because the font color of `pick a moment...` is grey. But for the `date` property, the font color for `pick a date...` is not grey, so it's hard to tell.

**Describe the solution you'd like**
change the font color for`pick a date...` in the `date` property to grey.

**Additional context**
![image](https://user-images.githubusercontent.com/38974541/174875214-75114fd3-ec26-487c-bcf6-05588b38e8d2.png)

**Comment by RafaelGB** [comment]
sure!

**Comment by RafaelGB** [comment]
Now empty calendars will show nothing. The placeholder appears once is selected
