### ISSUE TITLE
add button to remove date and time

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#160]
**Is your feature request related to a problem? Please describe.**
If you want to remove a date value or a time value from a cell, you can't do it from the date/time picker.

**Describe the solution you'd like**
Have a button to delete the date/time just in the select property.

**Describe alternatives you've considered**
Select the text and delete it manually, but it has unwanted behavior.
- When the property is `date`, If you select the text and delete it, it shows `date invalid`
- When the property is `time`, If you select the text and delete it, it breaks the db

**Additional context**

https://user-images.githubusercontent.com/38974541/174876315-7185f8a1-eb9c-4b22-a3a1-54fdb3c60c4e.mov

**Comment by RafaelGB** [comment]
seems reasonable
