### ISSUE TITLE
update values when switching property type

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#161]
**Is your feature request related to a problem? Please describe.**
When changing property types, the values are not updated until the db is reloaded.

**Describe the solution you'd like**
update the values when changing the properties.

**Describe alternatives you've considered**
change the property, then reload database manually to see changes

**Additional context**

https://user-images.githubusercontent.com/38974541/174877019-9e4aed64-dbb4-4e45-952c-1971f2392684.mov

**Comment by RafaelGB** [comment]
Yeah, happens to me a lot. Could be added too =)

**Comment by imeed166** [comment]
Even though it is marked as done in the roadmap, I'm not getting the new behavior, still the same as it was before (see video)

https://user-images.githubusercontent.com/38974541/176727414-f6a7e1af-e7b5-4610-9083-59e1a98b2af9.mov

**Comment by RafaelGB** [comment]
was fixed but looks like something breaks it again. With the v15 of obsidian API core stuff needs a review. Marked as reopen
