### ISSUE TITLE
improve hover on some properties

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#162]
**Is your feature request related to a problem? Please describe.**
this is a minor visual improvement, but I thought it would bring users consistency when using the plugin. For now, only text and date property include hover, the other properties don't.

**Describe the solution you'd like**
Make hover appear the same in all properties

**Additional context**

https://user-images.githubusercontent.com/38974541/174877838-036281c1-7ff0-44d2-aefa-19ae1f460dc8.mov

**Comment by RafaelGB** [comment]
hmm its ok for me but with a minor priority. Thanks!

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/189 looks like resolve this issue
