### ISSUE TITLE
[FR] Refresh Button

### ISSUE THREAD

**Issue by yurijserrano** [RafaelGB/obsidian-db-folder#163]
**Good Morning** @RafaelGB

I **hope** you are **well** and **safe**

When using your plugin I noticed that **when we add new data it is not included in the table** and **to be included we need to go to a note and then go back to the database.**

So, to leave the workflow only in the database **I suggest to put a Refresh Button at the top** so that the users can update the table without having to leave it.

An example of the button placement can be seen below:

![01](https://user-images.githubusercontent.com/14169134/175556511-a83b0231-4714-4e0e-815a-894ebca9bdcc.png)

If that is difficult, another alternative is to put a **Refresh option** in the **Database Menu**

I am at your disposal for any clarification.

Have a nice day

**Comment by RafaelGB** [comment]
Hi @yurijserrano thanks for your idea.

We can use the observer method of Obsidian to know if there has been any change. The happy path could be add those changes every x seconds to the database, but like a provisional solution a refresh button its ok for me. The code for that refresh is already implemented, should be easy to add it

**Comment by yurijserrano** [comment]
> We can use the observer method of Obsidian to know if there has been any change. The happy path could be add those changes every x seconds to the database

**Great idea Rafael**

Really your **idea** turns out to be the **best workflow**, **I hope it will be included in a future release**


> but like a provisional solution a refresh button its ok for me. The code for that refresh is already implemented, should be easy to add it

**Glad to hear Rafael** :smiley: 

**Once more, thank you so much for your attention.

I wish you a wonderful day.**

**Comment by RafaelGB** [comment]
good news @yurijserrano , the refresh button could be integrated with https://github.com/RafaelGB/obsidian-db-folder/issues/239 . With the new architecture of 2.0.0 I can start to dev dynamic events, so I move the filters to  the navbar. You don't need to refresh the view once you change a filter, the data will be refreshed instead. I am sure that fact could cover this request

**Comment by yurijserrano** [comment]
I am glad to hear @RafaelGB 

I am waiting eagerly to see this in the next update.

Thank you so much for including.


I wish you a great day.
