### ISSUE TITLE
Having options for non-primary columns imported from notes of a folder

### ISSUE THREAD

**Issue by ooker777** [RafaelGB/obsidian-db-folder#168]
We can create a table from a folder. Is it possible to have data for other columns also from other folders? This would be great for tag or select type

**Comment by RafaelGB** [comment]
I think this issue will be covered with https://github.com/RafaelGB/obsidian-db-folder/issues/156

**Comment by ooker777** [comment]
I'm not sure how having dataview queries as source can help notes in a folder being data for non-primary columns? Can you explain?

**Comment by RafaelGB** [comment]
closing this one

**Comment by ooker777** [comment]
for example can I populate the tags by notes from a folder? Each file name is a tag

**Comment by RafaelGB** [comment]
you can just do the same that you can do with dataview, sure
