### ISSUE TITLE
FR: Image column type

### ISSUE THREAD

**Issue by that0n3guy** [RafaelGB/obsidian-db-folder#17]
I've been doing something similar to this plugin with dataview for books (see image below).

It would be awesome if this would work for images.   I have a link in the "cover" data field and render it like so: 

```dataview
TABLE subtitle, ("![coverimg|100](" + cover + ")") as cover, creator, referrer, priority, purpose, status from "Books"
where file.name != "_Book Index"
SORT file.name
```

![image](https://user-images.githubusercontent.com/113870/165976780-8d939716-2f80-47f7-851c-a62fa8245b3f.png)

**Comment by RafaelGB** [comment]
I will try to render images with future versions. Thanks for the suggestion!

**Comment by RafaelGB** [comment]
After release 1.0.0 and make an skeleton of documentation with MKdocs I will Start with this feature

**Comment by RafaelGB** [comment]
With 1.1.0 I learnt how to render md link inside text type columns, but images and other kind of media I am afraid that needs another type of column to be render appropriately

**Comment by RafaelGB** [comment]
Studying the kanban plugin in addition with 1.1.0 md render I got the first step!

<img width="557" alt="Screenshot 2022-05-17 at 13 16 29" src="https://user-images.githubusercontent.com/11924043/168798969-c260c9e7-4831-4ebc-a655-f27e25a7fa99.png">


Reference: [here](https://github.com/mgmeyers/obsidian-kanban/blob/d709fd7c52aec97c5f7fc5b037dcbec6dd651460/src/helpers/renderMarkdown.ts#L142)

**Comment by RafaelGB** [comment]
@that0n3guy enjoy 1.1.1 version [notes](https://github.com/RafaelGB/obsidian-db-folder/releases/tag/1.1.1)

**Comment by that0n3guy** [comment]
That works for images/links that are already transcuded in the field.   But how about image urls?   For example: 
![image](https://user-images.githubusercontent.com/113870/168863274-0d281e9d-969e-4c36-9004-f5ca81c61708.png)

Also, would there be a way to specify size?   I can manually change image size with something like `![image|100]` but then I'd have to edit every page.    With Dataview, I would specify the column like so `("![anytexthere|100](" + cover + ")")`   

Is there a way to wrap the field inside a text cell with our own "code" per column?     If so, this would enable a user to do other things like wrapping the text of a column in bold, or highlight. or callout.

**Comment by RafaelGB** [comment]
Could be a nice setting feature, Could you open another issue with that petition? It will be added to the backlog.

About urls I tried while testing but the markdown obsidian does not offer a native way to render it. Is the URL working on dataview? I tried it too but just expose the link

**Comment by that0n3guy** [comment]
> Could be a nice setting feature, Could you open another issue with that petition? It will be added to the backlog.

Ok I'll open a new FR

> About urls I tried while testing but the markdown obsidian does not offer a native way to render it. Is the URL working on dataview? I tried it too but just expose the link

Yup... Here is my example: 

    ```dataview
    TABLE subtitle, ("![anyTexthere|100](" + cover + ")") as cover, creator, referrer, priority, purpose, status from "Books"
    where file.name != "_Book Index"
    SORT file.name
    ```

Looks like: 
![image](https://user-images.githubusercontent.com/113870/168871288-0fed6333-60ba-42f1-b594-53af694ced9e.png)

With files like: 
```
---
create_date: 2022-05-04
---

# AntiFragile

cover:: https://images-na.ssl-images-amazon.com/images/I/41wd4dlgGBL._SX322_BO1,204,203,200_.jpg
creator:: Nassim Taleb
priority:: Medium
purpose:: Execution, Strategy
referrer:: CEO Summit (june 2016)
status:: To Read
subtitle:: Things That Gain from Disorder
tags:: #source/books 
```

```
# Decisive

cover:: https://images-na.ssl-images-amazon.com/images/I/41v78m7Yt3L._SX333_BO1,204,203,200_.jpg
priority:: Medium
purpose:: Productivity
referrer:: Steve Graves Blog
status:: Read - Audio
subtitle:: How to Make Better Choices in Life and Work
tags:: #source/books 
```

My dataview version:
![image](https://user-images.githubusercontent.com/113870/168871698-9e3df5db-4565-4f50-8a1e-55a3455995b5.png)

Obsidian version:
![image](https://user-images.githubusercontent.com/113870/168871736-5c597006-4c3c-4108-a6a9-2f26ced52245.png)

**Comment by RafaelGB** [comment]
I will check the dataview repo and I'll look for "inspiration" =P
