### ISSUE TITLE
Link and backlink columns

### ISSUE THREAD

**Issue by isle9** [RafaelGB/obsidian-db-folder#170]
**Is your feature request related to a problem? Please describe.**
I'd like to see my links and backlinks directly in the database similarly how we can see our tasks there.

**Describe the solution you'd like**
Basically the same things as tasks, just for links and backlinks.

**Comment by RafaelGB** [comment]
included =) 

https://user-images.githubusercontent.com/11924043/189533911-726129db-c88a-4176-a5fe-203aa5506291.mov
