### ISSUE TITLE
[[Link]] in text field

### ISSUE THREAD

**Issue by balola** [RafaelGB/obsidian-db-folder#173]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by balola** [comment]
Hi,
Is it possible to write [[Link]] of md document in text field?
Füles

**Comment by RafaelGB** [comment]
Hi @balola , should be possible right now, there is not helper with autocompleting, but if you write the file should work

**Comment by RafaelGB** [comment]
Closing this one
