### ISSUE TITLE
template suggester too narrow

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#175]
**Describe the bug**
You can't see clearly the template when choosing between the files because the suggester is too narrow

**Expected behavior**
That there is enough space to see which template you're selecting

**Screenshots**

https://user-images.githubusercontent.com/38974541/176724614-0707bfe9-7476-4f8f-9b0b-77edfe1797f5.mov

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Obsidian 0.14.15

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/177 cover this one too
