### ISSUE TITLE
template suggester support for dark mode

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#177]
**Describe the bug**
the template suggester isn't adapted to work with dark mode (unlike the tag suggester), also the text isn't readable.

**Screenshots**

https://user-images.githubusercontent.com/38974541/176871924-e3931202-b716-4462-85fd-290f8ec9d620.mov

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Obsidian 0.14.15

**Comment by RafaelGB** [comment]
sure! added as visual

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/181275120-97659c5d-6917-439b-8619-b8e3137e7a2c.mov

After the improvements of design. I cover this issue too
