### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by ooker777** [RafaelGB/obsidian-db-folder#181]
Two of my Android phones are unable to loading the vault. If I move the dbfolder plugin outside the vault then they work again. What is more interesting is that your latest update 1.8.0 released two days ago. My phones only crashed yesterday, and it should be updated. (Or is it that BRAT updates slowly?)

Obsidian Android v1.2.2 in Android 5.1.1 and 7.1.1.

**Comment by RafaelGB** [comment]
Mobile Support is not ready yet. With BRAT its Possible to install it but not recommended

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/27

This is the current Issue. Clossing the new one

**Comment by ooker777** [comment]
Hmm but as you mentioned in the other thread the setting for running in mobile is false. Why can it still crash the app?

**Comment by RafaelGB** [comment]
the BRAT beta version is enabled to test it, use the official one instead
