### ISSUE TITLE
DB-folder inserts "true" instead of correct data

### ISSUE THREAD

**Issue by isle9** [RafaelGB/obsidian-db-folder#182]
**Describe the bug**
Sometimes db-folder inserts "true" into the field instead of inserting correct information like the date, tag etc.

**To Reproduce**
The bug isn't 100% reproducible since I don't know what's causing it.

1. Create a field.
2. Go to db-folder and set the type to whatever you want.
3. Input some data into the cell.
4. Occasionally DB folder just inputs true instead of whatever you've inputted.

**Desktop (please complete the following information):**
 - OS: [Win 11]
 - Version [e.g. 1.8.0]

**Comment by RafaelGB** [comment]
I will tag this feature on review until know how to reproduce it, if this happens to me, I will comment about it.

Thanks @isle9

**Comment by shamfold** [comment]
Hi,
I think I am getting the same issue and I think I have found how to reproduce it every time. I wasn't sure if I should raise a new issue or not but I though it best to comment on this issue instead, I apologize if that was wrong.

**To Reproduce**
When trying to use db-folder to update inline frontmatter from an initial value, the inline frontmatter field is instead permanently set to "true".

**Screen Recording**
> https://user-images.githubusercontent.com/108768328/177430000-5b51214b-6470-498a-a8d0-1c2e96d0009c.mp4

**Desktop (please complete the following information):**
- OS [Windows 10]
- Obsidian [0.14.15]
- db-folder [1.8.2]

**Comment by isle9** [comment]
@RafaelGB Will you be able to fix this before you start working on the new react table?

**Comment by RafaelGB** [comment]
I will give support just to bugs. Will try to reproduce it with @shamfold indications

**Comment by arminta7** [comment]
This is happening for me as well.

**Comment by RafaelGB** [comment]
Working on it. Now that the migration core is done I can return to support this issues

**Comment by javiavid** [comment]
+1

**Comment by RafaelGB** [comment]
fixed. Will be added with the official 2.0.0
