### ISSUE TITLE
Migrate plugin to react-table v8 + react18

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/obsidian-db-folder#189]
react-table v8 is stable now. The advantages of the version are too much important and all the issues have to wait until this is done

**Comment by RafaelGB** [comment]
Due to the scale of this task, a separate project will be generated
https://github.com/users/RafaelGB/projects/3/views/1

**Comment by RafaelGB** [comment]
The core of the table is already migrated. Now we have to work on the user interface, since the current one with the flex strategy is not supported

<img width="1919" alt="Screenshot 2022-07-12 at 21 07 34" src="https://user-images.githubusercontent.com/11924043/178574540-3b67455d-cc49-4ba9-947a-f04e16e1f8ff.png">

fun fact: With new version there is a native debug logs!

**Comment by RafaelGB** [comment]
btw: the DnD columns is removed (now supported with react18) and will be implemented from start with https://github.com/react-dnd/react-dnd/

**Comment by RafaelGB** [comment]
responsive table migrated and working, edition included.

<img width="1710" alt="Screenshot 2022-07-13 at 21 18 07" src="https://user-images.githubusercontent.com/11924043/178814043-509c70d9-3278-44fc-b67c-23f010e9ae45.png">

note: the objetive of 2.x.x its to migrate the actual dispatch strategy to https://github.com/pmndrs/zustand

**Comment by RafaelGB** [comment]
Far from perfect yet, but The DnD was reconstructed with another technology and its "working"
Compatible with resizing columns too!


https://user-images.githubusercontent.com/11924043/179350670-baf23fa1-97b9-4d68-bc2b-681f205a8c65.mov

**Comment by RafaelGB** [comment]
The core of the migration is finished I will prepare a beta this week

**Comment by Gentleman03** [comment]
Hey @RafaelGB I have table with 118 files and field add new barely works. It's incredibly laggy and easily freezes obsidian app. I have tried 1.8.2 and 2.0.0 beta 2 and it's the same. I have noticed that if I have put something into search and number of displayed books is smaller it doesn't lagg that bad as with whole table but it's still quite a significant lagg.

**Comment by RafaelGB** [comment]
hi @Gentleman03. Open a discussion and share your ddbb markdown file please. Will be attended properly

**Comment by Gentleman03** [comment]
> hi @Gentleman03. Open a discussion and share your ddbb markdown file please. Will be attended properly

Sorry for the delay. I would like to keep my DB private so if that's ok I can upload it somewhere and I'll send you a link. I'll just need an email adress or any other contact channel.
