### ISSUE TITLE
FR Support dates older than 2001 and/or partial dates

### ISSUE THREAD

**Issue by brimwats** [RafaelGB/obsidian-db-folder#191]
I'm trying to add a date column for a system that developed in 1995. I'd like to add just "1995" but it seems the oldest date allowed is 2001-01-01. It would be nice if we could use just YYYY or at least YYYY-MM-DD older than 2001 ! :)

**Comment by RafaelGB** [comment]
While the request reaches a release, you can edit the data manually in the cell itself (with a change it closes, but it allows you to modify at least one number)

**Comment by RafaelGB** [comment]
by default, the react-datepicker set that date when your write an invalid one, but you can edit it manually

Closing the issue
