### ISSUE TITLE
The user input is silently not saved  if yaml cannot be parsed

### ISSUE THREAD

**Issue by danieltomasz** [RafaelGB/obsidian-db-folder#196]
**Describe the bug**
- Create database with a file where yaml is corrupted, for example with `title: "title` (no quote)
- create a new column, and try to put some value there
- the value is not saved, and there is no notification about an error
Obsidian 0.15.4, plugin 1.8.2
Also why the quotes are removed from string ?
`title: "Title"` is becoming `title: Title`

**Comment by danieltomasz** [comment]
Also I  was able to identify use cases where plugin fails
For example, someone might use this schema with title  `title:'@title'` single quoted yaml which is a proper yaml entry, but the plugin is failing on it (the `title:@title` with plain scalar is not a proper yaml)
https://www.yaml.info/learn/quote.html

**Comment by RafaelGB** [comment]
I am using the ParseYaml function of Obsidian + Dataview Inline search for inlines.

The value requires an space after `:` to work

**Comment by danieltomasz** [comment]
I think it doesnt work because your plugin strip quotes from scalars, `title: '@title'` is a valid yaml entry but `title: @title` is not

You could compare results
```
---
title: title
Topic: topic
---
```
![image](https://user-images.githubusercontent.com/7980381/177974606-e2b47b45-0601-44e2-b2d3-6122b50c851c.png)

with 
```
---
title: '@title`
Topic: topic
---
```
![image](https://user-images.githubusercontent.com/7980381/177974797-58a3d1ca-4ccb-4b11-bdba-12374681f6df.png)

**Comment by RafaelGB** [comment]
I just test '@value' and works with 1.8.2

Notice that in your sample there are different types of quotes wrapping the value

` instead of '

**Comment by danieltomasz** [comment]
indeed, sorry for the confusion!

**Comment by RafaelGB** [comment]
Do not worry, I am happy to help!

About the error handler will takes time. The migration of react-table version and react will take 2 months aprox... But will be worth for sure!
