### ISSUE TITLE
Date box changes size

### ISSUE THREAD

**Issue by erankatz2020** [RafaelGB/obsidian-db-folder#197]
Hi there. I wanted to share a problem with the date box. When you scroll between months, if a month has 5 weeks instead of 4, the box is larger, and the arrow buttons change location, which is quite annoying if you want to move quickly between many months. See attached screenshot video: 
https://www.loom.com/share/97323468e3e44ed58421b30069853d4f

Also, if it would be possible to enter a date manually like in Notion (maybe using something like the Natural Language Dates in Obsidiain) it would save a lot of trouble.

Thanks! This is an awesome plugin.

**Comment by imeed166** [comment]
With the new theme, the date box doesn't change size, so this issue is reloved @RafaelGB.
