### ISSUE TITLE
Obsidian community plug-in release

### ISSUE THREAD

**Issue by jasmeetchadha** [RafaelGB/obsidian-db-folder#20]
Hi - it would be great if you would make a obsidian community release for rookies like me to install. I think an early release should also help get critical mass (perhaps attract more developers) into the project. 

Do you have a rough idea on when might you plan to release it in community plug-in (for easy install)? 

Thanks again!

**Comment by RafaelGB** [comment]
Hi!  I am working on a stable version with a huge reworking of some things

Its taking more time that was expected, but I think the result will be astounding.  I expect to get it ready in May I hope.

<img width="1051" alt="Screenshot 2022-04-30 at 18 44 14" src="https://user-images.githubusercontent.com/11924043/166114623-74f7c16d-2dfc-477d-9681-28d807fd0f17.png">

The roadmap is:
- [X] CSV download button
- [X] Add frontmatter/column key if does not exist in file (that's a big change)
- [X] custom CSS that does not break another plugins
- [X] The headers are static if you scroll down
- [ ] Auto resize of columns in function of size (This is my big problem right now....)
- [ ] Table navBar at the top with the style of your obsidian theme
- [ ] Unitary test

**Comment by RafaelGB** [comment]
Once I get all the points, I will request the release to the community =)

**Comment by boettges** [comment]
Off-topic: Why is the repo called "bd folder"? Just a typo or intentional?
I just installed the 0.0.7 and was searching my list of installed plugins for "bd" returning no result until I realized that the `manifest.json` defines the plugin's name as "DB Folder", which makes way more sense.

**Comment by RafaelGB** [comment]
jaja, because I am from Spain and database is said "base de datos"(bd)

I changed the language of both the comments and the project over time, but the title persist

**Comment by RafaelGB** [comment]
I will try to change before the official release

**Comment by boettges** [comment]
Ahhh, tiene sentido 👌
Thank you for clarifying

**Comment by RafaelGB** [comment]
Changed it!  dunno that rename repos was so easy

**Comment by jasmeetchadha** [comment]
> Hi! I am working on a stable version with a huge reworking of some things
> 
> Its taking more time that was expected, but I think the result will be astounding. I expect to get it ready in May I hope.
> 
> <img alt="Screenshot 2022-04-30 at 18 44 14" width="1051" src="https://user-images.githubusercontent.com/11924043/166114623-74f7c16d-2dfc-477d-9681-28d807fd0f17.png">
> 
> The roadmap is:
> 
> * [x]  CSV download button
> * [x]  Add frontmatter/column key if does not exist in file when you edit a cell (that's a big change)
> * [x]  custom CSS that does not break another plugins
> * [x]  The headers are static if you scroll down
> * [ ]  Auto resize of columns in function of size (This is my big problem right now....)
> * [ ]  Table navBar at the top with the style of your obsidian theme
> * [ ]  Unitary test

Thanks Rafael. Looking forward to the community release in May. Lots of hugs from Fuertaventura (holiday)

**Comment by RafaelGB** [comment]
I just applied for the PR of the plugin. Hope you can enjoy it soon as official plugin!!

**Comment by jasmeetchadha** [comment]
Gracias, looking forward to it!

**Comment by RafaelGB** [comment]
I am happy to announce that the plugin is officially released!

**Comment by jasmeetchadha** [comment]
Great! Look forward to trying tonight!
