### ISSUE TITLE
Table doesn't show in hover editor

### ISSUE THREAD

**Issue by dcoales** [RafaelGB/obsidian-db-folder#201]
If I hover over a link to a database file then the hover editor appears but is empty.  To see the grid I have to switch to markdown mode and then back to database view at which point the table renders correctly.

This happens to me on a windows desktop running version 0.15.4 of Obsidian, version 1.8.2 of DB Folder and version 0.10.7 of Hover Editor.

Awesome plugin BTW !

**Comment by RafaelGB** [comment]
The hover link of the database just render a dataview table (read only)
https://github.com/RafaelGB/obsidian-db-folder/issues/41

not sure if hover edition supports wraps on the same hover action ( same strategy of excalidraw plugin)
