### ISSUE TITLE
Blank Names Ruin Database Folder

### ISSUE THREAD

**Issue by ProStashio** [RafaelGB/obsidian-db-folder#203]
**Describe the bug**
When you are editing a database folder and you are editing one of the sections if you leave it blank either because you accidentally move away or because you go to copy and paste something it stops the whole database folder.

**To Reproduce**
If applicable, add your configuration YAML of your database to reproduce the bug

1. Go to 'Database Folder'
2. Click on 'Section'
3. Start to rename and leave blank

**Expected behavior**
There should be some backup where if it is blank it leaves it blank or leaves the name that was last used that worked.

**Screenshots**
https://gyazo.com/e71484c6601f578637f6c3c202a93319

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Obsidian Version 0.15.6

**Comment by RafaelGB** [comment]
hi @ProStashio 
Thanks for the report, will be added to the roadmap and fixed with 2.0.0

All the issues are frozen until the migration to react 18

**Comment by RafaelGB** [comment]
self reminder: Controlling empty inputs should resolve the issue

**Comment by RafaelGB** [comment]
Provisionally you can remove the column manually from the markdown

Just remove the block that starts with `:`
