### ISSUE TITLE
Position of the "Add Row" button 

### ISSUE THREAD

**Issue by DaniluFx** [RafaelGB/obsidian-db-folder#206]
It would be really useful that the position of the "Add Row" button was at the top and not at the bottom, because as your database grows you have to scroll down and down just to add another row.

Also It would be nice to have a "Dataview LIMIT filter" like, to show just the last n-rows created.

**Comment by RafaelGB** [comment]
Hi @DaniluFx, thanks for your comment.
About the fisrt petition, with 2.0.0 the add row form will be sticky just like the headers but at the footer. I leave the issue open to follow up on the task

The second one will be added with the pagination https://github.com/RafaelGB/obsidian-db-folder/issues/116

Currently you can use the dataview query source and add the limit filter

**Comment by RafaelGB** [comment]
After refactoring navbar and new row button css. This issue will be covered.

Will be included with 2.0.0

**Comment by RafaelGB** [comment]
Opinions?

https://user-images.githubusercontent.com/11924043/181265399-5d3cc017-6c28-49e9-a883-c1e97cd6af1e.mov
