### ISSUE TITLE
new text is misaligned (beta)

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#208]
**Describe the bug**
the text `new` is below the `+` icon instead of beside it.

**Screenshots**
![image](https://user-images.githubusercontent.com/38974541/180263696-548cd8b3-0183-4e20-9057-26a57f14cd29.png)

**Desktop (please complete the following information):**
 - macOS 12.3.1
 - Obsidian 
 - DB folder 2.0.0-beta.1

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/220
