### ISSUE TITLE
Field values being added (beta 2.0.0)

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#209]
**Describe the bug**
Plugin adds incorrect field values. They get added again even when deleted. In the below screenshot the ```label: "High, \-"``` value was not added by the user. 

**Screenshots**

<img width="505" alt="Screen Shot 2022-07-21 at 16 02 34" src="https://user-images.githubusercontent.com/7927356/180305089-3668b531-fcad-4a0c-8b5a-c3bba1ca632e.png">
<img width="706" alt="Screen Shot 2022-07-21 at 16 04 30" src="https://user-images.githubusercontent.com/7927356/180305457-62ce3481-bf35-4e03-b958-6e6c2954fe90.png">
<img width="371" alt="Screen Shot 2022-07-21 at 16 04 54" src="https://user-images.githubusercontent.com/7927356/180305519-46c39d9d-3243-4ac7-bc56-545c31ce3f97.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.3
 - Version 2.0.0-beta.2

**Comment by RafaelGB** [comment]
added to release 2.0.0 project

**Comment by RafaelGB** [comment]
duplicates are better controlled. Ready for the next iteration of beta

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/220
