### ISSUE TITLE
Template Parsing Issue when Using Folder Note

### ISSUE THREAD

**Issue by brimwats** [RafaelGB/obsidian-db-folder#21]
When I try to make a DB Folder from I get bunch of errors, mostly like

```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at OnFileModifyAutomatorManager.onFileModify (eval at <anonymous> (app.js:1:1502790), <anonymous>:5266:29)
```

and a templater one

```
VM152:82 Templater Error: Template parsing error, aborting. 
 Bad template syntax

Unexpected token '%'
====================
var tR='',__l,__lP,include=E.include.bind(E),includeFile=E.includeFile.bind(E)
function layout(p,d){__l=p;__lP=d}
const _prs = [];
tR+='---\n\ndatabase-plugin: basic\n\n---\n\n'
_prs.push(%
columns:
 column1:
  input: text
  key: column1
  accessor: column1
  label: Column 1
  position: 0
configuration:
 enable_show_state: false
%);
tR+='rJ2KqXzxQg'
const _rst = await Promise.all(_prs);
tR = tR.replace(/rJ2KqXzxQg/g, () => _rst.shift());
if(__l)tR=await includeFile(__l,Object.assign(tp,{body:tR},__lP))
if(cb){cb(null,tR)} return tR
```

The resulting file is called like `Untitled database` and looks like this:
![image](https://user-images.githubusercontent.com/73113656/166237077-f131a6ab-804f-44bd-95e3-95edf356ff26.png)

I suspect this is becvause I use Folder Note (https://github.com/aidenlx/folder-note-core) and / or Waypoint plugin. So this bug report is for compatibility with other plugins

I suspect that this is because I use Folder Note (https://github.com/aidenlx/folder-note-core), so

**Comment by RafaelGB** [comment]
Hi @brimwats ! thanks for your report.

This is a known compatibility error with Templates plugin when you have the next flag activated

<img width="611" alt="Screenshot 2022-05-02 at 15 04 20" src="https://user-images.githubusercontent.com/11924043/166238359-0ae47f8a-c644-4593-aa91-ff0b35092985.png">

But the file creation should be the same cause no template is executed. Does your files have those names (-oid,10. Root Words,...)?

**Comment by brimwats** [comment]
Thanks for the comment!

>  Does your files have those names (-oid,10. Root Words,...)?

yes! they're word stems :)
