### ISSUE TITLE
resizing column doesn't work right (beta)

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#210]
**Describe the bug**
I'm sure you are already aware of this. But just to make it easier to track, here's what I found :
- When selecting the line, instead of resizing, it moves the column
- when resizing last column, the "+" column is affected and becomes smaller with resizing.

**Expected behavior**
- When selecting to resize, the column shouldn't move
- When resizing the last column, the "+" column shouldn't be affected.

**Screenshots**

https://user-images.githubusercontent.com/38974541/180306786-258f77d3-473e-4868-b210-4c59ce0c3927.mov

**Desktop (please complete the following information):**
 - macOS 12.3.1
 - Obsidian 0.15.6
 - DB folder 2.0.0-beta.2

**Comment by RafaelGB** [comment]
The lag is cause by saving the size in real time, have to achieve a better solution
added to realise 2.0.0 project

**Comment by RafaelGB** [comment]
Now instead of being persisted in real time, there is a timeout of 1,5secs of wait after the last edition

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/220
