### ISSUE TITLE
sorting time column doesn't work (beta)

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#212]
**Describe the bug**
When sorting the time column, the rows without time stay in between the ones that include time.

**To Reproduce**
1. create time column
2. add time to some rows
3. sort by time column

[test1.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162434/test1.md)
[test2.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162436/test2.md)
[test3.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162435/test3.md)
[test4.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162433/test4.md)
[test5.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162432/test5.md)
[test6.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162431/test6.md)
[test7.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162430/test7.md)
[test8.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162428/test8.md)
[testing database.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162429/testing.database.md)

**Expected behavior**
Rows with time should be sorted before/after rows without time.

**Screenshots**

https://user-images.githubusercontent.com/38974541/180305037-88394202-0c2f-4a69-9a14-9c36c987c662.mov

**Desktop (please complete the following information):**
 - macOS 12.3.1
 - Obsidian 0.15.6
 - DB folder 2.0.0-beta.2

**Comment by RafaelGB** [comment]
added to 2.0.0 release project

**Comment by RafaelGB** [comment]
Fixed, the actual version of react-table do not support nullable values with the alphanumeric sorting function.

I generated a custom one:
```ts
import { Row } from "@tanstack/react-table";
import { RowDataType } from "cdm/FolderModel";

function customSortingFn(rowA: Row<RowDataType>, rowB: Row<RowDataType>, columnId: string): number {
    const a = rowA.getValue(columnId);
    const b = rowB.getValue(columnId);
    if (areEqual(a, b)) {
        return 0;
    }
    if (a == null) {
        return -1;
    }

    if (b == null) {
        return 1;
    }

    return fallback(a, b);
}
function areEqual(a: any, b: any): boolean {
    // It is necessary?
    if (a == null && b == null) {
        return true;
    }
    return a === b;
}

function fallback(a: any, b: any): number {
    return isNaN(a)
        ? a.localeCompare(b)
        : a - b;
}

export default customSortingFn;
```

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/220
