### ISSUE TITLE
tag column creates new options when refreshing (beta)

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#213]
**Describe the bug**
The tag column creates new options whenever I refresh the database. It duplicates the same options that were already presents with other colors.

**To Reproduce**
1. create tag column
2. add options
3. refresh database

[test8.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162388/test8.md)
[testing database.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162389/testing.database.md)
[test7.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162390/test7.md)
[test6.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162391/test6.md)
[test5.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162392/test5.md)
[test4.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162393/test4.md)
[test1.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162394/test1.md)
[test3.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162395/test3.md)
[test2.md](https://github.com/RafaelGB/obsidian-db-folder/files/9162396/test2.md)

**Expected behavior**
Don't duplicate tag options when refreshing database.

**Screenshots**

https://user-images.githubusercontent.com/38974541/180304255-bcaf7d3c-c76a-4aed-bd82-033ce17091fd.mov

**Desktop (please complete the following information):**
 - macOS 12.3.1
 - Obsidian 0.15.6
 - DB folder 2.0.0-beta.2

**Comment by RafaelGB** [comment]
duplicated with https://github.com/RafaelGB/obsidian-db-folder/issues/209
