### ISSUE TITLE
delay when dragging column (beta)

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#214]
**Describe the bug**
When dragging a column, there is delay before moving the column to its appropriate position.

**Expected behavior**
the column should move with the mouse drag.

**Screenshots**

https://user-images.githubusercontent.com/38974541/180303800-bdff144d-a107-43cf-a79d-0d96fe104e70.mov

**Desktop (please complete the following information):**
 - macOS 12.3.1
 - Obsidian 0.15.6
 - DB folder 2.0.0-beta.2

**Comment by RafaelGB** [comment]
Its cause by the position, not really delay but could be improved, sure

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/220
