### ISSUE TITLE
insert left and right doesn't work (beta)

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#216]
**Screenshots**

https://user-images.githubusercontent.com/38974541/180302965-4df34c1e-a795-4f0e-bd0e-b10506d0a0d9.mov

**Desktop (please complete the following information):**
 - macOS 12.3.1
 - Obsidian 0.15.6
 - DB folder 2.0.0-beta.2

**Comment by RafaelGB** [comment]
I cant reproduce the issue

https://user-images.githubusercontent.com/11924043/180470719-290374a7-a795-4414-a19e-730de34a8394.mov

**Comment by imeed166** [comment]
I tried it again with a clean vault, and still the same problem, nothing happens when clicking on `insert right/insert left`
dataview 0.5.41
DB Folder 2.0.0-beta.2
macOS 12.3.1
Obsidian 0.15.6
Installer 0.14.6

**Comment by arminta7** [comment]
I have the same issue.

**Comment by RafaelGB** [comment]
Maybe I fix it with another issue. Will be checked with the next beta iteration so. Thanks =)

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/220
