### ISSUE TITLE
[FR] Autosuggest/Autocomplete like Metadata Menu does

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#219]
Example: If I have a column named "Pillars", when I go to edit a cell in that column provide a dropdown with preloaded options for that field via Metadata Menu. I believe an API was just added for this?

Here's what the Metadata Menu autosuggest looks like:

<img width="383" alt="Screenshot 2022-07-22 at 11 50 05" src="https://user-images.githubusercontent.com/7927356/180476604-8987794a-3a89-4c6b-b3bc-3b2f384563d8.png">

**Comment by RafaelGB** [comment]
Hi @arminta7 , could be nice to implement the suggester like kanban plugin does, sure

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/107

Will be implemented in that issue. Closing this one as duplicated
