### ISSUE TITLE
Make it easier to create databases

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#22]
**Is your feature request related to a problem? Please describe.**
I'm sorry if I'm wrong and didn't read the documentation right, but I think it's pretty hard for new users to know how to write the query just right for the plugin to work.

**Describe the solution you'd like**
I see 3 different solutions :
1. A clear step by step on how to do that in documentation.
2. A command to create database directly without writing anything.
3. Include a way to write the query in dataview (users are already familiar with it) and display it as a database

(whatever is easier for you)

**Comment by RafaelGB** [comment]
Hi @imeed166 thanks for your suggestion. Right now the way to create a new database is the same way of the Kanban plugin.

<img width="283" alt="Screenshot 2022-05-02 at 17 38 29" src="https://user-images.githubusercontent.com/11924043/166263273-2cbfdcdd-3ff3-4cd3-bd84-3995cd7f36ba.png">

The documentation is not completed yet, just the base. I will work on it!

**Comment by imeed166** [comment]
Ah I see, thank you.
