### ISSUE TITLE
(BETA) Error selecting file template for autogenerate columns

### ISSUE THREAD

**Issue by kazdonkai** [RafaelGB/obsidian-db-folder#223]
The error message is shown in the image.

https://user-images.githubusercontent.com/90127278/181002356-95f5a7b0-01be-49b0-b313-1a33c4f58bf8.mov

**Comment by RafaelGB** [comment]
oh, I see. Know how to fix it! thanks for report

**Comment by RafaelGB** [comment]
I can not reproduce this problem. I thought it was caused by the wrap added to the config with https://github.com/RafaelGB/obsidian-db-folder/issues/207, but with new databases works nice
