### ISSUE TITLE
(BETA)[Bug]Adding an item doubles the number of columns

### ISSUE THREAD

**Issue by kazdonkai** [RafaelGB/obsidian-db-folder#224]
As you can see in the image #223, when I added 9 items, the column doubled and the message to add 18 items appeared.
Although not shown in the image, when I looked at the completed case, the beginning of the column became two types of columns, one with uppercase letters and the other with lowercase letters, doubling the number of columns.

**Comment by RafaelGB** [comment]
yeah, dataview duplicates the number of fields playing with caps.

Was controlled with the other template option.

I will control the duplicates with that too

thanks!
