### ISSUE TITLE
Cannot change Property Type on columns

### ISSUE THREAD

**Issue by MrFlomi** [RafaelGB/obsidian-db-folder#229]
**Describe the bug**
When I put my cursor on the Property Type value of a column inside a databse, no menu is opened. Clicking does not solves this. Deleteing and Reinstalling the plugin does not solve. Creating new DB does not solve. Updating does not solve. This occurs only on one specific vault. 

I can change the property type manualy by edditing the DB code.

**Expected behavior**
Pressing the property type value would open a menu to choose from.

**Screenshots**
![image](https://user-images.githubusercontent.com/110223160/181707886-1d81d6d5-e6d3-45b9-a8e8-5fc38656f76f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by RafaelGB** [comment]
there may be some incompatibility with some other plugin. It seems to be working correctly with v2.0.1

<img width="460" alt="Screenshot 2022-07-29 at 10 15 32" src="https://user-images.githubusercontent.com/11924043/181715628-9a75bc9c-7ebf-4019-9102-343c09a1a4a0.png">
