### ISSUE TITLE
[FR]Add columns from the template on the right side

### ISSUE THREAD

**Issue by kazdonkai** [RafaelGB/obsidian-db-folder#230]
Adding columns from the header template will add them to the left of the existing columns. However, this is contrary to normal column addition behavior.
Now we need to move the most important “File” column to the left side.
So, as the title suggests, could you please consider making the newly added columns be added on the right side?

**Comment by RafaelGB** [comment]
using a template replaces existing columns with new ones. By default, the metadata is included at the end. In case of moving the File column, Created, Updated & Tasks would be moved in the same way. It would require a refactor on how they are managed, but I will consider it

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/201479882-8de05326-beb0-4825-90aa-9db4454dfe2e.mov

@kazdonkai opinions? =)


Now the template does not replace the entire ddbb columns. Just add the not existing one
