### ISSUE TITLE
External File Links do not open but instead try to edit

### ISSUE THREAD

**Issue by JamesRuss** [RafaelGB/obsidian-db-folder#232]
To recreate:
Create a new column (i'm using an inline field), then ctrl+drag a file or folder from windows file explorer to the inline field. It pastes like this
folder:: [Alcuin the Witchunter - Presupported](file:///D:%5C3d%20printing%5CArchvillian%5CSinister%20Vault%5CAlcuin%20the%20Witchunter%20-%20Presupported)
When selecting this link from the database folder view it only attempts to edit the text instead of opening/navigating to the link.
![image](https://user-images.githubusercontent.com/50726121/181921095-bd1ebd1b-0064-43a1-ae82-64776e714ea0.png)

**Comment by JamesRuss** [comment]
To add to this, the ctrl+drag actually breaks when DB Folder is enabled and I can no longer add new links. When I disable the plug-in and restart obsidian ctrl+drag begins to work again.

**Comment by RafaelGB** [comment]
Hi @JamesRuss ,
I just try to reproduce this issue and works fine with inline and front matter links

https://user-images.githubusercontent.com/11924043/181968473-a6a3ad9a-73be-41dc-816b-f1324f475154.mov

I don't know if there is another incompatibility with other plugin.

Could you share your installed plugins?

**Comment by JamesRuss** [comment]
Hi, links to websites work fine for me like you've shared in your video. The link that doesn't work is link's to files saved on my computer. If I control+drag a file or folder to obsidian it creates a file:/// link that opens either the file in the default app or the folder in file explorer when selected. These links do not work in folder db and while the add-on is enabled ctrl+dragging to create these links do not work either.

I have disabled all other add-ons, themes, css snippets and attempted it in a new vault with the same results.

Thank you,

**Comment by RafaelGB** [comment]
Oh I see. Will be added to the roadmap. Thanks for the report

**Comment by RafaelGB** [comment]
I can not reproduce this on my MacBook. I will change this issue to a "feature" cause this functionality was not contemplated 

Had a low priority right now

**Comment by RafaelGB** [comment]
Commit 4a422ad2

ready for the next version!
