### ISSUE TITLE
[BUG] Queries no longer working

### ISSUE THREAD

**Issue by rapatel0** [RafaelGB/obsidian-db-folder#233]
**Describe the bug**
Upon upgrade from 1.8.2 to 2.0.1, all of my query tables are broken. Manually reverting sometimes fixes the problem, but I think something is wonky because it doesn't always fix the issue.

I think it has something to do with the string processing of the YAML within the db-folder configuration. All of my queries have double quotes and they all break. Previous versions of `db-folder` didn't put double quotes in the configuration. See the image 

**Error**
<img width="281" alt="image" src="https://user-images.githubusercontent.com/18704704/182046719-70e52a97-f1c6-4f06-bf19-4c3beafc0e6b.png">

**Quotes in Config File
<img width="420" alt="image" src="https://user-images.githubusercontent.com/18704704/182046749-16055c0e-527c-456b-887e-b8fb4424f623.png">

**To Reproduce**

All of the queries continue to work when used with standard dataview blocks.

**Queries that reproduce the error**
1. `from "/" where contains(tags, "Framework")`
2. `from "Operations/Calendar/Daily" where all(contains(tags, "Meeting"),(file.ctime >= date(today) - dur(30 day)), !Ignore)`

**Desktop (please complete the following information):**
 - OS: Mac OS 12.5

**Comment by RafaelGB** [comment]
hi @rapatel0 

With 2.0.0 it is necessary the quotes with configuration. 

if dataview does not support single quote with your query, We can work on save the internal quotes as `\”` so it can be read with yaml

**Comment by rapatel0** [comment]
Manually editing the database settings results in this error and then forces `current_folder` mode. 

<img width="275" alt="image" src="https://user-images.githubusercontent.com/18704704/182067330-5667583f-b26d-4baf-bc5f-d7bcb9ecede0.png">

If I then `open as Markdown` the escape characters that I put in for the quotes are removed. I've also tried using single quotes for the whole yaml string and individually for the sub strings. Neither works




As a **side** note, I also encounter this issue where the settings panel becomes useless

<img width="999" alt="image" src="https://user-images.githubusercontent.com/18704704/182067050-ebfc4971-fcae-4350-ae16-e1cce726acc1.png">

Always happens when the query doesn't work. Not sure if this is intended behavior

**Comment by rapatel0** [comment]
Then Attempted with the query validator in settings and got this result. Looks like it's not processing the escape

**Note: Used a simpler Query** `from \"Areas\" where contains(tags, \"Frameworks\")`


<img width="290" alt="image" src="https://user-images.githubusercontent.com/18704704/182068157-09510031-ea1d-4336-845b-3547065d4234.png">

**Comment by jcdeichmann** [comment]
@RafaelGB great work on this plugin. I love it! I was running into this same issue and after pulling the repository and playing around I was able to fix it by escaping/unescapeing special characters in strings in the `UnmarshallConfigHandler` and `MarshallConfigHandler`. If you'd like I can put up a PR for my changes sometime today/tomorrow. I don't think I have access to the repository right now.

**Comment by RafaelGB** [comment]
Hi @jcdeichmann will be very welcome!

I am currently focusing on https://github.com/RafaelGB/obsidian-db-folder/issues/227 where I am redoing how all events are managed to be more scalable and testable, so the PR will be approved but its possible that could be conflicts.

In this case, I will consult you in this thread if it is not a bother

**Comment by jcdeichmann** [comment]
Here's the PR: https://github.com/RafaelGB/obsidian-db-folder/pull/234
