### ISSUE TITLE
Integration with Obsidian tag function 

### ISSUE THREAD

**Issue by wcsolski** [RafaelGB/obsidian-db-folder#238]
Hi, thank you for developing this plugin. I really like the functionality and everything. 

I wonder if you can integrate the tag column with the Obsidian tag function, because I find that when I add tags in the column, it seems to not appear in the Obsidian tag system. Similarly, I couldn't configure the tags I created previously to the tag column. 

May I know if this feature could be added to the plugin? 

Kind regards,
Solomon

**Comment by RafaelGB** [comment]
HI @wcsolski , Thanks for using the plugin and contributing ideas to the project.

## first one
Currently there are two ways to integrate them with obsidian. Call you column "tag"

This will be the acpect
```
'''
tag:
 - atag
 - anothertag
 - anotherothertag
'''
```
## second one
With an inline column, just add `#` to the name of your tag
This will be the aspect
```
'''
'''

myInlineColumn:: #atag, #anothertag, #anotherothertag
```

**Comment by wcsolski** [comment]
Thank you!
