### ISSUE TITLE
[2.1.x BETA] Columns are created on the left

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#240]
When you create a new column, it appears on the left instead of on the right.
Also when you create a new column the last column shifts to the left.

https://user-images.githubusercontent.com/7627504/182825048-2fc44190-9ab0-4ebd-bc78-492a1e6d85cb.mp4

**Comment by javiavid** [comment]
Notice at 00:16 what happens to column 3, move column 4 to the end, column 3 goes to the beginning automatically.

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/pull/243 fixed
