### ISSUE TITLE
Use with Dataview or other type of query instead of folder

### ISSUE THREAD

**Issue by AMGMNPLK** [RafaelGB/obsidian-db-folder#242]
I'm not a friend of managing notes by folders, I rather MOCs. We are many who prefer this way. It could be possible to give the option of doing a search, or maybe in the overall vault with filters (a concrete field in the note, ideally, or a tag, string...).

**Comment by RafaelGB** [comment]
Hi @AMGMNPLK  You already can use dataview queries as a source of your table
Open the settings of your table and select the query source option, then write your query (starting with FROM, cause the columns will be autoadded with your ddbb columns)
<img width="599" alt="query" src="https://user-images.githubusercontent.com/11924043/182852172-453c748d-864d-4e1d-881a-b4aa065e9466.PNG">
