### ISSUE TITLE
Empty spaces and alignment

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#244]
The space it leaves in the cells (blue lines) seems a bit random and there is a lot of variation in alignment (red lines).
I think that to make them easier to see the tables should be unified automatically when created.

![image](https://user-images.githubusercontent.com/7627504/182879999-d9e0199e-0efe-4fc1-b529-3908286b955c.png)

**Comment by RafaelGB** [comment]
this is intentional and tied to the column type as a design decision to better distinguish types

**Comment by javiavid** [comment]
Ok, maybe the problem is the size (blue lines). For example, look at the difference between Budget and Hours or between Modified and Deadline.

**Comment by RafaelGB** [comment]
yeah, you can adjust the size now, therefore it is no longer controlled that it is homogeneous
