### ISSUE TITLE
[2.1.x BETA] Column name and order bug

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#247]
When trying to modify the name of a column, it does not save it correctly and the order of the columns is changed.

https://user-images.githubusercontent.com/7627504/182889110-7026f445-9a03-486c-8de2-6d7cf88f1d18.mp4

**Comment by RafaelGB** [comment]
fixed using the actual table columnOrder, not the state of zustand
```ts
// Update state of ordered
    const updateOrderWithNewKey = table.options.state.columnOrder.map((o) =>
      o === column.id ? newKey : o
    );
    table.setColumnOrder(updateOrderWithNewKey);
``
