### ISSUE TITLE
[2.1.x BETA] YAML error when changing the name of a column

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#248]
**Attached also the database**
[Freelance Jobs.zip](https://github.com/RafaelGB/obsidian-db-folder/files/9261121/Freelance.Jobs.zip)

https://user-images.githubusercontent.com/7627504/182890567-a5fe90f9-4c85-4d0f-9c66-0e6a90b8ff50.mp4

**Comment by RafaelGB** [comment]
While I was investigating https://github.com/RafaelGB/obsidian-db-folder/issues/247 I find this bug. Was fixed

Was an error updating the column key in every row
