### ISSUE TITLE
[FR] inline field supported

### ISSUE THREAD

**Issue by pastorjack** [RafaelGB/obsidian-db-folder#25]
**Is your feature request related to a problem? Please describe.**
I use Dataview inline fields extensively instead of YAML. This plugin can't read them so I would have to convert all of my fields in my notes to make this work.

**Describe the solution you'd like**
I'd love for the plugin to read/write dataview fields as well as YAML.

**Comment by RafaelGB** [comment]
Hi @pastorjack thanks for your suggestion.

The support of inline field is already in my internal roadmap (I have to share it, sorry) . The search engine is data view already and you can read the fields, but edit is not supported. I will put this issue into the backlog

**Comment by pastorjack** [comment]
Thanks!!!

**Comment by RafaelGB** [comment]
This is the current behaviour:
If you have a inline field
<img width="278" alt="Screenshot 2022-05-03 at 21 49 13" src="https://user-images.githubusercontent.com/11924043/166554823-dd5af8c2-9c83-4788-9a69-7bb1bc9d8662.png">

and the column with that key exist, it will be displayed
<img width="1124" alt="Screenshot 2022-05-03 at 21 49 39" src="https://user-images.githubusercontent.com/11924043/166554990-024deaad-609e-4717-81c5-d4d37fbba9e9.png">

But if you edit it, a front matter key is created, and produce a conflict if you open again the database
<img width="288" alt="Screenshot 2022-05-03 at 21 49 51" src="https://user-images.githubusercontent.com/11924043/166555172-8e541f2e-964e-44c0-859e-d73dc3d29d6a.png">

**Comment by that0n3guy** [comment]
I have a bunch of inline fields as well.  I will say that mixing the two doesn't work well.  You probably already knew that, I'm just reporting what I'm seeing in 0.1.2.   For example:
![image](https://user-images.githubusercontent.com/113870/166722770-79ec9362-a3cf-4604-9712-37b16ec81c1e.png)

When I look at the DB folder table, the "create_date" doesn't display because its in frontmatter, but the other fields display. 
![image](https://user-images.githubusercontent.com/113870/166722975-d8bf3fb8-489e-4977-8545-b104869b0c89.png)

Editing doesn't work for either, but you already knew that :).

**Comment by RafaelGB** [comment]
I am considering tackling this task for the next version. It is a core design and it will be more difficult to approach the more time passes

**Comment by RafaelGB** [comment]
progress report:
I refactored the edit function to be more consistent and scalable. Actually the edition of inline fields works. 
![Screen Recording 2022-05-06 at 17 21 44](https://user-images.githubusercontent.com/11924043/167163408-84502d3e-effa-4c56-abec-912f59f4daa3.gif)

roadmap:
- [x] Refactor edit to use dataview API
- [x] Edit inline fields
- [ ] Modify key when you edit label of column
- [ ] Remove field when you delete a column

**Comment by that0n3guy** [comment]
Is removing the field when you delete a column the normal YAML functionality?  Does that happen only if its empty?  

I'm not sure this thread is the right place to ask this, but in many cases I don't want to delete the field and its data from the page.  Often times I'm just wanting to delete that column from the DB view.

**Comment by RafaelGB** [comment]
Okey, I will add that option to the backlog. Right now if you just want to remove the column of the db view you have to remove it from yaml configuration
<img width="898" alt="Screenshot 2022-05-06 at 17 57 17" src="https://user-images.githubusercontent.com/11924043/167169194-3058fa0c-2a68-4adc-9c16-58f6c84fc0e2.png">

**Comment by RafaelGB** [comment]
0.2.0 is out!
<img width="378" alt="Screenshot 2022-05-07 at 13 28 14" src="https://user-images.githubusercontent.com/11924043/167252283-510768fa-dd50-4b41-bd25-3be5f86c0ac2.png">

now every column has an adjustment section to mark as inline. The columns with * means that are inline

The documentation will be updated as soon as posible. Enjoy!
