### ISSUE TITLE
Causes in-line formula rendering errors

### ISSUE THREAD

**Issue by wuzhen97** [RafaelGB/obsidian-db-folder#250]
**Describe the bug**

Causes in-line formula rendering errors.
 I don't konw if it's a bug. but when I enable this plugin, the line which has a in-line formula breaks in the READING VIEW. 

**Screenshots**

In edit view, the display is normal：

![Edit View](https://user-images.githubusercontent.com/61906420/183029397-a14b3fbb-7b25-4dcd-9455-4afa52ceedbb.png)

In reading view, the display is abnormal

![Reading View](https://user-images.githubusercontent.com/61906420/183029648-2db43ada-f192-4561-9260-e4e250d4a21b.png)

**Desktop:**
 - OS: [windows]
 - Version [10]
- Obsidian: 0.15.9

**Additional context**

Looking forward to your reply, thinks

**Comment by RafaelGB** [comment]
Hi @wuzhen97 
This issue was resolved with https://github.com/RafaelGB/obsidian-db-folder/issues/228

Already available as a beta. Once the 2.1.x betas will be stable. I will release an official one
