### ISSUE TITLE
Inline key:: value metadata fields

### ISSUE THREAD

**Issue by m-beau** [RafaelGB/obsidian-db-folder#255]
Hi,

The only thing stopping me from using your package is the incompatibility with dataview-style inline metadata, which allows to incorporate **obsidian-valid** links and tags to the table fields!

It would be awesome if, on top of the YAML front matter, your plugin also detected key:: value syntax in notes (and edited them accordingly when changing data by clicking around in your notion-like databases, exactly as it currently works with YAML front matter).

Thanks!

**Comment by RafaelGB** [comment]
Hi @m-beau,
the plugin already have the compatibility with inline fields.

just open the column settings by clicking in the header that you want to and change the type to inline. I dont know if you are looking for it

**Comment by m-beau** [comment]
Oh fantastic, I missed that - thanks for your help!

**Comment by m-beau** [comment]
Hi, I came back to this plugin after a while, and realized that if the 'inline mode' is enabled for a specific column (or all by default), modifying a specific property in the database does not work as expected. Instead of editing the value in the "key :: value" expression in the .md file, it creates a new variable in the YAML front matter.

For instance, a note with the following inline text:

> type:: task
> status:: To Do

Will be overwritten by the following if the 'status' property is changed via the database view:

> ---
> status: "To Do"
> ---
> 
> type:: task
> 

By the way: the database is populated with a dataview query, my notes do not sit in a specific folder.

Thank you for your help.
