### ISSUE TITLE
Dataview query not working for folders

### ISSUE THREAD

**Issue by pramodam** [RafaelGB/obsidian-db-folder#256]
**Describe the bug**
If the source of database data is selected as "query", and Dataview query is given as: FROM "folder_name", it breaks it.
Seeing the markdown file, i believe the error is because there is already a double quote for the whole TABLE query and another double quote within for the folder name is breaking it.

**To Reproduce**

1. Go to 'Open Database Settings' from the db file's menu
2. Select Source of database data is selected as "query"
3. Enter Dataview query as FROM "give_any_folder_name_here"

**Expected behavior**
The query should take only the files from the folder.

**Desktop (please complete the following information):**
 - OS:  macOS BigSur
 - Version 11.6.7

**Comment by RafaelGB** [comment]
Hi @pramodam ,
This problem was already fixed with 2.1.0 on https://github.com/RafaelGB/obsidian-db-folder/issues/233 . Currently is not an official version, you can download it as a beta with BRAT plugin.

**Comment by pramodam** [comment]
Thank you for the quick reply. This is an amazing plugin. Very useful. Great work.
