### ISSUE TITLE
[FR]Option to display line numbers added

### ISSUE THREAD

**Issue by kazdonkai** [RafaelGB/obsidian-db-folder#258]
Options to display line numbers on the left edge of each database row would be helpful.

**Comment by RafaelGB** [comment]
Hi @kazdonkai , for technical purposes, the plugin already saves the number of the row, so display it should be easy.

I have my doubts about if it's helpful. Could be configurable as metadata column to enable/disable it

**Comment by kazdonkai** [comment]
Hi, there is a slight difference between what you stated and my idea.
In one of my databases I have about 500 or so files.
I wanted to add sequentially numbered columns to that database, but it was tedious to put the numbers in order, so I thought what could be a better way?
(As I recall, it didn't work properly, but I remember there was one in the previous version.)
With numbered columns, you can sort files into your own unique order by adding branch numbers to certain files. Imagine Zettelkasten.
You can also revert back to the numbered order after sorting by name, etc.

Since you mentioned that there are internal numbers, it would be useful to have the ability to transcribe those numbers to a column at a time.
