### ISSUE TITLE
[FR]: Metadata columns of created and updated

### ISSUE THREAD

**Issue by that0n3guy** [RafaelGB/obsidian-db-folder#26]
It would be nice to sort by dates... thus have a date column.

I typically use 3 types of dates:
- File create date (dataview file.ctime)
- file modified date (dataview file.mtime)
- a yaml date

I wouldn't want to be forced to have the file date column, but if it could be added when needed, its handy.

**Comment by RafaelGB** [comment]
About the first and second points could be added as metadata columns like file. Added with toggle button local configuration 🤔

The Third point is already considered in [this issue](https://github.com/RafaelGB/obsidian-db-folder/issues/24)

**Comment by RafaelGB** [comment]
progress report:
I refactored the edit function to be more consistent and scalable. Actually the edition of inline fields works. 
![Screen Recording 2022-05-06 at 17 21 44](https://user-images.githubusercontent.com/11924043/167163408-84502d3e-effa-4c56-abec-912f59f4daa3.gif)

roadmap:
- [x] Refactor edit to use dataview API
- [x] Edit inline fields
- [ ] Modify key when you edit label of column
- [ ] Remove field when you delete a column

**Comment by huyz** [comment]
Is it possible to use `updated` instead of `modified`? That's what I have everything configured to use.
