### ISSUE TITLE
Search Function Does Not Work With Tags

### ISSUE THREAD

**Issue by ProStashio** [RafaelGB/obsidian-db-folder#260]
**Describe the bug**
Search Function Does Not Work With Tags

**To Reproduce**
Try to search for a tag

Try to search for a tag

**Expected behavior**
Should show the items that have the searched tag

**Screenshots**
https://gyazo.com/ee55d66cf7d7ea104af4ef98a8ae003c

**Desktop (please complete the following information):**
Window 11

**Additional context**

**Comment by RafaelGB** [comment]
yeah, the search engine does not support lists. We have to find a way to adapt them.

Right now we the tags columns have the search disabled. This issue will be added to the roadmap

**Comment by RafaelGB** [comment]
Found a way to fix it.
```ts
{
// ---
// Hack to force react-table to use all columns when filtering
getColumnCanGlobalFilter: (column) => true,
globalFilterFn: globalDatabaseFilterFn(ddbbConfig),
// ---
}
```
Then use a custom filter to sanitize the not atomic values to something you can search
```ts
export const globalDatabaseFilterFn: (ddbbConfig: LocalSettings) => FilterFn<RowDataType> = (ddbbConfig: LocalSettings) => (
    row: Row<RowDataType>,
    columnId: string,
    filterValue: string
) => {
    const value = row.getValue<Literal>(columnId);
    if (value === undefined) {
        return false;
    }
    const sanitized = DataviewService.parseLiteral(value, InputType.MARKDOWN, ddbbConfig, true);
    return sanitized.toString().includes(filterValue)
}
```
https://user-images.githubusercontent.com/11924043/185078554-bbb7109e-a9e2-42dd-bc01-ae0cbac75316.mov
