### ISSUE TITLE
Search Feature Not Working when just one column is Number

### ISSUE THREAD

**Issue by yurijserrano** [RafaelGB/obsidian-db-folder#262]
**Bug Description:**
When only one column is set to type Number the Search Function stops working.

**To Reproduce:**

1. Change any column to the Number Type
2. Use the Search Feature
3. Search will not work

**Expected behavior:**

Show the  rows that end up having the term being searched

**Video:**

https://user-images.githubusercontent.com/14169134/184977406-7784adf9-8550-4963-b757-cbb37d60886d.mp4

**Desktop (please complete the following information):**
 - OS: Pop OS
 - Version: 22.04

If you have any further questions please let me know

I wish you a great day

**Comment by RafaelGB** [comment]
this is an already fixed bug but not published yet. The problem was about the filter. Cast all the cell to lowercase and some files did not supported it.

I will mark this as wont fix until 2.2.0 is published

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/260
