### ISSUE TITLE
Menu 

### ISSUE THREAD

**Issue by yurijserrano** [RafaelGB/obsidian-db-folder#264]
**Describe the bug**
The Menu button is not showing the options when pressed

**To Reproduce**
Just click on the menu button

**Video**

https://user-images.githubusercontent.com/14169134/185152898-d6b64383-2f64-421b-8f8a-edee17c180c3.mp4

**Desktop (please complete the following information):**
 - OS: Pop OS
 - Version: 22.04

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/263

Yeah - I was working on it. Its a problem with the new MUI version. Would be included with a minor version

Thanks for your report @yurijserrano

**Comment by yurijserrano** [comment]
Sorry Rafael you were faster than me

I saw some other bugs and I will be creating other threads.

**Comment by RafaelGB** [comment]
I really appreciate it!

**Comment by RafaelGB** [comment]
I found the reason here https://github.com/RafaelGB/obsidian-db-folder/issues/263#issuecomment-1218074457
