### ISSUE TITLE
"Select an existing column to add" option is missing.

### ISSUE THREAD

**Issue by riedelmethis** [RafaelGB/obsidian-db-folder#272]
[Untitled database.md](https://github.com/RafaelGB/obsidian-db-folder/files/9383803/Untitled.database.md)

**Describe the bug**
I attempt to add a new column for existing YAML fields in my folder. When I click the "+" button, I expect to see an option that says "Select an existing column to add." Actual result, this option does not appear.
Attaching two screenshots. One is from my test vault, where I copied the exact same folder structure, and I saw my expected results. The other screenshot is from my personal vault, where I do not see the expected results.
My personal vault is using the Minimal theme, but I have tried with the default theme as well.

**To Reproduce**
Here's an example of the YAML of one of my files
>firstn: John
>lastn: Smith
>contact: J
>tags: contacts/2022, contacts/family, contacts/fishing
>created: 2022-01-01
>banner: "![[John Smith.jpeg]]"
>alias: Johnny

1. Go to the Contacts folder in the folder navigation
2. Right click, select "New Database Folder"
3. On the top right corner of the database, click "+" to create a new column

**Expected behavior**
I expect to see the option to add data from existing YAML fields.
<img width="723" alt="Screen Shot 2022-08-18 at 11 01 39 AM" src="https://user-images.githubusercontent.com/79488636/185665411-18719a34-9528-4955-bc13-3d82acbc9c19.png">

**Screenshots**
The expected option is missing.
<img width="616" alt="Screen Shot 2022-08-18 at 11 01 31 AM" src="https://user-images.githubusercontent.com/79488636/185665475-f6e25ddb-b65f-466d-bfd4-67aa7ad21fe2.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.5
 - Apple M1

**Comment by RafaelGB** [comment]
I see you read the answer on reddit =)

Looks like an incompatibility problem inside one of your notes of that folder.
I also have your same OS with the same M1. Using the note as you wrote with the same config works well:


https://user-images.githubusercontent.com/11924043/185667948-4fd7a1af-35de-4116-8197-11dc9e141263.mov


Lets do a thing. Open the console of obsidian (cmd+option+i) then open the menu. With some luck the error will be printed

**Comment by riedelmethis** [comment]
Thank you for the fast response. A lot of errors popped up, I'll add them here. Adding as screenshots, because it's a lot.
<img width="1277" alt="Screen Shot 2022-08-19 at 12 52 47 PM" src="https://user-images.githubusercontent.com/79488636/185669041-dabddde1-b87c-49bb-8128-b03fcfb2b2bb.png">
<img width="1280" alt="Screen Shot 2022-08-19 at 12 52 57 PM" src="https://user-images.githubusercontent.com/79488636/185669045-d857f775-6d04-49ce-9f0d-249e046099ba.png">
<img width="1277" alt="Screen Shot 2022-08-19 at 12 53 07 PM" src="https://user-images.githubusercontent.com/79488636/185669048-14593943-5ef7-4594-ad10-2405336d6cce.png">

**Comment by RafaelGB** [comment]
looks like a loop inside the dataview query I will prepare it as soon as I can then we can try out of the database to see if the error is replicated. The logs looks like there is not a database folder bug

**Comment by RafaelGB** [comment]
Use this query in any file

'''dataview
TABLE file from "path/to/your/folder"
'''

**Comment by riedelmethis** [comment]
The query returns what I'd expect: a list of my files in the "Contacts" folder with every attribute/value for each file.

**Comment by RafaelGB** [comment]
my clue could go by the depth of the search that dataview does. Maybe from the application it is at 0 but from the API at n

Inside the console that you open before, use this command:
```
app.plugins.plugins.dataview.api.pages('"path/to/your/folder"')
```

**Comment by RafaelGB** [comment]
Any news with this issue?

**Comment by riedelmethis** [comment]
Hi Rafael,

I have not had the time to return to his issue. I hope to follow up with you more this week.

Thanks,
Nathan Riedel

------- Original Message -------
