### ISSUE TITLE
Appearance problems

### ISSUE THREAD

**Issue by zuluwi** [RafaelGB/obsidian-db-folder#273]
## Calendar Datepicker / Default theme
- Calendar shows up under "add row" options:

https://user-images.githubusercontent.com/111116092/185738980-31581e2c-63ca-4b4f-a416-f5a04d421a62.mp4

## Property Type Menu / Prism theme
- Pop-up menu doesn't appear:

https://user-images.githubusercontent.com/111116092/185738990-d3e7e5fb-a713-4720-b563-42227e10c125.mp4

**Version:**
 - OS: Windows 10 21H1
 - Obsidian: 0.15.9
 - Plugin: 2.2.1

**Comment by RafaelGB** [comment]
Hi @zuluwi  thanks for your report
about the first is related to https://github.com/RafaelGB/obsidian-db-folder/issues/251. I think with up the z-index css property will be enough.

I will investigate the second one
