### ISSUE TITLE
Page does not appear when the column name is just a number

### ISSUE THREAD

**Issue by zuluwi** [RafaelGB/obsidian-db-folder#274]
Page does not appear when the column accessorKey or key is just a number:

https://user-images.githubusercontent.com/111116092/185738440-328ca1e9-ad0f-4541-ae52-973fd5afad9b.mp4

**Version:**
 - OS: Windows 10 21H1
 - Obsidian: 0.15.9
 - Plugin: 2.2.1

**Comment by RafaelGB** [comment]
Seems like a parsing problem. If you want a number as key, wrap it with quotes

I will add that quotes with the next version automatically

**Comment by zuluwi** [comment]
automatically removes quotes when page is refreshed

https://user-images.githubusercontent.com/111116092/185740549-8de30768-5cfb-4973-94d6-bcfa9e9aa75a.mp4

**Comment by RafaelGB** [comment]
yeah, is casting again. You will have to wait until the release of that fix, sorry. Its already implemented

```ts
if (typeof value === 'string') {
    value = `"${value}"`;
}
```
