### ISSUE TITLE
Datetime picker does not appear

### ISSUE THREAD

**Issue by zuluwi** [RafaelGB/obsidian-db-folder#275]
Datetime picker does not open unless something is written in date format:

https://user-images.githubusercontent.com/111116092/185745419-8b792297-d643-4fa6-a906-e2239f275ae6.mp4

When the page is refreshed, only the lines in "year - month" and "year - month - day" formats remain:

https://user-images.githubusercontent.com/111116092/185745511-8ac6a8df-058a-4ce0-b69a-9f848b695160.mp4

Page needs to be refreshed to display the edited datetimes (maybe related with #265 ):

https://user-images.githubusercontent.com/111116092/185745584-9ba0fa43-013f-4f6a-abf1-0f7bbff01b34.mp4

**Version:**
 - OS: Windows 10 21H1
 - Obsidian: 0.15.9
 - Plugin: 2.2.1

**Comment by RafaelGB** [comment]
Fixed. Was a problem with zustand refresh. Instead of refresh all the table now just refresh the cell and in background updates just the file
https://user-images.githubusercontent.com/11924043/185808807-7e67e5d7-d2dc-4933-9c83-6f92e118beaf.mov

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/273
