### ISSUE TITLE
Lists get cut off

### ISSUE THREAD

**Issue by ProStashio** [RafaelGB/obsidian-db-folder#278]
**Describe the bug**
Lists that appear at the bottom of the screen don't have enough room to display. When this happens, the list should flip and extend upwards to allow for more room.

**To Reproduce**
Open a long list

1. Go to a DBFolder
2. Make long list
3. Make multiple entries so it gets to the bottom of the screen
4. Open list
5. See issue

**Expected behavior**
The list should flip so you can always see the maximum amount possible.

**Screenshots**
[IMAGE](https://gyazo.com/0b9bcebf5abfc1874f20cc8cdcbdacae)

**Desktop (please complete the following information):**
Windows 11

**Comment by RafaelGB** [comment]
Thanks for the report, was added to the roadmap

**Comment by RafaelGB** [comment]
already fixed
