### ISSUE TITLE
Creating a new file through db folders is buggy

### ISSUE THREAD

**Issue by rexxDZN** [RafaelGB/obsidian-db-folder#279]
**Creating a new file through db folders is buggy**
Creating a new file through db folders would sometimes not add what i have added to the boxes
![image](https://user-images.githubusercontent.com/112089078/186680816-d2f6a2a4-59fc-415f-b4ff-ea2c3d69e0b5.png)
it then shows that i have written everything in the database, but when i again want to make a new file through the database, the previous ones is all deleted except the filename. The issue seem to lie in the new file creation, because when i ctrl+shift+i in obsidian it gave me this. 
![image](https://user-images.githubusercontent.com/112089078/186681279-9e50092a-6718-4b06-a320-6231ce136bfd.png)

**To Reproduce**
- make a new db folder, and create a data base, and through that note click on filename on new row and press enter 
![image](https://user-images.githubusercontent.com/112089078/186681637-1feb79c9-1ce3-4f60-a88e-61c9c5b7e958.png)
- after that fill in the boxes as usual
- write a new file name and make and repeat the first step...
- now the previous boxes are gone, as if u have filled nothing in...

**Desktop**
 - OS: windows 11 Home
 - Version 21H2
 - 
![image](https://user-images.githubusercontent.com/112089078/186682354-53a1809d-0fd2-4228-ae9f-0804a5cf2283.png)

(this is the first time i am using github so i apologize if i have done something wrong.)

**Comment by rexxDZN** [comment]
This is the yaml i forgot to put it in. 
---
category: 
Rating: 
Summary: 
url: 
---

**Comment by RafaelGB** [comment]
```ts
const trimedFilename = filename.replace(/\.[^/.]+$/, "").trim();
```

as solution with the next version

**Comment by rexxDZN** [comment]
Wow that was a quick fix. Was it something that I have done wrong or a bug in the code itself?

**Comment by RafaelGB** [comment]
Looks like when you add the buggy row you introduce a space at the start of the name. With this fix will be controlled and also remove special chars
