### ISSUE TITLE
[bug] Cannot reorder columns in database using drag-and-drop

### ISSUE THREAD

**Issue by davidmickelsen** [RafaelGB/obsidian-db-folder#280]
**Describe the bug**
After creating a database from a folder in my Obsidian vault and adding columns using the "Select an existing column to add" option, the columns cannot be reordered using drag-and-drop; if I try to change column order by dragging a column header to another position; it snaps back to its original position when I let go of the mouse.

**To Reproduce**

1. Create database from a folder in Obsidian
2. Add columns to database using "Select an existing column to add" option
3. Try to reorder the columns by dragging and dropping a column header
4. The column header will snap back to its original position

**Expected behavior**
Dragging and dropping a column header will reorder the column.

**Desktop (please complete the following information):**
 - macOS 11.6.8
 - Obsidian 0.15.9
 - DB Folder 2.2.2

Thank you for the development of this plugin. Your time and effort are appreciated.

**Comment by RafaelGB** [comment]
hi @davidmickelsen , Is disabled by default cause an open issue => https://github.com/RafaelGB/obsidian-db-folder/issues/239

You can enable it in the global settings, but the dnd of obsidian will stop to work while is enabled

**Comment by davidmickelsen** [comment]
Thanks very much for your reply, Rafael.
