### ISSUE TITLE
[FR] New database source - current folder ignoring nested folders

### ISSUE THREAD

**Issue by meskill** [RafaelGB/obsidian-db-folder#281]
**Is your feature request related to a problem? Please describe.**
I already have a lot of folders that usually contain nested folders with more details. I want to use db-folder to manage this kind of folders but without notes from nested folders

**Describe the solution you'd like**
An additional option for database source inside db settings that will pick notes from current folder ignoring any nested folders

**Describe alternatives you've considered**
Another way to do it is to specify dataview query that will filter out any nested notes. But I need to specify full query with path to current folder manually in order to make it work.

**Additional context**
It's manageable with the next dataview query: `FROM "folder_path" WHERE file.folder = this.file.folder`

**Comment by RafaelGB** [comment]
Could be an interesting option. Will be added for sure =) thanks for your idea

**Comment by RafaelGB** [comment]
Commit 96b120db
