### ISSUE TITLE
No way to unhide hidden stock metadata columns

### ISSUE THREAD

**Issue by pm64** [RafaelGB/obsidian-db-folder#283]
**Describe the bug**
If a "stock" metadata column (such as "Created" or "Modified") is hidden using the "Hide" feature, there is no way to unhide it using the UI.

**To Reproduce**
1. Click Modified column header
2. Select "Hide"
3. Observe that there is no way to reverse no. 2

**Expected behavior**
When adding a new column, in Columns Menu, switches to show/hide stock metadata columns should be displayed

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: All
 - Version 2.2.2

**Comment by RafaelGB** [comment]
added to the roadmap, thanks for the report =)

**Comment by RafaelGB** [comment]
Starting with this one. While is fixed, you can change the markdown property of that metadata column

isHidden: true => isHidden: false

**Comment by RafaelGB** [comment]
easy one: Fixed modifying `.filter(c => !c.isMetadata)` per `.filter(c => !c.skipPersist)`
