### ISSUE TITLE
Database tags seem isolated from main system tags

### ISSUE THREAD

**Issue by pm64** [RafaelGB/obsidian-db-folder#284]
**Describe the bug**
When entering tags into a tag column, added tags do not appear in Obsidian's tag pane. Furthermore, when using Obsidian to search the vault for a specific tag, Database rows using the tag are not reported.

**To Reproduce**
1. Designate a column a type "Tags"
2. Enter a new tag that doesn't exist in Obsidian's tag tree
3. Observe issue no. 1: the tag added to the database column is not added to Obsidian's tag tree.
4. In another row of the Tags column, add a tag that DOES exist in Obsidian's tag tree.
5. Use Tag Browser to locate the tag. Click the tag to initiate a vault search for that tag.
6. Observe that the search results do not include the Database row tagged with the matching tag.

**Expected behavior**
The effect of entering a tag into a Database should be the same as adding one to a document. That tag should be searchable and findable using the tag tree.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: All
 - Version 2.2.2

**Comment by RafaelGB** [comment]
hi @pm64 
to link the tags to obsidian there are 2 ways:

- change your column name to "tags" if you are using a yaml field type
- add # to your values if you are using inline field type

As soon as autocomplete issue is finished, this behaviour will be added to the docs

**Comment by pm64** [comment]
From what I'm observing, the tags remain unlinked even when either of the above conditions are met.

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/187052239-96303237-b88d-4d37-8de8-ad1a08d6b5d2.mov


Should be this way

**Comment by RafaelGB** [comment]
May I close this issue? was your use case resolved?
