### ISSUE TITLE
found that the ""normal"" double layer in the md file

### ISSUE THREAD

**Issue by cos2202** [RafaelGB/obsidian-db-folder#286]
**Describe the bug**
Open a database file again, an error will be reported, and it is found that the ""normal"" double layer in the md file.
**To Reproduce**
config:
  remove_field_when_delete_column: "true"
  cell_size: ""normal""
  sticky_first_column: "false"
  group_folder_column: ""
  show_metadata_created: "true"
  show_metadata_modified: "false"
  show_metadata_tasks: "false"
  source_data: ""current_folder""
  source_form_result: ""root""
  frontmatter_quote_wrap: "true"
  row_templates_folder: ""/""
  current_row_template: ""

**Screenshots**
![2022-08-28 12-01-59屏幕截图](https://user-images.githubusercontent.com/99573254/187057865-ca41709c-2635-4c84-a96e-61a5e38fb6af.png)
![2022-08-28 12-02-49屏幕截图](https://user-images.githubusercontent.com/99573254/187057869-d98330d3-8c16-41c5-882c-5b01b005a290.png)
Desktop (please complete the following information):

OS: All
Version 2.2.2

**Comment by RafaelGB** [comment]
Hi @cos2202 ,
if you remove them manually are they added again? can not reproduce the issue in any os

**Comment by cos2202** [comment]
When I in database setting select tag in this:
source_form_result: ""[[功能]]""

Obsidian 0.15.9
OS: Ubuntu 22.04

**Comment by cos2202** [comment]
I select this then :cell_size: ""normal"" ,
and many item changed :
config:
  remove_field_when_delete_column: "false"
  cell_size: ""normal""
  sticky_first_column: "false"
  group_folder_column: ""
  show_metadata_created: "true"
  show_metadata_modified: "true"
  show_metadata_tasks: "false"
  source_data: ""tag""
  source_form_result: ""Markdown""
  frontmatter_quote_wrap: "true"
  row_templates_folder: ""/""
  current_row_template: ""
  pagination_size: ""10""

---
Obsidian 0.15.9
OS: Ubuntu 22.04

**Comment by RafaelGB** [comment]
with 2.3.1 version I am trying wit a new ddbb modifying the cell size, source with tags and source with queries and is saved correctly:

```ts
source_data: "query"
source_form_result: "FROM \"[[sdasdas]]\""
```

or

```ts
source_data: "tag"
source_form_result: "3D"
```

The plugins saves internal quotes with \"

**Comment by www-wagner** [comment]
Hi @RafaelGB!

I've been having the same issue here! I find out the issue is not related to `cell_size` setting. It occurs when you set `frontmatter_quote_wrap: "true"` in database settings.

When you set it to `"false"`, the problem is gone!

**Comment by RafaelGB** [comment]
I will control properly that condition just for frontmatters, thank you!

**Comment by RafaelGB** [comment]
fixed! ready with next version
