### ISSUE TITLE
cannot drag columns

### ISSUE THREAD

**Issue by wuzhen97** [RafaelGB/obsidian-db-folder#287]
**Describe the bug**
- I can drag columns in previous versions, but not now. 
- I'm not sure if you have this problem

**Desktop (please complete the following information):**
 - OS: win10
 - Version obsidian 0.15.9

**Additional context**
looking forward to your reply, thanks.

**Comment by RafaelGB** [comment]
Hi @wuzhen97 
Its disabled by default until fix https://github.com/RafaelGB/obsidian-db-folder/issues/239

You can enable it on the global settings > developer section
