### ISSUE TITLE
[BUG] Empty yaml fields not specified as column sets with "null"

### ISSUE THREAD

**Issue by brimwats** [RafaelGB/obsidian-db-folder#29]
1. Create a DB for a folder with notes
2. Add columns. I added a select and a number one
3. The note is edited and data is placed at the top of YAML

Also I use the term "Metadata:" in all my notes and it looks like db-folder is adding something to that?

heres the edited file:

```
---
column1: Test
newColumn3: 100
Metadata: null
Created: 2021-06-04 21:45
Last Modified: 2021-10-28 01:43:05
fileClass: Thing
ThingType: DefinedTermSet
---
# aesth-
**BT⤴:: [[10. Root Words]]** 

## Definition

feeling, sensation - Greek

## Roots

αἰσθητός (aisthētós), αἰσθητικός (aisthētikós) of sense perception from αἰσθάνtemεσθαι (aisthánesthai) to perceive - aesthesia, aesthesis, aesthete, aesthetics, anaesthetic, synesthesia

```

**Comment by RafaelGB** [comment]
Hello @brimwats thanks for your feedback.

clarifications on the behavior of your case:

- With the edit engine, all yaml is replaced with the order of database columns, then your fields that you don't use with the database are written. This way you don't lose any previous info.
- About your metadata field I saw that if you have an empty field, when is "replaced" the way I explain, inserts a "null"

I will use this issue as a bug to fix that "null" set

**Comment by RafaelGB** [comment]
0.2.1 release out!
the empty fields add null value no more
