### ISSUE TITLE
Shade Alternate Rows

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#290]
When you have many rows it is useful to have a shading in alternate rows to identify the correct row.
There are more urgent things, but I think that in the future it would be good.

![image](https://user-images.githubusercontent.com/7627504/187248718-4f16075e-2bf1-48e1-a1f9-6ef744792f92.png)

**Comment by RafaelGB** [comment]
this could be an easy addition for future versions, sure!
