### ISSUE TITLE
Layout of top toolbar seems unusual

### ISSUE THREAD

**Issue by pm64** [RafaelGB/obsidian-db-folder#291]
**Describe the bug**
The layout of the top toolbar 

**To Reproduce**
1. Open database
2. Observe appearance of top toolbar

**Expected behavior**
Page number should not be covering text label, and labels should be legible. Also the search field seems rather tall, is this intended?

**Screenshots**
![image](https://user-images.githubusercontent.com/10715458/187263827-16dff0c6-3fed-4245-b284-f6fa8b126869.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Latest

**Comment by RafaelGB** [comment]
Page number only supports numbers.

About the color, could be related with the theme that you are using. Also the arrows are just enabled when there are more than 1 page

Which theme are you using?

**Comment by pm64** [comment]
Hey @RafaelGB, sorry if I wasn't clear -- I can see the page number only supports numeric input. I'm referring to the overlapping text label ("Page of 1" -- another bug, page what of 1?). The label text is black, I can't tell if it's behind the input field or in front of it. In testing and reporting these issues, I used the stock (built-in) theme only.

**Comment by RafaelGB** [comment]
I am using var(—normal-accent) color of the theme. I aill try more dark modes to choose a better form color

**Comment by RafaelGB** [comment]
fixed and also tested with v0.16 insider version of obsidian

<img width="908" alt="Screenshot 2022-08-29 at 23 44 38" src="https://user-images.githubusercontent.com/11924043/187305322-de28886c-9900-4ec4-895c-d9a6a18e612e.png">
