### ISSUE TITLE
Allow control over justification of cell content

### ISSUE THREAD

**Issue by pm64** [RafaelGB/obsidian-db-folder#292]
**Is your feature request related to a problem? Please describe.**
It seems that cell content is always displayed with centered justification. In many cases it is more appropriate to display cell content using a justification other than centered.

**Describe the solution you'd like**
Ability to display cell data using left or right justification, in addition to centered.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/10715458/187266554-6c6beb78-4834-4b74-9d50-caaeaf16e87c.png)

**Comment by RafaelGB** [comment]
So your are purposing a new setting property to choose how to adjust the text,right? 

Could be interesting. Sure

**Comment by pm64** [comment]
That's correct! Excited about this enhancement, thanks for all you do.

**Comment by RafaelGB** [comment]
Design opinions?

<img width="556" alt="Screenshot 2022-09-15 at 15 49 48" src="https://user-images.githubusercontent.com/11924043/190421336-6c047220-5f31-49b7-a255-f40763225f4b.png">
