### ISSUE TITLE
Display empty task cells as blank

### ISSUE THREAD

**Issue by pm64** [RafaelGB/obsidian-db-folder#293]
**Is your feature request related to a problem? Please describe.**
Currently, empty task cells display the following message: "Dataview: No results to show for task query." Users would likely prefer for such cells to simply be blank.

**Describe the solution you'd like**
Hide this specific Dataview warning, while continuing to display other Dataview errors/warnings should they occur.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/10715458/187267136-c69882c3-27e3-4cb5-a0d6-ca18822b4bb2.png)

**Comment by RafaelGB** [comment]
this is a dataview option, you can enable/disable in its global settings

**Comment by pm64** [comment]
Would you accept a PR that allows the user to suppress this message in obsidian-db-folder views?

**Comment by RafaelGB** [comment]
all help is welcome. Sure! but being configurable with dataview, it is really necessary? 

If you know the way to disable it just for the plugin will be nice

**Comment by pm64** [comment]
This is just my opinion -- but I think the option would have value. In one of my use cases, the database has hundreds of rows, but only 3 or 4 of them will have associated tasks at any given time. So it's annoying to see that message displayed hundreds of times. Also, even though this plugin uses Dataview behind the scenes, I feel this is an implementation detail that shouldn't necessarily be exposed to the user.

In terms of a pure CSS solution, it only seems possible to hide ALL DataView warnings/errors within the obsidian-db-folder view, using a CSS rule like the following:

```
div.database-plugin__table p.dataview-error-message {
  display: none;
}
```
This might be an acceptable solution for now. Ideally DataView's error message would also be encoded in the HTML using a data- attribute (i.e. data-error-type="no_results"), but it's not. So the next best thing would be for us to use JavaScript to check the error's innerHTML, then handle or display/hide each possible message. But that sounds messy, so maybe just an option to hide all DataView errors in Task cells using a rule similar to the above can suffice for now.

**Comment by pm64** [comment]
FYI -- I've opened a feature request for DataView to encode error details using data-* attributes: https://github.com/blacksmithgu/obsidian-dataview/issues/1378

Unsure how this will be received. But if it is ever implemented, plugin authors will have more flexibility in displaying/handling specific DataView error messages.

**Comment by RafaelGB** [comment]
Thanks for your effort with this issue. I will try this days your css solution :)
