### ISSUE TITLE
Allow renaming database using UI

### ISSUE THREAD

**Issue by pm64** [RafaelGB/obsidian-db-folder#294]
**Is your feature request related to a problem? Please describe.**
Currently, changing a database name ("new database" by default) appears to require editing of the underlying markdown. It would be more convenient if this value could be updated from the UI.

**Describe the solution you'd like**
Make database name label editable.

**Describe alternatives you've considered**
Editing underlying markdown.

**Additional context**
![image](https://user-images.githubusercontent.com/10715458/187267660-c2271048-a805-4f21-b3ec-1ab61ab0829d.png)

**Comment by RafaelGB** [comment]
This is a provisional UI until achieve multiple views. Could be interesting a double click edit in the future. I will add this like a subtask of that issue

**Comment by RafaelGB** [comment]
#4

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/4

**Comment by RafaelGB** [comment]
N/A with future changes
