### ISSUE TITLE
[BUG] add button is hiding last rows

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#295]
**Describe the bug**
the add row button is covering the last rows, so interaction with them is impossible.

**To Reproduce**
1. create many rows in database
2. allow many rows to be displayed in settings

**Expected behavior**
the add button should be underneath the last row to not cover them.

**Screenshots**

https://user-images.githubusercontent.com/38974541/187280225-1748abeb-358a-4fa1-9db2-902dcdea9d74.mov

**Desktop (please complete the following information):**
- macOS 12.3.1
- Obsidian 0.15.9

**Comment by RafaelGB** [comment]
This is a known issue. Before the release was happening with navbar too and I found a hacky way to fix it conserving the sticky property. I will try to implement that for.add row too
