### ISSUE TITLE
No access to the database settings

### ISSUE THREAD

**Issue by yurijserrano** [RafaelGB/obsidian-db-folder#296]
**Describe the bug**
After the last update, access to the database settings is not possible due to the fields "filename of new row" and "Without Template...".

**To Reproduce**

1. Select Obsidian Default Theme
2. Try to access database settings

**Expected behavior**
Access Database settings

**Screenshots**

![image](https://user-images.githubusercontent.com/14169134/187297315-6fac528b-274a-4afd-9931-b6704c410ea1.png)

**Desktop (please complete the following information):**
 - OS: Pop OS
 - Version: 22.04

**Comment by RafaelGB** [comment]
This is an incompatibility with sliding panes plugin and already fixed after test the version. Will be added anyway to the roadmap as indicator of the problem. Thanks!
