### ISSUE TITLE
[FR] Native Image Embedding with frontmatter yaml

### ISSUE THREAD

**Issue by yurijserrano** [RafaelGB/obsidian-db-folder#298]
I checked the threads that are in the links below:

https://github.com/RafaelGB/obsidian-db-folder/issues/136
https://github.com/RafaelGB/obsidian-db-folder/issues/25
https://github.com/RafaelGB/obsidian-db-folder/issues/17

And the inclusion of images into the database has an unsuitable flow as we have to include an inline field, having a duplication of data as can be seen below:

![embed_image_03](https://user-images.githubusercontent.com/14169134/187425199-2f74cd11-eb67-4f83-9229-28dad1e307da.png)

With Dataviewjs I can embed an image simply by using the functions dv.func.embed and dv.func.link as you can see below:

![embed_image_01](https://user-images.githubusercontent.com/14169134/187425372-f41a57fe-b859-4984-9c4d-d1c88435d829.png)

So, as you are using the Dataviewjs API I suggest that you include a toggle in the column telling the user if it wants to embed or not, that way using the dv.func.embed and dv.func.link functions the image will be displayed correctly and this can be seen below:

![embed_image_02](https://user-images.githubusercontent.com/14169134/187425390-eb602956-46c0-43f9-8cdf-64446a26f1fc.png)

QUESTION:

In the column there is a toggle that informs that after its activation the column is converted into an Inline Field, as can be seen below:

![embed_image_04](https://user-images.githubusercontent.com/14169134/187426124-4e5b261a-3982-4775-8123-a47bd629a239.png)

I don't know if this is in fact your purpose, but if it is it is not working as you can see below:

![embed_image_05](https://user-images.githubusercontent.com/14169134/187426208-bdd3adae-f1b9-4588-bbdc-e0804061f877.png)

**Comment by RafaelGB** [comment]
To transform into inline field you hace to edit the content, it does not migrate automatically all the values.

The embed media have window to improve, but with embed it should work

**Comment by yurijserrano** [comment]
Yes, @RafaelGB 

"The embed media have window to improve, but with embed it should work"

In my opinion, making this change will mean that users will not have to include an inline field, but will have to use the YAML field itself, not having to duplicate the data as in my case, and thus have a basic functional workflow.

So, here we have a problem, because when I edit the content the field is deleted and not transformed to an inline field as you can see in the video right below:


https://user-images.githubusercontent.com/14169134/187429088-979a52ab-d20f-4c50-9fbd-60af16cc01d3.mp4


Do you want me to open a specific ticket for the problem above?


I am waiting to hear from you

**Comment by RafaelGB** [comment]
There is already an issue for that bug. including ! at start of a yaml value makes the file unreadable by obsidian

https://github.com/RafaelGB/obsidian-db-folder/issues/123

**Comment by yurijserrano** [comment]
Oh thanks @RafaelGB 

So this thread can be just about the embed image

**Comment by RafaelGB** [comment]
You can save embed images wrapped with quotes in yaml

`"![[image.png]]"`
