### ISSUE TITLE
[BUG] multi-column sort doesn't respect priority

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#299]
## Describe the bug
From my testing, the sorting priority is determined by the order of the columns, NOT by which column the user sorts first.

### First test: 
The `numbers` columns is in the left, so it takes priority even if it has the second sort

https://user-images.githubusercontent.com/38974541/187449750-838a3fb0-e8d7-4475-841f-a174423b0c1d.mov

### Second test
The `letters` columns is in the left, so it takes priority even if it has the second sort

https://user-images.githubusercontent.com/38974541/187449665-6719f94d-b371-4342-be47-649712a8eab8.mov

### steps to reproduce
1. enable DND in developer section
2. restart obsidian
3. drag the column to the desired order
4. restart obsidian
5. sort the two columns
6. repeat the last steps and swap the order of the column to confirm behavior

### files to reproduce
[test15.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453194/test15.md)
[test14.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453196/test14.md)
[test13.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453197/test13.md)
[test12.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453198/test12.md)
[test11.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453199/test11.md)
[test10.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453200/test10.md)
[test9.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453201/test9.md)
[test8.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453202/test8.md)
[testing database.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453203/testing.database.md)
[test7.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453204/test7.md)
[test6.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453205/test6.md)
[test5.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453206/test5.md)
[test4.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453207/test4.md)
[test1.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453208/test1.md)
[test3.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453209/test3.md)
[test2.md](https://github.com/RafaelGB/obsidian-db-folder/files/9453210/test2.md)

## Expected behavior
The sorting priority should be determined by the order of the sorting, not by the order of the columns in the database.

## Desktop and Obsidian
- macOS 12.3.1
- Obsidian 0.15.9

**Comment by RafaelGB** [comment]
Thanks @imeed166 as always. Added as subtask of https://github.com/RafaelGB/obsidian-db-folder/issues/127

**Comment by RafaelGB** [comment]
You can also enable the table state to see which columns are sorted between other thinks

<img width="773" alt="Screenshot 2022-08-30 at 15 39 30" src="https://user-images.githubusercontent.com/11924043/187452370-c49cd808-1a22-4bc6-8761-e30dcc0d0e1b.png">


<img width="874" alt="Screenshot 2022-08-30 at 15 41 32" src="https://user-images.githubusercontent.com/11924043/187452682-bf7c9e49-1fae-4b04-9a63-89a415e5c80b.png">

**Comment by RafaelGB** [comment]
I checked but the behaviour after reordering seems fine for me

https://user-images.githubusercontent.com/11924043/187756317-f782c84e-d413-478e-ba88-00fe4a32f3ea.mov

**Comment by imeed166** [comment]
You can see it in your video https://github.com/RafaelGB/obsidian-db-folder/issues/127#issuecomment-1232899061 at 0:06, the right column can never have the priority in sorting

**Comment by RafaelGB** [comment]
But it has the second index. Do you mean that new sorts have to obtain the first priority moving +1 to the others?

**Comment by imeed166** [comment]
let's say, for example, you have 3 columns in this order `column 1 | column 2 | column 3` and you want to sort by all of them 


You should be able to sort by C3 then by C2 then C1
but with current implementation you can only do C1 then C2 then C3 because of the order of the columns

**Comment by RafaelGB** [comment]
I could reproduce it now, thanks for the explanation 


https://user-images.githubusercontent.com/11924043/187871767-d6a81b3b-cbc4-4416-9590-5138ca6a9921.mov

**Comment by RafaelGB** [comment]
Was a problem with the prev 2.0.0 architecture. Was updated

https://user-images.githubusercontent.com/11924043/187952990-e2b84219-48e6-41b8-9240-27b2a2cafacf.mov

**Comment by RafaelGB** [comment]
Fixed. It needs a refactor for all the sort logic as inheritance of older versions

https://user-images.githubusercontent.com/11924043/187961149-62a208b5-1d6b-4cea-a4dc-b77a3c85ae6e.mov

**Comment by imeed166** [comment]
The new sort works, but is not persisted (with version 2.3.4)

https://user-images.githubusercontent.com/38974541/188311668-4ba7d137-18f7-44ca-a5ad-cb5306763f00.mov
