### ISSUE TITLE
[BUG] db not refreshed in certain situations

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#300]
The db should refresh its content in these situations :
- renaming select column field

https://user-images.githubusercontent.com/38974541/187460019-2c206002-2b17-41a5-b193-d53c47880353.mov

- reset the content of select type cell

https://user-images.githubusercontent.com/38974541/187459928-1585db21-ba4b-4e5b-982b-0ed9b1d35870.mov

- changing the color of select option in column setting

https://user-images.githubusercontent.com/38974541/187459800-95f31d9f-c119-4b97-8ef7-523e1398c15c.mov

- macOS 12.3.1
- Obsidian 0.15.9

**Comment by imeed166** [comment]
another use case : changing select option when column is sorted

https://user-images.githubusercontent.com/38974541/187461933-9b384c17-d7a1-49dd-b178-56424c6f3f85.mov

**Comment by RafaelGB** [comment]
I will give this priority

**Comment by RafaelGB** [comment]
fixed. Maybe change the label is slower now but with pagination does not matter anymore

**Comment by imeed166** [comment]
The first two use cases are resolved :
- refresh when reset cell content
- refresh when renaming column name 

But the last two use cases are not :
- refresh when changing the select option color in column setting
- refresh when changing select option and column is sorted

**Comment by RafaelGB** [comment]
I opened a subtask https://github.com/RafaelGB/obsidian-db-folder/issues/305
