### ISSUE TITLE
Ability to make "inline field" the default

### ISSUE THREAD

**Issue by csss1234** [RafaelGB/obsidian-db-folder#304]
Would be nice. I like to hide inline fields at the bottom of a note, compared to yaml cluttering up the top of a note.

**Comment by RafaelGB** [comment]
Could be future configurations sure!
 - toggle for make new columns inline by default
 - dropdown to choose new inline fields position => ["top","bottom"]
 
 
 I like the idea, thanks @csss1234

**Comment by anonymous-philosophy** [comment]
+++ Really need this feature!

**Comment by arminta7** [comment]
Yes yes yes!

**Comment by RafaelGB** [comment]
okey okey, I got it! =P
