### ISSUE TITLE
Existing columns - Sort and Hide

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#306]
When you have many columns it is difficult to find the correct one if the list is not ordered.

It would also be interesting that when you press add, those that are no longer hidden disappear from the list.

![image](https://user-images.githubusercontent.com/7627504/187889017-69c09403-6f31-4b0b-a0e7-9d737dcf46c8.png)

**Comment by RafaelGB** [comment]
Added to the roadmap, Thanks for the suggestion

**Comment by jimbo108108** [comment]
+1

**Comment by RafaelGB** [comment]
now the keys are sorted on new column modal menu and filters selection
