### ISSUE TITLE
Database Table Disappears

### ISSUE THREAD

**Issue by Stilts15ak** [RafaelGB/obsidian-db-folder#309]
Hey Rafael,

First off, I like this plugin, that being said, please see below.

**Describe the bug**
Database table(s) disappear when clicking back and forth to database note file.

**To Reproduce**

1. Click on Database 1.
2. Click on Database 2.
3. Click back on Database 1. (Database does not show, it is gone.)
4. Can click back on Database 2. (Does not show, it is gone.)
5. Click on another note besides a database.
6. Click on Database 1 or 2. (Either database will now show, however they disappear again with steps 1-4.)

**Expected behavior**
Each database should render immediately depending on which note or database you have come from.

**Screenshots**
See attached video screen capture.

**Desktop (please complete the following information):**
 - OS: masOS Monterey - Version 12.5.1
 - Version: Obsidian Version 0.15.9 (Installer 0.15.8); DB Folder Version 2.3.1

**Additional context**

https://user-images.githubusercontent.com/106125987/187995857-320e2a56-ba12-4edf-98f4-0d919e1d0dd0.mov

**Comment by RafaelGB** [comment]
Oh I see. This is a known issue. Happens when you iterate between databases.

I was working on it, I don't know de cause yet. Thanks for the report @Stilts15ak . I'm going to follow up here

**Comment by Stilts15ak** [comment]
Thanks

**Comment by RafaelGB** [comment]
fixed! Was a problem with the state manager. Will be added with the next version
