### ISSUE TITLE
Unable to Search and Click on DB Database in Obsidian

### ISSUE THREAD

**Issue by g1thubth1nk** [RafaelGB/obsidian-db-folder#313]
**The Problem**
If a search is performed for a folder database created with DB Database in Obsidian, once that database is located, it cannot be clicked on and subsequently accessed. In other words, one can do the search and find the database. And from there, you have to locate the database in navigation, being where it is in the vault, instead of being able to simply click on and access a database presenting as a search result.

**What Would Help**
It would be useful and efficient to be able to search for any particular database and then be able to click on it to access it once the results show up among the search results in Obsidian.

**Existing Inefficient Alternatives**
The only alternative, at this time, is to search for a database and then manually locate it among the files in one's vault. This is time consuming and inefficient.

**Comment by RafaelGB** [comment]
The files are not loaded and filtered until you load your database file, so it will be impossible to use the search out of it
