### ISSUE TITLE
[FR] Select folder destination in case of choose another source different to current_folder

### ISSUE THREAD

**Issue by Stilts15ak** [RafaelGB/obsidian-db-folder#318]
**Describe the bug**
The database becomes unresponsive when a new row is inserted via the row template and must be reloaded by clicking on another note before the change is recognized and changes can be made to the entry. This can also be reproduced when no row template is present as well.

**To Reproduce**

1. Type in name of new row then click plus sign OR click plus sign for new row.
2. Click on any column of new row and it will not respond.
3. Click on another note.
4. Click back on database to reload and you should now be able to edit columns for that row.

**Expected behavior**
Row columns should be able to be edited after creation without a manual reload.

**Screenshots**
See video screen capture. (Apologies for the resolution.)

**Desktop (please complete the following information):**
 - OS: masOS Monterey - Version 12.5.1
 - Version: Obsidian Version 0.15.9 (Installer 0.15.8); DB Folder Version 2.3.3

**Additional context**
New notes are being moved to appropriate folder via the Auto Note Mover plugin upon creation.

https://user-images.githubusercontent.com/106125987/188204202-9054c16c-2f07-4138-9329-d02220850f4b.mov

**Comment by RafaelGB** [comment]
Could you share the console errors?
MacOS cmd+shift+I

Windows Ctrl+shift+I

I can not reproduce it, maybe the cause is the own template?

**Comment by Stilts15ak** [comment]
Attached
[obsidian.md-1662142880047.log](https://github.com/RafaelGB/obsidian-db-folder/files/9480235/obsidian.md-1662142880047.log)

**Comment by RafaelGB** [comment]
plugin:auto-note-mover:1850 [Auto Note Mover] Moved the note "Test File.md" to the "TV SERIES DATABASE/TV EPISODE RELEASES".
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'frontmatter')


looks lime you have another plugin(auto-note-mover) that moves the new note so it cant be edited

**Comment by Stilts15ak** [comment]
Ah, I see what you mean.

I was trying to keep the database outside of its source folder because I did not want the database to get lost inside of the source folder. 

I set up the source to be a certain tag (tv_episode) as I found this would allow the database to be outside of the source folder and I would not have to have "current_folder" selected. I would have had the source set up to a query, querying the source folder ("Life/TV SERIES DATABASE/TV EPISODE RELEASES", however I could not get that to work. Hence, this is also why I chose to go with the Auto Note Mover plugin, so once it was created, it could move it to the desired folder. I could set Auto Note Mover to do this manually after I have created and edited the entry note.

I am open to any other suggestions. However, it might be valuable if someone wants the database to be out of the source folder in another place, and have the new entry go into the desired source folder without another plugin involved.

**Comment by RafaelGB** [comment]
My proposal: In case a source other than the current folder is selected, show an optional configuration with the destination of new files. I can include it in the roadmap as a new feature

**Comment by RafaelGB** [comment]
In fact I want to include it with https://github.com/RafaelGB/obsidian-db-folder/issues/126

So this issue could be a subtask =)

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/188269999-45191491-272e-4c8d-9b2e-c538587a0b36.mov

**Comment by Stilts15ak** [comment]
Wow! I think that could be a great option!

**Comment by RafaelGB** [comment]
avaliable with 2.3.4
