### ISSUE TITLE
Database Disappears When Row Is Deleted

### ISSUE THREAD

**Issue by Stilts15ak** [RafaelGB/obsidian-db-folder#319]
**Describe the bug**
The database disappears when a row is deleted and has to be manually reloaded by clicking on another note and then clicking back on the database file.

**To Reproduce**

1. Delete row to be deleted. (This will make the database disappear.)
2. Click on another note to reload the database.
3. Click back on the database to see change.

**Expected behavior**
Database should not disappear when a row is deleted.

**Screenshots**
See attached video screen capture.

**Desktop (please complete the following information):**
 - OS: masOS Monterey - Version 12.5.1
 - Version: Obsidian Version 0.15.9 (Installer 0.15.8); DB Folder Version 2.3.3

https://user-images.githubusercontent.com/106125987/188205014-25a5fc9d-e5ba-4fde-9c6b-af83d834133a.mov

**Comment by RafaelGB** [comment]
yes, looks like an error introduced with 3.2.2, I will give this priority. Thanks for the report

**Comment by RafaelGB** [comment]
It does not happen always, I am trying to know the cause.
The plugin storage looks solid, but in some cases refreshing react-table framework does not rake the change and provokes a null pointer with the deleted ID

clues:
- zustand does not send the refresh signal
- react-table bug filtering rows
- zustand refresh the page before remove the row, so there is and async concurrent problem (worst scenario and the most likely

**Comment by RafaelGB** [comment]
fixed!
```ts
implementation.actions.removeRow = async (rowToRemove: RowDataType) => {
            try {
                await VaultManagerDB.removeNote(rowToRemove.__note__.getFile());
                set((state) => {
                    const filteredRows = state.rows.filter(
                        (r) => r.__note__.filepath !== rowToRemove.__note__.filepath
                    );
                    return {
                        rows: filteredRows
                    }
                })
            } catch (error) {
                new Notice(`Error: Could not remove note from database. path does not exist: ${rowToRemove.__note__.filepath}`);
            }

        };
```

Was the third option =) Will be avaliable with the next minor version

**Comment by Stilts15ak** [comment]
Wow! Awesome! Thank you for all of your hard work!
