### ISSUE TITLE
Database Gives An Error When Trying To Filter

### ISSUE THREAD

**Issue by Stilts15ak** [RafaelGB/obsidian-db-folder#321]
**Describe the bug**
When trying to filter both databases in Obsidian vault it comes back with an error. Error seems to be focused on column on the right of the File column on both databases.

**To Reproduce**
See attached log and video screen capture.

**Expected behavior**
Filtering a database should function as normal.

**Desktop (please complete the following information):**
  - OS: masOS Monterey - Version 12.5.1
  - Version: Obsidian Version 0.15.9 (Installer 0.15.8); DB Folder Version 2.3.3

[obsidian.md-1662240264927.log](https://github.com/RafaelGB/obsidian-db-folder/files/9483410/obsidian.md-1662240264927.log)

https://user-images.githubusercontent.com/106125987/188288101-05e44e52-0904-428b-935d-e405ef97c440.mov

**Comment by RafaelGB** [comment]
fixed on https://github.com/RafaelGB/obsidian-db-folder/issues/322 with 2.3.4
