### ISSUE TITLE
"Select" column & "Tag" Column Organization

### ISSUE THREAD

**Issue by Stilts15ak** [RafaelGB/obsidian-db-folder#323]
**Is your feature request related to a problem? Please describe.**
It would be nice if you could alphabetize the choices in "Select" & "Tag" columns via their setting sections. And/or the ability to manually rearrange them in there. It is difficult to navigate the choices in the drop-down menu sometimes as the choices you've already inserted, go by the order of creation.

**Comment by RafaelGB** [comment]
Sure! add as visual

**Comment by Stilts15ak** [comment]
Awesome!

**Comment by imeed166** [comment]
Adding to this feature, If we could re-arrange the options in `select` and `tag` properties (manually and alphabetically). The sort should follow this re-arrangement. The user will have to re-arrange the options in the setting to change the sorting behavior. I believe this is the way it's done in notion.

**Comment by RafaelGB** [comment]
ready for the next version =)
