### ISSUE TITLE
When selecting query as source of database data several "\" are added to the query and breaks the query. 

### ISSUE THREAD

**Issue by JagodaCJ** [RafaelGB/obsidian-db-folder#325]
**Describe the bug**
I have all my notes (which represent tasks) in a subfolder.
I created a DBFolder file on root of the of the vault and defined a query to get all notes from my tasks folder.
When selecting query as source of database data several "\" are added to the query and breaks the query:

![image](https://user-images.githubusercontent.com/97749383/188313260-32cf83e5-915f-4dd2-8eb4-64d20d0e919b.png)
![image](https://user-images.githubusercontent.com/97749383/188313303-0ef53e3c-e7e0-4d33-9b11-94e454c6dfb9.png)
![image](https://user-images.githubusercontent.com/97749383/188313360-cbac300e-6add-4c27-b852-6b65a940ec92.png)

**To Reproduce**
If applicable, add your configuration YAML of your database to reproduce the bug

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
It started to happen in the 2.3.2 release.

**Comment by RafaelGB** [comment]
Could you share original query?

**Comment by JagodaCJ** [comment]
Original query:

FROM "Workspace/Tasks"

After closing the window it changes to :

FROM \\\\\\\\"Workspace/Tasks\\\\\\\\"

**Comment by RafaelGB** [comment]
I will check it and fix it with a future minor version, thanks for the report @JagodaCJ

**Comment by JagodaCJ** [comment]
Thank you Rafael!

**Comment by RafaelGB** [comment]
fixed, was an error introduced with https://github.com/RafaelGB/obsidian-db-folder/issues/123 modifying the way of saving the yaml

**Comment by JagodaCJ** [comment]
Thank you Rafael, working perfectly with latest update.
