### ISSUE TITLE
Update Templates When Moved/Renamed

### ISSUE THREAD

**Issue by ProStashio** [RafaelGB/obsidian-db-folder#327]
**Is your feature request related to a problem? Please describe.**
When you move/re-name a template it doesn't auto-update so you need to go back and change it.

**Describe the solution you'd like**
Auto-update.

**Comment by RafaelGB** [comment]
So the request is to update the selected template associated with new rows?

It requires a permanent observer for every ddbb you have in all your vault, I think its an overkill to reduce 1click

**Comment by RafaelGB** [comment]
Maybe we can add a notice to show that the template not exist anymore

**Comment by ProStashio** [comment]
Essentially I know Obsidian has the functionality so where you move/rename something it updates where it is referenced everywhere else. Was hoping the same could be done for the templates

**Comment by RafaelGB** [comment]
I can not use that native architecture in this case because the template is one option more of the ddbb yaml, not a link. I am not sure if we can save that property as an internal link to use that functionality. The problem in that case will be to read it

**Comment by RafaelGB** [comment]
I am going to discard ( at the moment) this issue. Its not possible with the actual config
