### ISSUE TITLE
In V0.16.2 the option to review the database settings isn't available unless show tab title bar is turned on.

### ISSUE THREAD

**Issue by jimbo108108** [RafaelGB/obsidian-db-folder#330]
**Describe the bug**

**To Reproduce**
If applicable, add your configuration YAML of your database to reproduce the bug

1. Update to Obsidian V0.16.22. 
2. Open obsidian settings and confirm that Show tab title bar is turned off3. 
3. Open a Db. Folder4. 
4. You no longer can view the three vertical dots in the upper right that gives you the ability to review the database settings

Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by RafaelGB** [comment]
Hi @jimbo108108 ,yep I noticed that and I was thinking about moving all the settings options to the same menu of css download as alternative (not replace)

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/188505175-ab284d05-640f-4a90-8831-5b94ea53aceb.mov

for the next version
