### ISSUE TITLE
Go To Page On Entry Creation

### ISSUE THREAD

**Issue by Stilts15ak** [RafaelGB/obsidian-db-folder#332]
It would be nice if when a new entry is created, the database goes to the page the new entry is on and perhaps centered in the database window. Currently the database goes to the first page after an entry is created.

**Comment by RafaelGB** [comment]
I will work on that, thanks for the report

**Comment by ProStashio** [comment]
I agree, this would be excellent to have. When you make a new note if it jumped to the page the new note is on and perhaps even ran an animation that played for a second to highlight it would be amazing if that's possible.

**Comment by RafaelGB** [comment]
the react-table framework does not allow this functionality at the moment, it occurs to me to use the search so that, when adding a row, it filters the rest and only shows you the new entry.

What do you think?

**Comment by RafaelGB** [comment]
new rows will be added at the end. So add new rows will set the page to the last one

Commit e1d3ddc5
