### ISSUE TITLE
Tag Choose Window Gets Lost At Bottom Of Screen

### ISSUE THREAD

**Issue by Stilts15ak** [RafaelGB/obsidian-db-folder#333]
**Describe the bug**
When trying to choose tags near the bottom of a page, the scroll window for the tags gets lost (see video). It gets difficult to choose a tag (when scrolling) when it is on the very bottom of a page.

Would be great if the tags column when selecting would choose going up like the "select" columns when close to the bottom of the Obsidian window.

**Screenshots**
See attached screen capture video.

**Desktop (please complete the following information):**
 - OS: macOS Monterey Version 12.5.1
 - Version: Current version of Obsidian & DB Folder

https://user-images.githubusercontent.com/106125987/188758275-e93d18ad-e12d-4edd-aef6-6caa51e9096c.mov

**Comment by RafaelGB** [comment]
Already on process with https://github.com/RafaelGB/obsidian-db-folder/issues/139
