### ISSUE TITLE
Sort Alphabetically

### ISSUE THREAD

**Issue by ProStashio** [RafaelGB/obsidian-db-folder#335]
**Is your feature request related to a problem? Please describe.**
The issue lies when you have multiple folder

**Describe the solution you'd like**
Sort notes alphabetically

**Describe alternatives you've considered**
You can make a new column for just a name to sort, but it takes a lot of work especially with over 2000+ notes

**Comment by RafaelGB** [comment]
Do you mean to order the File column, right?

Its using the complete path to order it, I will try to use just the base name but its not trivial

**Comment by ProStashio** [comment]
> Do you mean to order the File column, right?
> 
> Its using the complete path to order it, I will try to use just the base name but its not trivial

Yeah, to be fair it wouod be useful for all, but having an alphabetical sort would be useful all around
