### ISSUE TITLE
Enabling "File Tasks Column" for Data view query based Databases makes list disappear.

### ISSUE THREAD

**Issue by cesarpereira904** [RafaelGB/obsidian-db-folder#336]
**Describe the bug**
For database using a Dataview query as source of data, when enabling File Tasks Column toggle makes all list to disappear.

**To Reproduce**
1 - Create a Database where the source of the data will be a dataview  query to a folder.
2 - Toggle on the File Tasks Column on the database settings
3 - List will no longer be shown.

n.a.

**Expected behavior**
Display Tasks Column.

**Screenshots**
![image](https://user-images.githubusercontent.com/70922426/188850970-0a500ad0-3208-467d-970f-0aa868e5da93.png)
![image](https://user-images.githubusercontent.com/70922426/188851014-a571953b-2a66-46cd-99d7-e1a0ab3f3424.png)
![image](https://user-images.githubusercontent.com/70922426/188851055-5ddb4596-d7f1-488a-9494-b5facf396ab7.png)

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
When using current_folder as source of data it display correctly the  Tasks Column after enabling it in the settings.

But, I would suggest if it would possible to insert a space between the checkbox square and the text:

![image](https://user-images.githubusercontent.com/70922426/188851723-ca6c47ef-4f06-40bd-8623-b46eb6b61ec2.png)

Also, specific for this column, align the content to the left to make it more readable.

**Comment by RafaelGB** [comment]
could you share de console logs? looks like a problem consulting dataview task in on of your files

About the align, I am working of css improvements after 0.16

**Comment by cesarpereira904gar** [comment]
Hi Rafael!

Here's the log using the following dataview query: FROM "Workspace/Tasks"where week = (date(today).weekyear)+1

![image](https://user-images.githubusercontent.com/96719799/188856220-c77a507e-4fcc-40d9-b5cf-444374b79287.png)

Here's the log removing the "where" clause from the dataview query: FROM "Workspace/Tasks"

![image](https://user-images.githubusercontent.com/96719799/188857348-4774c1bc-5b91-44d1-9932-d8fb5f96810c.png)

**Comment by RafaelGB** [comment]
Just to discard it. If you use the same query out of the plugin, is it works?

**Comment by cesarpereira904gar** [comment]
Yes,

![image](https://user-images.githubusercontent.com/96719799/188859238-ceef116f-a3a0-48cb-a971-80839cb2d6d7.png)

![image](https://user-images.githubusercontent.com/96719799/188859267-a59297b4-3882-4408-9f8c-ae43b0ea1291.png)

**Comment by RafaelGB** [comment]
de differences could be to add the other columns to your table query.

`table A,B,C FROM ...`WORKS TOO?
If so, I will add this to the roadmap as a bug.

Also if you can share a mock content of that folder that trigger the error will be easier to reproduce.

Thanks for the report @cesarpereira904gar

**Comment by cesarpereira904** [comment]
Adding the columns:

<img width="805" alt="image" src="https://user-images.githubusercontent.com/70922426/188866414-7e8381cb-e3d1-4141-9bc6-3f2ae54303a7.png">

File structure:
Workspace/Tasks

Here an example of how the files meta under this folder look like:

---
files: none
week: 37
ticket_duedate: 
requestedby: Montse
ticket_jira: "[link](https:www.something.com)"
ticket_happyfox: "[link](https:www.something.com)"
tags:
 - DATA-TASK
status: REVIEW
cssclass: mado-header
description: description of the task
banner: "![[Workspace/Attachments/wallpapper-b.jpg|wallpapper-b.jpg]]"
---


Hope this can help!

**Comment by cesarpereira904** [comment]
Hi Rafael,

Just to let you know that with the latest update of the Dataview plugin, 0.5.45, and DBfolader, 2.4.0, bug seems to be gone!

All my databases files, that use dataview query as source of data, display correctly the tasks.

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/70922426/189295240-1025b45a-4d02-408e-b105-4f57f2143f99.png">

**Comment by RafaelGB** [comment]
I forgot to move this to fixed =P yeah I found the bug!
In some cases the task objects were null and I was trying to read them
