### ISSUE TITLE
Update Of Any Entry Resets Database To Page 1 In Version 2.3.6

### ISSUE THREAD

**Issue by Stilts15ak** [RafaelGB/obsidian-db-folder#338]
**Describe the bug**
It looks like version 2.3.6 might have introduced a bug that resets the database to page 1 when an entry is changed on another page.

See attached video screen shot.

https://user-images.githubusercontent.com/106125987/188903285-f6f93f9a-173f-4a7b-b608-cf97bb5da2b2.mov

**Comment by RafaelGB** [comment]
Thanks for the report @Stilts15ak 

Now that I am using a global state to hook per row instead per cell, the react-table frameworks has a param to reset the pagination

I disabled it

```ts
autoResetPageIndex: false,
```

**Comment by Stilts15ak** [comment]
Thanks

**Comment by RafaelGB** [comment]
I don't know why a thing like that is enabled by default =(

**Comment by Stilts15ak** [comment]
🤷‍♂️
