### ISSUE TITLE
Checkbox Sort

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#339]
When sorting the checkbox column it doesn't sort correctly.

![image](https://user-images.githubusercontent.com/7627504/188945516-2813bbb4-e472-4ba4-a26f-8dfd445be073.png)

dbfolder 2.3.6
obsidian 0.16.2

**Comment by RafaelGB** [comment]
The 2.3.6 move checkbox from 0 - 1 to true-false. , so maybe is mixed right now in your ddbb.

I will add an option to choose how to persist it

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/158

**Comment by RafaelGB** [comment]
solucionado en al 2.4.0. Lo cierro como wont fix
