### ISSUE TITLE
[BUG] Columns move when resizing panel

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#34]
Hola Rafael! Muchas gracias por hacer este plugin

**Describe the bug**
The problem is that the columns move when resizing the panel.
I have tried with an empty vault, without snippets and without themes

**Expected behavior**
All columns move simultaneously

**Screenshots**
https://user-images.githubusercontent.com/7627504/167692464-32541bea-daf8-43f5-bc0c-5a687bb09f37.mp4

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome, edge
 - Version obsidian: 0.14.9

**Comment by RafaelGB** [comment]
Hola Javi gracias por tu feedback!

I am afraid that the video is not load correctly, but I saw myself testing the app and is already fixed in my actual branch. It will be added with 0.3.1

**Comment by RafaelGB** [comment]
0.3.1 available now

Could you confirm that is fixed?

**Comment by javiavid** [comment]
Solved, thank you
