### ISSUE TITLE
Need to escape (quote) texte in dataview entry

### ISSUE THREAD

**Issue by Lisandra-dev** [RafaelGB/obsidian-db-folder#343]
**Describe the bug**
When I try to edit the contents for the column, contents aren't save in any way, using inline or frontmatter entry.

**To Reproduce**
- Use a dataview queries
- Add column, already existant or not
- try to add some contents in the case
- reload the table 

**Expected behavior**
The contents must be save in the files.

**Screenshots**

![image](https://user-images.githubusercontent.com/30244939/189246856-20513ca7-aa55-480f-8ff6-93e8c8b831c3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Version [e.g. 22] Latest

**Additional context**
/

**Comment by RafaelGB** [comment]
Hello @Lisandra-dev ,
Could you share the dataview query taht you introduced?
The console log will be helpful too
- MacOS (cmd+shift+I)
- Windows,Linux (ctrl+shift + I)

Could be two possibilities:
- A bug with your query
- One of your yaml files is broken and can not be readable for the plugin (the console log will reveal it)

**Comment by Lisandra-dev** [comment]
None of these file have frontmatter, so it can't be that.
Also, I noticed these errors when I try to edit my file : 
![image](https://user-images.githubusercontent.com/30244939/189318824-eee939bc-9a74-4264-91fb-740beaf2d066.png)

I'm pretty sure, normally, inline dataview must accept `:content:`, as my normal queries doesn't have problem with it :(

**Comment by RafaelGB** [comment]
the clue here is that none of your notes has frontmatter.

The plugin requires a yaml to read, even is empty.

I will try to test that use case. Thanks for the report @Lisandra-dev

**Comment by Lisandra-dev** [comment]
I think I noticed why this perticular bug happened. In fact, the table detect the state of the key, without checking if it's a **dataview** key or a **frontmatter** key. By default, all key are treated as frontmatter. That's why I have this error.

The strange thing is : it detects the value of these key, so I didn't check if they was treated as dataview.

**Comment by RafaelGB** [comment]
Please, share a mock example with that conditions and I will work on it for the next version

**Comment by Lisandra-dev** [comment]
In a markdown file : 
```md
logo:: :icon:
another_fail:: text with ' in it
```

In a DB folder database, try to get this file (dataview query / folder) 

Set the column on `logo` and `another_fail` **without** set it in inline. You will see the contents in the column.

If you try to change the content or add a new column, you will see the error.

**Comment by RafaelGB** [comment]
BTW, I am working on NO add front matter section if there is not fields to add


```ts
  async function persistFrontmatter(deletedColumn?: string): Promise<void> {
    // If the frontmatter is empty, do not persist it
    if (Object.keys(rowFields.frontmatter).length > 0) {
      const frontmatterGroupRegex = contentHasFrontmatter ? /^---[\s\S]+?---/g : /(^[\s\S]*$)/g;
      const frontmatterFieldsText = parseFrontmatterFieldsToString(rowFields, ddbbConfig, deletedColumn);
      const noteObject = {
        action: 'replace',
        file: file,
        regexp: frontmatterGroupRegex,
        newValue: contentHasFrontmatter ? `${frontmatterFieldsText}` : `${frontmatterFieldsText}\n$1`,
      };
      await VaultManagerDB.editNoteContent(noteObject);
    }
  }
```
