### ISSUE TITLE
Edit multiple items

### ISSUE THREAD

**Issue by jakemkc** [RafaelGB/obsidian-db-folder#345]
**Is your feature request related to a problem? Please describe.**
Hi Rafael,

Thanks for the wonderful little plugin "DB Folder". It provides a simple way to view and handle meta data in YAML. It's intuitive as using Music app to handle my music library.

However, it seems that there is no way to edit info for multiple items, e.g., I have simple notes (one note one idea) from a single reference source, and I would like to put the ref url in a YAML field. I hope that I can input this information just once instead of doing multiple times.

**Describe the solution you'd like**
Highlight the cells in DB Folder I would like to edit, right click to edit multiple items. Similar to how we edit multiple items in the Music app in macOS.

**Describe alternatives you've considered**
Doing it one by one manually.

**Additional context**
nil.

**Comment by RafaelGB** [comment]
HI @jakemkc , This feature will not be trivial. The cells must be selectable just as excel to paste the same value. 

duplicate issue => https://github.com/RafaelGB/obsidian-db-folder/issues/45
