### ISSUE TITLE
DND conflicts with resize handle

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#349]
**Describe the bug**
When the user tries to resize the column, he selects the handle to the right, and the column is dragged with the resizing. 

https://user-images.githubusercontent.com/38974541/189478103-e556a2b2-1f16-4245-a51b-163978eb001b.mov

**Expected behavior**
There should be a safe zone around the handle for resizing where the user can't move the column if he dragged the mouse in that area.
![Screen Shot 2022-09-10 at 10 44 45 AM](https://user-images.githubusercontent.com/38974541/189478084-c121e888-c759-496a-9c77-6d702af62034.jpg)

**Desktop (please complete the following information):**
- macOS 12.3.1
 - Obsidian 0.15.9

**Comment by RafaelGB** [comment]
Already fixed with another branch. Thanks anyway for the report and will be available with next version
