### ISSUE TITLE
lack of dark mode support for various menus

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#350]
There is no dark mode for the database menu
![image](https://user-images.githubusercontent.com/38974541/189478244-e2f10d51-5b00-44f6-8bd8-4166952642f0.png)

no dark mode support for the filter menu
![image](https://user-images.githubusercontent.com/38974541/189478260-7883ae23-9898-417a-9db8-391a86104477.png)

no dark mode support for the arrows in pagination menu
![image](https://user-images.githubusercontent.com/38974541/189478284-be427886-9fb7-429c-b8b1-18e41cb1d174.png)

**Desktop (please complete the following information):**
- macOS 12.3.1
- Obsidian 0.15.9

**Comment by RafaelGB** [comment]
Annotated! =)
