### ISSUE TITLE
text cell doesn't reset color when unselecting

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#352]
**Describe the bug**
In dark mode, when you select a text cell, the color of the cell turn to grey. Then, when select something else, the color of the cell doesn't return to black. The color resets only when refreshing the db.

**Expected behavior**
The color should be reset to the default color when selecting other cells.

**Screenshots**

https://user-images.githubusercontent.com/38974541/189478635-336d1499-4bff-40f8-820b-1ce8692f3ab0.mov

**Desktop (please complete the following information):**
- macOS 12.3.1
- Obsidian 0.15.9

**Comment by RafaelGB** [comment]
there was a problem with empty cells after onBlur event. Fixed
