### ISSUE TITLE
[FR] option to disable line wrap of column items

### ISSUE THREAD

**Issue by afland** [RafaelGB/obsidian-db-folder#358]
The line wrapping of the filename column (and others) makes each item take up at least 2x more vertical space, meaning I only see 1/2 as many items on my screen at once. 

It would be great for there to be an option to disable line wrap, meaning columns would instead be cut off. Then the rest of the text would only be revealed by resizing the columns. To make that a little less manual, maybe there could also be an option to expand columns horizontally to fit the full text by default (although less important). 

Another issue is that the column resizing behavior is a little glitchy, maybe that could be improved on as well.

Thanks for this awesome plugin!

**Comment by afland** [comment]
I just saw that the "compact" cell size option disables line wrap. It would be nice to have that as a universal option in the plugin settings, rather than per file. Also, it seems you can't shrink/expand the compact columns at all

**Comment by RafaelGB** [comment]
Hello @afland ,
Yeah, the `row size` property enable/disable it.
Make it as global setting I do not think that is a good idea. Every table should be configurable. Maybe in the future we can create a "default" value

About the shink/expand its a "bug", The width in this case seems static and could not be dynamically adapted. We can follow up on this issue

**Comment by afland** [comment]
> Hello @afland , Yeah, the `row size` property enable/disable it. Make it as global setting I do not think that is a good idea. Every table should be configurable. Maybe in the future we can create a "default" value
> 
> About the shink/expand its a "bug", The width in this case seems static and could not be dynamically adapted. We can follow up on this issue

I agree that every table should be configurable, but there should be a global default option. There essentially already is ("normal" for the cell size option), but the user can't change it. It would be great if you could make the default table options configurable via plugin settings.

For example, the options in the image below are already available per-table and as global defaults in plugin settings:
![image](https://user-images.githubusercontent.com/67392684/190885608-54a3b91b-3b01-46e1-a308-7f47efea6527.png)

Applying the same idea to other options, e.g. the cell size option and the # of rows per page, would be useful. Another useful global feature would be to disable the blank Column 1, as I end up removing it every time anyway.

**Comment by RafaelGB** [comment]
Commit a7c39341
