### ISSUE TITLE
[FR] Option to hide the top bar + bottom bar (the new row/file)

### ISSUE THREAD

**Issue by afland** [RafaelGB/obsidian-db-folder#359]
To be honest, I find that that the top bar just takes up a lot of space and doesn't look very aesthetic. It would be nice if it could be replaced by just a search and settings icon in e.g. the top right.

![image](https://user-images.githubusercontent.com/67392684/189506552-dfead9ff-ac23-4a73-84e1-1ff311bb588b.png)

Same thing for the bottom bar (the new row/file)

![image](https://user-images.githubusercontent.com/67392684/189506585-1bd016f3-5f9f-4cfe-b98c-4a8002f5dc2d.png)

It would be nice if that doesn't always overlay on top, but instead only shows when you actually scroll to the bottom. Maybe the template selector could also be shrunk a bit and not have that intense white outline (I'm on minimal, but they're also present in default dark).

These are just my personal views on how the UI could be streamlined so that max space is dedicated to the table itself. It would be great if these changes were implemented, but I understand if they don't fall within your vision for the plugin

**Comment by RafaelGB** [comment]
The UI always have room for improvement.
About the bottom bar I am investigating ways to hide/unhide it, but the top bar right now I think its fine. The component that I want to remove/move its the name. between menu and input search.

Any idea/design/help is welcome =)

**Comment by afland** [comment]
> The UI always has room for improvement. About the bottom bar I am investigating ways to hide/unhide it, but the top bar right now I think its fine. The component that I want to remove/move its the name. between menu and input search.
> 
> Any idea/design/help is welcome =)

I agree that the top bar is fine, but I feel like its functionality doesn't justify it occupying that much space. All that's really needed for the functionality is a search and settings/menu icon

**Comment by afland** [comment]
Since there is a CSS snippet to hide the top bar already, maybe you could add an option somewhere else in the UI to search the database. That way users who want to remove the top bar can do so without losing functionality.
Next to the Open database settings option?
![image](https://user-images.githubusercontent.com/67392684/189545883-a2406955-983d-4b78-a366-334e27441477.png)

**Comment by RafaelGB** [comment]
Could you share that snippet? I am not familiarise with them.

Maybe we can use key shortcuts like ctrl+s (search) and ctrl+f(filters) to show those functions.

**Comment by afland** [comment]
```
.dbfolder-table-container .database-plugin__sticky-level-1 {
    display: none;
}
.dbfolder-table-container .database-plugin__sticky-level-2 {
    top: 0px;
}
```

**Comment by RafaelGB** [comment]
I'm trying to get mobile support for the taskbar since we're improving it, but I need help getting it to stick when scrolling horizontally. I released version 2.6.4 with improvements for mobile

**Comment by RafaelGB** [comment]
Option of bottom added. But I think that the top menu should not be hide for now.

I am working on a new style

https://user-images.githubusercontent.com/11924043/191317654-820bd1d2-293c-4264-ae4e-165957ab902b.mov

**Comment by imeed166** [comment]
Regarding the top bar, you could copy how kanban plugin does it **(with custom icons in obsidian top bar)** to replace :
- search
- filter
- open as markdown
- export
- import
- open settings


![Image](https://user-images.githubusercontent.com/38974541/191438199-138baf84-02b9-4ee0-aad4-3da94804cb89.png)



The only issue is the pagination, maybe if you include it in the bottor bar with your new style, you could remove the database top bar completely (just a suggestion)

**Comment by RafaelGB** [comment]
there would be a problem with it since in Obsidian v.16 that bar is optional. The user can disable it and all those accesses would be lost
