### ISSUE TITLE
[FR] option to display all rows in 1 continuous list (instead of splitting into pages)

### ISSUE THREAD

**Issue by afland** [RafaelGB/obsidian-db-folder#362]
### Present your request

An option to choose whether all rows are displayed in 1 continuous list or split by pages would be nice. I think it would make sense to have this as a global option, but having a per-database setting + a default setting would also work

I know there's the # of rows per page option in each database, but that doesn't seem to work for me, and an option to make the list continuous no matter the row count would be great

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
the problem with that is the performance. I mark the cap on 200 per page as the max for that reason.

If want to experience a continuous scroll you can always open the markdown of your database and modify the max rows per page manually without a maximum
