### ISSUE TITLE
[Bug]: can't delete the column generated automatically named "column 1"

### ISSUE THREAD

**Issue by Yubuxin** [RafaelGB/obsidian-db-folder#363]
### Contact Details

konger1116@163.com

### What happened?

A bug happened!
When I create a new database file, it always contain a column named "column 1" which can not be deleted.

### What platform were you using?

Desktop

### Version of the plugin

2.5.0

**Comment by Yubuxin** [comment]
And the modifying of file settings seems can not effect properly.

**Comment by RafaelGB** [comment]
was a problem with saving introduced with https://github.com/RafaelGB/obsidian-db-folder/issues/179

fixed with 5.0.1
