### ISSUE TITLE
[Bug]: can't add page in the raw

### ISSUE THREAD

**Issue by DmitryKorzhov** [RafaelGB/obsidian-db-folder#364]
### Contact Details

korzhov.work2019@gmail.com

### What happened?

When I tried add page in raw I faced with strange form of it. I tried to add [[Dmitry Korzhov]], but when I change any column or raw — this plugin transform it to "[[pages/Dmitry Korzhov.md|Dmitry Korzhov]]". But if I add some text before page — it's work correctly. For example: New [[Dmitry Korzhov]] — it's work. Only [[Dmitry Korzhov]] didn't work.

Bad work:
<img width="440" alt="Screenshot 2022-09-12 at 10 07 04" src="https://user-images.githubusercontent.com/110081614/189572328-c4b5f73a-d1ba-4dc0-91bd-c944e7c160dc.png">

Correct work:
<img width="272" alt="Screenshot 2022-09-12 at 10 10 29" src="https://user-images.githubusercontent.com/110081614/189572365-a9c0a616-272d-4c2c-bfe4-8156ad2eec5b.png">

### What platform were you using?

Desktop

### Version of the plugin

2.5.0

**Comment by RafaelGB** [comment]
Its intentional. It is the way that the plugin has to be sure that the link is unique.  add the route and put the name as an alias, at the visual level there would be no difference
