### ISSUE TITLE
[Bug]: Settings in database can't be saved

### ISSUE THREAD

**Issue by AndyLiu9** [RafaelGB/obsidian-db-folder#365]
### What happened?

With the latest version (2.5.0), settings and changes made in database can't be saved.
To illustrate, I have created a vault with only two plugins(Dataview and DB folder). Then I created a database note with "current folder". I chose one column and selected "Hide". But if I switch to another note then back to it, the column shows again. Seems that the changes or settings can't be saved.
My device is iPhone 11 and iOS 15.6.1. The same thing also happens on my Mac so I think it's not relevant to operating system or device. Or maybe I have missed something in setting? Could you please give some help? Thanks!

![61831E27-CD9A-4063-A082-1A10F665F2D0](https://user-images.githubusercontent.com/88693956/189578398-025816f0-b1ed-49d5-9d69-d2f80b13fa0e.gif)

### What platform were you using?

Mobile

### Version of the plugin

2.5.0

**Comment by RafaelGB** [comment]
was a problem with saving introduced with https://github.com/RafaelGB/obsidian-db-folder/issues/179

fixed with 5.0.1
