### ISSUE TITLE
[Bug]: Destination folder for New entries not working, all entries are created in the root folder.

### ISSUE THREAD

**Issue by cesarpereira904** [RafaelGB/obsidian-db-folder#367]
### Contact Details

cesarpereira904@gmail.com

### What happened?

For a Database created with a Dataview query, when defining the Destination folder of new entries, all entries are created in the root folder intead:

![image](https://user-images.githubusercontent.com/70922426/189623168-ece9b63b-3062-4835-ae4a-b164219e103b.png)

![image](https://user-images.githubusercontent.com/70922426/189623436-2d31c002-9680-4ab9-a0cc-564620da4726.png)

![image](https://user-images.githubusercontent.com/70922426/189623485-bb24c1b7-cdce-4ad5-9e7c-096236cf1a50.png)

If a group folder is defined, folder will also be created in the root:

![image](https://user-images.githubusercontent.com/70922426/189623748-bd3c3e69-52fe-478d-8461-af01db64392f.png)

![image](https://user-images.githubusercontent.com/70922426/189624262-dd836622-2ae7-45a9-af76-b98fddde7c6d.png)

### What platform were you using?

Desktop

### Version of the plugin

2.5.1.

**Comment by RafaelGB** [comment]
try with 2.5.2 version. There was a problem with new entries

**Comment by cesarpereira904** [comment]
Thank you so much Rafael,

As soon its out will check it and let you now.

**Comment by imeed166** [comment]
It's already out @cesarpereira904

**Comment by cesarpereira904** [comment]
For some reason can´t update it directly in Obsidian. 
![image](https://user-images.githubusercontent.com/70922426/189640029-bd6eb665-f848-419f-a1e7-6e2bdbc1d9f8.png)

I will dowload it directly.

thank you for letting me know Rafael!

**Comment by cesarpereira904** [comment]
Hi Rafael, 
Although I downloaded directly the files to the plugin folder I still see version 2.5.1 as latest version of the plugin.
Also tried to uninstall and install the plugin but still see latest version as 2.5.1.
Checking of the issue described before seems it remains.

**Comment by RafaelGB** [comment]
the version was incorrectly generated. Try to refresh again

**Comment by cesarpereira904** [comment]
Hi Rafael,

I Was able to donwload it and now using the 2.5.2 but new entries still are created in the root folder. 

Can I provide any other information to help?

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/189648128-be867988-7687-4ee7-9d9c-199feace3d42.mov

Looks like its working for me
try to select again another folder, maybe with previous versions was not well persisted

**Comment by cesarpereira904** [comment]
Ok I think I  found the problem, 

If I use tag as source of the database, as in your example,  it works, but If i'm using a dataview query as source for the database it doesn't work.

It seems is specific for when using dataview as source database.

I was trying for "current_folder", "tag", "outgoing_link" and "incoming_link" and it works fine for those database sources options.

**Comment by RafaelGB** [comment]
Oops... I see, Fixed for the next version =P 

<img width="1429" alt="Screenshot 2022-09-12 at 14 21 57" src="https://user-images.githubusercontent.com/11924043/189652141-e9690d94-1faa-4d75-aa2a-6eb0449b78f7.png">
