### ISSUE TITLE
[Bug]: Sorting not working for Metadata "Created" or "Modified"

### ISSUE THREAD

**Issue by cesarpereira904** [RafaelGB/obsidian-db-folder#368]
### Contact Details

cesarpereira904@gmail.com

### What happened?

Sorting by  "Created" or "Modified" columns not working:

Not Sorted:
![image](https://user-images.githubusercontent.com/70922426/189628102-efd37228-1766-434f-bb8a-1a736a3205de.png)

Sorted ascending by "Created":
![image](https://user-images.githubusercontent.com/70922426/189628235-44768c96-c2b8-43d1-a8b8-4b927b2cff95.png)

Sorted by descending by "Created":
![image](https://user-images.githubusercontent.com/70922426/189628382-a760be5a-f68b-4036-85b2-c35559fd2903.png)

Sorted ascending by "Modified":
![image](https://user-images.githubusercontent.com/70922426/189628476-968f29d9-bba3-42b8-b3b8-a64bdf481d30.png)

Sorted descending by "Modified":
![image](https://user-images.githubusercontent.com/70922426/189628539-2d61e320-1410-44fa-9319-c384cd4b0062.png)

### What platform were you using?

Desktop

### Version of the plugin

2.5.1

**Comment by RafaelGB** [comment]
thanks for the report. I will check it
