### ISSUE TITLE
[Bug]: sort doesn't apply in date column

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#371]
### Contact Details

danny@dannyhatcher.com

### What happened?

When sorting by a date property (deadline) there was no change in the display order. 
![image](https://user-images.githubusercontent.com/78496825/189680468-8c587c95-b42a-44e4-8f87-8081369d86a7.png)

### What platform were you using?

Desktop

### Version of the plugin

2.5.1

### Relevant log output

```shell
No idea what I am copy and pasting.
This is what I see

Uncaught (in promise) Failed to index file: Notes/database.md: Error: Cannot index file, since it has no Obsidian file metadata.
2plugin:dbfolder:10 Uncaught Error: Minified React error #200; visit https://reactjs.org/docs/error-decoder.html?invariant=200 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.Qr.Gr.createPortal (plugin:dbfolder:10:125962)
    at zU (plugin:dbfolder:238:357774)
    at Ei (plugin:dbfolder:10:62177)
    at Os (plugin:dbfolder:10:73445)
    at Cl (plugin:dbfolder:10:119595)
    at yc (plugin:dbfolder:10:107733)
    at vc (plugin:dbfolder:10:107661)
    at gc (plugin:dbfolder:10:107524)
    at ac (plugin:dbfolder:10:104331)
    at lc (plugin:dbfolder:10:104720)
```

**Comment by imeed166** [comment]
I tested it with 2.5.3, and it works normally if all the cells of the column are not empty. But, if some cells remain empty the sort with not work.
![image](https://user-images.githubusercontent.com/38974541/189685236-540e17a7-f07b-4056-95a0-944f8264e3b1.png)

**Comment by RafaelGB** [comment]
hi @DannyHatcher-Git , we are working on a new function to support multiple type of values. Currently is on "auto" mode provided for react-table framework

**Comment by DannyHatcher-Git** [comment]
Yes, thankyou! I checked for updates yesterday 🤷‍♂️ How do I get a notification about updates?

**Comment by RafaelGB** [comment]
You can watch/unwatch the repository to be notified

**Comment by imeed166** [comment]
Select "release" under custom
![image](https://user-images.githubusercontent.com/38974541/189699420-d87ccbc7-7dba-41ec-9278-6d3008e4f7bc.png)

**Comment by RafaelGB** [comment]
resolved with a custom function

```ts
import { Row, SortingFn } from "@tanstack/react-table";
import { RowDataType } from "cdm/FolderModel";
import { LocalSettings } from "cdm/SettingsModel";
import { InputType } from "helpers/Constants";
import { Literal } from "obsidian-dataview";
import { DataviewService } from "services/DataviewService";

const dbfolderColumnSortingFn: (
  ddbbConfig: LocalSettings
) => SortingFn<RowDataType> =
  (ddbbConfig: LocalSettings) =>
  (
    rowA: Row<RowDataType>,
    rowB: Row<RowDataType>,
    columnId: string
  ): number => {
    const a = DataviewService.parseLiteral(
      rowA.getValue<Literal>(columnId),
      InputType.MARKDOWN,
      ddbbConfig,
      true
    )
      .toString()
      .toLowerCase();
    const b = DataviewService.parseLiteral(
      rowB.getValue<Literal>(columnId),
      InputType.MARKDOWN,
      ddbbConfig,
      true
    )
      .toString()
      .toLowerCase();
    return a === b ? 0 : a > b ? 1 : -1;
  };

export default dbfolderColumnSortingFn;
```

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/189729338-94bdcfdc-8e55-4f53-86ed-5f7afde4598b.mov
