### ISSUE TITLE
[Bug]: Group Folders are created in root for databases with a dataview query as source data.

### ISSUE THREAD

**Issue by cesarpereira904** [RafaelGB/obsidian-db-folder#372]
### Contact Details

cesarpereira904@gmail.com

### What happened?

For a database with a dataview query as source data:
![image](https://user-images.githubusercontent.com/70922426/189695120-b106a640-b61a-4353-ba12-c9a6c13c6f0b.png)

If we define a group folder as follows:
![image](https://user-images.githubusercontent.com/70922426/189695223-038d1d7b-58d3-490c-937c-01532b026d36.png)

To map the "status" column:
![image](https://user-images.githubusercontent.com/70922426/189695389-799bcf46-987c-4ad7-b8dd-74af08ca165e.png)

Folders are created in the root of the vault.

Video:
https://user-images.githubusercontent.com/70922426/189695546-b5fd0122-d495-4539-95b7-196bf723a2b7.mp4

Would suggest that folder would be created under same folder as set in the destination folder:
![image](https://user-images.githubusercontent.com/70922426/189695772-7ded2baa-1505-4b60-85ed-423972cda856.png)

### What platform were you using?

Desktop

### Version of the plugin

2.5.3.

**Comment by RafaelGB** [comment]
Hi @cesarpereira904 , yeah I found this problem with your other issue https://github.com/RafaelGB/obsidian-db-folder/issues/367

Already resolved for the next version

**Comment by cesarpereira904** [comment]
Thank you Rafael,

You’re faster coding that me writing :)
