### ISSUE TITLE
[BUG]: Special characters on column names affects dv query

### ISSUE THREAD

**Issue by brandonkboswell** [RafaelGB/obsidian-db-folder#375]
### Contact Details

brandonkboswell@gmail.com

### Present your request

I want to see a query example in the docs when setting up a new database. I am trying to create dashboards for specific folders (without having to have the database in those folders), but I can't seem to get the syntax right or find a good example. I'm trying `FROM "2. areas"` and it says it is valid, but when I go to open the database I get an error obtaining query result, using current folder instead

### For which platform do you request this request??

Desktop

**Comment by imeed166** [comment]
Used the query source, with a similar `FROM "folder"` and it worked for me, on version 2.5.3. Make sure to use `copy file path` command to get the folder name. As this is a possible bug, I will change the label.

As for the example in the docs, I'll add one, thanks for the suggestion.

**Comment by brandonkboswell** [comment]
I have a folder named  `2. areas`. When I copy file path, I get "2. areas". When I put that into the query as `FROM "2. areas"`I get errors.

![image](https://user-images.githubusercontent.com/921925/189955655-c14ac482-15a9-4817-8ec7-8c78cbc2251e.png)

**Comment by RafaelGB** [comment]
I am trying to reproduce your case but it woks fine

Could you share your markdown database file?

another possibility is that the query does not work itself. try it out of the plugin with a simple
```
'''dataview
TABLE file FROM "2. areas"
'''
```
https://user-images.githubusercontent.com/11924043/189960925-1ceb1cc1-31c5-4e62-b79c-2a11c8a094ff.mov

**Comment by brandonkboswell** [comment]
The Dataview query works. This is my Markdown file. 

`---

database-plugin: basic

---

%% dbfolder:yaml
name: Area Dashboard
description: 
columns:
  __file__:
    key: "__file__"
    input: "markdown"
    label: "File"
    accessorKey: "__file__"
    isMetadata: true
    skipPersist: false
    isDragDisabled: false
    csvCandidate: true
    width: 329
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      media_width: 100
      media_height: 100
      isInline: true
      task_hide_completed: true
  __tasks__:
    key: "__tasks__"
    input: "task"
    label: "Task"
    accessorKey: "__tasks__"
    isMetadata: true
    isDragDisabled: false
    skipPersist: false
    csvCandidate: false
    width: 484
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
  2022-Q3:
    input: "select"
    accessorKey: "2022-Q3"
    key: "2022-Q3"
    label: "2022-Q3"
    position: 100
    skipPersist: false
    isHidden: false
    width: 109
    sortIndex: -1
    options:
      - { label: "On Track", backgroundColor: "hsl(106, 95%, 90%)"}
      - { label: "Slipping", backgroundColor: "hsl(37.42857142857143,91.30434782608697%,54.90196078431373%)"}
    config:
      enable_media_view: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
config:
  remove_field_when_delete_column: false
  cell_size: compact
  sticky_first_column: true
  group_folder_column: 
  show_metadata_created: false
  show_metadata_modified: false
  show_metadata_tasks: true
  source_data: query
  source_form_result: "FROM \"2. areas\""
  frontmatter_quote_wrap: false
  row_templates_folder: /
  current_row_template: 
  pagination_size: 145
  show_metadata_inlinks: false
  show_metadata_outlinks: false
  source_destination_path: 2. areas
filters:
  enabled: false
  conditions:
%%`

**Comment by RafaelGB** [comment]
The problem here is how is saved.

Instead "/"your folder/"". The yaml is saved without the /

Which version of the plugin are you using?

**Comment by brandonkboswell** [comment]
2.5.3

**Comment by brandonkboswell** [comment]
Hey Rafael, weirdly when I go into the markdown file the source_form_result already is that. Here's a Loom in case I'm doing something wrong: https://www.loom.com/share/28c4830ca3724d7dba140f1ddb6f4cb9

**Comment by RafaelGB** [comment]
I think I have found the problem with your query. The naming of your 2022-Q3 breaks the call. I have to investigate why

Try with another naming or rename manually the key,id... of the column less the label

The plugin use the id/key to construct the query

**Comment by brandonkboswell** [comment]
You appear to be correct. Renaming to Q32022 appears to work. Thanks!

**Comment by RafaelGB** [comment]
nice! I will check the reason about the problem with `-` in the names.

**Comment by brandonkboswell** [comment]
Interestingly, I still run into the issue with '2022Q3', so I think it might have more to do with the leading year than the dash

**Comment by brandonkboswell** [comment]
Thank you, @RafaelGB, for the wonderful plugin and support!

**Comment by RafaelGB** [comment]
okey looks like a bug with the DV api, Your field can not start with a number...

Anyway I will release a minor version where you can see on console log "info"lvl the entire query
