### ISSUE TITLE
[Bug]: when using the data view query as source you cant seem to add existing columns

### ISSUE THREAD

**Issue by zeltak** [RafaelGB/obsidian-db-folder#377]
### What happened?

Hi and thx for your amazing work!

I have started today to play around with db-folder and its amazing. one thing I have noticed is that when adding a DB to an existing folder its easy to add columns based on all available yaml data. But, when I put the DB file in another folder and use data view query as source to point to a folder I cant see to add/get the available yaml data sources

here is an example of how I point it to a folder

![CleanShot 2022-09-14 at 11 26 42](https://user-images.githubusercontent.com/498410/190104283-e8a0a214-522a-4d04-8f1f-ec2323b7a6db.png)

and then when trying to add columns I just get empty options

![CleanShot 2022-09-14 at 11 30 03](https://user-images.githubusercontent.com/498410/190104354-0d70c18c-2799-4c4c-a04f-732d4784e1df.png)

thx again , happy to help debug this

Z

### What platform were you using?

Desktop

### Version of the plugin

2.5.3

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Seems right, I will check the reasons for this, thanks for the report @zeltak

**Comment by RafaelGB** [comment]
We need to create a totally new query using LIST source because we already filter the rest of them using table

**Comment by zeltak** [comment]
thx for working on this! is there in the mean time a workaround (I like to have all my tables separated in a neat centralized folder :))

again thx for your epic work

best

Z

**Comment by RafaelGB** [comment]
Currently there is no solution. The API of dataview for literal queries already filter those values not selected from our table, so we can not obtain then.

To search all those values, we need to translate the literal query to JS query which returns all fields first and then you can filter manually. I think this issue does not have much priority and supposes a lot of work. It will arrive with future versions but I cant tell you when

**Comment by zeltak** [comment]
I totally understand, thank you!

**Comment by RafaelGB** [comment]
Commit 1765bb11

Found a solution =)

**Comment by zeltak** [comment]
awesome! thx so much @RafaelGB !!!
