### ISSUE TITLE
[FR]: Column option to wrap content

### ISSUE THREAD

**Issue by cesarpereira904** [RafaelGB/obsidian-db-folder#378]
### Contact Details

cesarpereira904@gmail.com

### Present your request

Add an option in the column settings menu to alight content to left, center or right and an option to wrap content. 

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
yeah, I want to add those options into the column settings

**Comment by imeed166** [comment]
Aligning content is already available, changing the note title for the remaining feature request.

**Comment by RafaelGB** [comment]
About to wrap content could take some time to do not break the actual row size setting

**Comment by cesarpereira904** [comment]
Amazing improvement Rafael!!! 

From both requests I think this one was really the most important, for databases with many columns this change makes it so much readable than before. 

Would be possible to replicate this to the file name column?
Usually my files names correspond to tickets codes, so they always have same number of characters and by making the column narrow all those ticket codes fit perfectly, but, in another database where I have notes files the names can vary according to the title I give then , which makes it harder to read.

**Comment by RafaelGB** [comment]
I will add justify content as an option too with this issue

**Comment by cesarpereira904** [comment]
Hi Rafael,

Thats a great idea.

I know this was not in the original request but because you're working on this feature I also would suggest to have an option  vertically align the content.

As an example:

![image](https://user-images.githubusercontent.com/70922426/192109742-5a5a142f-5119-4c68-9413-daaf3ac39475.png)

Where Date fields are vertical aligned to the top and the rest of the content in the center.

I think that if we will wrap a long text it might be easier to read if all content will be vertically align on top.
But if we are talking about short text so maybe align verticality to the center. (just like in excel).

What you think?
(I'm not aware how much work it requires so might not worth at this time among all other requests you have.)

**Comment by cesarpereira904** [comment]
Seems tags columns also aligns vertically to the top:
![image](https://user-images.githubusercontent.com/70922426/192110284-e6c79c1e-8632-41e3-83ae-02e03e43193b.png)

**Comment by RafaelGB** [comment]
I will investigate if it's easy to implement, if not we can separate it on another issue

**Comment by cesarpereira904** [comment]
Sounds great! thank you!
By the way, last update was fire!!! 
Amazing work

**Comment by RafaelGB** [comment]
I am glad that you enjoy it 😊
I am keeping working on improve the UI for mobile and desktop

**Comment by RafaelGB** [comment]
Last question before finish this issue. Default value of wrap: true or false?

**Comment by imeed166** [comment]
false

**Comment by cesarpereira904** [comment]
I would say false.

**Comment by RafaelGB** [comment]
Will be false then :)

**Comment by javiavid** [comment]
Hello Rafa,
I've tried the new plugin option and the wrap works fine, but it doesn't work in compact mode.
Is it possible to make it work in this mode?

**Comment by jkroes** [comment]
> Hello Rafa, I've tried the new plugin option and the wrap works fine, but it doesn't work in compact mode. Is it possible to make it work in this mode?

Or at least note this in the docs or settings. I had to search through the issues to figure out why wrapping didn't work.
