### ISSUE TITLE
[Bug]: Doesn’t display any data besides "Created" and "Modified" columns for dataview query Databases.

### ISSUE THREAD

**Issue by cesarpereira904** [RafaelGB/obsidian-db-folder#381]
### Contact Details

cesarpereira904@gmail.com

### What happened?

First of all...

 Congrats for this amazing update, it's a game changer to be able to use formulas.

 

Regarding this last update I'm experience only one issue for DV Databases.

With exception of the "Created" and "Modified" columns, all other columns don't display any data.

If I change the source of the database to "current_folder" it displays all information properly.

DB Folder configuration:
![image](https://user-images.githubusercontent.com/70922426/190239045-f63ef863-e45c-4153-8137-d84b00a6d0ac.png)

Results in DB Folder:
<img width="664" alt="image" src="https://user-images.githubusercontent.com/70922426/190239871-d66e3dad-89a7-4f71-85fe-90205319fc70.png">

Same dataview query as in the Database source:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/70922426/190239515-1f38c826-e0c9-47ef-ac0c-5c73208d7332.png">

Let me know if I can provide any other information that might help!

Things I have tried:
- restarted obsidian after updating the plugin
- uninstall & install the plugin.
- run the command "drop all cached file metadata"

Unfortunately none of these seem to work.

### What platform were you using?

Desktop

### Version of the plugin

2.6.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Maybe is related with https://github.com/RafaelGB/obsidian-db-folder/issues/375

I will test this issue, thanks for the report
