### ISSUE TITLE
[Bug]: Filter not saving

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#383]
### What happened?

When I save a second filter in a view (a done checkbox filter) it doesn't save the filter for when I next load the page. I get this error 
![image](https://user-images.githubusercontent.com/78496825/190249703-3c95c8bd-621a-43c3-a82c-afa5285b3395.png)
even though the filter worked fine before leaving the page.

### What platform were you using?

Desktop

### Version of the plugin

0.5.46

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
its a normal "error"

The plugin is evolving fast and we need need properties. With the version 2.6.0 now we have formulas, so a property `formula_folder_path` was added automatically when you opened again the ddbb

**Comment by csss1234** [comment]
I was having the same problem until manually editing the markdown. Try adding something like this at the very end
```
filters:
  enabled: true
  conditions:
    - {field: Date, operator: IS_NOT_EMPTY, value: S}
%%
```
