### ISSUE TITLE
[FR]: Option of save, sort and search formulas output

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#387]
### Contact Details

sarah.arminta@me.com

### Present your request

I want to see ...

Write the formula column as a field in each file along with the calculated value. The value updates in the file as needed. 

### For which platform do you request this request??

Cross

- [x] Save
- [x] Search
- [x] Sort

**Comment by RafaelGB** [comment]
Yeah, this is in my mind, but I want to make it optional. Also with the possibility of sort and search too but its not trivial.


I just want to share the first version of those formulas

**Comment by RafaelGB** [comment]
I found a way to persist the formulas, but vould be a problem have more than 1. Could overwrite the file between them, so a write queue is needed. It suppose some time
