### ISSUE TITLE
[FR]: Manually sort rows via drag and drop

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#388]
### Contact Details

sarah.arminta@me.com

### Present your request

I want to see ...

Use the context menu icon to drag and drop rows into the desired order. 

Bonus, have a corresponding "row id" column/property or similar that updates based on the sort order. 

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
The problem with dnd rows is the noise that it needs in every row, it must save a custom property 
For example, to persist that order and represent it:
```md
***
__rowIndex__: 2
***
```
will load that row in second position.

I do not thinks its a good idea but open to discussions

**Comment by RafaelGB** [comment]
The philosophy of the plugin is that the user does not have to include anything extra in their files for it to work.  That way you don't feel tied to this app.

currently I dont find anyway to allow manual row order without alter something inside of the notes

**Comment by RafaelGB** [comment]
suppose we have 10000 files. The plugin should read them all, order them, discard those modified or mossed files and reorder the list again including the new ones affecting the performance and multiplying the size of the dbfolder file to MBs just to order manually the rows. I think its not a good idea
