### ISSUE TITLE
[Bug]: Android search bar error

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#392]
### What happened?

The search bar is poorly displayed and difficult to use.
The rest of the items on the right are not displayed.

![image](https://user-images.githubusercontent.com/7627504/190594669-a8e6dbb7-68ba-4ceb-b0c5-0eda8c37ad94.png)

### What platform were you using?

Mobile

### Version of the plugin

2.6.2

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
At the moment we do not have enough contributors to support the mobile and its different incidents.

As soon as we achieve different cross milestones, we will dedicate time to solving mobile incidents

**Comment by javiavid** [comment]
Ok, thanks
