### ISSUE TITLE
[Bug]: Some problems with new function (inline fields as default)

### ISSUE THREAD

**Issue by anonymous-philosophy** [RafaelGB/obsidian-db-folder#394]
### What happened?

1. If a field is empty, and I put something in there, in a file it doesn't create a new string with new category, but puts it just after last symbols. And it not only looks bad, but also doesn't work. So there's a need of adding new paragraph in such case :)
2. Even if I don't use yaml-code at all (in the beginning of a note), it always puts two strings with --- after editing this file in DB-view. It doesn't change anything, but would be better if there wasn't one.

3. And one more thing I've noticed: when the content of a field is [[Link]], and I choose the "Select" property type, for some reason it appears in DB-view with a path, like [[Inbox/link.md|Link]]. And when I _select_ this in other notes, it also puts the link with the path in the note.

### What platform were you using?

Desktop

### Version of the plugin

2.6.2

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hi @anonymous-philosophy , thanks for the report.

The first two points will be resolved with https://github.com/RafaelGB/obsidian-db-folder/issues/343.
About the last one I know it is not the best solution but at the moment it is not possible to change it. We need to know the file path in case of possible duplicate names in the database. In the future we hope to find a less aggressive method for the user.
