### ISSUE TITLE
[Bug]: When renaming the database the database disappears

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#395]
### What happened?

https://user-images.githubusercontent.com/7627504/190848872-2a555eed-f872-4dff-83bb-8ae570ec7e54.mp4

### What platform were you using?

Desktop

### Version of the plugin

2.6.2

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
the problem was the react portal naming. Fixed with the next version
