### ISSUE TITLE
[Bug]: Can't create any database : file cannot contain any of these characters

### ISSUE THREAD

**Issue by Lisandra-dev** [RafaelGB/obsidian-db-folder#397]
### What happened?

- I tryed to create a new simple database
- I set the name "test" and the current folder as source
![image](https://user-images.githubusercontent.com/30244939/190856531-5fb5a659-4966-4595-949d-da69494b9b23.png)
- The following message appear : 
![image](https://user-images.githubusercontent.com/30244939/190856477-9b7a4c43-0f6c-4485-a17f-b2a64d96a823.png)
- I don't have any log related

### What platform were you using?

Desktop

### Version of the plugin

2.6.2

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
with the same names and target path I can not reproduce this issue, maybe fix with another fix?

**Comment by RafaelGB** [comment]
[Archive.zip](https://github.com/RafaelGB/obsidian-db-folder/files/9591705/Archive.zip)

Try this version to discard if its a possible fixed bug

**Comment by Lisandra-dev** [comment]
Nop, doesn't work. 
I think it's maybe an error that occur only on windows, where path contains `\` instead of `/` ? But I think that Obsidian fix that in their different function that includes path...

**Comment by RafaelGB** [comment]
I will test it on Windows to see if I can reproduce it

**Comment by RafaelGB** [comment]
Obsidian manage that relative paths internally. I could test it today on windows and its working cool

**Comment by Lisandra-dev** [comment]
I retry today, and no success to create a database using the command.
No error in log, just this message about incorrect naming.

**Comment by RafaelGB** [comment]
Could you share your active plugins? maybe exists some kind of incompatibility.

**Comment by Lisandra-dev** [comment]
I disabled all my plugins (keeping only db folder & dataview) and It continues to do that.
Interestingly, it doesn't do that in my other instance of Obsidian. 

At the moment, the only difference between my two vault : 
- The place (one on `I:\`, other in `D:\Documents\Github\Pingouin`)
- Syncing system : I use Obsidian Sync on the main vault, and none in the second (it's my vault test)

```
SYSTEM INFO:
	Obsidian version: v0.16.3
	Installer version: v0.14.15
	Operating system: Windows 10 Education 10.0.22622
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal
	Snippets enabled: 44
	Restricted mode: off
	Plugins installed: 88
	Plugins enabled: 2
		1: DB Folder v2.6.7
		2: Dataview v0.5.46

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

**Comment by RafaelGB** [comment]
I don't do anything strange with the create of the file, just the use of the Obsidian API
```ts
  /**
   * Add new file inside TFolder
   * @param file_path 
   * @param filename 
   * @param content 
   */
  async create_markdown_file(targetFolder: TFolder, filename: string, localSettings: LocalSettings, databasefields?: RowDatabaseFields): Promise<TFile> {
    LOGGER.debug(`=> create_markdown_file. name:${targetFolder.path}/${filename})`);
    const created_note = await app.fileManager.createNewMarkdownFile(
      targetFolder,
      filename ?? "Untitled"
    );
    let content = databasefields ? parseFrontmatterFieldsToString(databasefields, localSettings).concat("\n").concat(parseInlineFieldsToString(databasefields)) : "";

    // Custom content by source
    switch (localSettings.source_data) {
      case SourceDataTypes.TAG:
        content = content.concat(`#${localSettings.source_form_result}\n`);
        break;
      default:
    }
```
If you enable the plugin logs on debug mode (developer general settings section), we can see the exact generated path
`LOGGER.debug(`=> create_markdown_file. name:${targetFolder.path}/${filename})`);`

With that path you can reproduce it with the API directly on the console of Obsidian
`app.fileManager.createNewMarkdownFile(targetFolder,filename ?? "Untitled")`

Maybe Obsidian API its not prepared for some Windows disk as I://

**Comment by RafaelGB** [comment]
closed as wont fix
