### ISSUE TITLE
[Bug]: I cannot parse my database from other database

### ISSUE THREAD

**Issue by rohanbatraio** [RafaelGB/obsidian-db-folder#398]
### Contact Details
Github 

### What happened?

I created multiple databases and then used open as markdown to add tags in database. I wanted to make a second database which links to multiple smaller database, or can be called a nested database to make a execution flow. the query from dataview is running perfectly but when i try to do the same in DB folder it doesn't work, not with tags, not with dataview query.

Do we have support for querying database inside database? 

### What platform were you using?

Desktop

### Version of the plugin

2.6.2

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Internally the dbs filter its own frontmatter property

We want to cover your use case with views on the future

**Comment by rohanbatraio** [comment]
Thank you. May i please know how can i edit "dbs own frontmatter property"

**Comment by RafaelGB** [comment]
Its a core property inside the md

`database-plugin: basic`

But it is necessary to render them as a database, so you cant remove them

If you really need a db of dbs maybe we can change that filter to just filter the actual one

**Comment by rohanbatraio** [comment]
this "database-plugin: basic" corresponds to yaml entry right, anyways i would wait for bug squashing and next release. But till then if you have any suggestion in which i can achieve that please drop me an explanation. 

structure 
i have 4 databases 
1.md , 2.md , 3.md , 4.md 

all of these files have
---
tag: chapter-1
database-plugin: basic
---

when i parse them on a db files it throws some error where i really don't know. 

thank you

**Comment by RafaelGB** [comment]
I am afraid you have to wait until the resolution of this bug.

Could you share that error?

**Comment by rohanbatraio** [comment]
Sure, hold on a minute.

**Comment by rohanbatraio** [comment]
Something like this 
 "ERROR OBTAINING QUERY RESULT USING CURRENT FOLDER INSTEAD"

which looks like the error i see now and then.

**Comment by rohanbatraio** [comment]
> I am afraid you have to wait until the resolution of this bug.
> 
> Could you share that error?

Sure i would wait. Thank you for your awesome efforts.

**Comment by RafaelGB** [comment]
try your case with 2.6.3 =) should work now

**Comment by rohanbatraio** [comment]
Yes, it works now. Thank you so much.  It was quick.
