### ISSUE TITLE
[FR] tab and enter to go to the next cell

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/obsidian-db-folder#40]
Add events to every cell with tab and enter button so it will move to the next cell

**Comment by RafaelGB** [comment]
Tried without result use tab index and onFocus event with every cell, but seems not enough. I will try in the future again

**Comment by RafaelGB** [comment]
Finally working on this one



https://user-images.githubusercontent.com/11924043/210116438-e6733271-faae-436b-9456-6644d79de552.mov

**Comment by RafaelGB** [comment]
Also arrow control added =)

Commit 075ba07b ready for the next version

**Comment by javiavid** [comment]
Thanks for adding this, it is very useful to go quickly and without a mouse.

1 - The cursors work well, but the TAB key when pressed does not change from one cell to another directly, you have to hit it twice.
2 - Would it be possible for the cell to remain active when you press enter? So you could continue editing without having to press TAB or click the mouse first.

**Comment by RafaelGB** [comment]
We will iterate over this feature sure :) Its just the first version. 

We just need more feedback to know what window of improvement it has

**Comment by Cyletix** [comment]
I think switch cell easily is important to a table tool. 
By the way, I found a problem about use tab switch cell: the window slide speed is out of sync with cell's position
