### ISSUE TITLE
[Bug]: Number column does not display value of zero

### ISSUE THREAD

**Issue by dalewking** [RafaelGB/obsidian-db-folder#402]
### Contact Details

dalewking@gmail.com

### What happened?

When you create a column of type number and enter a zero for the value it does not display in the database table. In my case zero and no value are 2 separate things.

### What platform were you using?

Desktop

### Version of the plugin

Latest

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Thanks for ther report @dalewking I will fix it for the nexrt version.

Negative numbers or decimals des not display too
