### ISSUE TITLE
[FR]: new rows does not insert an empty yaml in favor of templates

### ISSUE THREAD

**Issue by aravindk100** [RafaelGB/obsidian-db-folder#403]
When I use the option to choose the template file to use for all new rows this template file is used but before that the columns I have added in database shows up as the first few yaml entries and with a end result of breaking yaml. Am i missing something?

---
status: 
note_status: 
dummy: 
---
---
type: 
status:
time spent:
---

**Comment by RafaelGB** [comment]
Hi @aravindk100 ,
The template currently are inserting the yaml of your columns first, but I think that we can change this behaviour with the lastest editing engine.

**Comment by aravindk100** [comment]
Thanks Rafael, I will disable templates until then. This plugin has been amazing and exteremely useful for my workflow. Really appreciate all the hard work you put in.
