### ISSUE TITLE
[Bug]: Export CSV does not appear in version 2.6.3

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#404]
### What happened?

<img width="169" alt="image" src="https://user-images.githubusercontent.com/7627504/191024469-77040a6e-6f3b-42b3-8ebf-24fbfe0e0e8b.png">

### What platform were you using?

Desktop

### Version of the plugin

2.6.3

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
As we talk, this looks like an incompatibility with another plugin. Closed as wont fix external
