### ISSUE TITLE
[FR]: Adding a jump up navigation in database ( probably using backlinks)

### ISSUE THREAD

**Issue by rohanbatraio** [RafaelGB/obsidian-db-folder#407]
### Present your request

I would love to have navigation being sorted out. 
I am working on a complex hierarchy of databases into databases as also stated in this [issue](https://github.com/RafaelGB/obsidian-db-folder/issues/398) which is now fixed. 

So the suggestion is when we land on database file, we have no choice to go back without using file explorer which is time consuming plus distractive (in my case as a student). 

say for example i have :

db1 with two links going to db2 and db3 respectively and db2 have links going to db4 and db5 and i followed the path as described below,

db1 --> db2 --> db4 

In pure md where i create dataview queries i use file linking,
[[db2 | previous link]]   something like that. 

But in db folder, this feature is not yet accessible as i don't have markdown area where i can write and view at the same time. what i want is having a button to jump up 1 point. It can be here somewhere

![crop-gt png-mh](https://user-images.githubusercontent.com/113782197/191091056-bb46c89c-7e10-4bda-b0f1-ef168e577c33.png)

Let me know what you think about this feature :+1: 

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
For your use case, the rollup option (https://github.com/RafaelGB/obsidian-db-folder/issues/53) planned in the roadmap fits me much better. I think it would make a lot of noise to put links in the navbar itself.

If you want to go back to the previous file, Obsidian will offer that option natively in the next version.

<img width="1083" alt="Screenshot 2022-09-19 at 21 19 27" src="https://user-images.githubusercontent.com/11924043/191098051-bb67816d-a926-49b1-920b-d3dca0a32a2e.png">

**Comment by rohanbatraio** [comment]
Yes I just want something that would work and if obsidian is going to release it natively then we are good to go. Also you mentioned [#53](https://github.com/RafaelGB/obsidian-db-folder/issues/53) which is in the roadmap i would love to try that once it arrives in the db folder. Thanks
