### ISSUE TITLE
[FR]: Tag selection menu enhancements

### ISSUE THREAD

**Issue by rohanbatraio** [RafaelGB/obsidian-db-folder#408]
### Present your request

I have tons of tags and also tons of nested tags on top of them, so to quickly add a tag i would love to have ability to start typing and the results would sort themselves up. I do have an alternative to dataview query for my case but i do know some non-tech background people tend to be scared from dataview. For them and speeding up my workflow i would love to have tag being searchable by typing. Thanks 

![gitnew png-mh](https://user-images.githubusercontent.com/113782197/191185730-78dd737f-9d97-4dfd-93db-54a44e072442.png)

### For which platform do you request this request??

Desktop

**Comment by rohanbatraio** [comment]
Also the scroll doesn't seem to help, it is shown to be rending no scroll bar, i am able to scroll but have no idea where i am. 

UI

![scroll-gitnew png-mh](https://user-images.githubusercontent.com/113782197/191186050-b24df05b-6961-4ded-8bf5-1b97a8fc0c9d.png)

**Comment by RafaelGB** [comment]
It is a simple addition that can give a lot of value, it seems reasonable

**Comment by rohanbatraio** [comment]
When bug #411  would be resolved we would be able to query multiple tags with dataview. So why not just implement that behavior here as well, I mean when we would be able to type tags we should be able to type MULTIPLE tags after the resolution of #411.

**Comment by RafaelGB** [comment]
The possibilities and cases are infinite with dv queries. Currently I think its not a priority to dev more source options

Its too much effort for something that already exist

**Comment by rohanbatraio** [comment]
Yeah that's reasonable, lets skip this and focus on just the tag typing enhancement.
