### ISSUE TITLE
[FR]: Small visual change: remove the magnifying glass in the search box.

### ISSUE THREAD

**Issue by cesarpereira904** [RafaelGB/obsidian-db-folder#409]
### Contact Details

cesarpereira904@gmail.com

### Present your request

Magnifying glass seems out of place in the search box. 
Having the "Search..." text inside the search box makes it clear this is a search box but the magnifying glass icon seems out of place inside this element.
Would it be possible to remove it? (alternatively is there a css snippet we can use to hide it?)

![image](https://user-images.githubusercontent.com/70922426/191206864-b9c8ecd7-1dc9-44a7-8470-599fd79ed0b5.png)

Thank you

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
with the last design this issue was resolved
