### ISSUE TITLE
[FR]: Support to preview database by inserting ![[database.md]] in Notes

### ISSUE THREAD

**Issue by OriOYue** [RafaelGB/obsidian-db-folder#41]
Blogger, could you develop a function like the excalidraw plugin that supports inserting ![[database.md]] in notes to preview the database。
![image](https://user-images.githubusercontent.com/72482686/168484328-4c85f3a7-139e-4b4c-91d1-0e6c33e48644.png)
Because the current effect can only be this:
![image](https://user-images.githubusercontent.com/72482686/168484481-b0f01e9c-f527-4720-83f4-825cb4ddddf7.png)
（My English is poor, so I don't know if the expression is appropriate.）

**Comment by RafaelGB** [comment]
Hi @MeerOst thanks for your suggestion.
I will add it to the backlog :)

**Comment by RafaelGB** [comment]
starting this issue

**Comment by RafaelGB** [comment]
with 1.5.1 preview mode shows a data view table with the content =)
