### ISSUE TITLE
[FR]: New Design Proposal

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#410]
### Present your request

I am sure that the proposal can be improved, but I think it would be good to unify the sizes of the boxes a bit.

![image](https://user-images.githubusercontent.com/7627504/191225952-6e079e60-193b-4100-83d7-0e32aa93f1b0.png)

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
I like it! We can work on it for future interations. Currently we need support for mobiles first
