### ISSUE TITLE
[Bug]: Dataview queries with optional tags

### ISSUE THREAD

**Issue by rohanbatraio** [RafaelGB/obsidian-db-folder#411]
### What happened?

I wrote a query 
`FROM #sop/chemistry/theory/sop OR #testing-1`

which passed the initial check of dataview but DB folder didn't seem to grab those, might be a bug.

### What platform were you using?

Desktop

### Version of the plugin

latest

### Relevant log output

```shell
Error obtaining query result.
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
I will check it, thanks for the report @rohanbatraio

**Comment by rohanbatraio** [comment]
You are most welcome, I am pushing the limits of DB folder and i hope you don't mind me reporting so many bugs.

**Comment by RafaelGB** [comment]
all feedback is welcome to improve the application =)

**Comment by nathan-sain** [comment]
@RafaelGB I am also experiencing a problem with the query source when using a tag in the DQL statement.
For example I created a new vault with only the DB Folder v2.6.4 and dataview v0.5.46 plugins installed. I created two files with a #thing tag within and I then created a database with the query source using the query `FROM #thing` which validates, but results in a "Error obtaining query result" message when closing the settings dialog.

**Comment by RafaelGB** [comment]
Maybe something is mot well saved into the database yaml or can not be read correctly.

I will check it as soon as I finish the "on process" issues

Try to wrap you query with quotes inside the markdown file manually while is reviewed/fixed
(config section)

**Comment by RafaelGB** [comment]
Was an easy fix!
```ts
export const MarkdownBreakerRules = Object.freeze({
  INIT_CHARS: ['`', '"', '[', '{', '*', '!', '>'],
  BETWEEN_CHARS: [':', '"','#'], // # added here to force quote wrap
  UNIQUE_CHARS: ['?'],
})
```

Will be ready for the next version
