### ISSUE TITLE
[Bug]: Editing inline fields inside [] fails

### ISSUE THREAD

**Issue by TomHall2020** [RafaelGB/obsidian-db-folder#413]
### What happened?

When creating a DB with inline fields, if the field is encludes in square brackets eg. `[key:: value]` then editing the field results in a new field being added to the note instead of changing the value in the existing field. "Naked" fields, or those in parentheses work as expected and the existing field is edited.

**Screenshots**

Set up before edit:
<img width="1081" alt="Screenshot 2022-09-21 at 11 55 22" src="https://user-images.githubusercontent.com/72264908/191487632-72affb7e-60bb-4227-9aab-dfb34be38c4d.png">

After editing fields inside table:
<img width="1082" alt="Screenshot 2022-09-21 at 11 55 45" src="https://user-images.githubusercontent.com/72264908/191487649-f29b7631-2648-47bf-a0fe-cd67bbf5bfc9.png">

### What platform were you using?

Desktop

### Version of the plugin

v2.6.4

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hi @TomHall2020 , Currently the edit engine supports inline for the next cases:
```md
key:: value
**key**:: value
in the middle of a sentence (key:: Value)
```
Is Dataview supporting [key:: value] ?

**Comment by TomHall2020** [comment]
Yes, the [dataview documentation](https://blacksmithgu.github.io/obsidian-dataview/data-annotation/#pages) shows both `(key:: value)` and `[key:: value]` as options for including fields directly inline, where the parenthesis syntax hides the key in read mode but the square brackets displays it. Both the bracketed options give a sligthly nicer display in read mode as well

<img width="599" alt="Screenshot 2022-09-21 at 12 12 51" src="https://user-images.githubusercontent.com/72264908/191489809-4849e4f6-9e88-4e1b-beb7-29bf1ea2c5f2.png">

**Comment by RafaelGB** [comment]
This is the current regex
```ts
export function inlineRegexInFunctionOf(columnId: string) {
    const wrappererKey = `_\\*~\``;
    const conditionalInitWithField = `[${wrappererKey}]{0,2}${columnId}[${wrappererKey}]{0,2}[:]{2}`;
    const thenRegex = `(^${conditionalInitWithField})(.*$)`;
    const elseRegex = `(.*)([(])(${conditionalInitWithField})(.*)([)])(.*$)`;
    const finalExpression = `(?:(?=(^${conditionalInitWithField}))(${thenRegex})|(${elseRegex}))`;
    LOGGER.debug(`<=> inlineRegexInFunctionOf: ${finalExpression}`);
    return new RegExp(`${finalExpression}`, 'gm');
}
```

We have to adapt the `elseRegex` with those marks then. Thanks for the report =)
