### ISSUE TITLE
[FR]: Append inline fields after last field

### ISSUE THREAD

**Issue by alancunha26** [RafaelGB/obsidian-db-folder#419]
### Contact Details

alanalegredacunha@gmail.com

### Present your request

In my vault I have my inline fields inside a callout on top of the file, and would be great if new fields were appended after the last field in the note.

![image](https://user-images.githubusercontent.com/46824739/192048437-a5d908df-21c4-42d3-aed2-c8b08536a664.png)

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
Currently we have the option of add new fields on top and bottom of your note.
Another choose of "last field" could be nice, but I think its a little bit complex.


I will add to the roadmap =)

**Comment by RafaelGB** [comment]
With https://github.com/RafaelGB/obsidian-db-folder/issues/556 done We can abord this one

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/207696923-3b925edf-109e-4cb5-b401-85582f2317b1.mov

This could be easily one of the most complicated regex of my career

The new property will respect the marks of your key and the position too

```typescript
INLINE_LAST_FIELD: /([\s\S]*)(^[^_*~`]*)([_*~`]{0,2})([A-Za-z0-9]+)([_*~`]{0,2})([:]{2})(.+\n{0,1})$([\s\S]*)/gm
```

```typescript
case INLINE_POSITION.LAST_FIELD:
                if (INLINE_REGEX.INLINE_LAST_FIELD.test(this.content)) {
                    inlineAddRegex = INLINE_REGEX.INLINE_LAST_FIELD;
                    regex_target = `$1$2$3$4$5$6$7$2$3${columnId}$5:: ${newValue}\n$8`;
                    break;
                }
```

**Comment by RafaelGB** [comment]
Commit d855b4c3
