### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Asetnozama** [RafaelGB/obsidian-db-folder#42]
Hello, I can't find this plugin in the Obsidian Community Plugins.
Could somebody please be so kind to explain me how to install this awesome looking plugin??

Thanks a lot!

**Comment by RafaelGB** [comment]
Hello @Asetnozama , the official release is on review yet. You can install this plugin with [BRAT](https://github.com/TfTHacker/obsidian42-brat) I will add into the documentation a mini guide to install as a beta plugin.

Thank you for the support!

**Comment by Asetnozama** [comment]
Thans you very much !!

**Comment by RafaelGB** [comment]
Anytime! added to https://rafaelgb.github.io/obsidian-db-folder/faq/

This question will be closed

**Comment by yurijserrano** [comment]
@RafaelGB  Just passing to say that your plugin is on the Obsidian store.

Great Work.


![image](https://user-images.githubusercontent.com/14169134/171773361-06e0b68e-38ac-4ee1-8dea-92fe86d0c3ee.png)

**Comment by Fedew10** [comment]
Hi congrats for the plugin.
I don't see the icon Open Database Settings

**Comment by RafaelGB** [comment]
Hi @Fedew10, thanks!

About the settings there is a problem with the public version https://github.com/RafaelGB/obsidian-db-folder/issues/193

Its updated to the new Obsidian API v15 (changes the core). Its working currently just with insider versions, sorry for the inconvenience. As soon I finished https://github.com/RafaelGB/obsidian-db-folder/issues/189 I will try to fixed. If Obsidian up the version to v15 sooner will work again too

**Comment by Fedew10** [comment]
I will be attentive to the new update
Thank you!
