### ISSUE TITLE
Bring source folder to database settings

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#420]
### Contact Details

imeed166@gmail.com

### Present your request

When creating a database from a folder, you can choose the **source folder** with the `database creator helper`. 
But when the database is created, when opening settings, you can't see the **source folder** anymore, you can only see the type of source (current folder).

Having this destination folder in the settings is good for two things : 
1- When the user forgets which folder the database is using, he can be reminded with this setting
2- When the user wants to change the folder source of the database, he can change it directly from this setting

https://user-images.githubusercontent.com/38974541/192090800-1a86ccde-dfdd-481b-8122-dde62036a528.mov

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
the reason is with the helper you need to select first where you want to create the database. Once is created you already know where the folder is located

**Comment by imeed166** [comment]
Okay, if you think that the user doesn't need it, you know better.

**Comment by RafaelGB** [comment]
If the user want to change the source of the folder, you just need to move the ddbb note to another one

**Comment by imeed166** [comment]
I see, I'll add this to the documentation, then.
