### ISSUE TITLE
[FR]: setting to toggle shading on and off

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#421]
### Contact Details

imeed166@gmail.com

### Present your request

I think some users (like myself) might like the old behavior where there was no shading. So a setting to disable the shading of the rows brought by the latest update would be nice.

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
Could be a possibility, sure

**Comment by RafaelGB** [comment]
Commit 6e10773a

Will be added with the next version
