### ISSUE TITLE
[Bug]: Existing YAML Overriden on Modify

### ISSUE THREAD

**Issue by lumargh** [RafaelGB/obsidian-db-folder#432]
### Contact Details

sebshq@gmail.com

### What happened?

1. Create a daily note with YAML metadata
<img width="702" alt="image" src="https://user-images.githubusercontent.com/106437649/192159118-b74fdedd-5701-49c2-86e1-e8dfb5cc5156.png">

2. In the database note, modify content for that same note (e.g. Summary:: adsfasd)

Current behaviour: YAML metadata is reset/overridden (looks like it's coming from my daily note template?)
<img width="442" alt="image" src="https://user-images.githubusercontent.com/106437649/192159138-38e729fc-cc53-42ee-bb09-6cc475e1fb39.png">

Expected behaviour: Existing YAML metadata stays the same; new content is modified or added as expected

Settings: 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/106437649/192159078-c6a40208-824a-469e-830f-e3a1e15fbc2e.png">

### What platform were you using?

Desktop

### Version of the plugin

2.6.6

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/194

I think this issue will "fix" your use case

currently the plugin check if the value is a list and represents it like that on the yaml

**Comment by RafaelGB** [comment]
check if 2.6.7 version fix your problem, if not maybe we have to configure different options to save lists

**Comment by lumargh** [comment]
Hi Rafael -- unfortunately the behaviour is even more bizarre now! 

Starting metadata: 
<img width="731" alt="image" src="https://user-images.githubusercontent.com/106437649/192400147-f90680e7-bee9-4454-8584-584b4340a286.png">

Modify a value in the db and hit enter, metadata in my note changes: 
<img width="409" alt="image" src="https://user-images.githubusercontent.com/106437649/192400217-cea1f499-6bca-4511-a030-640ff7a5e41f.png">

I'm not sure why the season, month, week, day, weekday, or date values disappear.

**Comment by RafaelGB** [comment]
Its the native way to persist the information. I will work on a custom one then

**Comment by RafaelGB** [comment]
one way or another the lists in yaml should be persisted with - , To persist them as an unique line you can use the inline field format

**Comment by RafaelGB** [comment]
This will be covered with https://github.com/RafaelGB/obsidian-db-folder/issues/441

And with the next version the dates/link will be respected as before
