### ISSUE TITLE
[Bug]: DB Folder Crashing and causing Vault to reload upon Search

### ISSUE THREAD

**Issue by evility1** [RafaelGB/obsidian-db-folder#433]
### Contact Details

stevenmfick@gmail.com

### What happened?

When I am searching for something within my DB Folder, it causes my Obsidian Vault to Crash and reload. 

I type in the name of the Author, or whatever I am searching for, press enter, and it immediately reloads my vault. 
Here is a Video that I have taken, it is unlisted, so not available to the general public: 

https://youtu.be/xCwQRHNa5C4

I can make this reoccur at will, so if you need any logs, please let me know. 

After the Vault reloads, this is what presents itself in the console

![image](https://user-images.githubusercontent.com/111452340/192301056-6ff68e09-0db5-49f7-b045-aab163428d85.png)

### What platform were you using?

Desktop

### Version of the plugin

2.6.6

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
it's very strange. Could you share the list of enabled plugins? if there were any incompatibility.

but to the point of crashing the application... Could you try it just with dataview and dbfolder enabled?

**Comment by evility1** [comment]
Here is a List of my Plugins: 

![image](https://user-images.githubusercontent.com/111452340/192313214-5aad2799-86ab-48e8-b612-0459cf3238ee.png)

I have disabled all community plugins and did the same test, and it is causing the Vault to reload. It is reloading to the DB because Homepage is disabled, but it still feels like a bug. 

What do you think?

**Comment by RafaelGB** [comment]
I will add this as external bug. Looks like an incompatibility for a reason we need to investigate

**Comment by evility1** [comment]
Thank you Sir.

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/435 could be the same source of the problem. The context of the activeWindow

**Comment by evility1** [comment]
[433SampleVault.zip](https://github.com/RafaelGB/obsidian-db-folder/files/9688041/433SampleVault.zip)


Here is a sample vault, hopefully. I did this correctly for you all.

**Comment by RafaelGB** [comment]
fixed with https://github.com/RafaelGB/obsidian-db-folder/issues/435
