### ISSUE TITLE
[Bug]: Problem with stack tabs mode of Obsidian 0.16.3

### ISSUE THREAD

**Issue by marcinfork** [RafaelGB/obsidian-db-folder#435]
### What happened?

When I create new database and enter it black screen  appear, only restart the obsidian helps. Turn off all of  the plugins and Sliding Panes plugin cuz the error.  

### What platform were you using?

Desktop

### Version of the plugin

2.6.7

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Could you share some logs and a list of the enabled plugins? The creation of a ddbb is just a new file with another view. If another plugin have some logic during the creation of a new file, maybe provokes an incompatibility

**Comment by tlinke** [comment]
I'm experiencing the same problem with insider build 0.16.3 and no other plugins installed besides dataview. In the default tab view mode it works as normal but in "Stack tabs" mode Obsidian crashes instantly when opening a database folder. The developer console gets disconnected by the crash, so I can't provide any logs.

**Comment by RafaelGB** [comment]
The stack tabs was the clue. I could reproduce it, thanks for the report =)

**Comment by toxfu** [comment]
I have the same error

**Comment by RafaelGB** [comment]
I don't know how to fix this issue. Its tough to debug the problem without any clue or documentation about stack tabs yet

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/469 related

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/discussions/472 discussion about issues with the same problem

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/194606356-30ebf3be-04a9-4125-a16a-cf0b27458cdd.mov

I found a good documentation and the issue was fixed even with UI improvements
