### ISSUE TITLE
[FR]:Create an option in Settings to config metadata dates

### ISSUE THREAD

**Issue by kazdonkai** [RafaelGB/obsidian-db-folder#436]
### Present your request

Hi,
In the current database, the Datetime is always displayed for Created and Modified, but it seems long and obtrusive. Therefore, could you please consider creating an item in the Settings to display only the Date?

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
<img width="795" alt="Screenshot 2022-09-27 at 12 10 45" src="https://user-images.githubusercontent.com/11924043/192498836-9e2fff4e-8c5e-402d-993b-2b3efbf7e521.png">

You have date format options on database settings to modify how to read/persist your dates

**Comment by kazdonkai** [comment]
Thanks for the reply.
I know that setting, I tried to create a database with Datetime empty, but it was set to the default, Datetime.
How do I set it?
Or is it a bug?
It is also confusing that there are two settings, Date and Datetime.

**Comment by RafaelGB** [comment]
We have 2 types of column: Date and Datetime. The metadata info takes datetime config

**Comment by kazdonkai** [comment]
How do I prevent Datetime from being displayed in the Created and Modified fields of the database?

**Comment by RafaelGB** [comment]
We maybe need another date format just for metadatas. Could be the tittle for this FR

**Comment by RafaelGB** [comment]
Commit b368eedc

Ready for the next version =)
