### ISSUE TITLE
[FR]: Chech Box display in the Task column.

### ISSUE THREAD

**Issue by cesarpereira904** [RafaelGB/obsidian-db-folder#437]
### Contact Details

cesarpereira904@gmail.com

### Present your request

This is not urgent at all it's just a tweak in the css, I tried to change it but was not able to do it.

When enabling the "Tasks" in the database:
![image](https://user-images.githubusercontent.com/70922426/192474940-f4f4fae2-121d-4e96-bce8-6ad2fbaf3ac9.png)

Space between the checkbox and the text gets is cut off:

Original Checkbox in the Note:
![image](https://user-images.githubusercontent.com/70922426/192475344-86f577f7-cacd-4846-83cd-dcfbfa25c4de.png)
`
Checkbox in the Database Task Column:
![image](https://user-images.githubusercontent.com/70922426/192475527-928d0b5c-0db3-4552-8f93-0ff67fb7ea1d.png)

Like I said not urgent, just a tweak in the css I think, most likely can be fixed with a css snippet but I just couldn't find how to do it.

thanks!

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
we can find css snippets of dataview taskList . We are rendering a taskList panel per cell

**Comment by RafaelGB** [comment]
I cannot support this issue as it is something external. With snippet adjustments it could be achieved for the dataview tasklist
