### ISSUE TITLE
[FR]: Field type to support YAML multiple values (not tags)

### ISSUE THREAD

**Issue by www-wagner** [RafaelGB/obsidian-db-folder#441]
### Contact Details

www.wagner.br@gmail.com

### Present your request

Current DB-Folder `Tags` field type allow multiple values for a unique field, but those values are saved in DB settings to be used in the entire DB scope. It's perfect to be used to Obsidian internal `tags` field.

On the other hand, the Obsidian internal field `aliases` doesn't match any DB-Folder field type. `aliases` field is meaningful only to a specific row of the DB. For example, if I have "Microsoft Office" in a row, the alias could be "MS-Office" and "Office", but those values doesn't make sense to the other rows, so they couldn't be "suggested".

So I ask for a new field type that allows list without suggestions.

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
Hi @www-wagner ,
So for example to use aliases like this example yaml?
```yaml
aliases: Office, MS-Office
myValue: a
myValue:b
```
Dataview transforms aliases into an array an our current yaml writter show them as a dot list
```yaml
aliases: 
  - Office
  - MS-Office
myValue: a
myValue: b
```

Obsidian does not recognize the second format?

**Comment by www-wagner** [comment]
Let's show a better example.

If I have the following YAML field:
![image](https://user-images.githubusercontent.com/18124316/192858084-a496795f-b80d-4070-9d73-4e2f2ecf1e33.png) or ![image](https://user-images.githubusercontent.com/18124316/192858839-3ba67d3f-7e31-4681-9915-4ddccb787432.png)

In the UI, it shows as `Text` type field (truncated, because I can't resize to fit the contents):
![image](https://user-images.githubusercontent.com/18124316/192858390-8f8c3916-12b1-4238-abca-bd1a21355fa9.png)

If I delete the second item using UI, the things are messed up:
![image](https://user-images.githubusercontent.com/18124316/192858624-4ded93d4-c5ce-4c49-85ba-979f7e3a8e9f.png)

In this case, I have to update the row directly in the file, to keep the things right!

My suggestion is having another field type, like `List` or `Array`, to keep itens isolated from each other. `Tags` type couldn't be used because the values are related only to current row.

**Comment by RafaelGB** [comment]
I guess could be easy to check if a text cell its an array or add a new toggle config per text column that interprets that it is an array

**Comment by csss1234** [comment]
> Let's show a better example.
> 
> If I have the following YAML field: ![image](https://user-images.githubusercontent.com/18124316/192858084-a496795f-b80d-4070-9d73-4e2f2ecf1e33.png) or ![image](https://user-images.githubusercontent.com/18124316/192858839-3ba67d3f-7e31-4681-9915-4ddccb787432.png)
> 
> In the UI, it shows as `Text` type field (truncated, because I can't resize to fit the contents): ![image](https://user-images.githubusercontent.com/18124316/192858390-8f8c3916-12b1-4238-abca-bd1a21355fa9.png)
> 
> If I delete the second item using UI, the things are messed up: ![image](https://user-images.githubusercontent.com/18124316/192858624-4ded93d4-c5ce-4c49-85ba-979f7e3a8e9f.png)
> 
> In this case, I have to update the row directly in the file, to keep the things right!
> 
> My suggestion is having another field type, like `List` or `Array`, to keep itens isolated from each other. `Tags` type couldn't be used because the values are related only to current row.

 would a temporary workaround be to use inline fields instead of yaml? Im on my phone right now, can’t easily test it out.  
 
  I run into this same problem because I use “quick add” plug-in to add to yaml bulleted list throughout the day. But if I make an edit in DB folder GUI, the reformatting essentially breaks my quick add shortcut.

**Comment by RafaelGB** [comment]
with the last update of 2.7.2 we are refactoring the edit engine to support objects.

Could be a partial solution controlling arrays too

try to write [a,b,c] inside a text cell

**Comment by RafaelGB** [comment]
With the next version you can use the text column as a list with `[]` wrapper

https://user-images.githubusercontent.com/11924043/207966083-3a696021-20fd-41f3-b751-efe5fd004832.mov

**Comment by csss1234** [comment]
Well I thought using inline fields was a decent workaround, but with DB Folder 3.2.3, unwanted bullets are showing up. See picture. Would love to be able to use "quick add" to log multiple data into one field throughout the day. Any suggestions for accomplishing that? I was using a YAML method, but there were some problems with that.

![Screen Shot 2023-01-11 at 11 45 38 AM](https://user-images.githubusercontent.com/45954264/211866528-24a5bdc6-c8a5-4403-a884-8a604db66abe.png)
