### ISSUE TITLE
[FR]: allow renaming labels for `Tags` and `Select` field types

### ISSUE THREAD

**Issue by www-wagner** [RafaelGB/obsidian-db-folder#443]
### Contact Details

www.wagner.br@gmail.com

### Present your request

Current the UI allows us to add new labels and change their colors but it isn't possible to change the text of an existing label.

It'd be nice if we could change labels text and those changes could be propagated to all DB rows.

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
This was in my mind for a while. My intention is to include the edit option on column config

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/196049391-4a1da23e-4adf-4dbd-8bb4-37b3c728e051.mov

**Comment by DannyHatcher-Git** [comment]
When will this be released?

**Comment by RafaelGB** [comment]
I have to first polish the version before uploading it, so I hope this week could be ready

**Comment by ronrdev** [comment]
Is it possible to use this to reorder the table? Can it be an array or only text field? If I used numbers and wanted to change a number, could this update all the files with the new values and reorder the table?
Example
Chapter:: 1
Chapter:: 2
Chapter:: 3
