### ISSUE TITLE
[FR]: Add interactive sort button in column header

### ISSUE THREAD

**Issue by zuluwi** [RafaelGB/obsidian-db-folder#447]
### Present your request

https://user-images.githubusercontent.com/111116092/193177109-4d302220-9bd7-43ac-9d57-6926df4d4ab1.mp4

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
Hi @zuluwi,

I guess you request an interactive sort button, right?

**Comment by RafaelGB** [comment]
I have to discard this in favor of the existing one (mobile support)
