### ISSUE TITLE
[FR] new option to enable/disable formula scripts load

### ISSUE THREAD

**Issue by beetrootpaul** [RafaelGB/obsidian-db-folder#457]
### Contact Details

paul@beetrootpaul.com

### What happened?

I was eager to try out database folder plugin in Obsidian, since I use Dataview a lot and have a lot of custom JS code used there to make data in tables interpreted and formatted as I want them to. But when I enabled the plugin and created my first database folder, I got spammed with "Error loading formulas. See check your <file> js file code" notifications. Ona first glimpse it seems that those files in notifications seem to be JS files from `node_modules` folder of one of my npm projects which, for some reasons, I want to keep inside Obsidian vault.

To be sure, I later disabled all plugins but database folder and dataview, then created an empty folder without any special characters in its name, and created a database inside. Same issue occured.

Here is the screenshot of the notifications I am talking about (under Minimal theme):
<img width="495" alt="screenshot 2022-10-01 at 18 03 01" src="https://user-images.githubusercontent.com/92947323/193418378-5efc0d0e-49ff-47ad-9312-4d627ef966fc.png">

### What platform were you using?

Desktop

### Version of the plugin

v2.6.7

### Relevant log output

```shell
[codo] >codo_init
[codo] platform: Emscripten
[codo] codo_system_init
[codo] codo_reset_timer
[codo] codo_gui_init
[codo] codo_keys_init
[codo] codo_text_init
[codo] codo_video_init
[codo] codo_mouse_init
[codo] codo_joystick_init
[codo] <ok
[codo] codo_load_pod: data.pod ok 
[codo] codo_set_screen 128 128 8 100
exception thrown: TypeError: Cannot read properties of undefined (reading 'addEventListener'),TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at eval (eval at <anonymous> (plugin:dbfolder), <anonymous>:6501:20)
    at Array.forEach (<anonymous>)
    at _SDL_SetVideoMode (eval at <anonymous> (plugin:dbfolder), <anonymous>:6500:134)
    at wr (eval at <anonymous> (plugin:dbfolder), <anonymous>:7874:62513)
    at Xq (eval at <anonymous> (plugin:dbfolder), <anonymous>:7874:58380)
    at lb (eval at <anonymous> (plugin:dbfolder), <anonymous>:7870:16495)
    at on (eval at <anonymous> (plugin:dbfolder), <anonymous>:7872:114059)
    at Ib (eval at <anonymous> (plugin:dbfolder), <anonymous>:7870:57321)
    at Object.callMain (eval at <anonymous> (plugin:dbfolder), <anonymous>:8079:28)
    at doRun (eval at <anonymous> (plugin:dbfolder), <anonymous>:8115:58)
```
```


### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
sorry about that, looks like you have some js scripts into your vault that they are incompatible with the plugin, just change your formulas folder inside the database config. Disable by default those formulas could be an option into future versions

**Comment by beetrootpaul** [comment]
> looks like you have some js scripts into your vault that they are incompatible with the plugin

correct, I have a lot of JS files here and there and they have nothing to do with the plugin

> just change your formulas folder inside the database config

how do I access database config? UPDATE: OK, now when I changed formula JS folder in the plugin settings **and** deleted the previous database **and** created a new one, there are no error notifications and db is rendered and I can see a menu to open db settings 👍 Was unable to do that before (or maybe would be able if would patiently wait? There was nothing rendered when notifications were spamming)

So, OK, thx for help 🙂 My current setup is as on a screenshot below and I assume it solves my issues 🙂 Not sure if to close this "bug", since on one hand it seems to be just a matter of an extra configuration to do but on the other I see it strange to consider all JS files in the entire vault as related to the plugin by default 🤔 WDYT?

<img width="998" alt="screenshot 2022-10-01 at 21 20 21" src="https://user-images.githubusercontent.com/92947323/193425068-48718300-2160-4b1e-975d-0fd5602cae2b.png">

**Comment by RafaelGB** [comment]
I am agree, generate by default the folder of the formulas as root could be problematic. I will consider to create a toggle flag to enable/disable scripts
