### ISSUE TITLE
[External]: Blue Topaz theme affects the horizontal scroll 

### ISSUE THREAD

**Issue by Issam-seghir** [RafaelGB/obsidian-db-folder#461]
### What happened?

I can't scroll horizontally in DataBase Folder WITH Too Much column 
in **Blue topaz theme** 
![image](https://user-images.githubusercontent.com/74573675/193450215-3b329445-b2d5-4dee-bca9-ee0e1a57db57.png)

### What platform were you using?

Desktop

### Version of the plugin

2.6.7

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hi @Issam-seghir , what theme are you using? default & minimal one has the scroll without problems
https://user-images.githubusercontent.com/11924043/193450564-2fb19594-f571-4c3b-95e0-125985587c90.mov

**Comment by Issam-seghir** [comment]
it's working with all themes I tried except this one :  **Blue topaz theme**

**Comment by RafaelGB** [comment]
I am afraid I can't give you support for custom themes. If you open an issue in their repo, I will be happy to collaborate with them if the y need some custom css variable
