### ISSUE TITLE
[FR]: auto sort when clicking on header

### ISSUE THREAD

**Issue by zeltak** [RafaelGB/obsidian-db-folder#463]
### Present your request

Hi

currently when clicking on a column header you get an option to sort by dialog...

![CleanShot 2022-10-03 at 12 59 30](https://user-images.githubusercontent.com/498410/193551009-c558e4ea-e35f-4506-a576-751ada6d6dbc.png)

Can one request to define a default (like sort by name) so we can quick sort without having to choose each time the sort method?

so a quick press on the header will toggle between sort A/D for name etc

thx 

Z

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/447. its already on the roadmap:)
