### ISSUE TITLE
[FR]: Align options for Tags, Markdown File and Select column types

### ISSUE THREAD

**Issue by kmaustral** [RafaelGB/obsidian-db-folder#464]
### Contact Details

mzantsi@gmail.com

### Present your request

I want to see the ability to align the file name column so that it is left justified, rather than centred as it is at the moment. 

I'm surprised this hasn't been requested before. 

Thanks for the amazing plugin. 

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
Hi @kmaustral , was proposed here last week https://github.com/RafaelGB/obsidian-db-folder/discussions/458. We can use this issue to add it to the roadmap

**Comment by RafaelGB** [comment]
Commit 0d5aa34f

Markdown will be keep without this options (as metadata column)
