### ISSUE TITLE
[FR]:  Adding multiple dates in the date field

### ISSUE THREAD

**Issue by rohanbatraio** [RafaelGB/obsidian-db-folder#468]
### Present your request

I assume this feature is for very selected use cases like mine, I want the db to record dates in visits, like for say i visited the note on xx yy zz dates, then i have no option to add multiple entries in date field, i believe dates should have multiple entries supported. 

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
You maybe needs a nested metadata https://github.com/RafaelGB/obsidian-db-folder/issues/442

I can not support a custom type for multiple dates yet
