### ISSUE TITLE
Trouble with changes saving and persisting. 

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#47]
**Describe the bug**
I'm having trouble getting the db view to save info that I enter or add. If I add a new column/field and change the name then click away from the file and come back it doesn't save. Or if I enter a new value into a field it doesn't write. Basically any change I make wont save until after some long amount of time (or perhaps some other action that I haven't been able to identify). Even if I leave the view open for 5-10 mins it wont save. 

**Expected behavior**
Changes save and persist within 5-10 seconds at max. 

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.3.1

**Comment by RafaelGB** [comment]
try now with 1.1.2 to confirm if its fixed

**Comment by arminta7** [comment]
Yes, it is working now! 🙏
