### ISSUE TITLE
[FR]: nowrap image type

### ISSUE THREAD

**Issue by SecretgardenA** [RafaelGB/obsidian-db-folder#476]
### Contact Details

alwaysme_why@163.com

### Present your request

Hello, Is there a way to import multi image in a nowrap style like notion:
![IMG_0588](https://user-images.githubusercontent.com/78669513/194745803-11777f5a-1373-4968-a718-a4d350782100.jpeg)
Now, it looks like this and kills the beauty of the whole table:
<img width="795" alt="Screen Shot 2022-10-09 at 16 21 08" src="https://user-images.githubusercontent.com/78669513/194745949-28b26082-5d3f-48c7-b08f-ab6e3a3e987f.png">

Thanks for this wonderful plugin! It's very nice and helpful!

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
I will add this to the roadmap, its an useful option =) thanks for your idea

**Comment by RafaelGB** [comment]
![Image](https://user-images.githubusercontent.com/11924043/208304626-92c0ca91-8604-4260-89a5-9ca66fd75c19.png)

**Comment by RafaelGB** [comment]
Commit da0e9ac8
