### ISSUE TITLE
[FR] Create new file/row from Template. 

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#48]
Would be great to be able to specify a template that is applied to all newly created files.

**Comment by RafaelGB** [comment]
This feature is in my internal roadmap, thanks for your suggestion! My idea is to integrate Templater features with a selector near the "add row" button

This will be added to the Long term tasks

**Comment by RafaelGB** [comment]
Tested. Works with Templater if you activate the option "Trigger templater on new file creation"
