### ISSUE TITLE
[FR]: Insert Property type when a new column is added

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#483]
### Contact Details

danny@dannyhatcher.com

### Present your request

When adding a column into the database view it defaults to text.

I would like it to either save settings from other views, or let me choose the property type when I insert the column.

eg: deadline - date

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
Sure, could be a good addition on new column form

**Comment by RafaelGB** [comment]
With the next version this menu will be refactored.

Now you can choose the type on add column modal, even modify the existing ones from a centralised menu

**Comment by javiavid** [comment]
It's great to be able to configure everything from here, but all the columns appear as if they were text and they are not like that.

Another thing is the design of the window, there is a lot of space in the middle. It is very good that it adapts to the size, but perhaps it could be a little narrower.

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/7627504/208307698-a8032797-e84f-4e44-97c2-3fb6757eb7e4.png">

**Comment by RafaelGB** [comment]
I noticed it testing the beta version and was already fixed :) 

About the size maybe its too much right now but the idea its to add new functions in the future
