### ISSUE TITLE
[Bug]: Search viewing box

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#486]
### Contact Details

danny@dannyhatcher.com

### What happened?

In dark mode on PC, I can't read the words "search" in the search box. There are also white outlines of the buttons which is offputting.

In addition, when I put my mouse in the box the cursor disappears. 

![image](https://user-images.githubusercontent.com/78496825/195045309-1d217db5-f675-454d-b8eb-278c503afca3.png)

### What platform were you using?

Desktop

### Version of the plugin

2.7.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
thanks for the report =)

**Comment by RafaelGB** [comment]
done in another issue

https://github.com/RafaelGB/obsidian-db-folder/issues/534
