### ISSUE TITLE
[FR]: Refresh tasks column with filters

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#487]
### Contact Details

danny@dannyhatcher.com

### What happened?

When I switch between group filters in a database the tasks column (dataview tasks query) becomes out of sync with the pages and some don't show any results at all even though there are tasks in the page.

I have tried refreshing the view (on and off filter) to bring up the dataview results but nothing seems to happen.

Loving the feature but this is irritating. Hope that makes sense.

### What platform were you using?

Desktop

### Version of the plugin

2.7.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
The tasklist component currently its rendered just once. Being a dataview component I can not control when is refreshed without render it again and it was a performance problem.

I will check if it’s possible to refresh it when you change the filter :)

**Comment by DannyHatcher-Git** [comment]
That is what I thought.

Thanks for the replay, I will keep my eyes open 😁

**Comment by RafaelGB** [comment]
With another change this feature was resolved

**Comment by RafaelGB** [comment]
Commit 8d73c2fb
