### ISSUE TITLE
Vertical Scroll on Insider Mobile

### ISSUE THREAD

**Issue by iangeckeler** [RafaelGB/obsidian-db-folder#488]
I am on iOS and using the latest insider build. I am unable to swipe with my finger to scroll down and see cells that are not above the page fold.

**Comment by iangeckeler** [comment]
Looks like if I rotate my device landscape I can scroll vertically but when it is not in landscape is when the scroll is disabled. Is this desired behavior?

**Comment by RafaelGB** [comment]
I will test the problem with this issue https://github.com/RafaelGB/obsidian-db-folder/issues/435 done because the scroll logic was changed for all the plugin.

Thanks for the report!

**Comment by iangeckeler** [comment]
awesome, thanks! love this plugin, super useful.

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/200116294-96222aa2-76b8-4787-af1a-37bd648276a1.mp4

looks like its fixed with the scroll update


Could you confirm it to close this issue?
