### ISSUE TITLE
[FR] Formula column type

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#49]
Just like in dv queries, be able to create a column from a formula.

**Comment by RafaelGB** [comment]
Could you give me an example? I'm not familiar with dv queries to create columns

**Comment by arminta7** [comment]
Yes, so say I have two inline fields:

`Total:: 5`
`Completed:: 3`

I could create a column that uses the formula `(completed/total)*100 + "%"` to show the result even though I don't have that field/column in the file.

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/227

Once this issue will be finished. The concept of a column formula will be closer

**Comment by RafaelGB** [comment]
ok, we're talking about a game changer here. This is a demo with a first version

https://user-images.githubusercontent.com/11924043/189980372-4beef336-e2f9-4878-b34c-7559a7855099.mov

**Comment by arminta7** [comment]
So exciting!!! 🤩
