### ISSUE TITLE
[FR]: View update on column addition

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#491]
### Contact Details

danny@dannyhatcher.com

### Present your request

Currently, when I add a column back into the database view it moves me back to the top of the page.

I would like it to keep me in the same place I was before adding the column in.

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
this supposes a technical challenge as the architecture is thought.  When adding a column and closing the modal window, the table is reloaded from 0 to be able to launch certain initializations.

to do it, the logic would have to be transferred to event management in Zustand (framework used by the plugin) to be able to control the position without relaunching everything

I dont know if its worth the effort (1 week of work)

**Comment by DannyHatcher-Git** [comment]
Ok. Maybe something for future consideration.
If you don't ask you never get 😁

**Comment by RafaelGB** [comment]
I will close this issue. may be addressed with future architecture changes
