### ISSUE TITLE
[FR]: Improve UX of colour picker

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#497]
### Contact Details

danny@dannyhatcher.com

### What happened?

When in the colour picker if I move the mouse out of the window it closes the box.

Can we add a confirm button?

Maybe a way to save previous colours would be nice as well.

### What platform were you using?

Desktop

### Version of the plugin

2.7.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
the save triggers with onblur event. Could be improved with some confirm button, but I can not save previous colors.

will be added as visual

**Comment by RafaelGB** [comment]
With 1.0 Obsidian API offers its own color picker selector. I will try it for sure

**Comment by RafaelGB** [comment]
Migrated react-color component to native Obsidian color picker, resolving this issue.


https://user-images.githubusercontent.com/11924043/196004406-2774865a-d89f-49a4-bf45-d1aba8357329.mov

The component offers keyboard shortcuts:

- esc to undo change / close selector
- enter to confirm the color
