### ISSUE TITLE
[FR]: Font size for table

### ISSUE THREAD

**Issue by ShravanSunder** [RafaelGB/obsidian-db-folder#498]
### Present your request

It would be great to have a specific font size for all DB Folder views.  I would like to see more on my screen for DB folder as compared to a normal text file.  A general font size setting would be great.

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
Hi @ShravanSunder ,

We have a compact mode on ddbb settings to reduce the space per row.

Also the plugin is using the font size configuration of Obsidian.

Tell me if that solve your use case

**Comment by ShravanSunder** [comment]
@RafaelGB What i mean is that it would be good for DB Folders (being a spreadsheet) to have a different font size configuration compared to other obsidian documents.  It makes it easier to see in the spreadsheet use case.

**Comment by RafaelGB** [comment]
I will investigate about to create a percentage setting of the Obsidian font size with a scroll just like pagination

**Comment by RafaelGB** [comment]
Font size selector included =)

https://user-images.githubusercontent.com/11924043/206704088-5ba427ea-4850-4380-84cd-1c040d0eba7e.mov

**Comment by padasch** [comment]
I really like this feature! I just tested the 3.1.0-beta.1 release (installed via BRAT) and the font adjustment only works for non-text cells. I am working on Linux and have not tested this on other platforms yet.

Also: It would be nice to have some text-size indicator and/or "reset to standard size" button in the settings to see what font size is currently selected.
