### ISSUE TITLE
[FR]: Calendar date picker week settings

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#501]
### Contact Details

danny@dannyhatcher.com

### Present your request

When bringing up the date picker I would like to have Monday at the start instead of Sunday.

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
I swear the framework used by the plugin offers a configuration about it, I will check to create a dropdown configuration 👌

**Comment by RafaelGB** [comment]
Commit bc13f56c
