### ISSUE TITLE
[Bug]: Blank line inserted at top of file every time inline value edited in db table

### ISSUE THREAD

**Issue by miscelly** [RafaelGB/obsidian-db-folder#504]
### What happened?

I use inline variables instead of YAML for my db values. Whenever I make a change to a value using the plugin there is a blank line inserted at the top of the changed file. This is consistently reproducible.

As an example, if I have a file that contains only this text:
```
variable1:: value1
```

and I edit value1 in a db table, a blank line will be inserted at the top of the file. If I change the value again in the table, another blank line is inserted at the top.  I tried changing the "Select position for new inline fields" to "bottom" even though I wasn't adding any new fields, but that didn't fix the issue. It doesn't matter if there is other text above or below the inline variable.

I'm using Obsidian version 1.0.0.  The OS is Windows 10. I did searches here for "line," "blank," etc. but didn't see this mentioned.

### What platform were you using?

Desktop

### Version of the plugin

2.7.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

Edit: Updated to be more concise.

**Comment by miscelly** [comment]
Just for some extra info, I created a new file that only had 

> variable:: value

at the top, and nothing else in the file, and was able to reproduce the issue.

**Comment by RafaelGB** [comment]
fixed =) thanks for the report was a regression of the last version
