### ISSUE TITLE
[Bug]: no rendering under unknown circumstances

### ISSUE THREAD

**Issue by scarfur** [RafaelGB/obsidian-db-folder#505]
### What happened?

nothing gets rendered where settings, colums, lines etc. should be - whole db folder note is blank;
![image](https://user-images.githubusercontent.com/51059311/196004651-67365c9d-2237-4dd1-b9ba-0674798ca610.png)

Could be that [[notes]] in text fields is breaking stuff now. I can't think of anything that would be different to other (still working after update) db notes/folders.

### What platform were you using?

Desktop

### Version of the plugin

2.7.2

### Relevant log output

```shell
plugin:dbfolder:10 Uncaught TypeError: e.label.localeCompare is not a function
    at eval (plugin:dbfolder:30:131317)
    at Array.sort (<anonymous>)
    at eval (plugin:dbfolder:30:131296)
    at Object.useMemo (plugin:dbfolder:10:68426)
    at Object.l.useMemo (plugin:dbfolder:1:6919)
    at zl (plugin:dbfolder:30:131227)
    at Ei (plugin:dbfolder:10:62183)
    at Cl (plugin:dbfolder:10:118741)
    at yu (plugin:dbfolder:10:107746)
    at vu (plugin:dbfolder:10:107674)
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
This error should be control on a previous filter.

```ts
const multiOptions = useMemo(
    () =>
      tableColumn.options
        .filter(
          (option: RowSelectOption) =>
            option.label !== undefined && option.label !== null // ***** HERE *****
        )
        .sort((a, b) => a.label.localeCompare(b.label))
        .map((option: RowSelectOption) => ({
          value: option.label,
          label: option.label,
          color: option.backgroundColor,
        })),
    [tagsCell]
  );
```

You can fix this manually the problem editing the markdown ddbb note. Just remove the column option with an empty label

I will add this issue to the roadmap to control those cases and remove empty options automatically

Thanks for the report!

**Comment by RafaelGB** [comment]
I don't know why the filter did not work in your case =(

**Comment by scarfur** [comment]
thanks for your reply :) there is no filter active in the DB if that helps anything?! the whole thing is invisible for some reason since the update. Other DBs work just fine so I think it has something to do with the entries of the datasets. I try to delete the nested [[]] notes and give you an update.

**Comment by RafaelGB** [comment]
the problem is not with the filters. One of the columns has an empty label inside its properties (I will work to prevent this in the future)

**Comment by RafaelGB** [comment]
there is no problem with the filters. One of your columns has an enpry label property. I will work to prevent this in the future

**Comment by scarfur** [comment]
Ok I misunderstood you then. So the only way to fix this is to delete every column with `input: select`? just deleting labels did not helped

**Comment by RafaelGB** [comment]
![image](https://user-images.githubusercontent.com/11924043/196005811-e2c01481-58d7-4e4b-a276-5b1a97d4fb43.jpeg)

So if you remove the options the problem persist?

**Comment by scarfur** [comment]
Yes indeed, I deleted the `options` line too (correct way to do it?)

**Comment by RafaelGB** [comment]
Removing it , the options will be regenerated. The problem is why was regenerated with an empty value hmm

**Comment by imeed166** [comment]
I just renamed the column ID and the database disappeared like in this issue, let me know if it's related

[testing database.md](https://github.com/RafaelGB/obsidian-db-folder/files/9793182/testing.database.md)

**Comment by RafaelGB** [comment]
@imeed166 I just check your file and its another problem.

You include a `-` at the end of your new id and it breaks the read of the yaml

**Comment by scarfur** [comment]
Unfortunately, I have not yet been able to find out what the reason for this could be, which is beyond my knowledge of the code. I can only say that a simple backroll to version [2.7.1](https://github.com/RafaelGB/obsidian-db-folder/releases/tag/2.7.1) directly solves the problem.

**Comment by RafaelGB** [comment]
I fixed the `-` problem and I can not reproduce the `e.label.localeCompare`

Could you try if with 2.7.3 the bug still persist?

**Comment by scarfur** [comment]
Woop woop [2.7.3](https://github.com/RafaelGB/obsidian-db-folder/releases/tag/2.7.3) fixes the problem <3
Mhmm same here regarding reproduce. Would be easier to nail it down to prevent it from happening in future builds if we could reproduce it. By the way, thank you very much for your excellent work on this occasion, your plugin is fantastic!

**Comment by RafaelGB** [comment]
I can go making beta versions for next big changes. With 2.7.2 and support for nested fields it could cause unforeseen behaviour (has been the case)

I will continue working to improve the stability of the application
