### ISSUE TITLE
[FR]: Please! wrap the markdown in a codeblock

### ISSUE THREAD

**Issue by rohanbatraio** [RafaelGB/obsidian-db-folder#509]
### Present your request

I accidentally used linter once on a db to add tags, and the database is of course messed up. I was lucky i didn't lint my whole vault, as it would be a mess with exponential time to be taken to fix everything. So please don't use raw markdown format as a config for ddbb. rather just enclose the whole into code block if possible. Or anything.

I am very well aware that i can have my linter exempt certain words, but our db file is not a constant one. Some of my database config have words that other don't have so fixing this problem from a linter perspective is a strict no go. 

### For which platform do you request this request??

Desktop

**Comment by rohanbatraio** [comment]
BEFORE

%% dbfolder:yaml
name: new database
description: new description
columns:
  column1:
    input: text
    key: column1
    accessorKey: column1
    label: Column 1
    position: 0
    skipPersist: false
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      media_width: 100
      media_height: 100
      isInline: false
  __file__:
    key: __file__
    input: markdown
    label: File
    accessorKey: __file__
    isMetadata: true
    skipPersist: false
    isDragDisabled: false
    csvCandidate: true
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: true
      task_hide_completed: true
config:
  remove_field_when_delete_column: true
  cell_size: normal
  sticky_first_column: false
  group_folder_column: 
  remove_empty_folders: false
  automatically_group_files: false
  hoist_files_with_empty_attributes: true
  show_metadata_created: false
  show_metadata_modified: false
  show_metadata_tasks: false
  show_metadata_inlinks: false
  show_metadata_outlinks: false
  source_data: tag
  source_form_result: resources/books/disha/solved-papers/physics/sectionwise/sample-papers/sample-paper-1
  source_destination_path: /
  frontmatter_quote_wrap: false
  row_templates_folder: /
  current_row_template: 
  pagination_size: 10
  enable_js_formulas: false
  formula_folder_path: /
  inline_default: false
  inline_new_position: top
  date_format: yyyy-MM-dd
  datetime_format: "yyyy-MM-dd HH:mm:ss"
filters:
  enabled: false
  conditions:
%%



AFTER 

`
%% dbfolder:yaml
name: new database
description: new description
columns:
  column1:
    input: text
    key: column1
    accessorKey: column1
    label: Column 1
    position: 0
    skipPersist: false
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      media_width: 100
      media_height: 100
      isInline: false
  __file__:
    key: __file__
    input: markdown
    label: File
    accessorKey: __file__
    isMetadata: true
    skipPersist: false
    isDragDisabled: false
    csvCandidate: true
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: true
      task_hide_completed: true
config:
  remove_field_when_delete_column: true
  cell_size: normal
  sticky_first_column: false
  group_folder_column: 
  remove_empty_folders: false
  automatically_group_files: false
  hoist_files_with_empty_attributes: true
  show_metadata_created: false
  show_metadata_modified: false
  show_metadata_tasks: false
  show_metadata_inlinks: false
  show_metadata_outlinks: false
  source_data: tag
  source_form_result: resources/books/disha/solved-papers/physics/sectionwise/sample-papers/sample-paper-1
  source_destination_path: /
  frontmatter_quote_wrap: false
  row_templates_folder: /
  current_row_template: 
  pagination_size: 10
  enable_js_formulas: false
  formula_folder_path: /
  inline_default: false
  inline_new_position: top
  date_format: yyyy-MM-dd
  datetime_format: "yyyy-MM-dd HH:mm:ss"
filters:
  enabled: false
  conditions:
%%
`

**Comment by rohanbatraio** [comment]
Is it possible?

**Comment by rohanbatraio** [comment]
I think you use 

%% 
%% 

as an identifier right? 

Changing that to 

`
```%%
%%``` 

`

would that make any issue?

**Comment by RafaelGB** [comment]
It represents a very big change for a very particular use case that can pose a risk.  In the past it was modified so that it doesn't affect the Templater plugin and I have an idea of ​​how to approach it but I don't think it's a good idea until I finish adapting the plugin to 1.0

**Comment by rohanbatraio** [comment]
Sure, its a problem to look after for stability, doesn't matter if it is implemented after 1.0 adaptation or anything that comes in between your roadmap. I can remember to NOT lint my vault but accidents do happen. So in the future, please look for a way which poses a workaround to this issue of mine.

**Comment by RafaelGB** [comment]
Commit e1a502db

I was able to reuse the logic that was assembled for the previous format migration.

As an added bonus, in markdown read mode a dataview table will be displayed


https://user-images.githubusercontent.com/11924043/196478281-1af9d7dc-ebe1-4789-b1e1-51481e962566.mov

**Comment by rohanbatraio** [comment]
Awesome !!!! 
Thank you so much. That's going to make my linting life easier.

**Comment by rohanbatraio** [comment]
> Commit [e1a502d](https://github.com/RafaelGB/obsidian-db-folder/commit/e1a502db2def46de4a30289afe8def2733684968)
> 
> I was able to reuse the logic that was assembled for the previous format migration.
> 
> As an added bonus, in markdown read mode a dataview table will be displayed
> Screen.Recording.2022-10-18.at.17.40.34.mov

The bonus feature is really impressive now we don't really have to create separate notes for dataview and db folder. Please do add a default view option if possible so the view can be set, if I want markdown to be rendered then give me markdown, if i want db give me db on file loading.

**Comment by rohanbatraio** [comment]
Also Is there a problem in adding additional things in the ddbb markdown file? like if i add my notes in conjuction with dbfolder.yaml would that break something?

**Comment by RafaelGB** [comment]
> What i wish is to set a default myself, right now default is being set to render the react table. But now that we have a BONUS feature which shows us dataview query then i would directly want to go into the note and VIEW it as a markdown.

It was a feature with old versions of Obsidian but since the tabs where included it was broken. We need to remake it but I don't know if the Obsidian architecture allows it now



> Also Is there a problem in adding additional things in the ddbb markdown file? like if i add my notes in conjuction with dbfolder.yaml would that break something?

While you do not edit the codeblock of `yaml:dbfolder` and the field `database-plugin: basic` you can include what you want
