### ISSUE TITLE
[Bug]: Inline field wrap quotes when it’s not necessary

### ISSUE THREAD

**Issue by icytree** [RafaelGB/obsidian-db-folder#510]
### What happened?

When the "Enable/Disable quotes wrap with frontmatter fields" setting is disabled, it still wrap frontmatter fields with quotes. Furthermore, it also does it to inline field. I also noticed that updating a field A (inline in this case) will make the plugin wrap in double quotes a field B (in YAML) for the same note... Here's a video that displays the whole thing. Note that I had also disabled this setting in the plugin options. I also did test it when enabled just in case and still, same outcome.

https://user-images.githubusercontent.com/80559262/196019285-10aae317-f03e-4526-82ea-e29975b9c8dd.mp4

### What platform were you using?

Desktop

### Version of the plugin

2.7.2

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
even if the option it’s disabled there are cases when we need to wrap with quotes the yaml to prevent possible errors

the wrap was used because the value contains `:` and its a potential yaml breaker

On the other hand, the inline field should not be necessary to wrap it, I will investigate the reason

**Comment by icytree** [comment]
> the wrap was used because the value contains `:` and its a potential yaml breaker

I see ! I did not think about this but it makes sense. 

> On the other hand, the inline field should not be necessary to wrap it, I will investigate the reason

Awesome, thanks a lot !
