### ISSUE TITLE
[Bug]: Making any changes in the notes fields also changes the "Banners" plugin image path.

### ISSUE THREAD

**Issue by cesarpereira904** [RafaelGB/obsidian-db-folder#515]
### Contact Details

cesarpereira904@gmail.com

### What happened?

Hi Rafael,

Not sure if its apropriate to report this here or if I should report it to the "Banners" plugin creator, but tests I made so far showed me that this is only happening when I makeany edits on the DB Folder lists.

Consider the following note:

![image](https://user-images.githubusercontent.com/70922426/196144235-24ccf637-62db-495c-adaa-5640831e83e0.png)

This note have a banner (https://github.com/noatpad/obsidian-banners):
![image](https://user-images.githubusercontent.com/70922426/196144437-1ae39c3b-0a77-4d58-a743-82f25d6be2ee.png)

![image](https://user-images.githubusercontent.com/70922426/196144525-aa9f4bec-694d-4d08-af37-4e643ef2a668.png)

When I change any value in the note:
![image](https://user-images.githubusercontent.com/70922426/196144657-90495cdc-acc6-480d-90a4-85703701bc08.png)
![image](https://user-images.githubusercontent.com/70922426/196144715-7a26c4cc-b582-4d17-acfc-12973f6127c1.png)
Banner path gets broken:
![image](https://user-images.githubusercontent.com/70922426/196144805-73cf20a2-1cf3-48de-a722-a9ea29f509c4.png)
![image](https://user-images.githubusercontent.com/70922426/196144869-638a66f1-001d-444a-977a-9e4e7a84996d.png)

Before changing the field in the DB filder list banner path was:
banner: "![[../../Images/aleks-dorohovich-nJdwUHmaY8A-unsplash.jpg]]"

And after changed to : banner: "![[Workspace/Images/aleks-dorohovich-nJdwUHmaY8A-unsplash.jpg|aleks-dorohovich-nJdwUHmaY8A-unsplash.jpg]]"

On the other side, if I change the value of that specific fields directaly in the file manually te banner remains unchaged and displays correctly. 

Any idea or sugestions are welcome and let me know If I should report this to the "Banners" plugin owner (If it's not related to DBFolder).

thank you

### What platform were you using?

Desktop

### Version of the plugin

2.7.3.

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
after every change the plugin overwrites all the info with the same value that it was read.

We have an issue for that here https://github.com/RafaelGB/obsidian-db-folder/issues/226 where you can find an explanation

The plugin of your banner does not allow absolute paths or alias? the path internally is the same one

**Comment by cesarpereira904** [comment]
Thanks for your cooments Rafael.

Cannot really answer that but here what the pugin developer states:

![image](https://user-images.githubusercontent.com/70922426/196152171-ab6aaf84-b6d8-4b85-98e2-206c6c55dea7.png)

Also, using any other plugins to change the frontmatter seems to work normally. 

I will try to check more details on this and let you know about any other findings.

Also, if instead of using a local image file I use a url link it's not affected by this problem, so seems it's only happening for local files.

**Comment by RafaelGB** [comment]
the plugin uses the datatype of dataview, in this case a Link for internal files.

In the case of Links we need the full path to avoid duplicates in your vault

**Comment by RafaelGB** [comment]
closed as wont fix. Feel free to coment if this problem still persist
