### ISSUE TITLE
[Bug]: Field position is wrong when "quotes wrap with frontmatter fields" is enabled

### ISSUE THREAD

**Issue by www-wagner** [RafaelGB/obsidian-db-folder#516]
### Contact Details

www.wagner.br@gmail.com

### What happened?

When I create a DB with more than 10 fields and  `quotes wrap with frontmatter fields` setting is enabled, fields with position "10", "11", etc. show before field with position "2".

When `quotes wrap with frontmatter fields` is disabled, the fields are shown correctly:

![image](https://user-images.githubusercontent.com/18124316/196218596-6160045f-f555-43f1-bfb5-e7aa8f3c845d.png)
![image](https://user-images.githubusercontent.com/18124316/196218488-b8362202-0cab-4c07-a843-cfbdb8d0435d.png)

When `quotes wrap with frontmatter fields` is enabled, the fields position gets wrong:

![image](https://user-images.githubusercontent.com/18124316/196218822-d8f18a09-2af8-429f-a79f-76ca2b0cd01e.png)
![image](https://user-images.githubusercontent.com/18124316/196218913-48568db2-46f8-4d1e-987d-7e8bc2a5c067.png)

But the DB settings is right:
![image](https://user-images.githubusercontent.com/18124316/196219559-3ae3c08a-5e5d-494e-ae19-a09865e48391.png)

### What platform were you using?

Desktop

### Version of the plugin

2.7.3

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
looks like the problem could be the type. Its read like string instead of number. Its an easy fix ;)

Thanks for the report

**Comment by RafaelGB** [comment]
Commit a9faf9b6

Fixed
