### ISSUE TITLE
[Bug]: Date property manual edit

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#517]
### Contact Details

danny@dannyhatcher.com

### What happened?

When I try to manually alter the date in the database view it kicks me out before I can make an edit.
I would like to be able to text in there just like a text property to manually change dates or times.

### What platform were you using?

Desktop

### Version of the plugin

2.7.3

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
currently you can already edit i manually, but had a conflict with the onChange event. Once you change just a number the plugin trigger onBlur,closing the edition

**Comment by DannyHatcher-Git** [comment]
Yeah that is what I have noticed.

For changing timestamps it is frustrating. Opening the page is quite long if I am changing lots of files.

**Comment by RafaelGB** [comment]
This was included with 3.0.0 as a result of other changes
