### ISSUE TITLE
[VS]: Formula property size in function of text

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#518]
### Contact Details

danny@dannyhatcher.com

### Present your request

I would like to keep the formula edit box larger in the settings menu so I don't have to keep changing the size each time I go in.
Having the text be larger in the box would also help with viewing.

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
its an Obsidian component. We have to investigate if it's possible

**Comment by RafaelGB** [comment]
Commit ba139a9f

dynamic size of text area
