### ISSUE TITLE
FR - Fit more columns on a screen without side scrolling

### ISSUE THREAD

**Issue by that0n3guy** [RafaelGB/obsidian-db-folder#52]
**I want to be able to see more info on the screen w/o side scrolling.**

I wasn't sure what to call this feature request because there are many ways to accomplish it.     

Some ideas on how to accomplish this:
- specify max table width
- specify width per column (in px or in percentages) 
  - drag columns to a width and remember the set width https://github.com/RafaelGB/obsidian-db-folder/issues/50 

Here are 2 examples (dataview vs db folder):
![image](https://user-images.githubusercontent.com/113870/168870619-0deb6c46-f899-443b-afbb-0bbd512345fb.png)

**Comment by RafaelGB** [comment]
I will assist this requirement with https://github.com/RafaelGB/obsidian-db-folder/issues/50 (the roadmap is growing too fast...)

**Comment by that0n3guy** [comment]
> I will assist this requirement with #50 (the roadmap is growing too fast...)

You should see if you can partner up with tomaszkiewicz .   Looks like he has a similar plugin: https://github.com/tomaszkiewicz/obsidian-database-plugin .   I think yours is further along.   Maybe he can jump on and help out??

P.s.   Awesome plugin by the way.   I'm shocked this hasn't been thought of before.

**Comment by RafaelGB** [comment]
I already talk with him weeks ago, but Tomas prefers his concept right now. Hope we can work together in the future. I really need another devs, the roapmap is astonishing...
