### ISSUE TITLE
[FR]: Enter for adding select and tag

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#520]
### Contact Details

danny@dannyhatcher.com

### Present your request

When adding select or tag options I need to push the add button with the mouse. 
I would like to be able to push enter making it quicker.

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
Do you mean inside the column config?
The enter button its already available on cell editor

**Comment by DannyHatcher-Git** [comment]
Yes the config settings, sorry.

**Comment by RafaelGB** [comment]
You want it, you got it =P

Commit 33e18f7d
