### ISSUE TITLE
[Bug]: Change page on Android

### ISSUE THREAD

**Issue by magiskai** [RafaelGB/obsidian-db-folder#524]
### What happened?

On my Android phone, the page change buttons don't show up (perhaps because the screen width is too small).

### What platform were you using?

Mobile

### Version of the plugin

v2.7.3

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Its a known issue. As you said, the reason it's the size of the screen.

Will be supported as soon as we find an alternative
