### ISSUE TITLE
[Bug]: Number sort

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#533]
### Contact Details

danny@dannyhatcher.com

### What happened?

The number property is sorting by individual number not the whole so we can get poor sorts.
![image](https://user-images.githubusercontent.com/78496825/196921472-f4421a84-e09b-443e-b2ea-7ee5dc9bff6f.png)

### What platform were you using?

Desktop

### Version of the plugin

2.7.3

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
I will apply the same solution of https://github.com/RafaelGB/obsidian-db-folder/issues/516

**Comment by RafaelGB** [comment]
Commit 5e8627b3
