### ISSUE TITLE
[FR]: Add filter/sort options for the tasks query results

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#536]
### Contact Details

danny@dannyhatcher.com

### Present your request

Have an options to sort by task amount or filter by tasks present or not.

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
The tasks column does not depents of the plugin and we can not obtain the information to order them.

The only order I can imagine could be the number of tasks, but not the text inside

**Comment by DannyHatcher-Git** [comment]
The number of tasks is all I would want/need.

**Comment by RafaelGB** [comment]
Commit b9062bbe

Ready for the next version =)
