### ISSUE TITLE
[FR] Checkbox type column

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#54]
Perhaps the possibility of adding a checkbox/toggle column? Maybe the result could be shown in markdown as a 0 or 1.

**Comment by RafaelGB** [comment]
is reasonably easy to achieve, could be the goal for version 1.2.0

**Comment by RafaelGB** [comment]
1.4.0 is out!
New metadata of type task. Render the checkbox of file and you can edit it

<img width="647" alt="Screenshot 2022-05-25 at 23 54 43" src="https://user-images.githubusercontent.com/11924043/170373871-9e9cea4c-34bf-42e9-923d-516ea3011cc2.png">
<img width="343" alt="Screenshot 2022-05-25 at 23 55 08" src="https://user-images.githubusercontent.com/11924043/170373882-1ec4fd59-3232-4a0f-b868-e550bd186ed5.png">
<img width="472" alt="Screenshot 2022-05-25 at 23 55 29" src="https://user-images.githubusercontent.com/11924043/170373889-1cb22d2f-8981-4234-9b73-d65c986510c5.png">

**Comment by RafaelGB** [comment]
when checkbox column has support for dark mode I will close this one
