### ISSUE TITLE
[FR]: Search result overlap

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#541]
### Present your request

When there are lots of search results the number overlaps the typing area.

![image](https://user-images.githubusercontent.com/78496825/197189109-d51fafb9-3d9d-472b-80ae-862fb44d2392.png)

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
This issue was resolved moving the info to the status bar with 3.0.0
