### ISSUE TITLE
[Bug]: vault is restarted when `Enter` key is pressed in search field

### ISSUE THREAD

**Issue by www-wagner** [RafaelGB/obsidian-db-folder#546]
### What happened?

![Obsidian_DB-Folder_bug](https://user-images.githubusercontent.com/18124316/197244005-07272154-e716-44ef-96f6-00ba173e730c.gif)

I've searched using the search field and it's worked correctly. But if I hit `Enter` after typing the text, the vault is restarted!

### What platform were you using?

Desktop

### Version of the plugin

2.7.4

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
thanks for the report

debugging I do not have any event associated with the enter, I will investigate the cause

**Comment by RafaelGB** [comment]
Commit c4d46faa

Fixed. Was a default event of MUI when a form is enabled and Obsidian can not handle it

**Comment by DannyHatcher-Git** [comment]
I was going to report this but will wait for the next update to see if it persists 😁
