### ISSUE TITLE
[FR]: bulk rows editing / deleting like Notion

### ISSUE THREAD

**Issue by www-wagner** [RafaelGB/obsidian-db-folder#548]
### Present your request

It'd be awesome if we could select **multiple** rows for **editing and deleting**, like Notion!

![Obsidian_DB-Folder_FR_bulk](https://user-images.githubusercontent.com/18124316/197247498-ad01fa1e-a2aa-4228-ad9c-a8eabebf9373.gif)

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
this option is integrated with react-table framework. It will be a future feature =)

**Comment by javiavid** [comment]
If this is complicated to integrate into the plugin, an alternative could be a selection column (checkbox).
This selection column could appear and hide when clicking, for example, on the search icon.

Example:

-Select all the files you want to do something to, even if they are on multiple pages
-Click on the options in that column and a menu appears to perform operations on those files.

Some basic could be, for example, delete files.

**Comment by RafaelGB** [comment]
First version with SHIFT+click event

You can click on header column to select them all, then you can right click the header to select the action on those marked rows.

https://user-images.githubusercontent.com/11924043/210823102-c3ba2d7c-039b-446b-bf8e-0fe7f62bd292.mov

**Comment by RafaelGB** [comment]
Commit 5bcbe7ee
