### ISSUE TITLE
[Bug]: Wrong attributes order after import from CSV

### ISSUE THREAD

**Issue by pharolog** [RafaelGB/obsidian-db-folder#551]
### What happened?

1. I have a CSV file with two columns: "name" and "description". Like this.

name,description
Name 1,Description 1
Name 2,Description 2

I want to have in Obsidian DB two files (or two values in DB): 
a) file name (page header) = value from column "name"
b) attribute "name"= value from column "name"
c) attribute "description" = value from column "description"

For example:
File (page name header): Name 1
name: Name 1
description: Description 1

2. Set in the plugin config "Mandatory header key" = name
![image](https://user-images.githubusercontent.com/116509453/197405804-38b3262e-32e2-474b-b58b-39510bdd63ec.png)

3. I have an empty DB.
![image](https://user-images.githubusercontent.com/116509453/197405188-d291724a-b7c5-4747-9f08-76f84a2aeec1.png)

4.  I use the "Import CSV" function, to upload the data.

5. It creates 2 files with proper filenames as requested in "a) file name (page header) = value from column "name"." 
![image](https://user-images.githubusercontent.com/116509453/197405373-a5fe8762-49d8-4f68-9b1e-78b3b35ceaf1.png)

6. But in metadata: "name" column contains values from "description" and "description" column is empty.

It means don't work two rules: 
b) attribute "name" = value from column "name" (it shows value from description)
c) attribute "description" = value from column "description" (the value is empty).

![image](https://user-images.githubusercontent.com/116509453/197405405-c58105c2-5733-4860-928a-5119e3c8b22a.png)

![image](https://user-images.githubusercontent.com/116509453/197405428-17cc3214-fea4-438f-9d2a-0cf7d9bce485.png)

What could I do wrong?

### What platform were you using?

Desktop

### Version of the plugin

2.7.4

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hi @pharolog , the mandatory field seems to replace your name instead of create another one asociated to the file. While its investigated try to create another column in your csv duplicating the name called "File"

**Comment by pharolog** [comment]
@RafaelGB Thanks a lot for the prompt answer. If I duplicate the column "name", like this.

name,name,description
Name 1,Name 1,Description 1
Name 2,Name 2,Description 2

The result is the same:
![image](https://user-images.githubusercontent.com/116509453/197410761-3304b87a-4dcc-43e1-aa10-95b9c665b9e8.png)

The same case if I duplicate the column name, but do not add values in rows:

name,name,description
Name 1,Description 1
Name 2,Description 2

**Comment by RafaelGB** [comment]
Try to change the mandatory field as File and change the duplicate column header as File too

**Comment by pharolog** [comment]
The same problem. 
--- case 1 Duplicate for two "Mandatory header key" ----
I set values according to Column (C) and Row Number (R) to see from which column the system takes values. 
Source file:

File,File,description
C1R1 File,C2R1 File,C3R1 Description 
C1R2 File,C1R2 File,C3R1 Description 

![image](https://user-images.githubusercontent.com/116509453/197415303-46a40f8d-e98b-4c9e-8a35-215a76ea1f11.png)
Mapping
1. Page header from column 1= Mandatory header key”
2. If 2nd column name=”Mandatory header key
then  value from the next column 3
3. “description” is empty

---- case 2 only one column with Mandatory header key
![image](https://user-images.githubusercontent.com/116509453/197415441-d7f94ae7-e425-4600-a3cf-83a813521fb1.png)

Mapping
1. Page header from column 1= Mandatory header key
2. If 2nd column name<>” Mandatory header key” name, then value from this column 2
3. “description” is empty

**Comment by RafaelGB** [comment]
Thanks for your testing. We will work on it!

**Comment by pharolog** [comment]
Thanks a lot! I'll be waiting for the news.

More details from testing. I hope it can help somehow in my case.

It is not possible to load data in the right structure without additional manipulation, because 
1. **One** column with **name** "File"="Mandatory header key"
2. Must have **Two** columns with the **File value**.
3. For other columns, values for a column with Header **X** should be stored in Column **X+1** 

**AS IS.**
I used this synthetic table to understand the current rules:
File,C2,C3,C4
C1R1 File,C2R1,C3R1,C4R1 
C1R2 File,C2R2,C3R2,C4R2 

With the result:
![image](https://user-images.githubusercontent.com/116509453/197418199-d4357b8c-a040-496b-97cf-18541eeb1978.png)


Thus, in my case rules works like this:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/116509453/197418053-13243d70-6399-4e03-a8c1-2e246dfce169.png">


**Workaround to avoid this bug (partially).**

The structure should be:
File,C2,C3,C4
File1,File1,C2,C3 
File2,File2,C2,C3 

The result will be 
![image](https://user-images.githubusercontent.com/116509453/197417788-fcf30a7b-2866-4133-91c1-ece34b747baa.png)

**Comment by pharolog** [comment]
Thanks a lot. For now only small, not critical bug #593

**Comment by RafaelGB** [comment]
thanks to you for your feedback!
