### ISSUE TITLE
[Bug]: Pop out window group issue.

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#552]
### Contact Details

danny@dannyhatcher.com

### What happened?

It might be due to the CSS update but the groups in the pop out window no longer appear the same.

![image](https://user-images.githubusercontent.com/78496825/197408117-16754622-d7a2-48b5-9fa4-276468d0cddd.png)

### What platform were you using?

Desktop

### Version of the plugin

2.7.4

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
What css snippet, plugins or themes do you have installed?

Looks like a css incompatibility

**Comment by DannyHatcher-Git** [comment]
Only a small snippet of my own that impacts colour, size of page preview and tasks blocks.

**Comment by RafaelGB** [comment]
try to disable them to check if affects the headers. I tested it with all the OS and works cool

**Comment by DannyHatcher-Git** [comment]
There is still the same issue. I can share a screen recording if you want.

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/588 will be atended here
