### ISSUE TITLE
[Bug]: changing the column type to `tag` kills the DB..

### ISSUE THREAD

**Issue by zeltak** [RafaelGB/obsidian-db-folder#555]
### Contact Details

zeltak@gmail.com

### What happened?

when changing a column type to `tag` It freezes and wipes out the DB (leaves with zero bytes)

this is what happens during the initial freeze

![CleanShot 2022-10-25 at 14 48 33](https://user-images.githubusercontent.com/498410/197768813-79fd67cc-2141-4c01-ad6e-112cb18c9169.gif)

### What platform were you using?

Desktop

### Version of the plugin

2.7.4

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
I will check this issue as priority.

In your video looks like there is too much files to edit the color property at the same time

**Comment by zeltak** [comment]
thx!

happy to help in anyway I can (though I cant code so only testing :))

you are a legend with this plugin!

Z

**Comment by RafaelGB** [comment]
Was a concurrency problem =(

Commit b50ce35c

When the plugin is trying to add a new option/color there is another row with another petition and overwrite it. Also the entire row is refreshed and trigger AGAIN the add function because the override thing

Will be added with the next version
