### ISSUE TITLE
[Bug]: obsidian-db-folder always only shows the code. It needs to manually close and reopen the Dataview to solve the problem.

### ISSUE THREAD

**Issue by chenxin0397** [RafaelGB/obsidian-db-folder#557]
### Contact Details

chenxin0397@163.com

### What happened?

A bug happened!The way I manage plugins is to use the template to call the plugin ID's method to start the plugins in batches.

Refer to the method here:
https://tfthacker.medium.com/improve-obsidian-startup-time-on-older-devices-with-the-faststart-script-70a6c590309f
My Dataview plugin is in the FastStart-Plugins-ShortDelay list.

The Dataview plugin is automatically opened every time OB starts, but the obsidian-db-folder always only shows the code. It needs to manually close and reopen the Dataview to solve the problem. Chinese forums say this is called (original state). The way I start the Dataview is not in the original state.

Above are some clues I provided. Are there any improvements to the plugin?

Anyway, with the launch method I used, the Dataview is available. But the plugin attached to the Dataview loses the relevant functionality

### What platform were you using?

Desktop

### Version of the plugin

2.7.4

### Relevant log output

```shell
I can't find the log
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by chenxin0397** [comment]
![image](https://user-images.githubusercontent.com/73974352/198341729-ef349a23-6a48-45d3-8358-440b46a1ae27.png)

**Comment by RafaelGB** [comment]
hi @chenxin0397 ,

Seems like with your starting batch method the load of the plugin is not finished once you open your vault.

The plugin needs to load its own view so Obsidian can open the database folder view when you open a note.

I don’t know how to fix this issue and I dont want to change the init function. Maybe we can expose an API so you can manage manually that initial state but could takes time and its not a priority right now by far
