### ISSUE TITLE
[FR]: Nested field column type that only needs the partent field.

### ISSUE THREAD

**Issue by xDovos** [RafaelGB/obsidian-db-folder#559]
### Present your request

i have deeply nested metadata for my formulas, where every subfields have their own names based on the formula note names.
currently the DB folder can't show the content of nested fields right and just shows it in the written out JSON style.
another problem is that it is breaking the links that are inside the nested list inside the YAML. 
into this:
Basic_Power_Variables:
  undefined:                                 - "[[Power]]"
   path: Variables/Power.md
   type: file
   embed: false

i have added an example file of one of my formula notes with the normal dataview table on how i would like to have it inside DB folder too, but it would be fine if everything is in just one column and not split into 3 like in the note.
[Formula Basic Power.md](https://github.com/RafaelGB/obsidian-db-folder/files/9890151/Formula.Basic.Power.md)

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
hi @xDovos thanks for your suggestions,

As we talk in discord we will try to create another kind of cell or a new config to render objects as pure markdown

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/209936461-68472aab-7e58-459f-9824-5c090bfb996a.mov

Found a way parsing it with yaml stringinfy and some tricks

**Comment by RafaelGB** [comment]
Commit 52bbc520
