### ISSUE TITLE
[FR] Conditional Formatting

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#56]
Ability to apply conditional formatting to rows. 

Examples:
- if name contains "_____" color row red
- if total > 50 color row green
- if date < date(today) bold text in row

etc, etc

**Comment by RafaelGB** [comment]
It may be a church arch, so I'm ruling it out for now. I really appreciate your proposals, the roadmap is more exciting than it was 1 hour ago
