### ISSUE TITLE
Date picker on mobile

### ISSUE THREAD

**Issue by Asetnozama** [RafaelGB/obsidian-db-folder#561]
Hi, I'm loving this plugin!!
Just one little issue: on mobile the date picker doesn't work as it supposed to do. It's not possible to move back and forward through the months to select a date. 

Thanks and have a nice day

**Comment by RafaelGB** [comment]
HI @Asetnozama, thanks for the report. I will work on mobile for the next versions

**Comment by Asetnozama** [comment]
Thans you very much for your effort!!!

**Comment by RafaelGB** [comment]
We need to change the datepicker framework. The current one does not support mobiles really well...

I was thinking about MUI

https://codesandbox.io/s/d9ugq3?file=/demo.tsx

**Comment by Asetnozama** [comment]
Looks great!

**Comment by RafaelGB** [comment]
@Asetnozama  with 2.8.2 now the calendar is easier to use with mobiles, but I am afraid we can not change the framework without lose some features right now.

We will keep working to work with the css. Now with tablets it would look the same as with a computer

**Comment by Asetnozama** [comment]
I didn't check on tablet yet, but is seems that on mobile phone there's no difference. ![image](https://user-images.githubusercontent.com/102867794/201359342-783eea91-3f65-419c-8f45-0500553729e0.jpeg)
Is there no possibility to make two " < and > " to scroll through the months?

**Comment by RafaelGB** [comment]
ywah, its the intention, but I don't know why the css does not work well.

The difference on mobile its now there is not keyboard menu when you use the calendar(easier to use)

**Comment by Asetnozama** [comment]
> The difference on mobile its now there is not keyboard menu when you use the calendar(easier to use)

Yes, that's true. 

Maybe in the future there will be another possibility to use the daypicker on mobile phones. 👍🏼🙋🏻‍♂️

**Comment by RafaelGB** [comment]
Fixed! was a problem with the obsidian buttons style

```css
.react-datepicker button {
  max-width: var(--react-datepicker-navigation-width);
  max-height: var(--react-datepicker-navigation-height);
}
```
did the trick
