### ISSUE TITLE
[FR]: Reorder Group filters

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#562]
### Present your request

I want to see the ability to move the group filters up and down in the edit window (left and right in the main table view).

At the moment I need to remove filters and then re-create them in the order I want them to appear.

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
I had it in mind, but I want to focus them with drag & drop. Can be tricky...

You can go into the markdown file and manually move it around to reorder without having to create it again.

**Comment by DannyHatcher-Git** [comment]
I will go in and do it that way. Even just a button for up and down in the window would work for me.

**Comment by RafaelGB** [comment]
Commit 73662e43

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/212740475-cd4f5c0b-d9d5-48de-93bf-cde17827aa32.mov
