### ISSUE TITLE
[BUG]: Date picker removal

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#564]
### Present your request

I can't seem to remove the date from the date picker.

The x closes the window and when I backspace the date, it pushes an error. 
I would like a 'clear date' option.

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
Its a known problem. You need to close the menu first (esc) and then click the button

**Comment by DannyHatcher-Git** [comment]
hmm, I tried that but it just seems to close down the window leaving the date there.

the esc works for the select and multi-select.

**Comment by RafaelGB** [comment]
Commit efa40c01

https://user-images.githubusercontent.com/11924043/200115728-a7e26063-cfde-416b-a935-b06ed95fe4a3.mov

Fixed:
- style
- remove button
- edit engine when is empty
- service of edition when dataArray was null
