### ISSUE TITLE
[Bug]: relation column shows empty select option

### ISSUE THREAD

**Issue by Rhydderch** [RafaelGB/obsidian-db-folder#568]
### What happened?

Setting a column to "relation" type and associating it to a DB does not work. It does not show any entry suggestion (I tried with several DBs of different sizes)

<img width="166" alt="image" src="https://user-images.githubusercontent.com/3197629/199201240-8482b079-7f05-4ac7-ba91-393752e9c9cf.png">

And here are the entries of the DB

<img width="338" alt="image" src="https://user-images.githubusercontent.com/3197629/199201933-918a4018-fda5-4201-a769-7f7963d853cd.png">

### What platform were you using?

Desktop

### Version of the plugin

2.8.0

### Relevant log output

<img width="417" alt="image" src="https://user-images.githubusercontent.com/3197629/199201740-79a24610-8302-41e4-aa89-42066201282c.png">

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Oh I see. The problem is with the dv query source. I will fix this for the next version =) thanks for the report

**Comment by RafaelGB** [comment]
Commit 80e74627

Was a quick fix

**Comment by RafaelGB** [comment]
With the next minor version we will add a lot of new rollup functions and a improved API for use them into the formulas =)

**Comment by Rhydderch** [comment]
Great :) Looking forward to it.
I also saw that long-term, you are thinking of adding views. Having similar views as notion (kanban, calendar, etc) would be the cherry on top!

**Comment by RafaelGB** [comment]
https://github.com/marcusolsson/obsidian-projects The views will be added with this plugin. 

Once it is published we will work to add the dbfolder view as one more. If makes sense, we will added our own views too when the application is consolidated

**Comment by rdx711** [comment]
I have the same issue. I created the databases and linked them last month. All was fine then. Now when I try to add a link, it shows 'No options' across all databases. Nothing has changed with respect to Obsidian and the plugin. I am on Obsidian Version 1.3.5 and DB Folder version 3.4.0.
Should I create a new issue?
