### ISSUE TITLE
[Bug]: Obsdian Crashes when setting Fromula's to "Persist Formula Output"

### ISSUE THREAD

**Issue by SenseiBas** [RafaelGB/obsidian-db-folder#569]
### What happened?

Obsdian Crashes when setting Fromula's to "Persist Formula Output"

**When Setting** a Formula: `${row.__inlinks__.length}` 
**to** "Persist Formula Output" 
**Then** Obsidian** Crashes 
**and** Cant Boot until I manually Fix the file in another application. 

### What platform were you using?

Desktop

### Version of the plugin

2.8.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
I can reproduce it too. Thanks for the report. 

we will give it priority for the next version

**Comment by RafaelGB** [comment]
Commit 27be9348

seem fixed but I can not guarantee for your use case. I will generate a minor version with another minor issues

**Comment by RafaelGB** [comment]
Please. let me know if 2.8.1 fixed the problem to close this issue

**Comment by SenseiBas** [comment]
Yes this FIxed it!
You sir are awesome, thanks for a great plugin!

I will do my best to report bugs as I find them
Not much of a programmer so don't think I can help a lot on that regard but if I can help let me know

**Comment by RafaelGB** [comment]
You  are already helping a lot with this reports =)
