### ISSUE TITLE
FR: Wrap Field with Markdown before render

### ISSUE THREAD

**Issue by that0n3guy** [RafaelGB/obsidian-db-folder#57]
Everyone has different field data.   If the user is able to wrap their field in markdown before rendering the cell it will enable very flexible column types.   

For example:
From: https://github.com/RafaelGB/obsidian-db-folder/issues/17#issuecomment-1129118138

If I could wrap a link in transluded image markup, the link can now get rendered as an image:

`cover:: https://images-na.ssl-images-amazon.com/images/I/41wd4dlgGBL._SX322_BO1,204,203,200_.jpg`

Could get setup as `"![anyTexthere|100](" + cover + ")"`.    

The above is a javascript syntax that is essentially putting a `![anyTexthere|100](` before `cover` field and `)` after the field.    The rendered markdown would look like:
`![anyTexthere|100](https://images-na.ssl-images-amazon.com/images/I/41wd4dlgGBL._SX322_BO1,204,203,200_.jpg)`

...Resulting in an image that is 100px wide.

This could be used for `**bold**`, `*italic*`, `==highlights==`...
Or if we can get really fancy and do multiline... things like callouts:
```
> [!TIP] Callouts can have custom titles
> **fields go here**!
```

I'm not sure JS is the way to do this.  Maybe some templating engine like `![anyTexthere|100]( {{cover}} )` would be simpler.

##### My assumption: This could probably hinder your ability to sort/filter on that column.  To some that might be worth the trade off.

**Comment by RafaelGB** [comment]
Starting with this soon. Will be the goal for 1.2.0

**Comment by that0n3guy** [comment]
Nice... getting so close.

**Comment by that0n3guy** [comment]
After testing it, it works great! 

I think that the 
![image](https://user-images.githubusercontent.com/113870/169369418-7633c167-bfc5-4ef5-bca3-01f880ba861a.png)

should probably be on a per column basis.    B/c if a different column is just a normal link, it will try to embed it.... like so:
![image](https://user-images.githubusercontent.com/113870/169369653-87f20c34-71ae-402c-b0b7-1dc37e7b2667.png)

**Comment by RafaelGB** [comment]
the last visual bug I could not reproduce it.

About move the configuration to column adjustment is one of the dots to 1.3.0
Right now, the header menu is not scalable at all. The refactor idea is to open another Obsidian Modal just as local database config, then add embedded media and the current inline option. So much better I think

**Comment by that0n3guy** [comment]
the "embeded link" bug was if I used a regular link (like to this github page) and not a link to an asset.

**Comment by RafaelGB** [comment]
I mean the other with blank settings section.

About regular link, if the header settings are refactored, could add an Iframe option :)

**Comment by that0n3guy** [comment]
> About regular link, if the header settings are refactored, could add an Iframe option :)

Sorry, that's not what I meant.   Here is an showing what I mean: 

![image](https://user-images.githubusercontent.com/113870/169394414-ce952905-2903-43c5-b620-1a82842b9881.png)
because the "enable media links" is global to the DB rather than the column... links try to embed... even if they aren't assets.

Here is the page content:
```
# AntiFragile

cover:: https://images-na.ssl-images-amazon.com/images/I/41wd4dlgGBL._SX322_BO1,204,203,200_.jpg
buyLink::  https://www.amazon.com/Antifragile-Things-That-Disorder-Incerto/dp/0812979680
creator:: Nassim Taleb
priority:: Medium
purpose:: Execution, Strategy
referrer:: CEO Summit (june 2016)
status:: To Read
subtitle:: Things That Gain from Disorder
tags:: #source/books 
```
