### ISSUE TITLE
[Bug]: Add new row button is covered by status bar

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#570]
### Contact Details

imeed166@gmail.com

### What happened?

https://user-images.githubusercontent.com/38974541/199296488-d01c9cef-0e2a-41be-a344-4890599e2c30.mov

### What platform were you using?

Desktop

### Version of the plugin

2.8.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Its a css issue related with z-index property of those components

added to the roadmap

**Comment by imeed166** [comment]
With the new design, this is no longer relevant.
