### ISSUE TITLE
[Bug]: Relations are saved but not shown after reloading database table depending on database name

### ISSUE THREAD

**Issue by randomsnowflake** [RafaelGB/obsidian-db-folder#572]
### What happened?

It seems there is a bug loading relationships, depending on the name or folder of the being related database.

I have a database `A` and a database `Sport Log`.
`A` has a relation field to a `Sport Log`.

I can add a `Sport Log` to an `A` row. The information is saved as an inline tag. So far so good.
BUT: When I reload the `A` database it does not show the relationship anymore, even though the field is still there.

This has something to do with the name or folder of the second database. If I rename `Sport Log` to `B` it works. I guess it has something to do with the space in the folder- or database name.

### What platform were you using?

Desktop

### Version of the plugin

2.8.0 and 2.8.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by randomsnowflake** [comment]
OK I figured it out:

Sometimes relations are saved with quote around the tag value (Sport_Log:: "[[path|name]]"). In that case the DB table will not show the relation when loading again. You have to remove the quotes to make it work - for example (Sport_Log:: [[path|name]]).

Please check how the relation tag is created, there seems to be a bug.

**Comment by RafaelGB** [comment]
hi @randomsnowflake,

I will check it. Thanks!

The inline insertion and editions should not include quotes. could be a problem with the parser to markdown

**Comment by RafaelGB** [comment]
Commit d43d7783

Fixed with the parser engine
