### ISSUE TITLE
[Bug]: Relations columns showing content of own DB instead of linked DB

### ISSUE THREAD

**Issue by Rhydderch** [RafaelGB/obsidian-db-folder#573]
### What happened?

DB type: tag
column type: relation
target: "media" DB

<img width="445" alt="image" src="https://user-images.githubusercontent.com/3197629/199439015-4896f448-9c42-4cfb-9d78-97f74df9b59c.png">

result: the suggestion show all the entries of the current DB (weekly notes) instead of the target DB
<img width="205" alt="image" src="https://user-images.githubusercontent.com/3197629/199439153-148d3012-f6e1-49ca-b21c-7270a2a38803.png">

Additionally, another bug is present: if the DB uses a dataview query, the suggestions are empty:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/3197629/199439348-97c3ec8c-cab0-4296-815c-afc600012470.png">

<img width="189" alt="image" src="https://user-images.githubusercontent.com/3197629/199439316-4104d78c-9c39-4032-aef3-81aea8f6e86e.png">

### What platform were you using?

Desktop

### Version of the plugin

2.8.1

### Relevant log output

```shell
No errors in the console
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by SenseiBas** [comment]
Addon: Relations Column seems to have some trouble reading the relations. 
Don't know if this a separate issue or not. 

![image](https://user-images.githubusercontent.com/97248289/199449009-6e087318-5933-4f1a-9e83-2d3b123b23f7.png)
![image](https://user-images.githubusercontent.com/97248289/199448945-00bb5a9e-eb02-4cde-bb9f-1491889b3303.png)

**Comment by RafaelGB** [comment]
@SenseiBas looks like the way to persist your links. Should not be persisted with "" or the plugin can not know that its a relation

@Rhydderch I need to test it

thanks for your reports. We will keep working on this feature. So much use cases 😅

**Comment by Rhydderch** [comment]
So many use cases and things that can break, indeed 😄 "Courage" (as we say in French) to polish this feature, and thanks again for making obsidian better:)

**Comment by OmniNaut** [comment]
I can confirm this behaviour if I set the source of the database to tag. 
If the source of the database is set to current folder the functionality works as expected.
I did not test any other sources, so maybe the bug is not exclusive to tag

**Comment by RafaelGB** [comment]
The problem was found!
We were using the wrong settings instead of the relation one

Commit 8c81b599

**Comment by Rhydderch** [comment]
Hello Rafael,

Thank you for fixing this.
There is still one use case that doesn't work: if the linked DB (the "target" DB) is using a dataview query.

**Comment by RafaelGB** [comment]
Commit 6457c8bb This will fix the dv source relations too =)

**Comment by Rhydderch** [comment]
That fixed it at the time (forgot to post here), but now it seems broken again? :)

**Comment by RafaelGB** [comment]
could you share more details?

Looks fine for me since 2.9.0
