### ISSUE TITLE
[Bug]: Value of filter gets erased on restart of Obsidian if it contains a hashtag

### ISSUE THREAD

**Issue by icytree** [RafaelGB/obsidian-db-folder#579]
### What happened?

https://user-images.githubusercontent.com/80559262/199802444-03eb8cf2-3cca-417b-8f01-0af7fa00e0c8.mp4

### What platform were you using?

Desktop

### Version of the plugin

2.8.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hi @icytree ,
The way yaml is saved maybe affects the read after reload Obsidian

I will check it! Thanks for the report

**Comment by RafaelGB** [comment]
Commit 648dffe9

The values will be saved using quotes now to avoid this problem
