### ISSUE TITLE
[FR] Pre-populate select/lookup fields

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#58]
Would be wonderful to have select options prepopulated from either a directory of files or perhaps a specified list from a file (like supercharged links does). Maybe even be able to specify prepopulated options from a dataview query?

Example:
I have a recipes folder and an ingredients folder. In my recipes database I would like to have a select field (ingredients) that shows me all of the files from the ingredients folder or a dv query and allows me to select them as links to those files.

**Comment by RafaelGB** [comment]
Currently the code is prepared to load preselected options, but I am not taking advantage of it at the moment, if you open the database as a file and add a column to the options field: a,b,c .... should charge them but is not tested

I will add it to the backlog,m maybe 1.3.0  =P

**Comment by RafaelGB** [comment]
after release of 1.2.0, this will be the next =)
- [ ] Options persisted in column configuration
- [ ] Color of tag will be persisted ( and selectable if possible)
- [ ] Refactor of tag selection portal. Options of remove included

**Comment by RafaelGB** [comment]
Options are now persisted, including colours!

Just one dot more and the new version will be ready
<img width="609" alt="Screenshot 2022-05-21 at 20 50 17" src="https://user-images.githubusercontent.com/11924043/169665400-39a3bc6b-cb01-4c73-9c0e-902f5185236c.png">

I will check the minimal plugin to create our own color selector
<img width="609" alt="Screenshot 2022-05-21 at 20 51 27" src="https://user-images.githubusercontent.com/11924043/169665456-9762a6ce-bf72-4686-8b2d-5c8ef2716057.png">

**Comment by RafaelGB** [comment]
@arminta7 1.3.0 is out! now the label can be pre selected and the existed ones will be persisted

**Comment by arminta7** [comment]
My goal for this request was to be able to have the select options automatically available via a directory, query, list in a file or similar. My understanding is that I still need to manually enter select options in the settings? Is that accurate?

**Comment by RafaelGB** [comment]
the development consisted of being able to persist the options and select the color of the label. Those preloaded options would be kept even if there is no cell with that value.

Use a dataview query to load an array could be another option, but less flexible
