### ISSUE TITLE
[FR]: Bidirectional relations

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#582]
### Present your request

When I add a relation to a page I would like a reciprocal to appear on the linked page.

EG: I link a video idea/project with plugin.
Video database -> Plugin database

The video has a relation inline field but the plugin doesn't.

I need to make the relation in the plugin database to the video database.
Plugin database -> Video database

Can we make this automatic?

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/581

duplicated
