### ISSUE TITLE
[FR]: dynamic row height when select option is hidden

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#587]
### Contact Details

imed#8086

### Present your request

When I select the cell of a `select property` column and the column width is too small, the current selected `select property` is hidden by the menu. The proposition is to make the row height adjust itself to display everything, just like it does in the `tap property`.

https://user-images.githubusercontent.com/38974541/200667250-a88695ef-53b6-474b-a707-5257fb311e57.mov

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
we can achieve that with a modal or with some advanced css trick. Both ways could be little bit difficult

**Comment by imeed166** [comment]
This is solved with the release of 3.1, so I'm closing this one.
