### ISSUE TITLE
[Bug]: Top bar not displayed correctly when open db in a new window

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#588]
### Contact Details

imed#8086

### What happened?

https://user-images.githubusercontent.com/38974541/200668786-a2ee8643-fb2d-4a20-a4b5-79e7e6bf5621.mov

### What platform were you using?

Desktop

### Version of the plugin

2.8.2

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
something happened with the new obsidian design :( thanks for the report

**Comment by RafaelGB** [comment]
I don't know if Obsidian fix this problem with 1.0.3 or was another issue, But I can not reproduce it anymore 


https://user-images.githubusercontent.com/11924043/201416317-0e7970c4-2090-4fcd-9c47-edd03015b418.mov

**Comment by imeed166** [comment]
It's weird, I still have the same issue in obsidian 1.0.3 with a clean vault without video except for db folder and dataview, and no CSS snippet with the default theme.

**Comment by imeed166** [comment]
And I found that it's a duplicate of #552. The only difference is that he is using windows and I'm using mac.

**Comment by RafaelGB** [comment]
We will try it after the next release in case another task fix this one

**Comment by RafaelGB** [comment]
maybe this bug only happens on windows OS. I will wait until Obsidian 1.1.0 to check if Obsidian itself fix the problem

**Comment by RafaelGB** [comment]
Possible solution Commit e38db8e9
