### ISSUE TITLE
[FR]: Option or css to be able to align not title not the left.

### ISSUE THREAD

**Issue by cesarpereira904** [RafaelGB/obsidian-db-folder#589]
### Contact Details

cesarpereirara904@gmail.com

### Present your request

My notes in obsidian might have have long names, and because those are always aligned to the center, it makes it hard to read them:

![image](https://user-images.githubusercontent.com/70922426/200785621-f0d29a4f-3a83-4122-a8fb-605fc4ae706d.png)

I was trying to do it by myself thru a css snippet but was not able to, so maybe someone with more knowledge of css could help here.

I think this would improve readability a lot,  especially when there are many notes with names that might vary in length.

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
sure! the logic is already done. We need to test it with another cell types

**Comment by RafaelGB** [comment]
Added with the next version

**Comment by RafaelGB** [comment]
Commit 1f677a6e
