### ISSUE TITLE
[FR] Create db from dataview query

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#59]
It would be fantastic to be able to create these databases from a dataview query 😄

**Comment by RafaelGB** [comment]
I already thought about this possibility although it breaks the name of the plugin (folder) a bit

my idea is, within the configuration, a "source" field where you can choose the current folder or a tag

**Comment by RafaelGB** [comment]
Starting this issue

**Comment by RafaelGB** [comment]
in addition to database filters, now you can choose the source (tag,outcoming links, incoming links...)

So this issue could be covered!

**Comment by RafaelGB** [comment]
<img width="627" alt="Screenshot 2022-05-30 at 19 25 12" src="https://user-images.githubusercontent.com/11924043/171038229-931af753-21c4-4d29-af2a-60c1ef1efa19.png">
<img width="627" alt="Screenshot 2022-05-30 at 19 25 39" src="https://user-images.githubusercontent.com/11924043/171038247-6a79d024-7e9b-4fe4-bae9-a92741174e13.png">

**Comment by RafaelGB** [comment]
@javiavid order the tags displayed? Sure! Please open another issue and will be added to the roadmap

**Comment by javiavid** [comment]
Ok
