### ISSUE TITLE
[Bug]: Creating a new note on the first click on a link after importing from CSV

### ISSUE THREAD

**Issue by pharolog** [RafaelGB/obsidian-db-folder#593]
### What happened?

A bug appears when testing "Wrong attributes order after import from CSV #551".

If a user imports a CSV file and first time (!) clicks on any link in column "File", then Obsidian creates the NEW empty note with the name: <existing note name> + "1". 

Use case.
1. Create the new Vault (locally or via Sync)
2. Install and enable the latest plugins "Dataview" and "DB folder".
<img width="641" alt="image" src="https://user-images.githubusercontent.com/116509453/201486207-ceb298ea-84c8-452e-919b-d751e271900c.png">

3. Create the new database with default parameters.
<img width="555" alt="image" src="https://user-images.githubusercontent.com/116509453/201486190-a69991b1-e703-441c-a5bd-6bf635a211f0.png">

4. Import the test CSV file (the same as in #551 ). Content of the CSV file:

File,C2,C3,C4
C1R1 File,C2R1,C3R1,C4R1
C1R2 File,C2R2,C3R2,C4R2

5. Click on any link in column "File" ( for example on "C1R1 File")
<img width="843" alt="image" src="https://user-images.githubusercontent.com/116509453/201486066-8423f654-bf89-49d0-8d12-a860bbf82bf8.png">

6. See the new empty note with the name C1R1 File **1**

<img width="612" alt="image" src="https://user-images.githubusercontent.com/116509453/201486096-5954bcbf-4bab-4e5f-b5c7-a0cea29b0b48.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/116509453/201486107-79d75a74-fd76-4d5d-836d-e533869d7432.png">

7. NB! It works only with the first click on any "File" Link in the DB. After the second click on a link in the column "File" all works without creating a new note).

### What platform were you using?

Desktop

### Version of the plugin

v2.8.3

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
I will test it, thanks! It seems to import the path of the file with a wrong name or is opened with that problem.

A quick refresh of the database ( go out the return) should fix it

**Comment by RafaelGB** [comment]
Commit 2f9ccf0f
