### ISSUE TITLE
[Bug]: I  am not able to select from the field "columns to group files by"

### ISSUE THREAD

**Issue by torstenkoepke** [RafaelGB/obsidian-db-folder#594]
### Contact Details

torstenkoepke@gmail.com

### What happened?

After setting up the complete table the above field ist empty. Clicking the empty space in the field also clicking the lens in the field does nothing.

Typing in the column name directly (without selecting from the expected dropdown-list, yields the below error in the dev. console

<img width="578" alt="CleanShot 2022-11-13 at 17 22 27" src="https://user-images.githubusercontent.com/49446717/201532454-00f714cd-1081-461e-9494-6d2c3da1cc78.png">

### What platform were you using?

Desktop

### Version of the plugin

2.8.3

### Relevant log output

```shell
plugin:dbfolder:122 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'columns')
    at OH.eval (plugin:dbfolder:122:20671)
    at Generator.next (<anonymous>)
    at i (plugin:dbfolder:1:417)
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
hello @torstenkoepke ,

Is your table empty? Looks like there is no columns to search. The list will display those with select type.

+ @ycnmhd as support

**Comment by torstenkoepke** [comment]
Ouch, I did not set the select type - thanks so much, it's now working (much better than I was hoping for!)
