### ISSUE TITLE
[Bug]: DB crushes when date format changed 

### ISSUE THREAD

**Issue by Gr-Nobel** [RafaelGB/obsidian-db-folder#595]
### What happened?

A bug happened!
I used this date format :Do MMMM YYYY (dddd)
the whole database crashed after picking a new date.

I also can't use the natural dates plugin inside of a text field property.

### What platform were you using?

Desktop

### Version of the plugin

latest

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
`Do MMMM YYYY (dddd)` seems to be a wrong format for date picker. Now we are controlling those errors with a default format instead.

The plugin is using Luxon date formats.

About natural dates plugin we don't have support for it. Maybe we need another issue to follow that support
