### ISSUE TITLE
[FR]: Combining property fields

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#598]
### Present your request

I have some fields I want to combine.
Date
Deadline

The idea is that if I change the Deadline ID to Date it will merge the properties.

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
could share an example?

A formula should do it I think

**Comment by DannyHatcher-Git** [comment]
The formula would be an output, I want to remove one property and replace it with another - merge.

https://user-images.githubusercontent.com/78496825/201663791-f849a565-22cd-4422-8b2d-392b5983e743.mp4
