### ISSUE TITLE
[FR]: Improve plugin icon to match the style of core icons

### ISSUE THREAD

**Issue by incyclum** [RafaelGB/obsidian-db-folder#599]
### Present your request

Hi!

Just noticed that the plugin icon doesn't match the style of the core Obsidian icons on the sidebar.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/7466095/201644496-cf999d70-ff9a-4ecb-9852-c6d2b6358b1c.png">

Could someone design-savvy improve the plugin icon to match the style of core icons?

Thanks in advance

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
Hi @incyclum ,

This is the current line of the SVG Icon https://github.com/RafaelGB/obsidian-db-folder/blob/66430e859c7bb5d009777236666b8a422dbf455a/src/helpers/Constants.ts#LL442C2-L442C2

I am not an expert designer. All help will be welcome =)

**Comment by RafaelGB** [comment]
New icon generated with AI!



![Image](https://user-images.githubusercontent.com/11924043/202316489-8df4ac5a-3b05-4ace-95a2-9ce6e7faf7ab.svg)





![Image](https://user-images.githubusercontent.com/11924043/202316541-264478a4-ea31-4baa-97b6-d02a2f219c1b.png)
