### ISSUE TITLE
The colors of the tags change every time I open the document

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#60]
**Describe the bug**
The colors of the tags change every time I open the document

**To Reproduce**
Create or select a tag
(It appears with a default color)
I close the database
I open the database

**Expected behavior**
I hope the colors are always the same

Screenshot

https://user-images.githubusercontent.com/7627504/169277948-61c18a19-84fb-4625-842c-735eaebfa80c.mp4

SYSTEM INFO:
	Obsidian version: v0.14.12
	Installer version: v0.14.5
	Operating system: Windows 10 Pro 10.0.22000
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 2
	Safe mode: off
	Plugins installed: 16
	Plugins enabled: 4
		1: Notion-Like Tables
		2: Obsidian42 - BRAT
		3: DB Folder
		4: Dataview

RECOMMENDATIONS:
	Custom theme: for cosmetic issues, please first try updating your theme to latest. If still not fixed, please try to make the issue happen in the help vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.

**Comment by RafaelGB** [comment]
Hi @javiavid ! Thanks for your suggestion. This is already a subtask here https://github.com/RafaelGB/obsidian-db-folder/issues/58

**Comment by RafaelGB** [comment]
This will be the column menu with selected type with the next version =) 
<img width="579" alt="Screenshot 2022-05-22 at 11 54 34" src="https://user-images.githubusercontent.com/11924043/169689962-20582191-8284-4dc7-ba15-58abcc06da22.png">

With a color picker
<img width="579" alt="Screenshot 2022-05-22 at 11 54 46" src="https://user-images.githubusercontent.com/11924043/169689966-b79f1e59-f5c0-45bd-b556-9b8e13a13d50.png">

**Comment by javiavid** [comment]
Brilliant!
It is very good to be able to choose the color for all the databases but I have a question:
Is it possible to create a tag with a random color as in the current version without having to go to the configuration?
I think it is very convenient to be able to create them from the database without entering the configuration.

**Comment by RafaelGB** [comment]
yes, the current feature of random color can continue to be used. The config is an alternative to add new labels or remove them

The actual problem is to reset the table after modify the config. when that problem is solved I generate the version =)

**Comment by javiavid** [comment]
Thank you Rafa!

**Comment by RafaelGB** [comment]
mark as finished. The app need a migration to another state strategy => https://github.com/RafaelGB/obsidian-db-folder/issues/37

but I found a provisional solution to reload database. Implied a minimal loading time, but do the job. This inconvenient will be improve with https://github.com/pmndrs/zustand

**Comment by RafaelGB** [comment]
@javiavid  1.3.0 out! enjoy the version with this change =)

This issue will be reopen if its necessary

**Comment by javiavid** [comment]
Thanks for the update, you're doing a great plugin.
Now the persistent colors work fine, but there is an error, the "tags" are duplicated when creating them in the menu.

https://user-images.githubusercontent.com/7627504/169861222-d071ae5b-2969-45cf-9a97-7903176e056b.mp4

**Comment by javiavid** [comment]
Ok, I delete it from the configuration

**Comment by RafaelGB** [comment]
new issue opened https://github.com/RafaelGB/obsidian-db-folder/issues/64

**Comment by RafaelGB** [comment]
Hopefully fixed with 1.3.1. Let me know

**Comment by javiavid** [comment]
Solved! 👏
