### ISSUE TITLE
[FR]: Date Range Filters

### ISSUE THREAD

**Issue by Stilts15ak** [RafaelGB/obsidian-db-folder#604]
### Contact Details

Stilts15ak@gmail.com

### Present your request

It would be nice when filtering for dates if hard coded ranges could be implemented. (i.e. "Yesterday", "Today", "Tomorrow", "(#) Days", "This Week", "Next Week", "This Month", "Next Month", "This Year", "Future")

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
Hello @Stilts15ak,
Generate custom filters in function of the tupe could be interesting.

There are two ways. 
- A search per column (just like the global search with custom inputs)
- Inside the filters

I think the first one is more interesting and easier to maintain.

**Comment by Stilts15ak** [comment]
Could this also be achievable (in the short term) with using a formula and using relative dates (i.e. "Today", "This Week", etc.)?

**Comment by RafaelGB** [comment]
You can already use Luxon formulas

https://rafaelgb.github.io/obsidian-db-folder/features/Formulas/

<img width="755" alt="Screenshot 2022-11-17 at 15 46 16" src="https://user-images.githubusercontent.com/11924043/202477261-d80a8f67-fd6d-40f3-9e2b-4b297496eef3.png">


https://moment.github.io/luxon/api-docs/index.html#datetimetorelative

```
${row.column1. toRelativeCalendar()}
```

**Comment by Stilts15ak** [comment]
Thanks! I'll play around with it.

**Comment by RafaelGB** [comment]
Also I saw a problem with the formula. It should be refreshed after any change of the row.

Will be fixed with the next version =) Commit b331dbd4

**Comment by Stilts15ak** [comment]
Yup! That's what I'm getting.

I think this is a nice solution. Whether it's short or long term.

However, it looks like DB will not filter a formula column.

**Comment by RafaelGB** [comment]
to allow the filters you need to persist the value (a toggle inside the column config)

**Comment by Stilts15ak** [comment]
Not sure I understand. Can you elaborate further?

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/202490635-5d1f351f-664a-4847-8f2e-1126273770ca.mov

**Comment by Stilts15ak** [comment]
Thank you! Works like a charm now.

Can I make a suggestion to where it says "Only persisted formulas could be searchable and sortable" to add "and filtered" as well?  And perhaps include this in the documentation too?

**Comment by RafaelGB** [comment]
We can improve the documentation, of course.

It's a young plugin and the changes are constant. So the documentation is hardly to maintain

**Comment by javiavid** [comment]
In the video example, Is it possible to use with the Created column (date from file created)?

**Comment by RafaelGB** [comment]
Yeah, it is possible

**Comment by javiavid** [comment]
It appears empty

![image](https://user-images.githubusercontent.com/7627504/207386538-871070e1-9081-4ed6-9e76-6b73ab32c1fb.png)

![image](https://user-images.githubusercontent.com/7627504/207386646-77f7dfb8-a423-4287-b31b-a1d79c0f55de.png)

**Comment by RafaelGB** [comment]
All metadata fields need `__<id>__` wrapping

Try with ${row.__created__.toRelativeCalendar()}

**Comment by javiavid** [comment]
Now it works, thanks Rafa!

**Comment by RafaelGB** [comment]
a new feature for calendar/calendar time will be added for the next version

If you add an `@` to some words like `today` or `next week`will be applied to your filter in function of the actual date

```javascript
import { DateTime } from "luxon";
const valueToCalendarConverter = new Map<string, DateTime>([
    ["today", DateTime.local().startOf("day")],
    ["yesterday", DateTime.local().minus({ days: 1 }).startOf("day")],
    ["tomorrow", DateTime.local().plus({ days: 1 }).startOf("day")],
    ["thisweek", DateTime.local().startOf("week")],
    ["lastweek", DateTime.local().minus({ weeks: 1 }).startOf("week")],
    ["nextweek", DateTime.local().plus({ weeks: 1 }).startOf("week")],
    ["thismonth", DateTime.local().startOf("month")],
    ["lastmonth", DateTime.local().minus({ months: 1 }).startOf("month")],
    ["nextmonth", DateTime.local().plus({ months: 1 }).startOf("month")],
    ["thisyear", DateTime.local().startOf("year")],
    ["lastyear", DateTime.local().minus({ years: 1 }).startOf("year")],
    ["nextyear", DateTime.local().plus({ years: 1 }).startOf("year")],
    ["thisquarter", DateTime.local().startOf("quarter")],
    ["lastquarter", DateTime.local().minus({ quarters: 1 }).startOf("quarter")],
    ["nextquarter", DateTime.local().plus({ quarters: 1 }).startOf("quarter")],
]);

export default class FilterValuesMapper {
    public static toCalendarValue(filterValue: string): DateTime {
        if (filterValue.startsWith("@")) {
            const potentialDate = valueToCalendarConverter.get(filterValue.slice(1).toLowerCase());
            return potentialDate ? potentialDate : DateTime.local();
        }

        const potentialDate = DateTime.fromISO(filterValue);
        return potentialDate.isValid ? potentialDate : DateTime.local();
    }
}
```
