### ISSUE TITLE
[FR] Self referencing relation

### ISSUE THREAD

**Issue by Calorion** [RafaelGB/obsidian-db-folder#605]
### Contact Details

Calion@mac.com

### Present your request

I would like DB Folder to support self-referencing, so that you can reference another column in the same table. 

### For which platform do you request this request??

Mobile

**Comment by RafaelGB** [comment]
hello @Calorion, Do you mean with relations?

**Comment by Calorion** [comment]
Yes, sorry.

**Comment by RafaelGB** [comment]
Could you share an example? a self relation maybe has more sense with a formula

**Comment by rshaw5** [comment]
👍 I would also like to see this. 

My example is a database of `people`. This database might have relationships like `parent/child`, `employer/employee`, or `friend/friend`. These relationships only make sense if I can relate a person to another person in the same database.

**Comment by RafaelGB** [comment]
The self relations will be available with the next version but there is a limitation...

The plugin currently can not refresh the associated rollups of those self relations, you have to do it manually. I will work to find a way but seems tricky

**Comment by RafaelGB** [comment]
Commit e80d58c7

**Comment by RafaelGB** [comment]
I found a way to refresh it related with https://github.com/RafaelGB/obsidian-db-folder/issues/482

Could be a performance problem so I was thinking about a toggle function

**Comment by therden** [comment]
Very glad to see that @RafaelGB has reconsidered supporting this feature since [this discussion](https://github.com/RafaelGB/obsidian-db-folder/discussions/576) last month! :+1:

**Comment by RafaelGB** [comment]
thanks to you and your suggestions! I just found a way to achieve it since 3.0.0
