### ISSUE TITLE
vault root folder without subfolders, e.g. to exclude daily notes

### ISSUE THREAD

**Issue by torstenkoepke** [RafaelGB/obsidian-db-folder#606]
### Contact Details

torstenkoepke@gmail.com

### Present your request

I saw the update with "New db source, current folder without subfolders". 

Unfortunately this seems to be working only in subfolders, but not the the root vault folder.   I am trying to **hide the daily notes** from the table, which I have in a separate folder. 

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
Maybe the filter is not working correctly with the root:

```typsecript
case SourceDataTypes.CURRENT_FOLDER_WITHOUT_SUBFOLDERS:
      pagesResult = DataviewService.getDataviewAPI().pages(`"${folderPath}"`)
        .where(p => (p.file as any).folder === folderPath);
      break;
    default:
```

You can always use the dataview query source to only filter the daily notes subfolder. This sourceType will filter ALL the subfolders

I will improve the option to allow the root too. Thanks for your report @torstenkoepke

**Comment by RafaelGB** [comment]
```typescript
case SourceDataTypes.CURRENT_FOLDER_WITHOUT_SUBFOLDERS:
      if (!folderPath || folderPath === '/') {
        pagesResult = DataviewService.getDataviewAPI().pages()
          .where(p => !(p.file as any).folder);
      } else {
        pagesResult = DataviewService.getDataviewAPI().pages(`"${folderPath}"`)
          .where(p => (p.file as any).folder === folderPath);
      }
      break;
```

**Comment by RafaelGB** [comment]
Commit 415fdfcb

**Comment by torstenkoepke** [comment]
Thanks!
