### ISSUE TITLE
BUG - Accessor, key and label needs to be edited without the UI and YAML in existing files shifts around?

### ISSUE THREAD

**Issue by spiritualgeek** [RafaelGB/obsidian-db-folder#61]
**Describe the bug**
2 Issues

1. The accessor, key and label is not configurable via the UI. I had to edit the file manually
2. The YAML in my file which I configured as keys/accessors  is suddenly placed at the top of the file when making an edit?
- The position should not move
3. My tags which were neatly 1 per line are suddenly comma delimited on a single line when making an edit?

**To Reproduce**
Tried it - See above

**Expected behaviour**
See above 

**Screenshots**
Not Applicable

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Obsidian: 0.14.12
 - Dataview: 0.5.20

**Smartphone (please complete the following information):**
Not Applicable

**Additional context**
None

**Comment by RafaelGB** [comment]
Hi @spiritualgeek
About first point. If you click in the header of the column, a menu will be displayed where you can edit the label. If some of the rows had that key, will be modified with the new trimmed  label. (my new label => mynewlabel)

<img width="206" alt="Screenshot 2022-05-22 at 14 28 15" src="https://user-images.githubusercontent.com/11924043/169695134-960b2391-ab5c-46c2-b882-fafb84f0897f.png">

second point. Yes, the edit engine add the column fields at the top of your front matter in order, then adds the rest. It was a design decision of performance to just write once in your file.

third point. I don't understand well the use case. Could you give me an example?

yourfield: #tag1 
                  #tag2
after edit are:
yourfield: #tag1 #tag2
?

**Comment by spiritualgeek** [comment]
1. I did that, and it did not work that is why I resorted to editing the file
2. This makes it frustrating when you want to use it on-top of existing notes where each attribute has its proper position (OCD perhaps, but it's somewhat irritating)
3. My tags are supposed to look like:
```
tags:
- 🧰
- person/me
- topic/util
- subtopic
- state/open
- activity/sorting
```
Post your tool it's `tags: 📞,person/me,topic/contact,subtopic,state/done,activity/done`

Great plugin with a lot of potential!

One last thing - The table has far too much white space (and I'm using 3 4K monitors)

Thanks for the quick response

**Comment by RafaelGB** [comment]
oh I see, currently yaml list are not supported. Will be added as a bug. Thanks for your testing.

The label editing maybe is affected about the list. I will report the advance here :)

**Comment by RafaelGB** [comment]
about the position of the frontmatter, I am afraid its not possible to readapt at the position, maybe add the not column fields first an then them. That could fix your issue?

**Comment by spiritualgeek** [comment]
- I'm uncertain if the label editing is related, as I created the "DB" first and then copied a few notes for testing into the same directory afterwards
    - If you think about it an attribute may be called `spendamount: $100` but in the table you simply want the label to be `Amount`- I could not see how you specify the attribute separate from the title? 
- On the positioning. I don't think it's too much of a big deal, but users will generally have their alias and tags at the beginning. I put my attributes (that a specific to a type of note) further down and always end off with an `update:` attribute that can contain a few lines of text.

Looking forward to this plugin appear in the gallery :)

**Comment by spiritualgeek** [comment]
This plugin updates the attributes in place if you want to look at it. It also does not touch any other attribute - https://github.com/beaussan/update-time-on-edit-obsidian

I see the update still has issues with putting a list on one line?

Have not played with the updated version extensively yet

**Comment by RafaelGB** [comment]
```typescript
export const parseFrontmatterFieldsToString = (databaseFields: RowDatabaseFields, deletedColumn?: string): string => {
    const frontmatterFields = databaseFields.frontmatter;
    const array: string[] = [];
    array.push(`---`);
    Object.keys(frontmatterFields).forEach(key => {
        if (key !== deletedColumn) {
            array.push(...parseLiteralToString(frontmatterFields[key], 0, key));
        }
    });
    array.push(`---`);
    return array.join('\n');
}

function parseLiteralToString(literal: Literal, level: number, key?: string): string[] {
    const literalBlock: string[] = [];
    literal = DataviewService.parseDataArray(literal);
    if (DataviewService.getDataviewAPI().value.isArray(literal)) {
        literalBlock.push(`${" ".repeat(level)}${key}:`);
        literal.forEach((literal, index) => {
            literalBlock.push(...parseLiteralToString(literal, level + 1));
        });
    }
    else if (key) {
        literalBlock.push(`${" ".repeat(level)}${key}: ${literal}`);
    } else {
        literalBlock.push(`${" ".repeat(level)}- ${literal}`);
    }
    return literalBlock;
}
```

**Comment by RafaelGB** [comment]
1.3.2 is out! please, let me know if you have any trouble
