### ISSUE TITLE
[FR]: Link Alias for Select Type Column

### ISSUE THREAD

**Issue by zcysxy** [RafaelGB/obsidian-db-folder#613]
### Present your request

Hi, I have a column/field to track `status` whose property type is **select** and its values are **links** instead of plain text. So it would be great if the Link Alias feature is also supported for select type columns. I can think of some other use cases, such as **select** a project note for a sub note.

<img width="262" alt="image" src="https://user-images.githubusercontent.com/48207708/202832708-9349cd0b-7453-4def-b2dd-697cd8d4e901.png">

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
Hi @zcysxy ,
to render a link we need to run Obsidian Markdown and the select component does not allow it.

Its a performance decision

I am sure it's possible but it requires to refactor all the select component (same of tags)

**Comment by advaitathreya** [comment]
If rendering links would be intensive, would it be possible to define a display alias for select options so that the linking structures are preserved in the notes but in the DB folder table we don't see the entire link text as so [[PATH|NAME]]? I imagine this could be an extra option in the labels list alongside the colors

**Comment by RafaelGB** [comment]
I think the performance will be cool.

The idea its to include an useEffect for the option component just like here

https://github.com/RafaelGB/obsidian-db-folder/blob/8fd0f60055ec112b6a2659d6fb2c9657d887444c/src/components/cellTypes/MarkdownCell.tsx#L20

But a problem could be the dropdown selector, I don't know if we can display the markdown there.

Once we start this issue we will see

**Comment by RafaelGB** [comment]
Commit 2ef9beee =)

Will be added with the next version, but there is no link helper menu
