### ISSUE TITLE
delete row and file

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#62]
**Is your feature request related to a problem? Please describe.**
I can't delete the rows from the database

**Describe the solution you'd like**
delete the row by an option provided in the row right click menu 

**Describe alternatives you've considered**
delete the file 

**Additional context**
Example from [AGtable plugin
](https://github.com/windily-cloud/obsidian-AGtable)

![image](https://user-images.githubusercontent.com/38974541/169865144-03047387-d941-4f41-b61e-fff9732efa18.png)

**Comment by RafaelGB** [comment]
Hello @imeed166 this is not a feature of this plugin yet. Row actions could be a future functionality but not in a sort them. I will add this to the roadmap.


thank you for your suggestion

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/55

row button mentioned here too

**Comment by RafaelGB** [comment]
first steps with this issue. A hovering event of the row to show a future menu component

https://user-images.githubusercontent.com/11924043/185679730-94d2f3f1-bb6b-424d-bf43-5d8c0f49c863.mov

So it will be shown just when the user put the mouse inside the row

**Comment by RafaelGB** [comment]
Working on visual improvements, but the base is done

https://user-images.githubusercontent.com/11924043/185795433-fa50eb9e-d87c-4dde-81aa-78b013ca84c1.mov
