### ISSUE TITLE
[Bug]: Sorting is broken since 2.9.1

### ISSUE THREAD

**Issue by OmniNaut** [RafaelGB/obsidian-db-folder#620]
### What happened?

Unfortunately sorting of columns is broken since 2.9.1, applies for ascending and descending, removing and applying sorting has no effect.

### What platform were you using?

Desktop

### Version of the plugin

2.9.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
a misunderstanding with how isNaN works

Commit 3bd2ca93
