### ISSUE TITLE
Add package-lock.json or yarn.lock to version control for reproducible builds

### ISSUE THREAD

**Issue by swar8080** [RafaelGB/obsidian-db-folder#621]
Hello, i'm looking for ways to help make plugins more secure. One way is through [Reproducible Builds](https://reproducible-builds.org/), which could detect a plugin version with a malicious `main.js` file that wasn't actually built from the source code

A `package-lock.json` or `yarn.lock` is needed though to build a `main.js` from source that's identical to the one obsidian downloads when installing the plugin. In general, any way you could make the build process easy to reproduce would help, like by removing steps that only work on your local development environment

**Comment by RafaelGB** [comment]
I currently create a package.lock.json but is but it is contemplated in the gitignore
