### ISSUE TITLE
[Bug]: selecting or deleting a "select type" value ads extra "" and breaks the list.

### ISSUE THREAD

**Issue by cesarpereira904** [RafaelGB/obsidian-db-folder#622]
### Contact Details

cesarpereira904@gmail.com

### What happened?

When removing a "select field type" value:

<img width="327" alt="1" src="https://user-images.githubusercontent.com/70922426/203547720-b16bfde0-52a8-4c0c-9c1f-ff73534ae036.png">

its ads "" :

<img width="338" alt="2" src="https://user-images.githubusercontent.com/70922426/203547872-f3b26c32-634f-4593-98ae-d984a211814d.png">

In the Markdown looks like:

<img width="667" alt="4" src="https://user-images.githubusercontent.com/70922426/203547927-98a04b0c-f290-4b91-8c14-37208734983e.png">

after this, an error accour :

<img width="224" alt="3" src="https://user-images.githubusercontent.com/70922426/203548090-d8720c24-2b6d-47aa-b65b-eaab20ce5325.png">

This also happens when trying to select a value:

<img width="326" alt="5" src="https://user-images.githubusercontent.com/70922426/203548424-7a080cb5-e284-4a2a-bc9f-95d0061fe6c7.png">

<img width="327" alt="6" src="https://user-images.githubusercontent.com/70922426/203548472-b21787a2-c96c-4a66-9b3d-55e6036f0413.png">

### What platform were you using?

Desktop

### Version of the plugin

2.9.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
I will generate a hot fix with this and the sorting
