### ISSUE TITLE
[FR]: Be compatible with faststart startup script

### ISSUE THREAD

**Issue by hustrjh** [RafaelGB/obsidian-db-folder#629]
## Faststart startup script
It's a customizable template which could be run by **`templater`** plugin. I use it as startup template to accelerate the startup speed. As you know there are so many plugins to be loaded which may impact the startup speed a lot. The template will delay the startup time of some plugins and accelerate the startup speed. It's really useful. Here's the template below.
![image](https://user-images.githubusercontent.com/69783980/203712476-8c3c3be3-3626-4473-bd8c-33032854ece2.png)

## My problem
I also delay the startup time of **`dataview`** plugin. So I encounter such problem that **`DBfolder`** can not detect **`dataview`** after I enable it.
![image](https://user-images.githubusercontent.com/69783980/203709894-04ecd7ae-18da-4e91-a02a-1d175e4719aa.png)

## My wish
I'm aware of that I can remove **`dataview`** from delay startup list. But I still hope that **`DBfolder`** could help me so I don't need to slow down startup speed. Thank you anyway for your effort! :+1: 

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
Hello @hustrjh ,

I want to help you with this issue but I still don't know how to be compatible with your script.

Do I need to wait until dataview plugin is enabled or the plugin requires any extra logic?

**Comment by hustrjh** [comment]
Hi @RafaelGB , thank you for your quick reply.
I guess the reason results in such problem is that I haven't enabled **`dataview`** plugin which means it hasn't been written in the `core-plugins.json` file. I guess `core-plugins.json` file is where **`DBfolder`** detects whether **`dataview`** is enabled or not.
But startup script can enable the plugin via JS method without help of Obsidian. So I needn't enable **`dataview`**. On the other hand, if **`dataview`** is enabled by default which means it is written in the `core-plugins.json` file, Obsidian will enable it automatically and impact the startup speed. The startup script will be useless.
## My suggestion
I think the easiest way to solve the problem is removing the detecting action or offer an option to avoid detecting whether **`dataview`** is enabled.

**Comment by RafaelGB** [comment]
I must not remove the detection (Its necessary for the plugin)

Instead we can wait async until its enabled but the db notes will be opened as markdown, which it's confusing.


Could you improve the script itself to load dbfolder after dataview?

**Comment by hustrjh** [comment]
Maybe I haven't make it clear. The truth is that **`Dataview`** has been enabled by startup script before I enable **`DBfolder`**. Actually I have tested that by enabling **`DBfolder`** manually after **`Dataview`** enables. However **`DBfolder`** couldn't detected **`Dataview`** which is working normally right now.

I don't mean that it's **`DBfolder`** 's problem. I hope to find some method to fix the problem. So the problem is that the detection is not correct as **`Dataview`** is actually working. So is there any method to detect correctly?

Also if it still seems wired to you and it's not worthy wasting time, I'm grateful for your kindness and patience anyway. Maybe I should remove **`Dataview`** from the delay startup list. ❤️

**Comment by RafaelGB** [comment]
The way dbfolder check if dv is enabled is:

```typescript
app.plugins.enabledPlugins.has("dataview")
```

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/blob/1113911601d98b2f0a94b64ac1b3b5fb1953147e/src/services/DataviewService.ts#L12

**Comment by hustrjh** [comment]
I got it. The reason is that **`dataview`** returns incorrect status. From my opinion it's probably no relation with async method or the order to load as I'm sure that **`dataview`** has been enabled before DBfolder enables. Thanks a lot for your help. Sorry to waste your time. What a nice plugin! 👍

**Comment by RafaelGB** [comment]
Happy to help!
