### ISSUE TITLE
[BUG] don't move column after last column

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#63]
**Is your feature request related to a problem? Please describe.**
I shouldn't be able to move the column after the last "add column"

**Describe the solution you'd like**
remove this functionality

**Additional context**

https://user-images.githubusercontent.com/38974541/169866062-1efaf2c5-6823-4105-89e3-d63e8bfd26ec.mov

**Comment by RafaelGB** [comment]
Its a known problem, the header dnd needs a refactor to change it. Will be added to the backlog =)

**Comment by OriOYue** [comment]
Why is this when I move the columns?
![image](https://user-images.githubusercontent.com/72482686/170018196-ffe579bf-f257-4c1b-8927-2016fe83d727.png)

**Comment by OriOYue** [comment]
> Why is this when I move the columns? ![image](https://user-images.githubusercontent.com/72482686/170018196-ffe579bf-f257-4c1b-8927-2016fe83d727.png)

Environment:
a whole new vault, plugin version: 1.3.1

**Comment by RafaelGB** [comment]
hi @OriOYue , its a visual known problem. the react-table has fixed configuration and the map of dnd position is moved, but there is no functional consequence

**Comment by RafaelGB** [comment]
1.6.3 is out with a huge battery of fixes
