### ISSUE TITLE
[Bug]: editing inline field (that is inside a callout) not working

### ISSUE THREAD

**Issue by Rhydderch** [RafaelGB/obsidian-db-folder#632]
### What happened?

It seems that something changed the behavior of inline fields.
It was working well but now editing an inline field that is inside a callout from the DB creates a new field in the note.

Reading an inline field that is inside a callout still works perfectly.
<img width="372" alt="image" src="https://user-images.githubusercontent.com/3197629/204132065-55fe2e7b-8811-4d43-9e1c-b18373b68146.png">

Updating it, does not:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/3197629/204132080-2b39a110-bacf-490d-b418-6edd9409c9c4.png">
results in
<img width="306" alt="image" src="https://user-images.githubusercontent.com/3197629/204132086-193b58cf-047b-48a2-b2af-c1e86cb51d82.png">

### What platform were you using?

Desktop

### Version of the plugin

2.9.2

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
yeah, its still on the roadmap

https://github.com/RafaelGB/obsidian-db-folder/issues/556
