### ISSUE TITLE
[FR]: Metadata Menu support

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#634]
### Contact Details

sarah.arminta@me.com

### Present your request

Collab with Metadata Menu to use for suggestions for fields with multiple select options. 

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
yeah, if the plugin has API could be great :)

**Comment by arminta7** [comment]
https://mdelobelle.github.io/metadatamenu/api/

**Comment by RafaelGB** [comment]
cool!

**Comment by chauser10** [comment]
+1 for this!

**Comment by profucius** [comment]
+1 for this too

**Comment by RafaelGB** [comment]
As a first point for this issue I will create a formula option to generate your own column options



![Image](https://user-images.githubusercontent.com/11924043/217346664-70c5e929-05d9-4885-8ff9-6b5654bebf6d.png)

You can use your own scripts, including Metadata API

**Comment by RafaelGB** [comment]
I have to generate the documentation, but with 3.3.1 its available to create formulas using any kind of API to generate your own options:

```javascript
{
   "label": "label of your option",
   "value": "value saved on file",
   "color": "color of your option (HSL, RGB or label like red)"
}
```

**Comment by RafaelGB** [comment]
An example of use for options columns. I will add new functions for formulas such as generate coolers for the next version:


https://user-images.githubusercontent.com/11924043/219962501-069d3838-30c4-4344-be6a-7ebc22e90935.mov

```javascript
/**
 * Generate a list of options in function of the tags of Obsidian
 */
function tagsAsOptions(db) {
    options = [];
    tagArray = app.metadataCache.getTags(); // Record<string, number>
    Object.keys(tagArray).forEach(tag => {
        options.push({
            value: tag,
            label: tag.slice(1),
            color: db.colors.randomColor()
        })
    });
    return options;
}

module.exports = tagsAsOptions
```
