### ISSUE TITLE
Footer per type

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/obsidian-db-folder#637]
Generate a footer (with an enable/disable option per table) where you can see some column info

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/204871647-e6ab1bbb-77fc-4573-8ef9-c07f9e60c46c.mov

**Comment by nysander** [comment]
will it support only total or counting all / not empty / empty etc. also?

**Comment by RafaelGB** [comment]
currently an experimental feature, with the time we can support multiple scenarios for sure

**Comment by nysander** [comment]
I've found obsidian + your plugin 2 days ago and you've made great job to "convert" notion db users like me to obsidian. Thank you

There is only one feature besides of above I miss now - automatic reverse relations ;)

**Comment by RafaelGB** [comment]
bidirectional relation is currently in the roadmap but could be a little bit tricky:
- add a new relation on the other table (easy)
- remove the relation if one of them are deleted (medium)
- add a new relation on both cells (hard)
- delete both relations if one of them is deleted (...)
