### ISSUE TITLE
saving filters

### ISSUE THREAD

**Issue by zeltak** [RafaelGB/obsidian-db-folder#639]
### Contact Details

zeltak@gmail.com

### Present your request

Hi Iooked into the documentation but failed to see some info on it so apologize in advance if this is covered somewhere

can one save a filter that will be available between sessions? currently if I apply an advance filter and restart obsidian it seems it isn't saved anywhere

best

Z

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
Hello @zeltak ,
The filters are currently saved here

https://user-images.githubusercontent.com/11924043/205238614-408cacc8-0fc7-4d1e-872c-34f93a19d6da.mov

Are you using the filters modal?

https://user-images.githubusercontent.com/11924043/205238890-250dcb99-da41-49ae-a830-cc95cc3ec7e0.mov

**Comment by zeltak** [comment]
ahh I see I needed to create a group , ok that's really helpful thx!!!

Z
