### ISSUE TITLE
[Bug]: The new add row button opens my import

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#641]
### What happened?

A bug happened!

When I click the add row button it takes me to my document import option rather than adding a row to the database

### What platform were you using?

Desktop

### Version of the plugin

3.0.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Its a problem with the tooltrip info

<img width="126" alt="naming problem" src="https://user-images.githubusercontent.com/11924043/205289226-9649ef1d-9bc4-4754-9376-2c114610dbc7.PNG">
