### ISSUE TITLE
"Dataview plugin not loaded" message

### ISSUE THREAD

**Issue by GitDAS** [RafaelGB/obsidian-db-folder#642]
With the latest version of DB Folder (12/1/22), the message "Dataview plugin not loaded yet. Please wait a few seconds and refresh the page." is spammed repeatedly on any table action.

![image](https://user-images.githubusercontent.com/34261172/205306613-56cba16a-8b35-4fd7-bea9-45ca9a18a7cd.png)

The Dataview plugin is loaded and queries are confirmed to be working in other files.

**Comment by RafaelGB** [comment]
Hello @GitDAS , This spam its already controlled and will be fixed with a minor version. To fix with the current one just restart Obsidian (its an startup control)

**Comment by DannyHatcher-Git** [comment]
Would this impact startup time of vaults as well?

Since the update my "loading cache" message has been taking a long time.

**Comment by RafaelGB** [comment]
@DannyHatcher-Git please restart your Obsidian after the update. This will be fixed with the next version as soon as possible (currently I am travelling)

The message is resolved just on startup

**Comment by DannyHatcher-Git** [comment]
I wish you well on your travels!

This bug is slowing down my vault considerably (I think) as it send that error message for each note I try and query in each table - which is a lot!

**Comment by RafaelGB** [comment]
Sorry for the inconvenience, the message should only come up once after relaunch the Obsidian app.  I will release a hotfix on wednesday

**Comment by DannyHatcher-Git** [comment]
Ok, I am fine in smaller vaults so it might just be that startup message taking that long... I will see whne the hotfix is released.

**Comment by DannyHatcher-Git** [comment]
Thank you.

I know get the error message every time I open a database
![image](https://user-images.githubusercontent.com/78496825/206445415-bb129c0a-3aa5-4b84-934f-9dc51785bb4c.png)

**Comment by RafaelGB** [comment]
I can only check that the index has been loaded during Obsidian boot. I will continue to improve this check to avoid the user having to restart the application with each update

**Comment by batman47steam** [comment]
Hi Rafael , after update , every time I open obsidian will get this messages . by didn't get these messages when I create a new database
by the way, thanks for developing this great add-on
![image](https://user-images.githubusercontent.com/36287035/206863031-75de336b-2e65-429a-b6f6-0cdba18644f0.png)
