### ISSUE TITLE
[FR]: Show filter bar as default option

### ISSUE THREAD

**Issue by freyart** [RafaelGB/obsidian-db-folder#643]
### What happened?

Since version 3.0.0 the navbar containing my database filters is hidden and I can't find any way or option to make it visible.

I had to create a CSS snippet for force it back.

.database-plugin__navbar { display: block !important; }

### What platform were you using?

Desktop

### Version of the plugin

3.0.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
ctrl+F or the magnificent glass button to show/hide it 😄

**Comment by freyart** [comment]
Thank you!
My mistake then. I didn't realise they were under the search option.

**Comment by RafaelGB** [comment]
with the new design its hidden by default , but we can include your snippet as a toggle configuration. I dont know if some users prefer to display it always

**Comment by freyart** [comment]
I think a toggle in the plugin's configuration would be appreciated and justified, 
My use of the plugin is based on the filters and I'm probably not the only one.

**Comment by RafaelGB** [comment]
I will include it as a global setting with the next version =)

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/206259548-0ed846ca-7e33-4861-b9d8-7ebf987a5099.mov

**Comment by RafaelGB** [comment]
Commit 0298aa9b

**Comment by freyart** [comment]
Perfect ! 
Thank you !
