### ISSUE TITLE
[FR] top bar icon for sorting

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#65]
**Is your feature request related to a problem? Please describe.**
I can't know by which column the table is sorted

**Describe the solution you'd like**
visual help in the top bar to know by which column the table is sorted and in which direction

**Additional context**
Example from [database plugin](https://github.com/tomaszkiewicz/obsidian-database-plugin)

https://user-images.githubusercontent.com/38974541/169867595-ce384a66-ba56-40fb-b869-3b9c0e6fcbd0.mov

**Comment by RafaelGB** [comment]
could be a good aggregation =) thanks for your idea

**Comment by imeed166** [comment]
Awesome, looking forward to it.

**Comment by imeed166** [comment]
Upon seeing the video, I can't help but notice the "viewed" column with a checkbox property, this type of property is not yet available right ? (sorry curiosity got the better of me)

**Comment by RafaelGB** [comment]
Yeah Its a little spoiler =P. Not the final design

**Comment by imeed166** [comment]
haha, good one.

**Comment by RafaelGB** [comment]
Was an easy upgrade after https://github.com/RafaelGB/obsidian-db-folder/issues/54, witch ve the architecture already
