### ISSUE TITLE
[Bug]: Last row can't be edited

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#652]
### What happened?

When the `filter bar` is enabled, you can't select the cells of the last row and you can't edit them.

https://user-images.githubusercontent.com/38974541/206567584-a9881e77-eb2b-454d-9c76-cacc98de824a.mov

### What platform were you using?

Desktop

### Version of the plugin

3.0.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Oh I didn’t notice it, thanks!
