### ISSUE TITLE
[Bug]: footer option for first and last column

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#653]
### What happened?

You can enable footer options for the first column (the number column) and the last column (add property column). The user shouldn't have the option to add a footer in these columns.

https://user-images.githubusercontent.com/38974541/206567221-e629f8e3-ba22-4d7f-9356-95c209091c1a.mov

### What platform were you using?

Desktop

### Version of the plugin

3.0.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
this is already fixed for the next version (I am experimenting with footer yet)
