### ISSUE TITLE
[Bug]: Column bar not persisted when scrolling

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#655]
### What happened?

The `show filter` icon (above the number column) is not persisted when scrolling horizontally.
When enabling `sticky first column` the file column header is not persisted when scrolling vertically.

https://user-images.githubusercontent.com/38974541/206565446-2f923e6f-219d-4436-9fc0-110f65120128.mov

### What platform were you using?

Desktop

### Version of the plugin

3.0.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
yeah I noticed it, Its a css z-index deep property. Will be fixes with the next version

**Comment by RafaelGB** [comment]
Commit cb01d346
