### ISSUE TITLE
[FR]: dark theme support of selector for select and multi-select

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#656]
### Present your request

In dark mode, when using the `select` or `tag` property, and selecting the cell, a white selector appears. 

To make it feel more native to the database look, make it the same color of the cell (just lik in light theme, it's white) make it dark when the dark theme is enabled.

https://user-images.githubusercontent.com/38974541/206568379-d32b420a-8190-4f9d-8174-9bf559c6eb50.mov

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
Could be an easy change , sure :)

**Comment by RafaelGB** [comment]
Commit ac96f56e
