### ISSUE TITLE
[FR]: dark theme support for date and time

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#657]
### Present your request

When selecting a cell of the properties `time` or `date` the modal that appears is white, change the color to black to match the dark theme.

https://user-images.githubusercontent.com/38974541/206569080-63a0aea4-1756-44ca-a59c-05f1dd2696df.mov

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
sure!

**Comment by RafaelGB** [comment]
I checked it and its already supported, dunno if you have some snippet

![Image](https://user-images.githubusercontent.com/11924043/206692112-ed99b2f1-9b11-4280-a65b-f606bb919992.png)

**Comment by imeed166** [comment]
It was [notion-like table plugin](obsidian://show-plugin?id=notion-like-tables) that caused this issue.
