### ISSUE TITLE
[FR]: Filename filter

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#659]
### Present your request

Can you add the option to filter by filename?

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
The metadata filters is a pending task. You can already search metadata info with global and particular search input, but they are not included on filters yet cause its not a direct value. With dv queries you can already filter by name, in/outlinks...

I will check how to do it from the plugin in the future for sure

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/211151243-c22ee8ee-0d9e-4ec8-b7eb-6a14f381bfe3.mov
