### ISSUE TITLE
[FR] sort by multiple columns

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#66]
**Is your feature request related to a problem? Please describe.**
I can only sort by one column at a time

**Describe the solution you'd like**
2 possible solutions :
1. either retain the first sort and add the second sort (just like in the video below)
2. add settings next to filtering to define multiple columns to sort by

**Additional context**
Example from [database plugin](https://github.com/tomaszkiewicz/obsidian-database-plugin)

https://user-images.githubusercontent.com/38974541/169868520-3cfb30ab-b967-46dd-a598-0137cecf3f81.mov

**Comment by RafaelGB** [comment]
sure =)
