### ISSUE TITLE
[Bug]: An error occurred while loading Obsidian. TypeError: cannot read properties of null (reading 'path')

### ISSUE THREAD

**Issue by batman47steam** [RafaelGB/obsidian-db-folder#660]
### Contact Details

batman47steam@outlook.com

### What happened?

A bug happened! when I enabled dbfloder and then restarted obsidian. It says that `An error occurred while loading Obsidian. TypeError: Cannot read properties of null (reading 'path')`, and if I entered in safe mode, and them enable plugins, dbfloder seems work fine. but every time I open obsidian I got the same error, and must reload with safe mode, then enable these plugins again.
![image](https://user-images.githubusercontent.com/36287035/206939719-22898ee3-7a7f-41d7-a82c-3599409cda7f.png)
![image](https://user-images.githubusercontent.com/36287035/206939729-47f80f83-bec6-476a-b538-49e4f1e6ad30.png)

### What platform were you using?

Desktop

### Version of the plugin

3.0.1

### Relevant log output

```shell
app.js:1 TypeError: Cannot read properties of null (reading 'path')
    at LB.destroy (plugin:dbfolder:118:54468)
    at LB.eval (plugin:dbfolder:118:54700)
    at Generator.next (<anonymous>)
    at eval (plugin:dbfolder:1:938)
    at new Promise (<anonymous>)
    at r (plugin:dbfolder:1:697)
    at LB.onClose (plugin:dbfolder:118:54661)
    at LB.<anonymous> (app.js:1:1122474)
    at app.js:1:235201
    at Object.next (app.js:1:235306)
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @batman47steam ,
Could you share the ddbb file that is causing this problem? I can mot reproduce it without lore info.

It will be attended with priority once we can reproduce the bug, sorry for the inconvenience and thanks for reporting it!

**Comment by batman47steam** [comment]
where can I find the ddbb file ?

**Comment by batman47steam** [comment]
Hi, RafealGB
I upload my .obsidian file and relating plugins, I test this in my computer, once restart, I can only open obsidan with safe mode
https://github.com/batman47steam/test
I hope this can help you reproduce the error

**Comment by RafaelGB** [comment]
Commit fbb7525d
