### ISSUE TITLE
[FR]: control illegal characters on save (improve the message error on read)

### ISSUE THREAD

**Issue by zeltak** [RafaelGB/obsidian-db-folder#668]
### What happened?

I get the following error after defining  a tag column

![CleanShot 2022-12-15 at 11 58 29](https://user-images.githubusercontent.com/498410/207829792-173e9282-b32c-41a1-825b-1ae423b90eda.png)

any clue?

### What platform were you using?

Desktop

### Version of the plugin

3.0.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @zeltak , I am glad the the new error handler print those errors =)

You have an invalid character with the value of your label

Open your markdown file and modify
`label: "\-"` with `label "-"`

If the error persist I will investigate it better

**Comment by zeltak** [comment]
thx @RafaelGB !

yeah that did the trick! still dont know which note had that invalid character (I tried searching :)) but now all is well

thx so much a bunch for you continuous amazing work that makes my (and many others!) life that much more enjoyable :D 

best

Z

**Comment by RafaelGB** [comment]
Thanks for your feedback too! it makes this plugin so much easier to maintain

I will try to check this kind of illegal characters with the plugin, so you dont have to worry about

**Comment by RafaelGB** [comment]
Commit d6dd0df9
