### ISSUE TITLE
[FR]: keep old height of cells

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#669]
### Present your request

From **_2.8.3_** to **_2.8.4_** until now in **_3.0.1_**, the height of cells in `normal mode` has changed. I'd like to be able to switch back to the old height, because I think the current one is too narrow. 

Here is a comparison between **_2.8.3_** and **_2.8.4_**.

![Screen Shot 2022-12-16 at 8 34 29 AM](https://user-images.githubusercontent.com/38974541/208047847-219eb082-052e-4cc7-b4e6-0746011c5709.jpg)
![Screen Shot 2022-12-16 at 8 34 05 AM](https://user-images.githubusercontent.com/38974541/208047799-a456d191-3533-473b-aa7b-feb4d56d9b2b.jpg)

And here is the DB files I'm using
[task1.md](https://github.com/RafaelGB/obsidian-db-folder/files/10243644/task1.md)
[task2.md](https://github.com/RafaelGB/obsidian-db-folder/files/10243645/task2.md)
[task3.md](https://github.com/RafaelGB/obsidian-db-folder/files/10243646/task3.md)
[Untitled database.md](https://github.com/RafaelGB/obsidian-db-folder/files/10243647/Untitled.database.md)

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
With the enxt version there are some changes with this question, even yu will have  a new property to adjust the size of the font

https://github.com/RafaelGB/obsidian-db-folder/issues/498

Do you think this could cover your request?

**Comment by imeed166** [comment]
I don't think I'll change the font size. But I'll wait for the next version to see if the height changed or not.

**Comment by RafaelGB** [comment]
I will close the issue as wont fix by now. Feel free to reopen it if the new version does not cover it
