### ISSUE TITLE
[FR] persist sorting

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#67]
**Is your feature request related to a problem? Please describe.**
When I close the database and switch back to it, I lose the sort

**Describe the solution you'd like**
persist sort even when closing database

**Comment by RafaelGB** [comment]
It will be a possibility, but require a high effort, will be added as long term

**Comment by RafaelGB** [comment]
Finished and with multi sort!
<img width="326" alt="Screenshot 2022-05-27 at 18 14 36" src="https://user-images.githubusercontent.com/11924043/170779549-ba705509-4568-4828-883d-52d4fdf652b3.png">

**Comment by imeed166** [comment]
It does persist, thank you, closing this.
