### ISSUE TITLE
[FR]: Keep cursor on text field when adding options in select and multi-select column settings

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#670]
### Present your request

When I add options in the `select` and `tags` column properties, the cursor leaves the text field, so I have to select it again. In order for the user to add options in succession, the cursor needs to stay in the text field even after creating an option, just like in the add button menu.

https://user-images.githubusercontent.com/38974541/208049343-6f1b024c-3b3c-49b0-93e7-cb0b546ce38f.mov

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
oh I see. I will fix this issue =)

THanks for the reporting

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/208192854-e4e4bb8d-7b95-4f47-9f0d-86e327d69776.mov

**Comment by RafaelGB** [comment]
Commit e4454729
