### ISSUE TITLE
[FR]: Remove the Icons in the select and multi-select cells

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#671]
### Present your request

You can remove the "X", the separator "|" and the "V" that appears when selecting a `select` or `tag` property cell. It doesn't leave any space for the option to be displayed, and they don't add any value. 

- The dropdown is always shown, so the "V" and the separator "|" are not needed.
- The X can be removed, and the user can clear all the options with a keyboard shortcut like `cmd+delete` or something similar.

For context:

![image](https://user-images.githubusercontent.com/38974541/208051363-bf6b51b8-f068-4a61-8f37-4e2edafebfac.png)

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
The "X" is a must to remove the current content. I tried to remove the "V" couple of times but I dont not find the way inside "react-select" documentation

I will check again if we can disable that part

**Comment by imeed166** [comment]
I wonder if you looked at how the [metadata menu plugin](https://github.com/mdelobelle/metadatamenu) handles adding `select` and `multi-select`. It uses the obsidian command bar. Here is a [part of a demo video](https://youtu.be/vc55ivQuHuY?t=105) to illustrate what I mean.

I wonder if it requires too much work, or even if you're interested in switching to using something like this.

**Comment by RafaelGB** [comment]
The demo shows an Obsidian modal component, but I want to use the react one:
- control of styling like colors
- performance improved with other components
- search included
- a lot of documentation
- continuous support with new versions

I will improve our component but change it now requires tons of work and disavantages

**Comment by imeed166** [comment]
I see, thanks for explaining and providing me with the advantages of the current implementation.

**Comment by RafaelGB** [comment]
![Image](https://user-images.githubusercontent.com/11924043/208166171-335b012a-5726-49c9-86dc-f80b3aade2ef.png)

**Comment by RafaelGB** [comment]
Commit 116fe568
