### ISSUE TITLE
[Bug]: Filters (etc.) hidden each time DB opened

### ISSUE THREAD

**Issue by silverpurp** [RafaelGB/obsidian-db-folder#672]
### Contact Details

monthly.cactus0w@icloud.com

### What happened?

Not certain but I'm pretty sure this is a bug? On the newest update, there doesn't seem to be the option to keep the search bar visible permanently. This bar shows the filters which are often used, and on the newest version I have to click the search icon each time to bring these options available. 

<img width="1148" alt="Screenshot 2022-12-16 at 10 32 50 pm" src="https://user-images.githubusercontent.com/110116853/208199867-5c9d41d9-4902-4735-9933-1686c305a178.png">

### What platform were you using?

Desktop

### Version of the plugin

3.0.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Yeah. With the next version we will add a new toggle setting to enable it by default

https://github.com/RafaelGB/obsidian-db-folder/issues/643

You can also use ctrl+f to open the bar

**Comment by RafaelGB** [comment]
Also we will include color options for the filters =)
