### ISSUE TITLE
Filter GUI disappeared

### ISSUE THREAD

**Issue by Mazarkus** [RafaelGB/obsidian-db-folder#673]
The filter GUI is no longer visible above the table. I can still see the filters I previously created in the markdown file, and they are still properly filtering things, but I no longer have access to the GUI to manage it

Edit: this is on both windows and android

**Comment by RafaelGB** [comment]
Hi @Mazarkus , its hidden by default, use the search button to display it. Also with 3.1.0-beta.1 you can enable it by default again too

**Comment by Mazarkus** [comment]
![Screenshot_20221217_182658](https://user-images.githubusercontent.com/110579342/208269692-b9d7b34a-1b2c-427f-b397-0710e184c00b.jpg)
When I click on the search button, the search options show up for each column but I still don't see the filter GUI, looks similar on my desktop as well

**Comment by Mazarkus** [comment]
Wait, I found it, different search button on the top! Thanks for your help, looking forward to the default toggle coming in 3.1.0
