### ISSUE TITLE
[Bug]: Editing columns or entering data via Obsidian Projects resets the db-folder config and loses settings

### ISSUE THREAD

**Issue by KayLuke** [RafaelGB/obsidian-db-folder#674]
### What happened?

When I create a DB folder view in Obsidian Projects, I cannot add any new columns within Obsidian Projects. 

I can edit the DB file directly using db-folder, and add columns, update column types, e.g. create a select column with different colors for different statuses, but if I open DB view in Obsidian Projects AND then ediit it in any way, the DB file is reset to the original state, and loses any edits I had made.

What I tried to do:
- I wanted to have a Status column with different colors for each status
- I wanted to have a linked DB column for team members

Observed behavior:
- The settings above do not "stick" if I try to edit any of the columns in obsidian projects

Advanced settings for status column:
![pic1](https://user-images.githubusercontent.com/2609441/208187310-61e98a38-7af4-4cbe-8dd2-3e23cfdbb51d.png)

Display in obsidian db-folder and obsidian projects (on first open)
![pic2](https://user-images.githubusercontent.com/2609441/208187474-a2999c85-b9cf-45c9-ab94-3f9a19b3495a.png)

Display in obsidian projects after any edits that cause the plugin to refresh the view:
![poc3](https://user-images.githubusercontent.com/2609441/208283399-379b46ea-f895-4443-aef8-6f33cac27784.png)

### What platform were you using?

Desktop

### Version of the plugin

v3.0.1

### Relevant log output

```shell
plugin:dbfolder:118 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'columns')
    at LB.eval (plugin:dbfolder:118:53476)
    at Generator.next (<anonymous>)
    at i (plugin:dbfolder:1:748)
eval @ plugin:dbfolder:118
i @ plugin:dbfolder:1
plugin:dbfolder:118 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'columns')
    at LB.eval (plugin:dbfolder:118:53476)
    at Generator.next (<anonymous>)
    at i (plugin:dbfolder:1:748)
eval @ plugin:dbfolder:118
i @ plugin:dbfolder:1
plugin:dbfolder:118 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'columns')
    at LB.eval (plugin:dbfolder:118:53476)
    at Generator.next (<anonymous>)
    at i (plugin:dbfolder:1:748)
eval @ plugin:dbfolder:118
i @ plugin:dbfolder:1
plugin:dbfolder:118 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'columns')
    at LB.eval (plugin:dbfolder:118:53476)
    at Generator.next (<anonymous>)
    at i (plugin:dbfolder:1:748)
eval @ plugin:dbfolder:118
i @ plugin:dbfolder:1
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
with 3.1.0 You can add new columns via projects. Delete is not supported yet since projects does not allow to remove the content (just hide) and could affects its behaviour

**Comment by RafaelGB** [comment]
I will close this issue. Feel free to comment about a reopen.

To Delete you can enable the "remove fields" toggle
