### ISSUE TITLE
[FR]: Arbitrarily wide columns

### ISSUE THREAD

**Issue by padasch** [RafaelGB/obsidian-db-folder#676]
### Present your request

It would be nice to have arbitrarily wide columns and not limited options from the compact-normal-similar selection.

Writing in the scalable box from this [feature update](https://github.com/RafaelGB/obsidian-db-folder/issues/200) is a blast, and it would be nice to always have columns as wide as I like them. Also, this would make use of additional screen space on larger displays.

(I was surprised I did not come across this in other issues. If I missed it, I apologize for spamming.)

Thanks! Keep up the great work :)

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
Hello @padasch , thanks for your suggestions.

So the idea would be to apply a slider to that feature as an option? It is more oriented to the width of the column? They have a range from 30px to 350px currently

The height is dynamic. The row height will be the biggest of its cells

```typescript
const defaultColumn: Partial<ColumnDef<RowDataType>> = {
  minSize: DatabaseLimits.MIN_COLUMN_WIDTH,
  maxSize: DatabaseLimits.MAX_COLUMN_WIDTH,
  cell: DefaultCell,
  header: DefaultHeader,
  enableResizing: true,
  footer: DefaultFooter,
};
```

**Comment by padasch** [comment]
I was not thinking about a slider but generally allowing wider columns. I guess allowing to increase `maxSize` (if that refers to the 350px you mentioned) either through a parameter in the settings or through dynamic adjustment when clicking and dragging the border of the column header.

Here's a screenshot showing the maximum width of the cell in "column 1" and the width I would like to have in "new column 3":
![image](https://user-images.githubusercontent.com/80832353/208669225-a509f948-338c-482c-9aa7-7c78b8c3d2ac.png)


PS: I thought the `cell size` option set to `wide`  would allow wider columns, but I just realized it sets the cell's padding (I guess?).

**Comment by RafaelGB** [comment]
yeah, the cell size dropdown configure the height with some padding. We can modify the max size of the width for the next version
