### ISSUE TITLE
Make all plugin's settings in same place

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#68]
**Is your feature request related to a problem? Please describe.**
Is it intentional that the menu at the top left only have one option : `export to CSV` and that the other options : `open as markdown` and `open database settings` are on different settings menu ?

**Describe the solution you'd like**
I don't know if this is better, but in my opinion, having all plugin related settings in one place would be best (simpler for the new user).

**Additional context**

https://user-images.githubusercontent.com/38974541/169869811-134a08ae-a1b3-46be-8c16-dbd497f27575.mov

**Comment by RafaelGB** [comment]
the actual csv issue marks it as a provisional solution, the idea is to add it in the file obsidian menu
