### ISSUE TITLE
[Bug]: Filter UI gone

### ISSUE THREAD

**Issue by Amparose** [RafaelGB/obsidian-db-folder#682]
### What happened?

I previously had a filter set up to not show rows that had a specific column empty. The YAML (which still filters my table) is:

```yml
filters:
  enabled: true
  conditions:
      - field: Finish
        operator: IS_EMPTY
        value: ""
```

I can't see a way to edit/remove/add new filters since updating (can't remember which version had this UI). Is this a bug or a feature that will be returning?

### What platform were you using?

Desktop

### Version of the plugin

3.1.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hi @Amparose , just click on search bar button to show that options, now its hidden by default. If you want to have that bar again by default you can enable it on global settings

**Comment by RafaelGB** [comment]
more info here https://github.com/RafaelGB/obsidian-db-folder/issues/673

**Comment by Amparose** [comment]
> Hi @Amparose , just click on search bar button to show that options, now its hidden by default. If you want to have that bar again by default you can enable it on global settings

That is the search bar, which seems to have replace the previous "filters" feature. Outside of editing the YAML directly, I can't see a way to turn off the filter I have active. The problem is that it is useful to filter by IS_EMPTY. How does one do that via the search?

**Comment by RafaelGB** [comment]
There is another button in the top as 🔍 to enable that bar or just try "ctrl+f"

**Comment by Amparose** [comment]
The only icon I have just shows the quick search bar:
![CleanShot 2022-12-21 at 13 06 32@2x](https://user-images.githubusercontent.com/949192/208901808-d5c4b41e-4e38-4319-a629-2cf7cb765134.png)

But I see that there is an entry in the command palette and I can access the filters panel there. I should have checked this first. Thanks for your help.

**Comment by RafaelGB** [comment]
I think you have disabled the tab bar on appearance settings (Obsidian)

<img width="417" alt="On appearance settings" src="https://user-images.githubusercontent.com/11924043/208903055-ba38f8c2-778f-4b42-8e65-d7b9600f724c.PNG">

So you can see this core options of the plugin. In any case the plugins offers some shorcuts for every option too =)

<img width="108" alt="bar settings" src="https://user-images.githubusercontent.com/11924043/208903125-37302675-33f0-4b4d-aa08-1c6cd1173abd.PNG">

**Comment by Amparose** [comment]
> disabled the tab bar on appearance settings (Obsidian)

Yep! There's the options I was missing. All makes sense now.

**Comment by zcysxy** [comment]
> I think you have disabled the tab bar on appearance settings (Obsidian)
> 
> <img alt="On appearance settings" width="417" src="https://user-images.githubusercontent.com/11924043/208903055-ba38f8c2-778f-4b42-8e65-d7b9600f724c.PNG">
> 
> So you can see this core options of the plugin. In any case the plugins offers some shorcuts for every option too =)
> 
> <img alt="bar settings" width="108" src="https://user-images.githubusercontent.com/11924043/208903125-37302675-33f0-4b4d-aa08-1c6cd1173abd.PNG">

Putting them in the titlebar is neat! But it also took me here to find where they are. I think it maybe helpful to add a small css snippet (like Kanban plugin)

```css
.workspace-leaf-content[data-type="database-plugin"] .view-header {
    display: flex;
}
```
