### ISSUE TITLE
[Bug]: No difference between Calendar Property and Calendar/Time Property

### ISSUE THREAD

**Issue by daw0du** [RafaelGB/obsidian-db-folder#683]
### What happened?

After updating to the newest version, the property for "Calendar" changes YAML to include both date and time--not just the date itself. I have change the database settings for metadata date format but to no avail. Have I missed something? Thanks again for this awesome plugin!

### What platform were you using?

Desktop

### Version of the plugin

3.1.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @daw0du , with 3.1.0 we are using the native API to write inside the yaml now. You can still read the correct value with your format in the table but the information persisted follows the ISO standard of Datetime Luxon library.

We will work to save them properly

**Comment by RafaelGB** [comment]
Commit 4386cead
