### ISSUE TITLE
[Bug]: Dropdown view color

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#685]
### What happened?

This is not what I was expecting to see.

![image](https://user-images.githubusercontent.com/78496825/209170511-46f9da87-4664-46cd-863e-55977fe126fb.png)

### What platform were you using?

Desktop

### Version of the plugin

3.1.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @DannyHatcher-Git ,
https://github.com/RafaelGB/obsidian-db-folder/issues/684 working on it here. It just affects to the dark mode
