### ISSUE TITLE
[Bug]: Lists in a Text property column now have brackets inserted around them, which breaks links in the list

### ISSUE THREAD

**Issue by Mazarkus** [RafaelGB/obsidian-db-folder#686]
### Contact Details

lecardinal@gmail.com

### What happened?

It looks like version 3.1.0 now adds brackets when a property value is in a list, and it breaks linking when those properties are links to another page.  Previously when a column type is "text", it would just take the text by itself and everything in the list of links would work

![error2](https://user-images.githubusercontent.com/110579342/209344975-e775d70e-350f-446c-9c5a-6930c047f82d.png)

![error1](https://user-images.githubusercontent.com/110579342/209344998-da437aee-3b37-4c77-a6b5-f8da846d09f4.png)

### What platform were you using?

Desktop

### Version of the plugin

3.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Oh I see, we won’t consider the inline arrays with links. Will be fixed with next versions. Thanks for the report!

**Comment by RafaelGB** [comment]
As a better aproximation

```javascript
// Is a list
if (/(^\[{1})([^\[]{1}.*[^\]]{1})(\]{1})$/.test(newValue)) {
      // Remove brackets
      newValue = newValue.replaceAll(/(^\[{1})([^\[]{1}.*[^\]]{1})(\]{1})$/, "$2");
     // Another things               
  }

**Comment by Mazarkus** [comment]
Thanks for the rapid feedback! Really enjoy this plugin, I switched from notion and not having databases was my main hesitation

**Comment by RafaelGB** [comment]
I am glad that you enjoy it =)

Fixed and also with an improvement


https://user-images.githubusercontent.com/11924043/209405913-09be8017-09fe-4e2b-bd29-197ea0bedbbd.mov

**Comment by Mazarkus** [comment]
With the most recent fix, the lists are a little buggy still.  If I format my list the way I originally posted, it adds a blank entry in the display.

Example setting in YAML:
aliases:
- alias 1
- alias 2

Example visual display
-
- alias 1
- alias 2
