### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by ramarivera** [RafaelGB/obsidian-db-folder#687]
### Contact Details

Over github comments 

### What happened?

I'm unable to install the plugin. 
I always get the same error about it not being a suitable version. Am I missing something very obvious here?

![Screenshot_20221223_155543_Obsidian](https://user-images.githubusercontent.com/7547875/209356401-7d5a32e6-cba1-4634-8705-e24d113ce8fc.png)

### What platform were you using?

Mobile

### Version of the plugin

LATEST

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @ramarivera ,
what version of Obsidian are you using?
1.1 is required now since they add an API to edit metadatas

**Comment by ramarivera** [comment]
Version 1.4.1 (83)
API v1.0.3

**Comment by RafaelGB** [comment]
Please update to Obsidian 1.8 (the canvas official upgrade)

API >= 1.1

**Comment by RafaelGB** [comment]
Oh I saw uou are on mobile :( you can't use the lastest version until Obsidian do. You can always use BRAT to install older versions. 3.0.1 will be fine for mobiles

Sorry for the inconvenience, I will check if I can expose a custom verification for mobile devices

**Comment by ramarivera** [comment]
Oh I see. Thanks for pointing that out! 
Do you have any kind of idea how long that could take?

**Comment by RafaelGB** [comment]
they say on internal chats "when its ready" so I can't tell
