### ISSUE TITLE
change row height

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#69]
**Is your feature request related to a problem? Please describe.**
currently the rows takes a bit too much space, so you can't see many rows at once

**Describe the solution you'd like**
for a more compact feel, and to see more information at once, provide other row height option just like Airtable

**Describe alternatives you've considered**
scroll to see everything

**Additional context**
![image](https://user-images.githubusercontent.com/38974541/170124032-5f0e902a-e899-4d58-852b-b0cbd11f2e59.png)

**Comment by RafaelGB** [comment]
Hi @imeed166. Yeah, the css has a lot of room for improvement. Your petition will be considered and added to the roadmap

**Comment by artisticat1** [comment]
I can work on this!

**Comment by imeed166** [comment]
The implementation is really nice, thank you. One nitpick however, when adding multiple tags to one cell, it gets larger, so the compact mode is not respected in this case. Would it be possible to make it the priority and not show all the tag (like in the picture) and keep the cells compact even if it doesn't fit the content of the cell.

![image](https://user-images.githubusercontent.com/38974541/173113239-1ec2856d-56e0-41db-a667-cfd3f163d049.png)


If the user wants the cell to adapt to the cell content, he'll have to switch to `normal` mode again.

**Comment by artisticat1** [comment]
Good idea, I added this in the latest commit.

![image](https://user-images.githubusercontent.com/100622574/173193846-3d1660f4-605c-4d01-9c2a-31585fece0ea.png)

**Comment by imeed166** [comment]
Great, does this apply to text type cells too ?

**Comment by artisticat1** [comment]
Yep!
![image](https://user-images.githubusercontent.com/100622574/173194428-3fd82c7f-bab2-4873-8259-fe4e3595de71.png)
