### ISSUE TITLE
[FR]: Custom font size for text column

### ISSUE THREAD

**Issue by Rhydderch** [RafaelGB/obsidian-db-folder#692]
### Present your request

I would like to be able to define a font size for the text columns, in the same way we can define a font size in the config file.
For now, all columns do not use the font size in the config file.
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/3197629/209426458-227a5f8c-b3ce-45b7-a101-7178b6892361.png">

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
I noticed that. Needs some css tricks to avoid the Obsidian default size.

Added to the roadmap =)

**Comment by Rhydderch** [comment]
Thank you :)

**Comment by RafaelGB** [comment]
fixed here https://github.com/RafaelGB/obsidian-db-folder/issues/694
