### ISSUE TITLE
[FR]: Support labels for values of columns

### ISSUE THREAD

**Issue by Rhydderch** [RafaelGB/obsidian-db-folder#693]
### Present your request

I would like to assign a label to each value of a select type column.
For instance, this would allow me to use numbers as values for rating, but show stars instead of the numbers.
So in the dropdown, we would see the labels assigned to each value instead of the value itself.

UI wise, I guess this could be done by putting a text field on the left of the value text field (there's room for it!)
<img width="375" alt="image" src="https://user-images.githubusercontent.com/3197629/209426700-b1da56cc-bba6-49d6-94b8-a67568f54050.png">

Do you think this would be possible?

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
Could be interesting!

Maybe requires some changes on save but I don't think that its difficult

**Comment by Rhydderch** [comment]
Awesome!

**Comment by RafaelGB** [comment]
![Image](https://user-images.githubusercontent.com/11924043/216810980-ed97a7f1-23bf-4ac3-ab21-2eb951988544.png)

**Comment by RafaelGB** [comment]
Commit b2952c0d

Finished some details =)
