### ISSUE TITLE
[Bug]: Text area font size is different than the text's font size

### ISSUE THREAD

**Issue by Rhydderch** [RafaelGB/obsidian-db-folder#694]
### What happened?

For now, the font size differs between the edit text area and the text field.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/3197629/209426794-cc941595-64a9-42aa-9546-f442474d01d3.png">
<img width="259" alt="image" src="https://user-images.githubusercontent.com/3197629/209426798-3ef770fa-f01b-4eeb-8a20-b33807af9ac4.png">

I think it would be nice for the font size to remain the same, for consistency and ease of use/viewing

### What platform were you using?

Desktop

### Version of the plugin

3.1.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
the size is dynamic. We can include the same "wrap" or "no wrap" property of the rendered cell

**Comment by RafaelGB** [comment]
fixed with next version

Commit 4386cead
