### ISSUE TITLE
Will deleting rows and changing the order of rows be supported in the future?

### ISSUE THREAD

**Issue by OriOYue** [RafaelGB/obsidian-db-folder#70]
Like the title, I hope the plugin can support deleting rows and changing the order of rows, so that the plugin is more perfect.

**Comment by OriOYue** [comment]
Also I would like to support changing the name of the file directly in the database in the future.
Thanks!

**Comment by RafaelGB** [comment]
HI @OriOYue . Its already considered in the roadmap here

https://github.com/RafaelGB/obsidian-db-folder/issues/62

I am waiting to the v8 react-table dependency then add action buttons per row ( add files above or below, delete, DnD...)

Its currently in alpha, but will bring breaking changes =)

**Comment by OriOYue** [comment]
> please, consider to add that petitions inside #62

Ok, I understand.
This plugin has helped me a lot, and I'm looking forward to it being even greater. Thank you very much for your efforts.

**Comment by RafaelGB** [comment]
Thanks! still a lot of work to do, we want to conquer Notion users =)
