### ISSUE TITLE
[Bug]: property type tags auto label and single-line problem

### ISSUE THREAD

**Issue by mineclover** [RafaelGB/obsidian-db-folder#702]
### What happened?

This problem occurs when manipulating property type tags in the DB view.

1. Write text::value4 in md file
2. Manipulate values with tags in db view
3. Bugs can be checked in the yaml of the automatically updated md file
4. You can also check the added label

If you write `text::value 3` inside md, the previously entered
text:
- abc
- 😀😀😀
is entered as a comma and is condensed
text:
- abc, 😀😀😀
- value 3

This has a problem with [abc, 😀😀😀] appearing in the data base view as well.
 [abc, 😀😀😀]  is added to the label as well.

"text : abc, 😀😀😀 , value 3" in md

This behavior also causes the problem of tags labels being added.

DB folder is the default value, and when yaml and single-line contents are long, it seems that line breaks are used automatically.
Word wrap causes errors in auto lint

I am maintaining yaml with mutli-line

### What platform were you using?

Desktop

### Version of the plugin

3.1.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Sorry for the inconvenience and thanks for the quick report =)

**Comment by mineclover** [comment]
I received the 3.1.2 version and tried it, but there is still a problem.

Existing yaml values are stored as comma arrays (123,456,789).

The problem is that when you use the key:value method, the database view recognizes the existing value 
(-123 
- 456
- 789) as 123,456,789, making it a single tag.
also.
Key :: The value is recognized as a different tag, leaving a total of two tags in the frame.

Occurs when adding tags or manipulating DB views.

![image](https://user-images.githubusercontent.com/61359316/209756818-023bf925-92c9-4766-b300-c435a8691f79.png)

![image](https://user-images.githubusercontent.com/61359316/209756841-1235102d-57fd-4d94-a0fc-d10d0f4d4df9.png)

**Comment by RafaelGB** [comment]
The other key is how dataview works. It will recognise all the duplicate properties as another array entry. DBfolder just read it
