### ISSUE TITLE
Error reading YAML file on mobile

### ISSUE THREAD

**Issue by Asetnozama** [RafaelGB/obsidian-db-folder#705]
I want to change a column value on mobile and get the next error
![image](https://user-images.githubusercontent.com/102867794/209779845-bcb381b9-7fe4-4512-8f03-3b8f6f712d80.jpeg)

Possible edition issues while you are saving a cell change

YAML of the destination file is not well-formed
--> I didn't change the YAML and it worked before

The destination file does not exist or is not a file. This can happen if the file was deleted or renamed while you were editing it.
--> I didn't delete or rename the original file

Is there something else that I can try?
Thanks

**Comment by RafaelGB** [comment]
What version did you install with BRAT?

You have to use a frozen one <=3.0.1

This error its caused by the new editor API of Obsidian with frontmatter params

**Comment by Asetnozama** [comment]
> What version did you install with BRAT?
> 
> 
> 
> You have to use a frozen one <=3.0.1
> 
> 
> 
> This error its caused by the new editor API of Obsidian with frontmatter params. Use an old version until they release the 1.1 on mobiles

Thank you 🙏

**Comment by RafaelGB** [comment]
I am happy to help!

Sorry I don't have several supported editing engines, I want to focus development efforts on the latest version of the application since they are preparing deep changes in their metadata system and it is convenient to be up to date.

**Comment by csss1234** [comment]
I'm not a coder or contributer to github, so this could just be me, but would it make sense to keep this "bug" as _open_? I spent 15 mins searching for answers before I realized I needed to also check the "closed" bug requests.

Love DB Folder, thanks for all your work : )

**Comment by RafaelGB** [comment]
its opened as discussion.

Really sorry for the mobile inconvenience but I can not maintain different versions.

I suggest the option to expose different versions for desktop and mobile to the Obsidian developers

Once Mobile version is released it will be fixed including tons of new features
