### ISSUE TITLE
[FR]: Multi-tag support

### ISSUE THREAD

**Issue by StrollStars** [RafaelGB/obsidian-db-folder#706]
### Present your request

I want to see I can select two or more tags to use as source of data.
Although Dataview query can be used, I found that other content in the metadata cannot be selected as a column.

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
Hello @StrollStars, This issue is related to https://github.com/RafaelGB/obsidian-db-folder/issues/377

Could be a good moment to give it a second chance

About the multi tag selection could be a good addition, sure!

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/210018091-49a30e31-1d9a-4eca-9fad-f0b1d57089df.mov

**Comment by StrollStars** [comment]
@RafaelGB Thank you, I expect it to be released soon.

**Comment by StrollStars** [comment]
Exactly as expected, thank you.
