### ISSUE TITLE
[Bug]: plugin not downloading on mobile app

### ISSUE THREAD

**Issue by MrAltF4** [RafaelGB/obsidian-db-folder#707]
### Contact Details

N/a

### What happened?

I went to the community plugin section to download the plugin, pressed "install" and a small popup said "no appropriate version found."

I'm on Android.
Apologies if this isn't the way you're meant to download the plugin. I couldn't find a solution online.

Also apologies for ticking the boxes below but it wouldn't let me log this issue unless I ticked them. As I can't download I had to lie in these (sorry)

### What platform were you using?

Mobile

### Version of the plugin

Can't download 

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @MrAltF4 , Sorry for the inconvenience but Temporarily the mobile version should be downloaded woth BRAT plugin.

https://github.com/RafaelGB/obsidian-db-folder/discussions/699

soon or later it will be available again on mobiles with Obsidian 1.1
