### ISSUE TITLE
Columns' [Property Type] (Text, Select, Checkbox, etc) create invalid YAML syntax for "Projects" Plugin.

### ISSUE THREAD

**Issue by Do11-Master** [RafaelGB/obsidian-db-folder#712]
When you create a new column, and select the column's property as "Checkbox", it creates a **Text** Type YAML front matter, when really, it should create "Boolean" Type. This creates issues with the Obsidian _Projects_ Plugin, from Marcus Olsson. 

If you create a checkbox column, and click the box (or uncheck it) on a row, this is the YAML created as a result: 
```
---
Column_Name: "true"
---
```
or
```
---
Column_Name: "false"
---
```

However, because it's a boolean value, it should probably create the following YAML instead. The syntax below is actually recognized by "Projects" plugin, as a boolean data type.
```
---
Column_Name: true
---
```
or
```
---
Column_Name: false
---
```
______________
This issue also concerns the other property types such as 'Tags' or 'Select', etc

I've also mentioned the related problems for other Property Type on Obisidan Forum here: 
[Link](https://forum.obsidian.md/t/projects-db-folder-plugins-problem-with-changing-field-type-text-boolean-true-false-etc/51101)

**Comment by RafaelGB** [comment]
I can not reproduce the problem under Obsidian 1.1.9 and dbfolfer 3.1.3

We are using the native edit engine

**Comment by Do11-Master** [comment]
I am also unable to reproduce the issue as well at the moment after updating to dbfolder 3.1.3.
Not really sure where this came from. Thank you for the plugin. Great work
