### ISSUE TITLE
[Bug]: Creation or Updates of Inline field does not work when it is inside a callout

### ISSUE THREAD

**Issue by juanjoarranz** [RafaelGB/obsidian-db-folder#717]
### Contact Details

juanjoarranzales@gmail.com

### What happened?

I have my inline fields inside a callout. 

The DB Folder plugin can read the inline fields inside the callout but cannot update them INSIDE callout. Instead it recreates the inline field outside the callout, so you end up having a duplicated inline field with different values

### What platform were you using?

Desktop

### Version of the plugin

3.1.2

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @juanjoarranz , could you share the content of your callout and its configuration (column config)?

I just check the callout install (under 3.1.3) and it works


https://user-images.githubusercontent.com/11924043/210227030-771bf0ef-6dfa-4936-9704-9911783f3af6.mov

**Comment by juanjoarranz** [comment]
This is the issue:
![image](https://user-images.githubusercontent.com/5842578/210243309-d1319aef-d274-4e4c-b94c-54ed3ff853fa.png)

**Comment by juanjoarranz** [comment]
And this is the Status field settings: 
![image](https://user-images.githubusercontent.com/5842578/210243828-15fd7143-c432-443f-b1fb-80292b38d021.png)

**Comment by juanjoarranz** [comment]
I already found exactly when the issue happens:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/5842578/210245065-db20241f-2212-4127-9b39-75ff1f7c516f.png">

**Comment by RafaelGB** [comment]
The regular expression of the edit engine requires that space (some use cases could be broken)


Thanks for your report 👌 

Could we close this issue then?

**Comment by juanjoarranz** [comment]
Yes, close it please. I already included a space in all affected notes. Thank you for your very quick response
