### ISSUE TITLE
[FR]: Set Default Pagination Size

### ISSUE THREAD

**Issue by FriedrichStein** [RafaelGB/obsidian-db-folder#718]
### Contact Details

j.friedrich-stein@gmx.de

### Present your request

Small QOL Feature.
Being able to set a default pagination size in settings. 

The Default is 10 and I constantly change this, after wondering where my new entry has gone :D 

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/210227684-e2555e01-6b1f-40a3-93c5-8556373f5455.mov

 This was a `You want it, you got it` situation =)
 
 Ready for the next version

**Comment by RafaelGB** [comment]
Also we add a default font size setting

**Comment by FriedrichStein** [comment]
Just magic! Thanks!
