### ISSUE TITLE
[FR]: Bi-directional Relations

### ISSUE THREAD

**Issue by manuelweisser** [RafaelGB/obsidian-db-folder#719]
### Present your request

Not sure, if this is already possible, but I could not find it. 

I would like to have bi-directional relations. Currently, when I add a relation between 2 database-folders, this is only shown in the database where I created the relation. 
I want to see the relation in both databases, i.e. I want that the yaml-metadata are edited in both files when I change the relation. 

### For which platform do you request this request??

Desktop

**Comment by manuelweisser** [comment]
Just found out that this is a duplicate from #581

**Comment by RafaelGB** [comment]
yeah, Its a short term feature to do. I have to find the way to achieve it
