### ISSUE TITLE
[Bug]: DB Table just shows nothing

### ISSUE THREAD

**Issue by As-Design18** [RafaelGB/obsidian-db-folder#721]
### What happened?

Hello again, 
i fixed my former issue but now two other tables are disappeared. I started Obsidian again and nothing changed. 
Here is one of my files. Hopes this helps. 

Evergreen Notes 🌲.md

<img width="1472" alt="SCR-20230102-qox" src="https://user-images.githubusercontent.com/117035403/210314128-4638d2ca-9022-475b-b1d8-0a7e7f465dea.png">

### What platform were you using?

Desktop

### Version of the plugin

newest

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
hello @As-Design18, the file was not uploaded.

Also you can watch the logs with:
- ctrl+shift+I (windows-linux)
- cmd+opt+I (macOS)

**Comment by toxfu** [comment]
I have the same problem

**Comment by As-Design18** [comment]
i think i figured it out. I did have multiply tags as inputs ( 📥 and #📥) and i removed both and set only one again. Now everything is showing up perfectly again. Maybe that helps

**Comment by toxfu** [comment]
No, the problem persists. I don't have multiple repeated tags.

**Comment by RafaelGB** [comment]
U can search your db file here and I will check the problem


Anyway I improved the error handler for tags sources Commit e63dc69a (next version)

**Comment by toxfu** [comment]
It works well. Thanks!
