### ISSUE TITLE
[FR]: Have database row entries without needing to create a note

### ISSUE THREAD

**Issue by dylanvanw** [RafaelGB/obsidian-db-folder#723]
### Contact Details

github messages
sorry I do not want my email public

### Present your request

I there 👋  I love your database plugin concept and think I have an idea on how it could become even more powerful.

# Inspiration from Kanban plugin
My idea comes from working with the Kanban community plugin. With this plugin you can create cards with some title. For some cards these are small tasks that you just need the title to remind you of having to do something. In that case, no note is needed to be created for this card since you only need the card title. Other times, I need some more context to the task so I create a note that is linked to the card just by clicking on it.

# Same concept applied to Database Folder
I would think this can be a very powerful functionality for database folder too. So if you create a row in the database, it is first created as a row in the database and not as a new note right away like what is currently happening. This comes from the fact that I often want to create database rows with just the title, but do not need the whole note to be created. Currently I have many almost completely empty notes since Database Folder forces me to create a new note for each new row I create.

I think many more people could benefit from this feature and it would open up this plugin for very new applications of keeping track of data that do not need a new note for each row.

Would love to hear what you think!

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
Hello @dylanvanw,
the purpose for this year will be to apify the plugin offering a CRUD for different implementations that use the table.

One of those implementations could be to write a conventional table into a file like https://github.com/trey-wallis/obsidian-notion-like-tables

**Comment by dylanvanw** [comment]
That sounds great!

I also thought about the implementation as a table. A table that just has rows and columns but where it is possible to have a row link to a specific note where the data in the note also updates the row in the table and if you change the data in the table row, it will update the note. Just like the plugin currently behaves.

Great to hear that this is already the idea for this year. I think it would launch databases folder into one of the core community plugins for the obsidian ecosystem.

**Comment by RafaelGB** [comment]
We have already a big step thanks to zustand since 2.0

https://github.com/RafaelGB/obsidian-db-folder/blob/master/src/cdm/TableStateInterface.ts

We have to offer the CRUD with that interfaces being the setters here

https://github.com/RafaelGB/obsidian-db-folder/tree/master/src/stateManagement

**Comment by dylanvanw** [comment]
Cool! I am currently still under contract but I have some downtime in a few months. I think this could be a really cool project that I can contribute something to. Assuming you could use some help by then of course ;)?

I am just new to typescript so I need a bigger time investment to be able to contribute than I can currently offer. I know about interfaces from my time with java briefly but that has been a  few years ago so I need to refresh a lot of my knowledge. State management is something I have used once in a project with React some time ago so I will need to read up on that too.

**Comment by dylanvanw** [comment]
If we would use a table instead of notes that are currently used. Would that not mean that searching rows would no longer be possible? Since dataview is used for searching and dataview uses only notes and not table entries?

**Comment by RafaelGB** [comment]
we are going to need another read system but that will be the last part.

We need to apify first out state management as a CRUD (create read update delete)

Internally the state manager used is Zustand. Every action method that interacts with the notes has two steps

- interacts with disk
- interacts with memory


We have to apify just the first.

I will be happy to design some class diagram and you are more than welcome to contribute to this ambitious feature!

**Comment by dylanvanw** [comment]
It would indeed be ambitious but I think it would be a very valuable feature. I would really like to contribute but I won't be able to do it at the moment. My contract ends 1st of June but I would like to be able to already study some and get familiar with your codebase. 

Some diagrams would help and where and how should I start getting familiar with the codebase, any tips on that front?

**Comment by RafaelGB** [comment]
sure,
the first step should be how the Obsidian plugin architecture works .

You can check the main.ts => onload method

In this method we expose the view of the plugin and all the necessary events to use it

**Comment by RafaelGB** [comment]
I'm on vacation right now and I'm making a lot of progress with other features.  During the week I will create in the docs folder some Obsidian canvas to paint the operation of the plugin at a high level

**Comment by dylanvanw** [comment]
Thanks! Enjoy your holiday!

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/167 its the API issue
