### ISSUE TITLE
[FR]: Relationship Input with optional filters..

### ISSUE THREAD

**Issue by tonogdlp** [RafaelGB/obsidian-db-folder#725]
### Present your request

I want to see ...

When I have a relationship between 2 Databases, the list that appears as input options has all the rows from the other database. Most of the time this is way to many options, and I'm not really interested in most of them.  Also, there are times where I know which rows of the related database are relevant to the current row in the current database. 

Here's a quick example. I have 2 databases: Agents and Clients.

Agents are my company's employees..  Each client is assigned an Agent. Both the Agents and the Clients have a city where they live / work.
<img width="324" alt="Screen Shot 2023-01-04 at 4 41 24" src="https://user-images.githubusercontent.com/8254361/210547675-d2b6e5db-f582-4dcb-bebb-8fa554b81bde.png">

<img width="385" alt="Screen Shot 2023-01-04 at 4 42 56" src="https://user-images.githubusercontent.com/8254361/210547907-cfcab4e2-8f33-4033-b844-d49897e85b80.png">

Whenever I add a new client to my database, I first add the Name and City of the client. That should be enough for me to filter my input for my relationship Client -> Agent. For example.. if I have a new client in NY, I want the relationship field to only show people from NY... 

<img width="400" alt="Screen Shot 2023-01-04 at 4 44 22" src="https://user-images.githubusercontent.com/8254361/210548099-9da3b786-058d-4af8-969f-7ab1d7893544.png">

It would be awesome if you could somehow filter the list based on both the current database and the destination database. Some other examples I can think of:

 - Only show me rows from related database if the row has a checkbox == true     (only checks related DB)
 - Only show rows from related database if date is in current month                        (only checks related DB)
 - Only show rows from related database if date is equal as current's row 'due-date'     (checks both current and related DB)
 - Only show possibilities if the current row's checkbox == turn     (Only checks current DB.. can be used as safeguard)

### For which platform do you request this request??

Cross

**Comment by RafaelGB** [comment]
Hello @tonogdlp, thanks for your suggestion!

I think when we get into this other feature it will cover your case.

https://github.com/RafaelGB/obsidian-db-folder/issues/635

It will be more flexible
