### ISSUE TITLE
[FR]: Wikilinks as Column Headers (Not IDs!)

### ISSUE THREAD

**Issue by danrfletcher** [RafaelGB/obsidian-db-folder#728]
### Contact Details

danrfletcher@outlook.com

### Present your request

I would like to see column headers be linkable to pages. I understand we can't have the actual ID be a wikilink but it would be nice to link from the column header in order to be able to quickly access useful information and related content to the data in a column.

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
Hello @danrfletcher ,

I think it’s duplicated with https://github.com/RafaelGB/obsidian-db-folder/issues/665
Applying markdown render to the column label will cover your case :)

**Comment by RafaelGB** [comment]
By duplicate, I meant that this request has already been made and we have it included in our roadmap. It is not yet implemented but we will take it into account for future developments

**Comment by danrfletcher** [comment]
Gotcha, thanks for clarifying.
