### ISSUE TITLE
Table Filter buttons

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#73]
I know that creating good filters can have many options and be complex, but here are some ideas to make quick use of filters.

**Is your feature request related to a problem? Please describe.**
I think something like this solves several problems and is faster.
- Create a filter with the current search
- Activate and deactivate filters quickly
- Select individual filters
- More integrated in the table without going to the configuration

**Additional context**
 
![image](https://user-images.githubusercontent.com/7627504/170447724-eab80f4f-15d0-4979-b5b3-cd389936163e.png)

(Filters created here would appear in the settings as well)

**Comment by RafaelGB** [comment]
hi @javiavid Its a nice design! This was in my personal backlog but with low priority, Could be a nice feature with the actual filters!

**Comment by javiavid** [comment]
Of course, I think there are more important things right now.

**Comment by chaosmonster** [comment]
Alternative idea to this could be to define the dataview (or dataviewjs) query that fills the table

**Comment by RafaelGB** [comment]
First version of this menu according with your design

<img width="944" alt="Screenshot 2022-08-10 at 19 23 20" src="https://user-images.githubusercontent.com/11924043/183976929-385e2647-f2db-4199-8260-79301f741a94.png">

**Comment by RafaelGB** [comment]
Nearly final version. Happy with the result!

The filter/unfilter button could be used as a refresh of the table too
https://user-images.githubusercontent.com/11924043/184618527-2cab6b87-45d1-446b-a39b-ee71e277e505.mov
