### ISSUE TITLE
When i open a database that is based on a tag, I just get a blank page. Databases based on folders work just fine[Bug]: 

### ISSUE THREAD

**Issue by Nepentho** [RafaelGB/obsidian-db-folder#732]
### Contact Details

jonas.w.spitzer@gmail.com

### What happened?

A bug happened!

### What platform were you using?

Desktop

### Version of the plugin

3.2.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @Nepentho ,

Please check out discussion about tags sources migration since 3.1.2

https://github.com/RafaelGB/obsidian-db-folder/discussions/724

**Comment by Nepentho** [comment]
Hey,
this (#724) did help. I can now fix my older databases. But now every new one i create, needs this fixing as well..

**Comment by RafaelGB** [comment]
The new ones should have the tags correctly parsed, let me know if it happens with any new db =(

**Comment by RafaelGB** [comment]
fixed with the last version
