### ISSUE TITLE
[Bug]: quoted attributes from an imported CSV aren't respected

### ISSUE THREAD

**Issue by Obsidian-user** [RafaelGB/obsidian-db-folder#734]
### What happened?

When importing a CSV, every comma is treated like a data separator even when quoted / escaped.

For example, with the following CSV:

```
File, col2
"object 1, with note", object 2
```

I would expect
```
---
File: object 1, with note
col2: object 2
---
```

instead I get

```
---
File: object 1
col2: with note
undefined: object 2
---
```

### What platform were you using?

Desktop

### Version of the plugin

3.2.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @Obsidian-user, Thanks for the report

I will check this issue

**Comment by RafaelGB** [comment]
I will change the actual [csv library](https://github.com/react-csv/react-csv#readme)per a custom solution we can parse better.

I am working on a plugin API for another Input/Output solutions and this tutorial could be an aprox https://refine.dev/blog/how-to-import-csv/

**Comment by RafaelGB** [comment]
This is the first step of a huge refactor Commit 41480453

It will fix this issue
