### ISSUE TITLE
[Bug]: BRAT always update to another version

### ISSUE THREAD

**Issue by Lisandra-dev** [RafaelGB/obsidian-db-folder#739]
### What happened?

Hello!
BRAT always update to an older version, so it's not pretty pratical. Because of that, I disabled BRAT auto-update but...

You need to update the [manifest-beta.json](https://github.com/RafaelGB/obsidian-db-folder/blob/master/manifest-beta.json) to the last version, or removing it to falling back to the manifest.json. 

### What platform were you using?

Cross

### Version of the plugin

/ not relevant

### Relevant log output

```shell
/
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @Lisandra-dev ,
You can check the reasons about this temporal decision here:

https://github.com/RafaelGB/obsidian-db-folder/discussions/736

**Comment by Lisandra-dev** [comment]
The problem is : using sync, I can't have a different version, using BRAT or not.

Also, updating to the last version will obviously create problem.

I dunno if there is a way to prevent downloading a specific version on mobile... Asking the developper can be useful for that.

At last it can be a good FR for BRAT.

Thanks for your reply anyway.

**Comment by RafaelGB** [comment]
if there is no news of 1.1 during the following week I will consider to support mobile version with a conditional editor
