### ISSUE TITLE
[FR] Remove Select and Folder

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#74]
**Is your feature request related to a problem? Please describe.**
It is possible to create a select or folder column and add a value, but it is not possible to quickly remove that value.

**Describe the solution you'd like**
A solution would be to create a button with an X to remove those values.
In the case of a folder, the file should also **be moved** to the root folder.

![image](https://user-images.githubusercontent.com/7627504/170939415-a081d4ed-c0ca-4637-91e2-432f433e9bf4.png)

**Describe alternatives you've considered**
An alternative is that if it detects that the folder value is empty (because you have manually deleted it) the file is moved to the root of the folder.

**Comment by RafaelGB** [comment]
This will be a nice feature! added to roadmap.

The idea was to wait multi select type column and integrate the cross inside the label

**Comment by javiavid** [comment]
Maybe it's better to have the X in each select as you thought or use this X only for the folders.

**Comment by RafaelGB** [comment]
Was added with another issue >1month ago.
