### ISSUE TITLE
[Bug]: CSV export issue

### ISSUE THREAD

**Issue by Rsose** [RafaelGB/obsidian-db-folder#740]
### What happened?

Hi RafaelGB
When I export csv file the time format will be garbled. 
Original VS Exported
![image](https://user-images.githubusercontent.com/51273534/211162699-b977e110-6d8a-44e3-8ed7-066c89f44725.png)
![image](https://user-images.githubusercontent.com/51273534/211162665-349c522d-77bb-48c4-bcfa-718d949107df.png)

---

Antoher request
Export and import CSV file, then when I re-import CSV file it will add duplicate files(There is any good solution for this?)
My idea is when re-import the csv file just update the column information instead of adding duplicate files

Thanks
Waiting for a reply

### What platform were you using?

Desktop

### Version of the plugin

3.2.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hi 👋,
We are not maintaining csv for a while.

There are plans this year to improve the experience with

https://github.com/RafaelGB/obsidian-db-folder/issues/631

about your dates they are exported as timestamp milliseconds (an standard for dates when you are using csv) we can find an option to choose the deserved format to use

**Comment by RafaelGB** [comment]
Fixed related to https://github.com/RafaelGB/obsidian-db-folder/issues/782
