### ISSUE TITLE
[Bug]: Formula column not working

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#743]
### Contact Details

javiavid@gmail.com

### What happened?

I have copied a folder from one vault to another, in 3.0.1 it works fine, in 3.2.1 the formula is empty.
I have tried to update the version of the white vault and it has stopped working correctly.

3.0.1 (white theme)
3.2.1 (black theme)

Formula
${row.number}

![image](https://user-images.githubusercontent.com/7627504/211184020-7b356426-753c-41ab-95de-53d5402f339b.png)

### What platform were you using?

Desktop

### Version of the plugin

3.2.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Commit 38444fa3

Fixed!
