### ISSUE TITLE
YAML list adds a blank entry when displayed

### ISSUE THREAD

**Issue by Obsidian-user** [RafaelGB/obsidian-db-folder#745]
If I have list in a document's YAML, it adds a blank entry in the display:

Example setting in YAML:
```markdown
h1:
- s1
- s2
```

Example visual display
```markdown
-
- s1
- s2
```

_Originally posted by @Mazarkus in https://github.com/RafaelGB/obsidian-db-folder/issues/686#issuecomment-1368473786_

_p.s. Thank you so much for your hard work_

**Comment by RafaelGB** [comment]
Thanks for the report! Will be reviewed

**Comment by ManuelVicenteG** [comment]
The same happens when in a YAML field there is a wikilink preceded by a comma, in enumerations for example. In this case it generates in the table a list with a blank in the first line and the font size is not affected by the configuration.

Thanks for the great plugin

**Comment by RafaelGB** [comment]
Commit 9d12dc76 fixed for the next version
