### ISSUE TITLE
[Bug]: Returning to my vault after a few months and I am getting this

### ISSUE THREAD

**Issue by ProStashio** [RafaelGB/obsidian-db-folder#748]
### What happened?

Returning to my vault after a few months and I am getting this

### What platform were you using?

Desktop

### Version of the plugin

Current

### Relevant log output

```shell
https://gyazo.com/bd0a6c569fcb53f51f4d00460e8dd427
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
could you share your db file? I can not know the problem with thst log :(

**Comment by ProStashio** [comment]
> could you share your db file? I can not know the problem with thst log :(

Sent via Discord

**Comment by RafaelGB** [comment]
check this discussion with the solution https://github.com/RafaelGB/obsidian-db-folder/discussions/711
