### ISSUE TITLE
[FR]: Make scroll bar thicker

### ISSUE THREAD

**Issue by Rsose** [RafaelGB/obsidian-db-folder#749]
### Present your request

Hi RafaelGB
Is there any way to make the left and right scroll bars thicker?
I have a lot of columns, each time I need to click multiples for getting it
Using the middle button of the mouse is also not flexible or you can adjust it to a thicker scroll bar like EXCEL's

![image](https://user-images.githubusercontent.com/51273534/211364153-54e0c21a-18f9-49d6-a212-27bb9cf0906e.png)
EXCEL scroll bar
![image](https://user-images.githubusercontent.com/51273534/211365148-0133d15d-b8fd-4f9c-b025-9943ced44385.png)

Thanks
Waiting for a reply

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
sure!
I was thinking about a css snippet. Could be more flexible

**Comment by stefandanzl** [comment]
can be modified with css snippet: 
```
/* Scrollbar */
/* change height for horizontal scrollbar */
::-webkit-scrollbar {
  height:15px;
}
```
