### ISSUE TITLE
Allow editing of existing notes

### ISSUE THREAD

**Issue by crazymedguy** [RafaelGB/obsidian-db-folder#75]
I've been trying to create a workflow using Auto Note Mover. When I tag it with #task, it automatically shifts it into a folder "Tasks". What I'd like the database plugin to do is recognise this new file, and be able to assign YAML attributes to it. Currently, it is not able to write into this existing file.

**Comment by RafaelGB** [comment]
Hi @crazymedguy. So you have your database inside that Tasks folder, right? Currently you need to refresh the database view to can edit that file.

I am working on another feature that I think resolves your problem https://github.com/RafaelGB/obsidian-db-folder/issues/59

**Comment by RafaelGB** [comment]
closing this issue
