### ISSUE TITLE
[Bug]: Documentation Error

### ISSUE THREAD

**Issue by JordanChoe** [RafaelGB/obsidian-db-folder#753]
### Contact Details

kenziechoe@gmail.com

### What happened?

On the Notes page in the Documentation at https://rafaelgb.github.io/obsidian-db-folder/features/Notes/ for the section Deleting and Renaming Notes, it accidentally says to select the number on the right to rename or delete a note.  This should be on the left according the video.  I highlighted it with bold.  

"Deleting & Renaming Notes

You can right-click on the numbers to the **right** of every row, to bring up a menu where you can delete or rename the note associated with the row"

### What platform were you using?

Desktop

### Version of the plugin

Version irrelevant, documentation. 

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
yeah, thanks for the report. This event was changed with 3.0.0 but the docu was not updated
