### ISSUE TITLE
[FR]: Open note in new panel

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#754]
### Contact Details

javiavid@gmail.com

### Present your request

In Obsidian there are two ways to open files, new tab (CTRL + click) and new panel (CTRL + ALT + click).
The second option doesn't work when you click on the filename in the plugin.

It is interesting to be able to simultaneously see the content of several files to edit them or to correct metadata problems.

Optionally it would be nice to have an option in the settings for these panels to open vertically (split right) or horizontally (split down).

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
sure!

**Comment by stefandanzl** [comment]
added in #1023
