### ISSUE TITLE
[Bug]: Has the version number not changed?

### ISSUE THREAD

**Issue by StrollStars** [RafaelGB/obsidian-db-folder#760]
### What happened?

I install v.3.2.4, but it still looks like 3.2.3 in the settings.

### What platform were you using?

Desktop

### Version of the plugin

3.2.4

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
hello 👋,

The manifest and config have the correct version

https://github.com/RafaelGB/obsidian-db-folder/blob/master/manifest.json

**Comment by RafaelGB** [comment]
Found the problem!

The release was updated =)
