### ISSUE TITLE
[FR]: Add new row to related DB

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#762]
### Contact Details

sarah.arminta@me.com

### Present your request

I would love to be able to enter a new relation directly from the table cell. Currently I have to go to the related table, create a new row, then nav back to the original table and add the new row as a relation. 

It would be great to be able to select a relation cell, type in the desired name and have it created as a relation and in the related table. 

I hope that makes sense.

Currently it looks like this:
<img width="460" alt="Screenshot 2023-01-15 at 14 37 54" src="https://user-images.githubusercontent.com/7927356/212563280-65df3a71-8105-49b0-a7ab-84a8fb0af5d7.png">

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
Could be a nice QoL inclusion =)

**Comment by gjjg007** [comment]
This would be extremely helpful for productivity and help function more like a regular relational database tool.

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/221412306-3cb2100d-ce53-49dc-afa1-9b7a27c264cd.mov

We will work with any kind of source for your relational database origin.

Commit 9d35b8ae
