### ISSUE TITLE
[Bug]: Files appear that are not in the folder

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#763]
### What happened?

Starting obsidian and opening the database starts showing up a lot of files that don't belong in the folder.
After a while I close and reopen the database and everything is fine.

https://user-images.githubusercontent.com/7627504/213145084-16aee81b-1be3-49b7-8a7d-eb4b8a0b916b.mp4

### What platform were you using?

Desktop

### Version of the plugin

3.2.4

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @javiavid , this bug is caused by the refresh engine. It swear it was well controlled but maybe something changes.

Once dv is loaded the refresh listener turns on. If that listener turns on before the load event its when you can see that behaviour

**Comment by RafaelGB** [comment]
Could your verify if this still happens? It should be fixed for folder and tags sources (with other ones I have to find the solution yet)

**Comment by javiavid** [comment]
Solved, thank you
