### ISSUE TITLE
[Bug]: Regression in nested metadata feature

### ISSUE THREAD

**Issue by ksexton** [RafaelGB/obsidian-db-folder#769]
### What happened?

Using nested values in YAML front-matter I expected to be able to update the values from the database view. Actual result is that the format is changed to what appears to be a json object?

Older version (tested against what I had on-disk, 2.8.0) the value is updated properly.

https://user-images.githubusercontent.com/180931/213880327-1e73f420-8fb3-46d3-8fd1-62829eb51296.mp4

### What platform were you using?

Desktop

### Version of the plugin

3.2.4

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Oh that's true! 
Will be fixed with the next version Commit 5ab88c02

https://github.com/RafaelGB/obsidian-db-folder/blob/5ab88c02d13a4a014e672b14a714ad64e3d04362/src/services/parseServiceHelpers/MarkdownParser.ts#L45

This flag was needed
