### ISSUE TITLE
[BUG] Changes not persisting

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#77]
Having issues again with my edits not persisting. For example, adding a column, changing the name, populating values within the column, etc. If I navigate and return to the db page, all changes are reset to default. 

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 12.3.1

**Comment by RafaelGB** [comment]
This bug worries me a lot. Happens only when including new rows?

**Comment by arminta7** [comment]
When adding new columns. Maybe sometimes when editing existing columns? It's really hard for me to tell if it happens with other edits, I'll need to pay attention more closely. But it seems, for me, that most of the time my edits don't save.

**Comment by RafaelGB** [comment]
could you share your database yaml? (the markdown mode)

**Comment by arminta7** [comment]
This?

<%%
name: pillars database
description: 
columns:
  __file__:
    key: __file__
    input: markdown
    label: File
    accessor: __file__
    isMetadata: true
    skipPersist: false
    csvCandidate: true
    isInline: false
    config:
  __modified__:
    key: __modified__
    input: calendar_time
    label: Modified
    accessor: __modified__
    isMetadata: true
    skipPersist: false
    csvCandidate: true
    isInline: false
    config:
  Type:
    input: text
    key: Type
    accessor: Type
    label: Type
    position: 0
    config:
      enable_media_view: true
      media_width: 100
      media_height: 100
      isInline: true
  Projects:
    input: text
    accessor: Projects
    key: Projects
    label: Projects
    position: 2
    config:
      isInline: true
      media_height: 100
      media_width: 100
      enable_media_view: false
  Status:
    input: text
    accessor: Status
    key: Status
    label: Status
    position: 3
    config:
      isInline: true
      media_height: 100
      media_width: 100
      enable_media_view: false
  Testing:
    input: text
    accessor: Testing
    key: Testing
    label: Testing
    position: 4
    config:
      isInline: true
      media_height: 100
      media_width: 100
      enable_media_view: false
config:
  enable_show_state: false
  remove_field_when_delete_column: false
  group_folder_column: 
  show_metadata_created: false
  show_metadata_modified: true
  source_data: current_folder
  source_form_result: 
filters:
%%>

**Comment by RafaelGB** [comment]
exactly! thanks, I will try test it

**Comment by arminta7** [comment]
No, it isn't just that. Here's what I just tried:

Added the field "Test" to two files. 
Added a new column "Test" in their db
Went to the settings to specify inline
Exited settings and the column name was set back to "New Column 7" (didn't save name)

Renamed column to "Test".
Filled out text values for the two Test field in the 2 pages I created the Test field in. 
(I have both pages open and the value was not changed when entering these values)
Exited the db folder page (navigated to a different page).
Went back to the db folder page. 
Column was reset to "New Column 7"
All entered values were erased. 
No values in the pages with "Test" field.

**Comment by RafaelGB** [comment]
I found the first problem of renaming. When you close column settings, the table is restarted. The edited name of the column is not shared well with the settings part and its overwritten again with old one.

After fix that, I will try to reproduce the second part. Thanks for the testing as always @arminta7

**Comment by RafaelGB** [comment]
This still happening with 1.6.2? Working with lot of bug fixes on 1.6.3 but this is not reproduced anymore in my tests

**Comment by arminta7** [comment]
Yes, this seems much better!! Nice work 👏
