### ISSUE TITLE
[Bug]: Changing Column ID deletes corresponding YAML attribute

### ISSUE THREAD

**Issue by Fonell** [RafaelGB/obsidian-db-folder#770]
### What happened?

Changing ID of a Column deletes every corresponding YAML attribute in all files of the database.
I would expect it to keep the values and just update the attribute ID.
It also moves the Column to the end of the database.

Before
![image](https://user-images.githubusercontent.com/47721786/213883692-d5019b35-bf90-4db0-b850-edce60d08e2c.png)

Changing the ID of the column id_test to id_test2
![image](https://user-images.githubusercontent.com/47721786/213883729-79a02710-631f-4e27-ae50-6cf7f7063e4f.png)

Result - attributes are gone, column is moved to the end
![image](https://user-images.githubusercontent.com/47721786/213883745-328444de-c19c-4622-ad99-7dc401998207.png)

It seems odd that I am the only one to have this problem, so maybe it's something to do on my end? However, I am relatively new to Obsidian and have only installed a small number of plugins and changed a few settings.

### What platform were you using?

Desktop

### Version of the plugin

3.2.4

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @Fonell , Thanks for the report

I could reproduce it. Will be attended for the next version

**Comment by RafaelGB** [comment]
Commit d579b39c

Fixed =P was a legacy problem
