### ISSUE TITLE
[Bug]: Can't see relations in light mode

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#771]
### Contact Details

sarah.arminta@me.com

### What happened?

The font color for the relation dropdown is very light and I can't see the options in light mode. I thought it might have been something funny with my CSS but this is in a default test vault:

<img width="325" alt="Screenshot 2023-01-21 at 23 18 26" src="https://user-images.githubusercontent.com/7927356/213900432-394706af-461a-4b42-a963-2434b254a1b1.png">

### What platform were you using?

Desktop

### Version of the plugin

3.2.4

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hi @arminta7 ,
I don't know why the contrast function does not work well in this case but it will be fixed with the next version 

Commit 343da0c3

**Comment by RafaelGB** [comment]
You can check the contrast in action with the demo of bidirectional relations too =) 

https://github.com/RafaelGB/obsidian-db-folder/issues/581#issuecomment-1399576721

**Comment by arminta7** [comment]
Much better!
