### ISSUE TITLE
[Bug]: Interesting bidirectional linking behavior

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#775]
### Contact Details

sarah.arminta@me.com

### What happened?

It's easier to see in a video. The button I'm pressing in the beginning is the filter button to refresh the table. I can get rid of the added files by clicking the filter button again but that row with the linked table still appears. 

https://user-images.githubusercontent.com/7927356/214458349-3968cd4e-9550-4b07-81cf-b556dd81d756.mov

### What platform were you using?

Desktop

### Version of the plugin

3.3.0-beta.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Sorry I did not read your issue. Looks like its fixed, right?

**Comment by arminta7** [comment]
Yes, it seems to be fixed!
