### ISSUE TITLE
[Bug]: Export to CSV changes the date format in inappropriate format such as 2023-01-25 to 1.67459E+12

### ISSUE THREAD

**Issue by BKPro22** [RafaelGB/obsidian-db-folder#778]
### Contact Details

bhavinpro22@gmail.com

### What happened?

A bug happened!
Export to CSV changes the date format in inappropriate format such as 2023-01-25 to 1.67459E+12
[Final Test.csv](https://github.com/RafaelGB/obsidian-db-folder/files/10500773/Final.Test.csv)

### What platform were you using?

Desktop

### Version of the plugin

3.2.4

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
We can use the same solution of the import with https://www.papaparse.com/

Thanks for the report =)

**Comment by RafaelGB** [comment]
In addition to https://github.com/RafaelGB/obsidian-db-folder/issues/782 this issue was fixed with Commit fb1052d8


Ready for the next version

**Comment by BKPro22** [comment]
Hey Rafael,

That's great. Thanks for your reply and making improvements to the
plugin. 👍


Thanks,
Bhavin Khatri

**Comment by BKPro22** [comment]
Yes, That's perfect!
In version 3.3.0 it works absolutely fine. Great job! 👍


Thanks & Regards,
Bhavin Khatri
