### ISSUE TITLE
New relation list design

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/obsidian-db-folder#779]
@RafaelGB not sure if it fits here or if it could be a visual enhancement feature request.

Would it be possible to display the table name in the relation field the same as tags instead of a list?
I think by using a list there's too much wasted space there.  Even if we might have several tables it would still look better like in tags.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/70922426/214557649-3c0389b6-dc84-4774-91f5-2ca96f8b795b.png">

thank you!

_Originally posted by @cesarpereira904 in https://github.com/RafaelGB/obsidian-db-folder/issues/581#issuecomment-1403507595_

**Comment by RafaelGB** [comment]
Also I added a selection color per column for the relations =)


https://user-images.githubusercontent.com/11924043/215267640-e380767a-a781-4545-95c9-b65c892a6a7f.mov

**Comment by RafaelGB** [comment]
Commit 5a1a1078

**Comment by cesarpereira904** [comment]
Amanzing work Rafael, it looks neat!!!
