### ISSUE TITLE
[FR] Support links within the select column type. 

### ISSUE THREAD

**Issue by arminta7** [RafaelGB/obsidian-db-folder#78]
Currently links show link this in select columns:

<img width="399" alt="Screen Shot 2022-05-30 at 18 51 05" src="https://user-images.githubusercontent.com/7927356/171065837-3d98e1fb-cbf8-4490-b62f-840425253691.png">

Would hope that they could show as actual links!

**Comment by RafaelGB** [comment]
hi @arminta7! currently links are just supported with text column type. Render markdown links inside that label could be a thing... It will be considered =)

**Comment by RafaelGB** [comment]
This go out of my capabilities.

Render links inside select needs a markdown render of obsidian and affect the actual visual component. Sorry but I have to discard this issue until the arch of obsidian allows it
