### ISSUE TITLE
[Bug]: csv export produces blank file

### ISSUE THREAD

**Issue by mylenrath** [RafaelGB/obsidian-db-folder#782]
### Contact Details

mylenrath@gmail.com

### What happened?

I have several database folders with different fields and data.  When I try to export to csv from any database, the result is always a blank file.  Running version 3.2.4

### What platform were you using?

Desktop

### Version of the plugin

3.2.4

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @mylenrath ,

Could you share your db and some mocked file to reproduce the problem?

We are transitioning to using the paparse library due csv was not being maintained. We hope in a short term to be able to solve it.

You have available the beta version 3.3.0 where some of these changes have already been introduced.

**Comment by mylenrath** [comment]
Heres my database

**Comment by RafaelGB** [comment]
Commit 737eceae

will be fixed with a custom solution. react-css library was removed

Ready for the next version
