### ISSUE TITLE
[Bug]: Unable to delete associated by clicking

### ISSUE THREAD

**Issue by Rhydderch** [RafaelGB/obsidian-db-folder#783]
### What happened?

Clicking on the "x" to delete an relation exits the focus of the cell instead of deleting the relation.

I have this problem with tags and with relation columns.

<img width="136" alt="image" src="https://user-images.githubusercontent.com/3197629/215320519-df520850-083a-4a9f-be9a-9478562ac622.png">

<img width="112" alt="image" src="https://user-images.githubusercontent.com/3197629/215320532-bf17cdb4-e34e-466f-9249-69f1d33ea19b.png">

I am only able to delete a link/tag by moving with the navigation keys or tab.

### What platform were you using?

Desktop

### Version of the plugin

3.3.0

### Relevant log output

Note this is happening since a few weeks, but I only put an issue now.

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by Rhydderch** [comment]
Okay, I understand. I'll use esc for now.
Do I close this issue or do I leave it open? (perhaps it will be easier for other to find if it stays open?)

**Comment by RafaelGB** [comment]
leave it open :) will be fixed eventually

**Comment by RafaelGB** [comment]
- Fixed for tags and relations with https://mui.com/material-ui/react-click-away-listener/
- Fixed for select types with a default `-- None --` option to clear the cell

Commit 5812aab8
