### ISSUE TITLE
[Bug]: Row Formulae Output Disappears on Pagination

### ISSUE THREAD

**Issue by be-studio** [RafaelGB/obsidian-db-folder#785]
### What happened?

I have a formula column with a row formula that calculates a result per row based on the values in another column of rollup type. The results appear in the rollup column, but when paging through the table and paging back, the results in that column disappear as if the formulae have not been calculated on returning to that page.

### What platform were you using?

Mobile

### Version of the plugin

3.3.0-beta

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @be-studio ,
Could you confirm if this happens with the last official version? (3.3.0) I could not reproduce the problem

**Comment by Jeffliv5** [comment]
I have also encountered this issue. Almost exactly the same as you. 
FYI, it only  happens when the formula column is not empty in the original files. So if you turn on the "Persist formula output" setting it will trigger this issue.

**Comment by uroybd** [comment]
> I have also encountered this issue. Almost exactly the same as you. FYI, it only happens when the formula column is not empty in the original files. So if you turn on the "Persist formula output" setting it will trigger this issue.

This happens even without persisting.

**Comment by RafaelGB** [comment]
I will investigate this case. Added to the roadmap

**Comment by uroybd** [comment]
> I will investigate this case. Added to the roadmap

All the formula related bugs came to existence after the 3.1.3 release. I'm still using this version without any problem. They seem to be related. Diffing the 3.2.0 with 3.1.3 might give us a clue.

**Comment by RafaelGB** [comment]
sorry for the inconvenience @uroybd , too much work this months...

fixed for the next version. Was a bad positioned condition before the renderMarkdown
