### ISSUE TITLE
[Bug]: Regresion with obsidian projects support - load

### ISSUE THREAD

**Issue by captorxxv** [RafaelGB/obsidian-db-folder#786]
### What happened?

A bug happened!
![image](https://user-images.githubusercontent.com/102044296/215344344-00d3e871-605a-49af-a45e-12f1db0f8b90.png)
![image](https://user-images.githubusercontent.com/102044296/215344364-9aeea49b-5df2-4bba-928d-8b8d5d311e54.png)

After Update, all colors are very bright, and looks wierd 
I can see some errors in the console 
Also, every time i open database i have to open seetings in order to display data as otherwise i cannot see anything 

### What platform were you using?

Desktop

### Version of the plugin

3.3.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
hello @captorxxv ,
its a controlled error after dataview indexes all the files. It just should happen at startup of Obsidian.

it happens after the first load?

**Comment by captorxxv** [comment]
> hello @captorxxv ,
> its a controlled error after dataview indexes all the files. It just should happen at startup of Obsidian.
> 
> it happens after the first load?

Yes, every time I switch between databases, I also use Project plugin with dbfolder so not sure if this is related, for now I've reverted back to the previous version until is fixed 
Thanks

**Comment by RafaelGB** [comment]
With the last version of projects a reload is needed due a career condition of onData with onOpen events

Commit eb1b3acf
