### ISSUE TITLE
[Bug]: Tags/Select font color is changed to white/gray and can't change back to black

### ISSUE THREAD

**Issue by Mazarkus** [RafaelGB/obsidian-db-folder#787]
### Contact Details

lecardinal@gmail.com

### What happened?

The bubbles in the tags/select column types has had the font color changed to a gray/white, with the background colors still being pastel by default, which makes the text almost impossible to read.  I can't find a way to change the font color back to the original black that it used to be.

![image](https://user-images.githubusercontent.com/110579342/215354447-4bd0f86c-5044-43a6-aacd-0b01b71f0ffe.png)

### What platform were you using?

Desktop

### Version of the plugin

3.3.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by martinbb** [comment]
I'm seeing the same behaviour.  Latest version of plugin and Obsidian (just checked both).

**Comment by RafaelGB** [comment]
With the new feature of links inside the tags and select, the text color will be the same of your appearance option.

We can create a css snippet, not problem at all =)

**Comment by martinbb** [comment]
Thank you -- good to know.  

PS: *you* may be able to create a css snippet, but I don't think I can! ;)

**Comment by ProStashio** [comment]
I am also in the same boat of not knowing how to fix this issue with a snippet. Do you have an example that came be used?

**Comment by euler007** [comment]
Same issue

**Comment by captorxxv** [comment]
Same here with latest version, reverted back to previous build for now

**Comment by LeslieP-TX** [comment]
I had the same visibility problem with the tags, since I use dark mode. The fix for me was to open the database as Markdown, then change the L (lightness) value of all of the colors from 90% to 20%

Replace
Find `, 90%)"`
Replace `, 20%)"`

Maybe that could be added to this wonderful plugin as an automatic thing when dark mode is detected?

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/809 will fix this issue
