### ISSUE TITLE
[Bug]: Gray Highlight

### ISSUE THREAD

**Issue by ProStashio** [RafaelGB/obsidian-db-folder#788]
### What happened?

The new update has a strange grey highlight over all my selects
<img width="885" alt="b159928c31c870002f8230fe80837f60" src="https://user-images.githubusercontent.com/19267479/215493107-822ccf8c-29ad-486e-86f9-15ddb120bdaa.png">

### What platform were you using?

Desktop

### Version of the plugin

Current

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/787 will be check with another issue
