### ISSUE TITLE
Hide option in column menu

### ISSUE THREAD

**Issue by javiavid** [RafaelGB/obsidian-db-folder#79]
Sometimes screen space is limited and you need to be able to show a column, change it and then hide it.

![image](https://user-images.githubusercontent.com/7627504/171108387-39c98d08-c55b-4f8a-99b4-36e1d179fbd1.png)

**Comment by RafaelGB** [comment]
The request would be to hide the entire column then? I do not get it well, sorry

**Comment by javiavid** [comment]
Yes, hide the column

**Comment by RafaelGB** [comment]
the problem with that its to create another UI to enable again the column, maybe inside database config. That makes sense?

**Comment by javiavid** [comment]
I guess the configuration window is the easiest option, but I would try to avoid having to open a lot of configuration, I think it is more agile and intuitive to do everything possible from the table itself.
I've been looking at notion and they solve it with the typical 3 dots icon next to the + icon.

Maybe something similar could be a good option, but I guess there are a lot of priorities first.

**Comment by RafaelGB** [comment]
The 3 dots could be the database config itself. We can show the hidden columns inside columns section , so you can enable them again

**Comment by javiavid** [comment]
Yeah, it's really the same thing haha
The only difference is that it's cleaner, but I think it's a good solution.

**Comment by RafaelGB** [comment]
it is to follow the aesthetic line of Obsidian plugins, in fact, the css button will be moved to that 3 dots too someday

**Comment by javiavid** [comment]
Yes, that's perfect. Thank you very much

**Comment by imeed166** [comment]
Just a proposition, but current behavior of the plugin when `remove fields` is disabled in db settings is exactly what hiding a column is. 

So, I'm proposing to : 
- switch the default behavior of `detele` to deleting metadata and column,
- add another option `hide` (like in the picture above) to delete the column but not the metadata behind it.

When it comes to re-enabling the column, I believe the idea in #112 would solve this.

What do you think @RafaelGB ?

**Comment by RafaelGB** [comment]
@imeed166 thanks for your idea.
Could be interesting, but my idea for 112 its another button that display a modal like Notion and choose the columns that you want to add.
It would be a refactor of the actual new column button to show an Obsidian way of this
<img width="304" alt="Screenshot 2022-06-24 at 16 02 12" src="https://user-images.githubusercontent.com/11924043/175551852-acdcc9d1-049f-4a36-9d90-f14e1cada704.png">

**Comment by imeed166** [comment]
I see, but that would still work for re-enabling previously deleted column with existing metadata. 

I just think that there should be one place to `add a column that have metadata` instead of having one in the `new column botton` and one in `db settings`, to avoid users getting confused.

**Comment by javiavid** [comment]
I think notion is very well planned in the design, maybe it would be good to try to do something similar. I don't know if this is possible or too complicated

**Comment by RafaelGB** [comment]
The hide option as you said could be the "delete without remove all the fields inside the files". In the future modal will be 2 buttons with every column. Hide & delete

**Comment by RafaelGB** [comment]
yeah, this will not be another settings option, will be a new modal that replace the actual new column button

**Comment by imeed166** [comment]
Great, thanks for taking my ideas into consideration.

**Comment by RafaelGB** [comment]
final design. I think its cool =)

https://user-images.githubusercontent.com/11924043/184692085-91b586ff-033d-4175-8c99-7723ce043acd.mov
