### ISSUE TITLE
[VS] scrollbar css addition for dropdown search

### ISSUE THREAD

**Issue by dapaning** [RafaelGB/obsidian-db-folder#795]
### Contact Details

dapan1020@gmail.com

### What happened?

When searching, I have 41 attributes, but the screen only shows 23 attributes

![2023-02-01_17-02-40](https://user-images.githubusercontent.com/66105129/215998382-35018cf3-2bc4-427a-a64f-5bfdbf9cf8bc.jpg)

### What platform were you using?

Desktop

### Version of the plugin

3.3.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
hi @dapaning ,
If you write inside it should filter in function of your prompt and show those hidden values

**Comment by dapaning** [comment]
Thanks for your reply, what you said is a good solution, it would be great if you could add a scrollbar
