### ISSUE TITLE
[Bug]: Fields are moved from inline to FrontMatter

### ISSUE THREAD

**Issue by SpocWeb** [RafaelGB/obsidian-db-folder#796]
### Contact Details

I'm on GitHub

### What happened?

Hi, first of all thank you for this Plugin!
But when I edit an inline Field, it is moved into the FrontMatter. I don't think this is intended, because I have selected "Enable inline Fields as Default" both in the DB and the Plugin Settings. 
This is a question; if you need a sample I can try to upload the zipped Folder somewhere. 
Thanks for your help.

#### Before: 
```
---
type: Continent
tags:
  - geo/Continent
---
[IsDeleted:: true]
[IsPrivate::]
[name-en::Antarctica]
[name-de::Antarktis]
```
#### After: 
```
---
type: Continent
tags:
  - geo/Continent
IsDeleted: false
---
[]
[name-en::Antarctica]
[name-de::Antarktis]
```

### What platform were you using?

Desktop

### Version of the plugin

3.3.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @SpocWeb , Enable inline Fields as Default will create the NEW columns with that flag activated, but the existing one will be threated like frontmatters.

I do not know if its the case here

**Comment by Alejandro-Stolz** [comment]
@SpocWeb check the title of the Column in the db. If it has a * next to it, it is an inline field.
![image](https://user-images.githubusercontent.com/73649874/216040423-e0235b1c-33f3-48f5-99a9-1189938ba209.png)
To change that click settings for the column:
![image](https://user-images.githubusercontent.com/73649874/216040472-dfc3baa1-618b-4f88-a7a5-89e1f5dfc5ec.png)
And tick the second option.
![image](https://user-images.githubusercontent.com/73649874/216040520-47d52f01-8354-4e78-b8c8-cf4e00fd0f77.png)
This happened to me and it may be the same thing causing it for you. If not, then it's a bug

**Comment by SpocWeb** [comment]
That's it!
As I see right now, you can configure it for each column individually and that's what I didn't pay attention to. 
I populate the Columns from the sample Record using your Button "Use all Fields" and this does not seem to set this Checkbox. If it is possible to defermine from the Obsidian or DataView API whether the Data comes from Inline or Frontmatter it would really save me and other people from being perplexed. 
Alternatively I would volunteer to expand your documentation in this respect, to help future Users

**Comment by SpocWeb** [comment]
I'll do a global search/replace from isInline: false to isInline: true in all my dbs now, because it doesn't cost much more space and is more versatile; I can add Tags and Links. I hope this doesn't make a big difference performance-wise. 

thank you all for your help!
