### ISSUE TITLE
[FR]: Displaying of text in table as plain text

### ISSUE THREAD

**Issue by Alejandro-Stolz** [RafaelGB/obsidian-db-folder#797]
### Present your request

The text in the metadata of some files may contain *, **, [, [[, etc. At the moment, they are rendered as markdown (italic, bold, ...), but in my case, they are not supposed to be markdown. 
I have currently 2 ideas in mind. T
- To not render the markdown, when the text is in ", as the "Projects" plugin does in the table view. 
- Or providing a setting for each DB-Folder or Column, although some may prefer more fine control over the displayed data.
Thank you

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
It could be another column config with a toggle settings, sure!

**Comment by Alejandro-Stolz** [comment]
Gracias Rafael :)
