### ISSUE TITLE
[Bug]: Inline Tag is not closed when using the tags column Type

### ISSUE THREAD

**Issue by SpocWeb** [RafaelGB/obsidian-db-folder#798]
### Contact Details

directly in GitHub

### What happened?

when choosing 'inline field' to store a Column of tags Type, the Inline Element is not properly closed. 
This results of course in not properly reading it. 
Actual inline text: `[tags:: geo/Continent, newTag`
Expected      text: `[tags:: geo/Continent, netwTag]`

### What platform were you using?

Desktop

### Version of the plugin

3.3.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by SpocWeb** [comment]
As a workaround I will use FrontMatter Storage for now.
thank you for this fabulous component!

**Comment by RafaelGB** [comment]
Hello @SpocWeb , thanks for your report. I will add it to the roadmap

**Comment by RafaelGB** [comment]
https://regex101.com/r/mpJEMP/1

Possible solution for a more complete regex

**Comment by SpocWeb** [comment]
Not bad, which RegEx dialect are you using? I suppose EcmaScript? 
Some dialects support matching Brackets which would allow for [[links]]  or {{templates}} in the Value. 
Let me see if EcmaScript supports this.

**Comment by SpocWeb** [comment]
This is the feature explained: [Balancing Groups](https://www.regular-expressions.info/balancing.html)

**Comment by SpocWeb** [comment]
In JavaScript: [API :: XRegExp.matchRecursive](http://xregexp.com/api/#matchRecursive)

XRegExp.matchRecursive(str, '\\[', '\\]', 'g');

but for primitive Values like simple Strings and Numbers this is probably overkill.

**Comment by RafaelGB** [comment]
Yeah, EcmaScript. With older version I was using those balancing groups like a form of ternary, but it scale bad. So I dev a builder pattern => https://github.com/RafaelGB/obsidian-db-folder/blob/master/src/patterns/builders/NoteContentActionBuilder.ts

Sacrificing some performance for readability

**Comment by SpocWeb** [comment]
So you construct the RegEx above with this code?

**Comment by RafaelGB** [comment]
Yeah, so we can construct pairs of regex-replaceFormula and run a list of them for a content

**Comment by SpocWeb** [comment]
Instead of recursive Parsing one can also hard-code a single Pair of Braces for a WikiLink inside the Text, which speeds up matching too. When you are building the Pattern, it should be possible to generate the matching cases to the RegEx, similar to here: 
Without recursion up to 3 levels of nesting:
(JS, Java and other regex flavors)

To prevent [runaway](https://www.regular-expressions.info/toolong.html) [if unbalanced](https://regex101.com/r/S9aU9Y/1), with * on innermost [)(] only.

\((?:[^)(]|\((?:[^)(]|\((?:[^)(]|\([^)(]*\))*\))*\))*\)
[Demo at regex101](https://regex101.com/r/UmerYN/1); Or [unrolled](http://www.softec.lu/site/RegularExpressions/UnrollingTheLoop) for better performance (preferred).

\([^)(]*(?:\([^)(]*(?:\([^)(]*(?:\([^)(]*\)[^)(]*)*\)[^)(]*)*\)[^)(]*)*\)

**Comment by RafaelGB** [comment]
With this solution we can cover the following cases:
- key:: value
- **key**:: value (and all the variants _~`)
- `>` key:: value (> * n)
- --text-- [key:: value] --text-- (and all de variants, including pathentesis)

Problems:
- values that contains ) or ]. Relations for example (I.E.: [key:: [[my related note]]])

`/([\s\S]*)(^[^_*~`a-zA-Z1-9\[\(]*)([\[\(]{0,1})([_*~`]{0,2})([A-Za-z0-9]+)([_*~`]{0,2})([:]{2})([^\]\)]+)([\]\)]{0,1})(\n{0,1})([\s\S]*)/gm`

the group 8 and 9 its the heat point. I am keep thinking about how to improve it

**Comment by SpocWeb** [comment]
This is so dense! But [[Relations]] would be nice. 

What are the Parentheses for? (key:: value) Relations?

**Comment by RafaelGB** [comment]
dataview supports both (key:: value) and [key:: value], yep

**Comment by RafaelGB** [comment]
Commit 61cce176

https://regex101.com/r/yCVOs0/1
