### ISSUE TITLE
[FR] Writing to an existing file with no Front Matter

### ISSUE THREAD

**Issue by kazdonkai** [RafaelGB/obsidian-db-folder#80]
Currently, new columns can be inserted into files that already have Front Matter, but will not be written to files that do not have Front Matter.
Therefore, please consider making it possible to write to files that do not have Front Matter.

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/171138548-3015e575-40b0-4361-b638-d9708fa0e487.mov

**Comment by RafaelGB** [comment]
I could reproduce it today! Will try to bring a minor fix this week

**Comment by RafaelGB** [comment]
confirm that its fixed to close this issue

**Comment by kazdonkai** [comment]
It works well now.
