### ISSUE TITLE
[Bug]: empty space for first position of an array

### ISSUE THREAD

**Issue by Shaeeeeeee** [RafaelGB/obsidian-db-folder#803]
### What happened?

There is always a blank line in front of the bullet list. Even though I try to delete the comma in the front, it's useless because the comma soon comes back.
<img width="443" alt="截屏2023-02-02 19 49 03" src="https://user-images.githubusercontent.com/109874978/216316926-9ea4a4c0-c2ac-4c11-91dd-c6d327e27d06.png">
<img width="360" alt="image" src="https://user-images.githubusercontent.com/109874978/216317074-b99f0c6d-c9a6-4202-8c3b-b6a5bb5bc088.png">

### What platform were you using?

Desktop

### Version of the plugin

3.3.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
this issue will be fixed with the next version :)
