### ISSUE TITLE
Problem on load

### ISSUE THREAD

**Issue by Potorato** [RafaelGB/obsidian-db-folder#81]
Hello. I have downloaded the plugin, I have copied (unzipped) it to the plugins folder of my vault, like other times. When I try to enable it, it returns an error. Any ideas?

**Comment by RafaelGB** [comment]
hello @Potorato . Try to use BRAT plugin instead to download betas. You have the link in FAQ section of the documentation

**Comment by Potorato** [comment]
Gracias. Lo miro y te digo.

**Comment by RafaelGB** [comment]
nada! cualquier duda comentamos por aquí =)
Marco el issue como duplicado ya que está en questions

https://github.com/RafaelGB/obsidian-db-folder/issues/42
