### ISSUE TITLE
[Bug]: Typo in EnableAutoUpdateToggleHandler import

### ISSUE THREAD

**Issue by schoonc** [RafaelGB/obsidian-db-folder#815]
### What happened?

Typo in `EnableAutoUpdateToggleHandler` import:

_import { EnableAutoUpdateToggleHandler } from 'settings/handlers/helpersCommands/EnableAutoUpdateT_**O**_ggleHandler';_

### What platform were you using?

Desktop

### Version of the plugin

v3.3.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
thanks! fixed with the next version
