### ISSUE TITLE
[Bug]: range input may not display the actual value of "Pagination size"

### ISSUE THREAD

**Issue by schoonc** [RafaelGB/obsidian-db-folder#816]
### What happened?

[2023-02-12 13-52-15.webm](https://user-images.githubusercontent.com/4659633/218306913-cbd5ddfe-5332-46ce-99ef-d67f1163bcde.webm)

1. Set the "Pagination size" value in the plugin settings to greater than 100.
2. Close the settings.
3. Open the settings.

We will see that the input value is 100 (although the real value in the config is 200). I suspect that an input has a maximum value of 100 by default. So we have to call `setLimits` first and then `setValue` here:

![image](https://user-images.githubusercontent.com/4659633/218306962-d6927226-73f0-4289-b6e7-efc47b20864e.png)

I'm ready to create the PR.

### What platform were you using?

Desktop

### Version of the plugin

v3.3.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
I really appreciate your analysis. You are more than welcome to perform PRs

**Comment by schoonc** [comment]
@RafaelGB I've created the PR: https://github.com/RafaelGB/obsidian-db-folder/pull/819
