### ISSUE TITLE
[BUG] Can't create column

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#82]
**Describe the bug**
Whenever I press `add column`, it's blank.

**To Reproduce**
files : 
- [test1.md](https://github.com/RafaelGB/obsidian-db-folder/files/8822359/test1.md)
- [test2.md](https://github.com/RafaelGB/obsidian-db-folder/files/8822360/test2.md)
- [test3.md](https://github.com/RafaelGB/obsidian-db-folder/files/8822361/test3.md)
- [test4.md](https://github.com/RafaelGB/obsidian-db-folder/files/8822362/test4.md)
- [database.md](https://github.com/RafaelGB/obsidian-db-folder/files/8822367/database.md)

**Expected behavior**
create column

**Screenshots**

https://user-images.githubusercontent.com/38974541/171596640-477eda66-d63f-454d-9966-eaf0b52f8b6c.mov

**Desktop (please complete the following information):**
 - OS: MacOs monterey 12.3.1
 - Version Obsidian 0.14.6 Installer 0.14.6

**Additional context**

**Comment by RafaelGB** [comment]
Thanks for the "to reproduce" section!

Its a problem with duplicate column id. Will be added as a bug and fixed with next minor

**Comment by RafaelGB** [comment]
1.6.3 is out with a huge battery of fixes
