### ISSUE TITLE
[Bug]: very slow to open new pages in obsidian

### ISSUE THREAD

**Issue by toxfu** [RafaelGB/obsidian-db-folder#822]
### What happened?

A bug happened!
When I updated the plugin, suddenly the pages that I opened began to load too slowly. Moreover, some of them did not even show the content. This happens when you have obsidian open for some time

### What platform were you using?

Desktop

### Version of the plugin

3.3.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
We were testing on windows and Mac the version without find any performance problem. I will try to test it, sounds strange

**Comment by toxfu** [comment]
Yeah. You are right the problem returned. I don't know what happened to my obsidian. Being this misunderstood, he thought it depended on the plugin. Thanks for the great job. Greetings!
