### ISSUE TITLE
[Bug]: Non-use of native colour palette for label backgrounds causes odd-looking results

### ISSUE THREAD

**Issue by robertandrews** [RafaelGB/obsidian-db-folder#823]
### What happened?

The way colours are implemented for tag and relation value backgrounds leaves it open to poor-looking results.

Here is the default colour when used in dark mode...

![IMG_1140](https://user-images.githubusercontent.com/3158787/219485854-bcbb3e82-aa86-4edf-8946-fa3019f18494.jpeg)

This problem is multiplied infinitely because you use a full colour value picker.

You could condense the available colours down to a handful, each of which has a light mode and dark mode representation, like how, say, Notion does it.

PS. Use of background colours behind links to relation items, which is uncommon, may conflate the relation with tags, where the convention is more commonplace.

### What platform were you using?

Mobile

### Version of the plugin

3.3.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
will be fixed with this one https://github.com/RafaelGB/obsidian-db-folder/issues/809

**Comment by robertandrews** [comment]
Not specific to dark mode. See this picture of a relation. The text is unreadable.

![IMG_1256](https://github.com/RafaelGB/obsidian-db-folder/assets/3158787/75af9a5b-ed25-46f6-9cb4-a7d5572298b2)
