### ISSUE TITLE
[BUG] content is not deleted immediately

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#83]
**Describe the bug**
When I delete a column, then create a new column with the same name, the content of the column is persisted, but it should be deleted.

**To Reproduce**
1. Make sure that the new column will the same name as the column deleted
2. delete that column
3. create new column

**Expected behavior**
create new blank column (without text)

**Screenshots**

https://user-images.githubusercontent.com/38974541/171597631-24c9d862-2f2f-456a-813e-6f8a4fe346ab.mov

**Desktop (please complete the following information):**
 - OS: MacOs monterey 12.3.1
 - Version Obsidian 0.14.6 Installer 0.14.6

**Additional context**

**Comment by RafaelGB** [comment]
Hi @imeed166 . If you want that behaivour. You can use this property
<img width="727" alt="Screenshot 2022-06-02 at 11 19 01" src="https://user-images.githubusercontent.com/11924043/171598521-5d905cca-b212-4739-a283-3866c3e3b741.png">

**Comment by imeed166** [comment]
I have it enabled.
The column is deleted only when refreshing the database (going to another note, then back to database note). 
When I stay on the same note, the content of the column is not deleted.

**Comment by RafaelGB** [comment]
hmm okey. added as a bug

The reason is that exist 2 kind of data to make possible the dbfolder. The React table data and the dataview+yaml information

1.6.1 & 1.6.2 were adjsutments about differences between both types.

Will be added as a visual and added with minor version

**Comment by RafaelGB** [comment]
1.6.3 is out with a huge battery of fixes
