### ISSUE TITLE
[Bug]: No hiding of completed tasks

### ISSUE THREAD

**Issue by dapaning** [RafaelGB/obsidian-db-folder#839]
### Contact Details

dapan1020@gmail.com

### What happened?

This confuses me, if my file source is dataview search, it will not hide the completed tasks; if the file source is the current directory, it can be displayed normally
![2023-03-04_03-30-41](https://user-images.githubusercontent.com/66105129/222810927-e023d226-a70b-4285-8af8-30aca8ee31a0.png)

![2023-03-04_03-31-25](https://user-images.githubusercontent.com/66105129/222810947-532b277d-ff8a-4c98-b828-80bdc394d302.png)

### What platform were you using?

Desktop

### Version of the plugin

3.2.2

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
thanks for your clue about the source of the problem! I was trying to fix the bug for a while

**Comment by RafaelGB** [comment]
Commit 862b21c0

with a better control of dataview events and a refactor of tasks this will be resolved with the next version
