### ISSUE TITLE
[BUG] column width is too wide when creating column

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#84]
**Describe the bug**

**To Reproduce**
When creating a column, it's very wide. But when switching back and forth, the column width is adjusted.

1. create column
2. go to another note then back to the database

**Expected behavior**
create column with normal width

**Screenshots**

https://user-images.githubusercontent.com/38974541/171598207-93ad59a2-dab7-410e-8277-16289031eff4.mov

**Desktop (please complete the following information):**
 - OS: MacOs monterey 12.3.1
 - Version Obsidian 0.14.6 Installer 0.14.6

**Comment by RafaelGB** [comment]
the width of column will be refactored with https://github.com/RafaelGB/obsidian-db-folder/issues/50. Its a known problem

Added the reference of this issue and closed as a duplicate
