### ISSUE TITLE
[Bug]: "Columns to group files by" needs select column ID not column header name

### ISSUE THREAD

**Issue by PJC24** [RafaelGB/obsidian-db-folder#842]
### Contact Details

philcoggins@mac.com

### What happened?

When using "Configuring about columns" >"Columns to group files by name" the dropdown selection presents the name of the header row of that column in the database, not the underlying column ID of the select column. When this is true files are not sorted/filed by the select column. Manually changing "group_folder_column:" in config in mardown view to the correct column ID solves the problem.

For example: 
column ID = my_column but column header is = My Column. group_folder_column = My Column  - this does not work

column ID = my_column but column header is = My Column. group_folder_column = my_column  - this works

### What platform were you using?

Desktop

### Version of the plugin

3.3.2

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
It should be easy to fix. Thanks for your testing!!

**Comment by PJC24** [comment]
Thank you Rafael…. for building such an excellent and useful plugin for Obsidian. I can't tell you how fantastic it is for my use case, and it's getting better and better with each release.

Best Regards,
Phil

**Comment by RafaelGB** [comment]
Commit 4438d222
