### ISSUE TITLE
[FR]: can we drag tags in the tag pane into one (or several) specific cells so that the tag goes into the yaml of the corresponding files? 

### ISSUE THREAD

**Issue by ghweili** [RafaelGB/obsidian-db-folder#847]
### Contact Details

livey_liwei@hotmail.com

### Present your request

I'm hoping to be able to classify a series of files by properly marking them (such as job 1 done, job 2 done), so that I know where to continue next time. Using tags is probably the best way.

If we can drag the tags in the tag pane to a specific cell of the database, it would be quite convenient.  Moreover, there are cases that we may want to select several entries, then assign them with the same tag from the tag pane. Would there be a convenient way to do this in a batch? 

### For which platform do you request this request??

Desktop

**Comment by ghweili** [comment]
Now I got the chance to try this function. After installing tag-wrangler plugin, one can drag a tag in the tag pane to a normal md file so that the tag will be pasted to where I release the mouse. However, it is not possible to drag the tag into any of the cells within a database file.

I guess this functionality can be implemented easily when used in combination with tag-wrangler, which is quite good, even though it would be even better if it is possible to pick up several tags in the tag pane and drag them simultaneously into a cell. Such an operation is not yet supported by tag-wrangler yet.

**Comment by ghweili** [comment]
After more trials, it seems that when using the "Tag" cells of db-folder, the drop-down list only memorizes those that were created within the database file, while the other tags in the tag pane of the system (that were created outside the database file). This is quite inconvenient.

Then I tried another column with "Text" property, then I can enter contents including tags using the format "sth... #tag1, #tag2". This works fine, as shown below, but they are not recognized as tags, so I can't filter files using them. The yaml of one sample file now becomes:

---
tags:
  - tagsss
  - sdff
  - sdf
tags_1: "#n/sun  #jsido #n/sun"
---


![image](https://user-images.githubusercontent.com/33361275/225187791-27eaecc5-8640-487a-b01d-c5e0013c35f3.png)

**Comment by ghweili** [comment]
I believe that it is a very useful function to allow database files to interact with system tags more conveniently, including creating tags and assigning tags in the tag pane to one or more cells in a convenient way.

One possible scenario is: I'd like to label a large number of files using different tags (each file can contain several tags reflecting information on different aspects), so that I can filter out those belonging to certain categories later on (after I finish labeling all the files) and treat files of different categories (tags) separately.   

The required function will dramatically reduce the effort involved.

**Comment by ghweili** [comment]
after more trial, I guess the required function is best fulfiled upon using columns of Text Format with "Inline Option" enabled. In this way, one can type anything just as if he is typing in a regular note, so that, when he types # key, the system tag list will show up for the user to pick up; moreover, one can input multiple tags simply upon adding spaces between them.  

As a result, besides the columns with a Tag Format, I would also request dragging tags from the system tag pane (with the aid of the tag-wrangler plugin) to columns of the Text Format, so that the tag will be appended at the end of the cell (separated by a space with the previous content).

I'm making this request because it seems that it will take much more effort to realize the required function if one uses columns with the Tag Format, after I tried out both approaches.

**Comment by RafaelGB** [comment]
Hello @ghweili ! (tons of text =P)
everything that has to do with dragging elements usually has a technical complication to integrate with the Obsidian panel. I add the roadmap!

We would investigate the other plugin to see if it can be reused or docked natively.

**Comment by ghweili** [comment]
Thanks for the reply. The "tag-wrangler plugin" already makes it possible to drag tags into a note, which is highly likely to be relevant here.

As for db database, I notice that one normally has to double click on a cell to make it editable, I suspect that, if this limitation is released, it might be possible to realize the desired behavior. However, if this is needed for some reason, then maybe we can consider giving the users an option (switch) to set specific columns to be editable without having to click on it.
