### ISSUE TITLE
[BUG] checkbox text is black in dark mode

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#85]
**Describe the bug**
Completed checkbox is not distinguishable in dark mode

**To Reproduce**
1. create checkbox column
2. switch to dark mode

**Expected behavior**
checkbox text should be white in dark mode

**Screenshots**

https://user-images.githubusercontent.com/38974541/171598743-5ee23062-e682-454b-86d0-5dcfefeab14c.mov

**Desktop (please complete the following information):**
 - OS: MacOs monterey 12.3.1
 - Version Obsidian 0.14.6 Installer 0.14.6

**Comment by RafaelGB** [comment]
@imeed166 I created a testing vault and use the same dark mode and I'm agree, the chosen  background does not work well with all dark modes flavours. I was working on it, but with your issue its well documented

**Comment by RafaelGB** [comment]
1.6.3 is out with a huge battery of fixes

**Comment by imeed166** [comment]
It's better than it was, but in light mode, it appears all black. It doesn't really matter because I can differentiate between the checked and the unchecked.

https://user-images.githubusercontent.com/38974541/172002897-6c2d1586-d94e-426f-9a2a-b09577725511.mov

**Comment by RafaelGB** [comment]
The decision was use the max contrast between light & dark so it can be differenciable with all the themes
