### ISSUE TITLE
Unable to use Javascript, Database Disappears 

### ISSUE THREAD

**Issue by ccr112393** [RafaelGB/obsidian-db-folder#851]
Hi!

I am experiencing a similar issue to the one below. I've enabled Javascript and specified my scripts folder, but DB Folder doesn't seem to be able to see the files and when I enable Javascript at the database level it completely disappears. 

        Hey, I can’t use javascript in formula,
I have a code in "/js/test.js"
``` 
function test(){
    return "test";
}
module.exports = test;
```
I’m using the formula
`${db.js.test()}`

So my filename seems good, in setting, I activated the JS, and select the folder "js" 
What is the problem ?

_Originally posted by @VociNur in https://github.com/RafaelGB/obsidian-db-folder/discussions/784_

**Comment by ccr112393** [comment]
Here's a quick [screen recording](https://1drv.ms/v/s!AqpXHisUYh8ggaJzn98T-UfWkUbLsA?e=CUzNiT) showing what happens.

**Comment by donovanrost** [comment]
I'm having a very similar issue. DBFolder doesn't seem to recognize my `.js` files. To sort of test this, I set my formula to `${JSON.stringify(db.js)}` and the value is `{}`.

**Comment by ccr112393** [comment]
It started working for me. I can’t say for certain, but I think it was because I had an error in my code. But it would still happen even if I only had the example script in the folder. Not sure - but it has been working well for the last few days! Thank you dev for such an awesome plugin!

**Comment by Pukimaa** [comment]
Having the same issue with this code:
```js
/**
 * Formula: ${db.js.punkte(row.hausaufgaben,row.gelernt)}
 * @param {*} hausaufgaben [idk the type of booleans so this type is empty]
 * @param {*} gelernt int
 * @returns string representing the status of the goal
 */
function punkte(hausaufgaben, gelernt) {
  var hausaufgaben_punkte = 0;
  if (hausaufgaben) {
    hausaufgaben_punkte = 3;
  }
  return gelernt / 10 + hausaufgaben_punkte;
}

module.exports = punkte;
```

**Comment by Pukimaa** [comment]
@RafaelGB @ccr112393
