### ISSUE TITLE
[BUG] inconsistent names of properties

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#86]
**Describe the bug**
When creating a date or datetime property, the name of the column property is not the same.

**To Reproduce**
1. create date property
2. create datetime property

**Expected behavior**
The property names should be the same

**Screenshots**

![Screen Shot 2022-06-02 at 10 29 36 AM](https://user-images.githubusercontent.com/38974541/171600627-78b5abf0-45d0-4048-8b94-5502d78b61df.jpg)

![Screen Shot 2022-06-02 at 10 29 02 AM](https://user-images.githubusercontent.com/38974541/171600647-8654159e-fc33-4e22-92d4-7cf75d1011f3.jpg)

**Desktop (please complete the following information):**
 - OS: MacOs monterey 12.3.1
 - Version Obsidian 0.14.6 Installer 0.14.6

**Comment by RafaelGB** [comment]
its a known thing. Was a request of official version to rename Calendar for Date and Calendar time for Datetime, but property name has different source and needs a little refactor. As a visual minor thing it was at the bottom of the drawer

**Comment by RafaelGB** [comment]
1.6.3 is out with a huge battery of fixes
