### ISSUE TITLE
[FR]: Support multiple entries in frontmatter (besides tags)

### ISSUE THREAD

**Issue by aparente** [RafaelGB/obsidian-db-folder#874]
### Present your request

I'm trying to use database folder to create a CRM of sorts. I want to create a column where each row is a person I'm talking to and I have a column for their work/school affiliations. 
```
---
aliases: [alt_name_1, alt_name_2]
tags:
    - tag1
    - tag2
affiliations:
    - school_2
    - school_1
    - work
---
```

I usually fill these out by editing each note manually rather than using the database, and then have the database update. 

The problem that I'm having is that db folder will only display the first entry if I set the column as text. It will display all the entries if I use tags, though. But I'd like to preserve the ordering in the front matter as well. 

My ideal scenario would be to use nested front matter also, e.g. where I could filter by the years spent at a specific affiliation (e.g. filter to all people who went to this school during the time period of 2010-2012). I thought maybe nested frontmatter and dataview querying could fix this but I'm not sure. 

```
---
aliases: [alt_name_1, alt_name_2]
tags:
    - tag1
    - tag2
affiliations:
    - school
        - start_year:end_year
    - work
---
```

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
helo @aparente , you currently use animated fields. the required syntax its to join with dots those fields inside `id` column config:
`affiliations.school` will cover
```yaml
affiliations:
    school:
    - start_year
```

**Comment by aparente** [comment]
thank you!
