### ISSUE TITLE
[FR] Add option for 'lists' in property type

### ISSUE THREAD

**Issue by Trinsec** [RafaelGB/obsidian-db-folder#88]
So far the options available are: Select, text, number, date, datetime and checkbox. What I want is close to select, but then with those options toggleable each.

Consider this scenario: I've got a movie database, and I've got a column 'genre'. A certain movie is SciFi _and_ Fantasy. It'd be nice if I could toggle the individual selections to add/remove them to that note.

Right now a little workaround is to have the select type populated with all kinds of combinations possible. If you only have 3 or 4 genres, that's still doable.. but if you have more than 10 to choose from, that's going to be a huge list!

**Comment by RafaelGB** [comment]
hi @Trinsec . thanks for your comment.

there is a multi select feature in progress

https://github.com/RafaelGB/obsidian-db-folder/issues/36

that will cover your issue I think
