### ISSUE TITLE
[FR] Add more folder options in 'source'

### ISSUE THREAD

**Issue by Trinsec** [RafaelGB/obsidian-db-folder#89]
Currently the database source can be the following: current_folder, tags, outgoing_link, incoming_link.

I'd like to be able to select a folder that is not the current folder. This way I'd be able to have a bunch of various database views in one folder for convenience. I wonder if this is possible?

I'd also like to be able to toggle whether the subfolders are included or not. I've noticed the default seems to include subfolders.

**Comment by RafaelGB** [comment]
Add another folders breaks  the philosophy and your database source inside the same place it mixes.

I can open a discussion about
https://github.com/RafaelGB/obsidian-db-folder/discussions/92

**Comment by RafaelGB** [comment]
@Trinsec this will be cover by https://github.com/RafaelGB/obsidian-db-folder/issues/156
