### ISSUE TITLE
[Bug]: Empty frontmatter makes DB Folder unable to add data

### ISSUE THREAD

**Issue by acook** [RafaelGB/obsidian-db-folder#896]
### What happened?

Given the frontmatter is empty
When you try to edit a cell
Then DB Folder cannot save cell change, and instead presents this error:

![Screenshot from 2023-04-25 04-09-13](https://user-images.githubusercontent.com/71984/234229998-8c0e3898-7741-4f65-9157-e32832dd91ff.png)

For example, the frontmatter looks like this:

```yaml
---

---
```

I would expect DB Folder to just add the YAML field as normal, but it cannot. 

### What platform were you using?

Desktop

### Version of the plugin

3.4.0

### Relevant log output

```shell
No log output in console.
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by GaboCapo** [comment]
maybe you had an bad entry in you DB file, go to the three dots in your db view -> open as markdown.
Then find the wrong entry that  then find the wrong entry and remove it manually. Then you can close the DB and open it again.

**Comment by acook** [comment]
I'm not sure what that has to do with the bug I reported? I supplied the way to reproduce it. It's just when the frontmatter is empty.

**Comment by GaboCapo** [comment]
Thanks for the clarification. I tried reproducing it on an empty Vault with the empty frontmatter you presented but could not find an error. What type of cell are you editing?

**Comment by acook** [comment]
Just double checked. Looks like it's working now. There's been a lot of changes in DB Folder and Obsidian since then, I could do a git bisect, but I think I'll take the W.

Thanks for checking in, I'll close this issue now!
