### ISSUE TITLE
[Bug] Quotes in text very buggy.

### ISSUE THREAD

**Issue by Trinsec** [RafaelGB/obsidian-db-folder#90]
**Describe the bug**
If a text in a column contains quotes ("), it will be inconsistent depending on how those quotes are done.

**To Reproduce**
Input column Text: `"Quoth"`
In YAML: `Text: "Quoth"`
Back to table, it'll display Text: `Quoth` (note without the quotes).

Input column Text: `"Quoth" said the raven.`
In YAML: `Text: "Quoth" said the raven.` <-- Note it's invalid YAML now.
Back to table, it'll display Text: Nothing, text fails to show now.
Try to change text now to anything else, like `Test`.
In YAML: `Text: "Quoth" said the raven.` <-- It failed to change while YAML is invalid. Have to change it manually to something valid.

**Expected behavior**
I'd like it if the column can display that the key is found but that the value is invalid so I get warned that I have to fix things. Otherwise it'll just show an empty column that I think I can type something in but it won't save due to invalid YAML.

I've noticed it with the quotes (") so far.  The backtick is also an iffy one which can produce invalid YAML, messing things up. As a fix, I think as soon as there is a special character used that can mess up things, have the text completely surrounded by "" and escape out the " inside the text if any is present.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by RafaelGB** [comment]
@Trinsec thanks for the report. Will be added to roadmap

**Comment by Trinsec** [comment]
Just wanted to update that using a `:` in the text also breaks YAML (makes sense). Using `*` is also iffy. I think the easiest solution is probably to force "" around the whole text as soon as it's more than just alphanumerical and `-` and `_` characters (and escape out any " that is inside the text).

**Comment by RafaelGB** [comment]
good point.

the plugin had a refactor from contentEditable to just input text (more flexible and was a request to update the plugin)

before the whole text was cover by html tags <p><\p>

**Comment by Trinsec** [comment]
Oh wow, this is actually an annoying issue. I've got a bunch of values surrounded by "" already from before. If I change a value, all the other values will have their "" stripped off. I think that shouldn't happen at all. So even if I escaped stuff out properly already, it all gets undone by one edit via the plugin.

**Comment by RafaelGB** [comment]
could you attach ddbb file and some example? I will check it

**Comment by Trinsec** [comment]
I've made a new vault. I install Dataview and DB Folder fresh.

Created folder `Database`. Made it a database.
Put in just one note `Datafile 1`.
Added in the database via the tables:
`Col1` and `Col2`.
In `Datafile 1` I manually did this:
```
---
Col1: "Value1"
Col2: "Value2"
---
```
That's all. Then back to table. It shows everything fine, no problem.
I decide to change `Value2` from `Col2` into `Value22`.
I check the `Datafile 1` markdown again.
All "" are removed. The result is now:
```
---
Col1: Value1
Col2: Value22
---
```

As an extra, I made `Datafile 2` and repeated everything above for both files up until the change to Value22. Only the file whose value I changed got affected, that's a relief at least. Still, it shouldn't strip any "" at all. This is a new vault with everything set to default.

With ddbb you mean the database markdown file? Alright, here you go,
[Database Master File.md](https://github.com/RafaelGB/obsidian-db-folder/files/8835431/Database.Master.File.md)

**Comment by RafaelGB** [comment]
all values is wrapped with dataview types and parse "" into a normal string. Have an idea of how to fix your issue. thanks for your testing. Really apreciate it

**Comment by RafaelGB** [comment]
Because dataview returns me the data without `"`
this is my solution. I think it works pretty well

https://user-images.githubusercontent.com/11924043/171998087-af561847-36e6-4b45-8bc5-d6039cf3afc7.mov

**Comment by RafaelGB** [comment]
1.6.3 is out with a huge battery of fixes

**Comment by Trinsec** [comment]
I went to test this out immediately. :) It's getting there, but not completely fixed yet. But you're on the right track!

- If I typed in \` (a backtick), it creates invalid yaml.
- If I typed in `"Woohoo"`, it creates "Woohoo" in yaml, but it should be more like `\"Woohoo\"`.
- If I typed in `"Quoth" said the Raven.`, it creates invalid yaml.
- Ok lol, this one circumvents your solution in the video: If I typed in `"Key: Value"` it creates invalid yaml because it ends up as `""Key: Value""`. :D
- If I typed in `?`, it creates invalid yaml.
- Related to above: if I typed in `"?"` it's fine. Then I change another value in the same file, the `"?"` becomes `?` and creates invalid yaml.

Anything that contains more than `A-Z`, `0-9`, `-` and `_` should get wrapped with "", and any `"` inside the text should be escaped out. That's the simplest approach I think.

**Comment by RafaelGB** [comment]
@Trinsec Thanks for the second iteration test.
The problem is that dataview returns the value without validations (was not intended to edit later)

The plugin has its own parser. I separated writing as markdown parser and reading as text parser.

I can add your proposals to the markdown one now easily =)

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/103. as subtask of this one was generated
