### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by joesanga** [RafaelGB/obsidian-db-folder#908]
### What happened?

It seems that once a database view has been created off a list of notes, and then if you add columns with values to the database, then each individual note gets written with YAML code. And if you were to delete the columns later, that YAML code inside each note would never get deleted!!! Is that correct? 

The above has a major downstream problem where if you were to create a new fresh database from the same list of notes, existing YAML seems to persist and play havoc in the new database! Is this a known bug? Seems like this is affecting my sorting of the rows. When columns are deleted, underlying YAML of each note should also be deleted!!

Thanks.

### What platform were you using?

Desktop

### Version of the plugin

3.4.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by SVNKoch** [comment]
You can configure that. Open the database, open its database settings, scroll to "Remove fields", enable it.
Now when you delete a column the underlaying yaml data in your notes gets deleted too.

_PS: You forgot to add a title to your issue, it is just "[BUG]:"_
