### ISSUE TITLE
[Bug]: Date pattern is not applied/parsed after creating a note

### ISSUE THREAD

**Issue by m-primo** [RafaelGB/obsidian-db-folder#912]
### What happened?

The template is working properly with other plugins (such as obsidian-projects).

![image](https://github.com/RafaelGB/obsidian-db-folder/assets/44984918/eb9f7bb6-a18f-47b3-8106-290a0818d202)

Now when I add a note, it's just copying the template without any parsing for the date!

![image](https://github.com/RafaelGB/obsidian-db-folder/assets/44984918/d58543f1-1132-4e24-bc56-464537c6604b)

I tried editing the pattern with double quotes and many other retries and I couldn't get it work.

Is there any specific thing to make it work, or it just by design won't work?

### What platform were you using?

Desktop

### Version of the plugin

3.4.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by DC23** [comment]
Other template fields are also not expanded. For example: {{title}}.
