### ISSUE TITLE
[Bug]: Hidden columns cannot be recalled again

### ISSUE THREAD

**Issue by yoghurtdewdew** [RafaelGB/obsidian-db-folder#926]
### What happened?

I found that the hidden columns cannot be recalled again. The corresponding option was not found in the add column.

### What platform were you using?

Desktop

### Version of the plugin

3.4.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by stefandanzl** [comment]
It's in `Open Database Settings`
