### ISSUE TITLE
[Bug]: I cant sort DBFolder in canvas

### ISSUE THREAD

**Issue by Cyletix** [RafaelGB/obsidian-db-folder#928]
### Contact Details

1016120209@qq.com

### What happened?

I can sort my files in the DBFolder file,

then I want to add the DBFolder file into Canvas, but I cant sort DBFolder in canvas, the order is almost random, 

I have searched all the setting options, but there is no setting works

I'm sure this is a bug, I really need this function

Please fix it : )

### What platform were you using?

Desktop

### Version of the plugin

all version

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by HanaNoAme** [comment]
I have the same issue! It seems like it's not yet possible to sort the items when the DB folder is displayed on a canvas.
