### ISSUE TITLE
[Bug]: Starting Obsidian with a DB open => DB is shown empty

### ISSUE THREAD

**Issue by SVNKoch** [RafaelGB/obsidian-db-folder#931]
## Reproduce

1. Open a database with values inside
2. Close Obsidian
3. Reopen Obsidian
4. => Table is not showing any values (they briefly flash for like 0.1 seconds and then dissapear)
5. close db tab
7. reopen db tab
8. => values are still there

### What platform were you using?

Desktop

### Version of the plugin

3.4.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by SVNKoch** [comment]
hm, doesn't always happen, not sure what triggers it yet

**Comment by AMGMNPLK** [comment]
I have the same problem, or quite similar. My table looks empty most of the time.

**Comment by aubreyz** [comment]
Yet more bugs being closed with "not planned" ... Sigh....
