### ISSUE TITLE
Saved 0 Rows with various CSV formats

### ISSUE THREAD

**Issue by sh4d0wl3ss** [RafaelGB/obsidian-db-folder#946]
HI.. It's probably something I'm not doing right but I get the above trying to import this CSV (sanitized version)

"Filename","FirstName","LastName","Email-1","Email-2","Phone-1","Phone-2","Linkedin","Facebook","Cloze","FirstInteraction","LastInteraction","Tag"
"Jordan_Tiffany","Tiffany","Jordan","xxx","xxx","xxx","xxx","xxx","xxx","http://xxx.com","xxx","xxx","xxx"
"Walker_Jay","Jay","Walker","xxx","xxx","xxx","xxx","xxx","xxx","http://xxx.com","xxx","xxx","xxx"
"Cowan_William","William","Cowan","xxx","xxx","xxx","xxx","xxx","xxx","http://xxx.com","xxx","xxx","xxx"
"Berry_Kristen","Kristen","Berry","xxx","xxx","xxx","xxx","xxx","xxx","http://xxx.com","xxx","xxx","xxx"
"Gardner_Phil","Phil","Gardner","xxx","xxx","xxx","xxx","xxx","xxx","http://xxx.com","xxx","xxx","xxx"
"Baso_Steve ","Steve ","Baso","xxx","xxx","xxx","xxx","xxx","xxx","http://xxx.com","xxx","xxx","xxx"
"Murray_Matthew","Matthew","Murray","xxx","xxx","xxx","xxx","xxx","xxx","http://xxx.com","xxx","xxx","xxx"
"Baker_Bruce","Bruce","Baker","xxx","xxx","xxx","xxx","xxx","xxx","http://xxx.com","xxx","xxx","xxx"
"Ritchie_David","David","Ritchie","xxx","xxx","xxx","xxx","xxx","xxx","http://xxx.com","xxx","xxx","xxx"
"Hart_Bev","Bev","Hart","xxx","xxx","xxx","xxx","xxx","xxx","http://xxx.com","xxx","xxx","xxx"
"Dickerson_Verne","Verne","Dickerson","xxx","xxx","xxx","xxx","xxx","xxx","http://xxx.com","xxx","xxx","xxx"

**Comment by michidk** [comment]
Same issue with following csv:

```
Beans,Grind,Weight,Puck?,Extraction (grams),Double?
Illy classico,7,10g,Yes,14g,No
Illy classico,8,13g,No,13g,No
Illy classico,9,9.5g,Yes,10g/20sec,No
Lavazza Super Crema,8,11g,No,31g,No
Lavazza Super Crema,8,8g,No,27g,No
Lavazza Super Crema,9,8.6g,No,61g = 30g,Yes
Lavazza Super Crema,9,9g,No,47g,No
Lavazza Super Crema,9,25g,Yes,25g,No
```

**Comment by astraetech** [comment]
I have the same problem. What does it mean "not planned"?
