### ISSUE TITLE
[Bug]Column name changes are not reflected in files

### ISSUE THREAD

**Issue by kazdonkai** [RafaelGB/obsidian-db-folder#96]
Hi,
As shown in the video, renaming a column in the database is not reflected in the front matter of files.

https://user-images.githubusercontent.com/90127278/171864557-2319d29f-7950-4e75-9aed-f5ec44f53cfb.mov

**Comment by RafaelGB** [comment]
1.6.3 is out with a huge battery of fixes

**Comment by kazdonkai** [comment]
It is not working well yet.
Column name changes are not being written to the file.
If I rename the column and change the value, it is written, but this means I end up having to rewrite all the values.

By the way, Modified in the database is not changed even if there is a change in the file.

[2022-0605.mov.zip](https://github.com/RafaelGB/obsidian-db-folder/files/8839787/2022-0605.mov.zip)

**Comment by RafaelGB** [comment]
when you edit the column and then click in the property, maybe another event is thrown, have to test it. If you click out of the menu or press enter happens the same?

**Comment by kazdonkai** [comment]
Yes.
Moreover, as shown in the video, when I rewrite and enter new values, they are reflected in the file, but when I transition from the database to another file and then back to the database, the values are gone.
[画面収録 2022-06-05 21.27.56.mov.zip](https://github.com/RafaelGB/obsidian-db-folder/files/8839963/2022-06-05.21.27.56.mov.zip)

**Comment by RafaelGB** [comment]
looks like the name of the column is updated but not the keys. I will reopen the issue and try to reproduce it. With my tests its working well.
Thank you for your feedback

**Comment by RafaelGB** [comment]
@kazdonkai I really can't to reproduce your issue. Could you attach your database and some note example inside?

**Comment by kazdonkai** [comment]
It now works in the latest version 1.7.0.
Thx.
