### ISSUE TITLE
[FR]: Option to hide ribbon icon / PR permission request

### ISSUE THREAD

**Issue by fmbarina** [RafaelGB/obsidian-db-folder#966]
### Present your request

I'm trying to follow the [developer contribution guidelines](https://rafaelgb.github.io/obsidian-db-folder/contributing/developersContribution/). If I've made any mistake, please inform me.

I only create database folders using the right-click menu, so I don't need the sidebar icon. I'd like to be able to remove it.

I propose a new setting: "Show icon in sidebar"

- A toggle that defaults to true.
- Only add the sidebar icon at startup if the value of this setting is true.
- When turned on/off in the settings, the sidebar icon is added/removed accordingly.
- I don't think it fits in any existing section, so I suggest a new one at the top, something like "General configuration".

Of course, these ideas are just what I picked as a starting point, not something set in stone.

If this feature request is accepted, I'd like to send a PR for it (in fact, I've already implemented it).

### For which platform do you request this request??

Desktop

**Comment by stefandanzl** [comment]
I did personally (am not the plugin's owner) close it for now in an effort to focus on more important issues, as ribbons can already be easily be hidden without having to implement and test even more features in the plugin.
I also have not seen a PR for this feature yet.
