### ISSUE TITLE
New Notes Missing Data Values

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [RafaelGB/obsidian-db-folder#97]
**Describe the bug**
I can create the database note and then add Files. The files contain the header column names but none of the entries into those fields is flowing into the actual notes. 

**To Reproduce**
Any attempt to create a new database folder is doing this for me. The database folder in Markdown view is very empty. It just says 'Database of Items' with no other information. 

I am seeing a lot of errors in the Console:

plugin:dataview:16524 Uncaught (in promise) TypeError: Cannot read property 'addChild' of null
    at DataviewApi.table (plugin:dataview:16524)
    at PreviewDatabaseModeService.eval (plugin:dbfolder:125481)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:dbfolder:23)
table @ plugin:dataview:16524
eval @ plugin:dbfolder:125481
fulfilled @ plugin:dbfolder:23
Promise.then (async)
step @ plugin:dbfolder:25
fulfilled @ plugin:dbfolder:23
Promise.then (async)
step @ plugin:dbfolder:25
fulfilled @ plugin:dbfolder:23
Promise.then (async)
step @ plugin:dbfolder:25
fulfilled @ plugin:dbfolder:23
Promise.then (async)
step @ plugin:dbfolder:25
eval @ plugin:dbfolder:26
__awaiter @ plugin:dbfolder:22
PreviewDatabaseModeService.renderPreview @ plugin:dbfolder:125463
eval @ plugin:dbfolder:125429
eval @ plugin:dbfolder:26
__awaiter @ plugin:dbfolder:22
PreviewDatabaseModeService.tmpObsidianWYSIWYG @ plugin:dbfolder:125413
eval @ plugin:dbfolder:125401
eval @ plugin:dbfolder:26
__awaiter @ plugin:dbfolder:22
PreviewDatabaseModeService.markdownPostProcessor @ plugin:dbfolder:125395
e.postProcess @ app.js:1
e.postProcess @ app.js:1
h @ app.js:1
t.onRender @ app.js:1
requestAnimationFrame (async)
Le @ app.js:1
t.queueRender @ app.js:1
t.set @ app.js:1
e.set @ app.js:1
e.setViewData @ app.js:1
e.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.loadFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.setViewState @ app.js:1
eval @ plugin:obsidian-kanban:74
o @ plugin:obsidian-kanban:23
eval @ plugin:obsidian-excalidraw-plugin:48
o @ plugin:obsidian-excalidraw-plugin:48
eval @ plugin:dbfolder:125722
wrapper @ plugin:dbfolder:125359
eval @ plugin:dbfolder:125597
eval @ plugin:dbfolder:26
__awaiter @ plugin:dbfolder:22
setMarkdownView @ plugin:dbfolder:125596
eval @ plugin:dbfolder:125114
t.handleEvent @ app.js:1
Show 38 more frames
plugin:templater-obsidian:82 Templater Error: Template parsing error, aborting. 
 Bad template syntax

Unexpected token '%'
====================
var tR='',__l,__lP,include=E.include.bind(E),includeFile=E.includeFile.bind(E)
function layout(p,d){__l=p;__lP=d}
const _prs = [];
tR+='---\n\ndatabase-plugin: basic\n\n---\n\n'
_prs.push(%
name: new database
description: new description
columns:
 column1:
  input: text
  key: column1
  accessor: column1
  label: Column 1
  position: 0
  config:
   enable_media_view: true
   media_width: 100
   media_height: 100
   isInline: false
filters:
config:
 enable_show_state: false
 group_folder_column: 
 remove_field_when_delete_column: true
 show_metadata_created: true
 show_metadata_modified: true
 source_data: current_folder
 source_form_result: root
%);
tR+='rJ2KqXzxQg'
const _rst = await Promise.all(_prs);
tR = tR.replace(/rJ2KqXzxQg/g, () => _rst.shift());
if(__l)tR=await includeFile(__l,Object.assign(tp,{body:tR},__lP))
if(cb){cb(null,tR)} return tR

log_error @ plugin:templater-obsidian:82
eval @ plugin:templater-obsidian:103
rejected @ plugin:templater-obsidian:57
Promise.then (async)
step @ plugin:templater-obsidian:62
eval @ plugin:templater-obsidian:63
__async @ plugin:templater-obsidian:47
errorWrapper @ plugin:templater-obsidian:98
eval @ plugin:templater-obsidian:3813
eval @ plugin:templater-obsidian:63
__async @ plugin:templater-obsidian:47
overwrite_file_commands @ plugin:templater-obsidian:3811
eval @ plugin:templater-obsidian:3899
fulfilled @ plugin:templater-obsidian:50
Promise.then (async)
step @ plugin:templater-obsidian:62
eval @ plugin:templater-obsidian:63
__async @ plugin:templater-obsidian:47
on_file_creation @ plugin:templater-obsidian:3877
eval @ plugin:templater-obsidian:3958
t.tryTrigger @ app.js:1
t.trigger @ app.js:1
e.trigger @ app.js:1
e.onChange @ app.js:1
t.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileFileCreation @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.reconcileInternalFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
(anonymous) @ app.js:1
n @ app.js:1
Promise.then (async)
t.queue @ app.js:1
t.write @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.create @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.createNewMarkdownFile @ app.js:1
eval @ plugin:dbfolder:125617
eval @ plugin:dbfolder:26
__awaiter @ plugin:dbfolder:22
newDatabase @ plugin:dbfolder:125612
eval @ plugin:dbfolder:125656
t.handleEvent @ app.js:1
app.js:1 Uncaught TypeError: Cannot read property 'querySelector' of null
    at eval (plugin:obsidian-icon-folder:1672)
    at e.t.tryTrigger (app.js:1)
    at e.t.trigger (app.js:1)
    at e.trigger (app.js:1)
    at DatabaseView.e.onMoreOptionsMenu (app.js:1)
    at DatabaseView.onMoreOptionsMenu (plugin:dbfolder:125132)
    at DatabaseView.e.onMoreOptions (app.js:1)
    at HTMLAnchorElement.<anonymous> (app.js:1)
eval @ plugin:obsidian-icon-folder:1672
t.tryTrigger @ app.js:1
t.trigger @ app.js:1
e.trigger @ app.js:1
e.onMoreOptionsMenu @ app.js:1
onMoreOptionsMenu @ plugin:dbfolder:125132
e.onMoreOptions @ app.js:1
(anonymous) @ app.js:1
setTimeout (async)
t.tryTrigger @ app.js:1
t.trigger @ app.js:1
e.trigger @ app.js:1
e.onMoreOptionsMenu @ app.js:1
onMoreOptionsMenu @ plugin:dbfolder:125132
e.onMoreOptions @ app.js:1
(anonymous) @ app.js:1
plugin:dataview:16524 Uncaught (in promise) TypeError: Cannot read property 'addChild' of null
    at DataviewApi.table (plugin:dataview:16524)
    at PreviewDatabaseModeService.eval (plugin:dbfolder:125481)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:dbfolder:23)
table @ plugin:dataview:16524
eval @ plugin:dbfolder:125481
fulfilled @ plugin:dbfolder:23
Promise.then (async)
step @ plugin:dbfolder:25
fulfilled @ plugin:dbfolder:23
Promise.then (async)
step @ plugin:dbfolder:25
fulfilled @ plugin:dbfolder:23
Promise.then (async)
step @ plugin:dbfolder:25
fulfilled @ plugin:dbfolder:23
Promise.then (async)
step @ plugin:dbfolder:25
eval @ plugin:dbfolder:26
__awaiter @ plugin:dbfolder:22
PreviewDatabaseModeService.renderPreview @ plugin:dbfolder:125463
eval @ plugin:dbfolder:125429
eval @ plugin:dbfolder:26
__awaiter @ plugin:dbfolder:22
PreviewDatabaseModeService.tmpObsidianWYSIWYG @ plugin:dbfolder:125413
eval @ plugin:dbfolder:125401
eval @ plugin:dbfolder:26
__awaiter @ plugin:dbfolder:22
PreviewDatabaseModeService.markdownPostProcessor @ plugin:dbfolder:125395
e.postProcess @ app.js:1
e.postProcess @ app.js:1
h @ app.js:1
t.onRender @ app.js:1
requestAnimationFrame (async)
Le @ app.js:1
t.queueRender @ app.js:1
t.set @ app.js:1
e.set @ app.js:1
e.setViewData @ app.js:1
e.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.loadFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
e.setViewState @ app.js:1
eval @ plugin:obsidian-kanban:74
o @ plugin:obsidian-kanban:23
eval @ plugin:obsidian-excalidraw-plugin:48
o @ plugin:obsidian-excalidraw-plugin:48
eval @ plugin:dbfolder:125722
wrapper @ plugin:dbfolder:125359
eval @ plugin:dbfolder:125597
eval @ plugin:dbfolder:26
__awaiter @ plugin:dbfolder:22
setMarkdownView @ plugin:dbfolder:125596
eval @ plugin:dbfolder:125114
t.handleEvent @ app.js:1
Show 38 more frames
app.js:1 Uncaught TypeError: Cannot read property 'querySelector' of null
    at eval (plugin:obsidian-icon-folder:1672)
    at e.t.tryTrigger (app.js:1)
    at e.t.trigger (app.js:1)
    at e.trigger (app.js:1)
    at e.onMoreOptionsMenu (app.js:1)
    at e.onMoreOptionsMenu (app.js:1)
    at eval (plugin:obsidian-kanban:74)
    at e.o (plugin:obsidian-kanban:23)
    at eval (plugin:obsidian-excalidraw-plugin:48)
    at e.o (plugin:obsidian-excalidraw-plugin:48)
eval @ plugin:obsidian-icon-folder:1672
t.tryTrigger @ app.js:1
t.trigger @ app.js:1
e.trigger @ app.js:1
e.onMoreOptionsMenu @ app.js:1
e.onMoreOptionsMenu @ app.js:1
eval @ plugin:obsidian-kanban:74
o @ plugin:obsidian-kanban:23
eval @ plugin:obsidian-excalidraw-plugin:48
o @ plugin:obsidian-excalidraw-plugin:48
eval @ plugin:dbfolder:125751
wrapper @ plugin:dbfolder:125359
e.onMoreOptions @ app.js:1
(anonymous) @ app.js:1
setTimeout (async)
t.tryTrigger @ app.js:1
t.trigger @ app.js:1
e.trigger @ app.js:1
e.onMoreOptionsMenu @ app.js:1
e.onMoreOptionsMenu @ app.js:1
eval @ plugin:obsidian-kanban:74
o @ plugin:obsidian-kanban:23
eval @ plugin:obsidian-excalidraw-plugin:48
o @ plugin:obsidian-excalidraw-plugin:48
eval @ plugin:dbfolder:125751
wrapper @ plugin:dbfolder:125359
e.onMoreOptions @ app.js:1
(anonymous) @ app.js:1
2app.js:1 Uncaught TypeError: Cannot read property 'querySelector' of null
    at eval (plugin:obsidian-icon-folder:1672)
    at e.t.tryTrigger (app.js:1)
    at e.t.trigger (app.js:1)
    at e.trigger (app.js:1)
    at DatabaseView.e.onMoreOptionsMenu (app.js:1)
    at DatabaseView.onMoreOptionsMenu (plugin:dbfolder:125132)
    at DatabaseView.e.onMoreOptions (app.js:1)
    at HTMLAnchorElement.<anonymous> (app.js:1)
eval @ plugin:obsidian-icon-folder:1672
t.tryTrigger @ app.js:1
t.trigger @ app.js:1
e.trigger @ app.js:1
e.onMoreOptionsMenu @ app.js:1
onMoreOptionsMenu @ plugin:dbfolder:125132
e.onMoreOptions @ app.js:1
(anonymous) @ app.js:1
setTimeout (async)
t.tryTrigger @ app.js:1
t.trigger @ app.js:1
e.trigger @ app.js:1
e.onMoreOptionsMenu @ app.js:1
onMoreOptionsMenu @ plugin:dbfolder:125132
e.onMoreOptions @ app.js:1
(anonymous) @ app.js:1
plugin:dataview:16524 Uncaught (in promise) TypeError: Cannot read property 'addChild' of null
    at DataviewApi.table (plugin:dataview:16524)
    at PreviewDatabaseModeService.eval (plugin:dbfolder:125481)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:dbfolder:23)

**Expected behavior**
I'm expecting it to modify the values of tags in the front matter of the pages it creates. 

**Screenshots**
![image](https://user-images.githubusercontent.com/96321415/171962207-743ae65c-64a2-46a3-96bf-6a86077609ea.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (19043.1706)
 - Version 1.6.2

**Additional context**

**Comment by ObsidianTTRPGProject** [comment]
Some further testing. 

Disabled all plugins - Creates Note, Add's Tags, Fails to write values. 
Disabled all snippets - Creates Note, Add's Tags, Fails to write values. 
Turned Theme bas to Default - Creates Note, Add's Tags, Fails to write values. 
Note: The plugin is not reading any of the files in the folder. It's completely empty until I add new records. 

Made a complete copy of vault
Now it creates the Note, Add's Tags, Writes the value that I enter. 
Example: FileName | Player | CharName
Data Entered: Filename | Josh | John
If I enter Player and then CharName. I can see in real-time that Josh is written to the file but then it is deleted when I enter John into the cell next to it. 
The plugin is listing the files within the folder like this however. 

![image](https://user-images.githubusercontent.com/96321415/171988584-e796ab9e-d980-4910-a9e7-e43e1a8a7067.png)

![image](https://user-images.githubusercontent.com/96321415/171988610-5b57b8b1-70f6-4b8b-8312-3a69270238e7.png)

**Comment by ObsidianTTRPGProject** [comment]
I tried creating a new folder after this to see is the name of my folders might be messing with it. 
It reverted to the original behaviour where it creates the note, adds the frontmatter but will not copy values. 
![image](https://user-images.githubusercontent.com/96321415/171988686-4d4b59cb-be69-4d69-b443-0748394a8367.png)

**Comment by ObsidianTTRPGProject** [comment]
With everything turned back on this is the dev console. 
![image](https://user-images.githubusercontent.com/96321415/171988865-8d4a6d46-3fc7-40b3-b039-4532ca1c2e7e.png)

**Comment by RafaelGB** [comment]
Hi @ObsidianTTRPGProject thanks for your testing. Could you attach your db filer? I will try to reproduce your problem

My first think if the `Active?:` field. Try to remove the `?`

**Comment by ObsidianTTRPGProject** [comment]
I wondered if the ? might be the cause myself. So I did already try remove that. As you can see though even with the ? gone it still won't read anything. I wondered if the '0.' in the folder name might be causing it also so I tried to create it in a new folder with a simple name. Same issue. 

[1. CreateNewPlayer.md](https://github.com/RafaelGB/obsidian-db-folder/files/8837549/1.CreateNewPlayer.md)


![image](https://user-images.githubusercontent.com/96321415/171996646-623edf30-cfca-4eac-9a0f-3b28f769d52d.png)

Here's the file from the test folder. 
[Untitled database.md](https://github.com/RafaelGB/obsidian-db-folder/files/8837554/Untitled.database.md)

And the resulting MD from making a new file. If i click out of the DB file and back in all the records are gone. 
[Test.md](https://github.com/RafaelGB/obsidian-db-folder/files/8837555/Test.md)

**Comment by RafaelGB** [comment]
added to the roadmap. I will let you know when I have news about

**Comment by ObsidianTTRPGProject** [comment]
@RafaelGB 
> added to the roadmap. I will let you know when I have news about

I think I figured it out. I have some folders/files paths that are too long. I moved those folders out of the vault and everything started working again. 

It's not folders that are being used but I'm guessing the code is querying the rest of my vault and possibly erroring out as a result.

Everything seems to be working lovely now.

**Comment by RafaelGB** [comment]
ohh! Yeah, The ddbb takes all subfolders and not listed values of your notes too.

U have the option of use tags as a source if you want to have your ddbb in the same place. (configuration of the note > sources > tags)

**Comment by RafaelGB** [comment]
Windows SO had a problem with big paths but your can enlarge them.

https://www.microfocus.com/documentation/filr/filr-4/filr-desktop/t47bx2ogpfz7.html

**Comment by RafaelGB** [comment]
1.6.3 is out with a huge battery of fixes

**Comment by ObsidianTTRPGProject** [comment]
@RafaelGB 
Thanks. I've updated but still getting the same result. 
I've checked my registry and I already had LongPathsEnabled set to 1. 
I tried changing to Tags but that is not returning any results either. 
I tested in both my original folder and the Untitled Test folder. 

- CreateNewPlayer - not displaying any results. Can create a new file and it populates the tags but values do not feed through. 
- Untitled database - displaying results and allowing me to make changes to the data. The data reflects in the file but the Database file reverts back to the original value if you reload it. 

I'm trying to locate the files and rework it into a new folder structure. Do you use the full UNC path? I assume I can't just fix this by mapping it further down the tree. 

![image](https://user-images.githubusercontent.com/96321415/172006030-73bd1761-ba78-4f4e-a289-3d62a8ba7c61.png)

**Comment by RafaelGB** [comment]
I use Mac but windows at work. I will try to investigate it deeper. I remember to change it years ago with a similar problem

**Comment by ObsidianTTRPGProject** [comment]
I nuked my vault structure quite a bit. Got all the files back to max 183 chars or 245 Url Encoded. 
It is now reading the files into the database notes but it still won't save any changes made back to the notes. 

![image](https://user-images.githubusercontent.com/96321415/172016071-65802360-a80d-4577-bd50-6009e01d1d63.png)

Getting some different errors too. Interestingly here I do not have a folder called Barbarian. Looks like it's pulling one of my Choice field choices into the file name. 
![image](https://user-images.githubusercontent.com/96321415/172016391-f7dcaa83-6754-434e-b0c9-22b25588363f.png)

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/discussions/104

I create a discussion to search for the community support with this problem. Closing the issue as won't fix
