### ISSUE TITLE
[Bug]: Issue with a comma in file name

### ISSUE THREAD

**Issue by psuto** [RafaelGB/obsidian-db-folder#971]
### Contact Details

sutovsky@gmail.com

### What happened?

If a file name contains a comma like this "Graduate Data Scientist (Python, Matlab) - Oldham - Innovative Technology",
a file link is shown in the column/field "File" not as a link but as the following text:

[Pages/Jobs/Graduate Data Scientist (Python
Matlab) - Oldham - Innovative Technology.md|Graduate Data Scientist (Python
Matlab) - Oldham - Innovative Technology]

### What platform were you using?

Desktop

### Version of the plugin

3.5.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by codyburleson** [comment]
I confirm the same or a similar problem. When there are commas in a file name, the file name column is messed up and the next row shows content in the file name column from the body of the previous item.
