### ISSUE TITLE
[Bug]: Comma in Links Breaks List Format

### ISSUE THREAD

**Issue by IvyDliu** [RafaelGB/obsidian-db-folder#972]
### Contact Details

ivyliudd@gmail.com

### What happened?

Similar To Issue #971. When a field contains comma, and that field happens to be in wikiLink format (i.e [[link]]), even if it is not the default File field, it will render incorrectly.

Example:
<img width="325" alt="image" src="https://github.com/RafaelGB/obsidian-db-folder/assets/19966196/88c84d3a-66ce-40b2-b21f-8f0db0f9bb2c">
In DB note:
<img width="980" alt="image" src="https://github.com/RafaelGB/obsidian-db-folder/assets/19966196/fda95f29-aac6-4f46-9aa2-c55365ee3b9b">

As it is shown, the first column "outlinks" appears to be in the correct format, but the last column  #"question" is not. 

I might have pin-pointed the issue causing this in the source code, if @RafaelGB you would like, I could submit a pull request.

### What platform were you using?

Desktop

### Version of the plugin

3.5.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by Lordfirespeed** [comment]
This issue arises [here](https://github.com/RafaelGB/obsidian-db-folder/blob/9ed8427ee8939c15103f85478281caf915518a75/src/services/MarkdownRenderService.ts#L43C20-L43C20) when the markdown string to be rendered is split by comma.

Related issues could also be resolved: #980, #971, #848

**Comment by stefandanzl** [comment]
fixed in #1023
