### ISSUE TITLE
[FR]: Middle Click to Open in New Tab

### ISSUE THREAD

**Issue by acook** [RafaelGB/obsidian-db-folder#973]
### Contact Details

github@anthonymcook.com

### Present your request

In the rest of Obsidian if you middle click on a note link it will open it in a new tab.

I would like the same functionality in DB folder when you middle click on the filename column link.

Thanks!

### For which platform do you request this request??

Desktop

**Comment by stefandanzl** [comment]
Will be fixed with #1023
