### ISSUE TITLE
[Bug]: URLs with @ sign do not work correctly, Youtube also does not work as expected

### ISSUE THREAD

**Issue by quincyp** [RafaelGB/obsidian-db-folder#979]
### Contact Details

quincytpham@gmail.com

### What happened?

Getting started on a simple database with an entry  page that looks like the following:

Fireship
---
tags:
  - "#youtuber"
url: https://www.youtube.com/@Fireship
---

On the entry page the url will be linked and clickable.
On the DB page it has a broken image icon then the text url. This is not clickable.

Different permutations of updating the url link that did not fix the bug / work around the problem:

https://www.youtube.com/Fireship (@ removed)
this is the incorrect link, but also adds an entire youtube video embed that does not play

(https://www.youtube.com/@Fireship)
On the entry page, not clickable
On the DB page, clickable but formatted with the () around it

[Fireship](https://www.youtube.com/@Fireship)
On the entry page, not clickable at all
On the DB page, formatted correctly and working

Seems to be an issue with the @ sign, but also potentially youtube links.

### What platform were you using?

Desktop

### Version of the plugin

3.5.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by stefandanzl** [comment]
this is a youtube specific issue because obsidian tries to embed a video frame
