### ISSUE TITLE
An interrelated setup to emerge our daily life database 

### ISSUE THREAD

**Issue by Gourav1910** [RafaelGB/obsidian-db-folder#98]
Is it possible anyhow in obsidian to make our database and also able to calculate just like notion. I was using notion for tracking my finances such as budgeting, income and expenses. So there when I put value of any field it then automatically include that new value in previous calculations and generate new calculations by formula setup. 

So, what I looking for in obsidian, if i put my expenses or income in daily note so it automatically add to the previous calculation and generate a new calculation in a seperate finance dashboad(that we create for tracking finances).

Personal finance is just an example but I am looking for such kind of stuff.

See this notion template as reference: https://full-fibula-3c0.notion.site/Personal-Cash-Flow-From-Youtube-c4d5989eed6147f998de8b52b4dc5751

**Comment by RafaelGB** [comment]
Hi @Gourav1910  Its the idea of https://github.com/RafaelGB/obsidian-db-folder/issues/49

Its a long term feature but that's the goal of a 2.0.0 version

**Comment by RafaelGB** [comment]
You can comment your ideas in that issue. Thank you for your feedback =)

**Comment by Gourav1910** [comment]
I am happy that this feature is possible in obsidian and you are going to make it in future.
