### ISSUE TITLE
[Bug]: Commas now break the file link (special character in filename issue)

### ISSUE THREAD

**Issue by kinginmotion** [RafaelGB/obsidian-db-folder#980]
### Contact Details

kinginmotion@gmail.com

### What happened?

Commas were always fine in the filename until the latest Obsidian update v1.4.13
Now, any file with commas no longer shows as links. This applies to other special characters too probably, but commas and periods have always worked for me.
![image](https://github.com/RafaelGB/obsidian-db-folder/assets/2424857/d5e96a70-69c9-4a3a-99e5-489b0ab86633)

Here it looks fine when the comma is removed. (the period is still there)
![image](https://github.com/RafaelGB/obsidian-db-folder/assets/2424857/8a793e59-1c6d-4278-860f-f6661698847a)

I see there is another special character issue, but this seems different. https://github.com/RafaelGB/obsidian-db-folder/issues/974

### What platform were you using?

Desktop

### Version of the plugin

3.5.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by Gentleman03** [comment]
Same here, hope It will be fixed soon :)

**Comment by kabokabeso** [comment]
also for me very anoying bug. Would be great if it would be fixed soon :)
