### ISSUE TITLE
[FR]: Enable Multi-Select in Table Mode with Shift Key

### ISSUE THREAD

**Issue by killcider** [RafaelGB/obsidian-db-folder#995]
### Present your request

Currently, the "Tab" key allows us to enter into the table cell selection mode where a select box appears. Pressing "Enter" then allows input into the cell. The feature request is to enhance this functionality by enabling multi-cell selection when the "Shift" key is held down in table cell selection mode.

Expected Behavior:
Press the "Tab" key to enter table cell selection mode (existing functionality).
While in table cell selection mode, hold down the "Shift" key.
With the "Shift" key held down, the user should be able to multi-select cells.
By implementing this feature, users can more efficiently manage and manipulate tables, thereby enhancing the plugin's usability.

Feel free to adjust the wording to better match the context or specifics of your situation.

### For which platform do you request this request??

Desktop

**Comment by stefandanzl** [comment]
But what actions do you want to perform with the multi selection?
As I see it you can only add or edit text, so CTRL+C and CTRL+V will probably suffice
